Minor changes + Alerte déconnexion
PapillonApp/papillon-v7 pull request #113
Opened 2024-09-02 19:10 UTC by Slysoks

# 🚀 Nouvelle Pull Request

## Checklist d'avant pull request

- [ X ] Vous avez testé de build le projet avec vos modifications et ce build **a réussi**
- [ X ] Vous respectez les conventions de codage et de nommage du projet
- [ X ] Vous utilisez la **tabulation** pour l'indentation afin de maintenir un code lisible
- [ X ] Cette pull request **n'est pas un duplicata** d'une autre
- [ X ] Cette pull request est prête à être **revue** (review) et **fusionnée** (merge)
- [ X ] Il n'y a pas de **`TODO`** (aka des annotations pour du code manquant) dans vos modifications
- [ X ] Il n'y a pas **d'erreurs de langue** dans votre code (grammaire, vocabulaire, conjugaison, orthographe)
- [ X ] Les détails des changements ont été décrits ci-dessous
- [ X ] Cette pull-request n'est pas une **"breaking-change"** (des modifications qui vont entraîner la modification du fonctionnement de certaines fonctionnalités déjà existantes)

## Changelogs proposés

- Ajout d'un `https://` devant l'URL de connexion si `https://` ou `http://` ne sont pas précisés
- Changement de formule d'appel de l'utilisateur (vouvoiement -> tutoiement)
- Nombre de lignes variables dans l'infobulle
- Ajout d'une belle alerte de déconnexion

## Informations supplémentaires

- Passage de l'URL des CGU et ToS dans des variables pour simplifier leur édition en cas de besoin
- Affichage de l'os et de sa version en dessous de la version du programme
- Ajout d'un lien pour voir les collaborateurs de Papillon

2024-09-02 19:11 UTC, Slysoks commented
Ca fait peut-être un peu bcp là mais ça vaut le coup je pense !!

2024-09-02 19:12 UTC, Vexcited approved these changes

2024-09-02 19:12 UTC, Vexcited commented on src/services/pronote/determinate-authentication-view.tsx
> +  console.log(pronoteURL);
Tu pourrais enlever les `console.log` please ?

2024-09-02 19:13 UTC, Gabriel29306 commented
Tu pourrais envoyer un screen shot de l'alerte de déconnexion ?

2024-09-02 19:20 UTC, Slysoks commented on src/services/pronote/determinate-authentication-view.tsx
> +  console.log(pronoteURL);
bien sûr

2024-09-02 19:21 UTC, Slysoks commented
![Screenshot_20240902_211951_Expo Go.png](https://github.com/user-attachments/assets/67b35b29-6cea-4fa3-8024-88db285af9f7)

![Screenshot_20240902_212000_Expo Go.png](https://github.com/user-attachments/assets/9e1c23ad-4ec9-4659-b120-e39cc3ecfb80)

2024-09-02 19:22 UTC, Slysoks commented
Et voilà

2024-09-02 19:29 UTC, Gabriel29306 approved these changes
LGTM

2024-09-02 19:37 UTC, Slysoks commented
Et bonne rentrée à toute l'équipe (car je pense que vous aussi c'est mardi) !

2024-09-02 19:39 UTC, Rexxt commented
nan ma pré c'était ce matin, premier cours dans 1sem, mais merci du coup

2024-09-02 19:40 UTC, Rexxt commented
par rapport à l'alerte elle est un poil déséquilibrée visuellement mais ça se règle

2024-09-02 19:43 UTC, tom-theret commented
> ![Screenshot_20240902_211951_Expo Go.png](https://github.com/user-attachments/assets/67b35b29-6cea-4fa3-8024-88db285af9f7)
> 
> ![Screenshot_20240902_212000_Expo Go.png](https://github.com/user-attachments/assets/9e1c23ad-4ec9-4659-b120-e39cc3ecfb80)
> 
> 

Il y a une alert prévu à cette effet et même pour l'entièreté de d'app mais n'est pas documenté.

2024-09-02 19:44 UTC, tom-theret requested changes
Ne pas utiliser d'alert custom alors qu'on en a une qui a été spécifiquement créer pour ce type d'occasion.

2024-09-02 19:46 UTC, Slysoks commented
La quelle ?

2024-09-02 20:00 UTC, Slysoks commented
Car si c'est celle dans le @/src/providers/AlertProviders, elle ne convient pas au style de l'application

2024-09-02 20:26 UTC, tom-theret commented
> Car si c'est celle dans le @/src/providers/AlertProviders, elle ne convient pas au style de l'application

On peut la remixer pour qu'elle supporte n'importe quel situation !

2024-09-02 20:36 UTC, Slysoks commented
Je vous fait ça demain !

2024-09-03 17:23 UTC, Slysoks commented
Je close cette PR en attendant que je fasse l'alerte

2024-09-03 18:47 UTC, Slysoks commented
En fait, je me suis très vite rappelé que je ne comprends pas vraiment le coté Type de TypeScript (car je suis habitué au JS), donc j'ai tout remis comme avant au niveau de cette notif...

2024-09-05 15:01 UTC, godetremy commented
Perso, je trouve qu'il y a beaucoup de motifs pour une seul PR, si tu pouvais la séparer en plusieurs ça serait super !

2024-09-05 18:20 UTC, Slysoks commented
Jpp

2024-09-05 19:45 UTC, Louis-htmlcss commented
> Jpp

Mdrrrr

2024-09-06 09:36 UTC, godetremy commented
> Jpp

Tant pis je le ferai...

2024-09-07 21:29 UTC, tryon-dev commented
Je close car finalement quelqu'un d'autre la fait plus intégré a l'ui design de papillon

2024-09-07 21:29 UTC, closed without merging

2024-09-07 22:34 UTC, Slysoks commented
> Je close car finalement quelqu'un d'autre la fait plus intégré a l'ui design de papillon

Tkt, j'en referai une pr les "Minor changes" uniquement