✨ [Homework] : Ajout du sélecteur de date et d'un panneau de réglage de l'onglet - 🚨 iOS ONLY 🚨
PapillonApp/papillon-v7 pull request #158
Opened 2024-09-05 14:59 UTC by godetremy

## Checklist d'avant pull request

Veuillez cocher toutes les cases applicables en remplaçant [ ] par [x].

- [x] Vous avez testé de build le projet avec vos modifications et ce build **a réussi**
- [x] Vous respectez les conventions de codage et de nommage du projet
- [x] Vous utilisez la **tabulation** pour l'indentation afin de maintenir un code lisible
- [x] Cette pull request **n'est pas un duplicata** d'une autre
- [x] Cette pull request est prête à être **revue** (review) et **fusionnée** (merge)
- [x] Il n'y a pas de **`TODO`** (aka des annotations pour du code manquant) dans vos modifications
- [x] Il n'y a pas **d'erreurs de langue** dans votre code (grammaire, vocabulaire, conjugaison, orthographe)
- [x] Les détails des changements ont été décrits ci-dessous
- [x] Cette pull-request n'est pas une **"breaking-change"** (des modifications qui vont entraîner la modification du fonctionnement de certaines fonctionnalités déjà existantes)

## Changelogs proposés

Ajout du sélecteur de date et d'un panneau de réglage de l'onglet
<div>
<img src="https://github.com/user-attachments/assets/09ecc098-561c-4a29-a4b6-d666f41fd11a" width="33%"/>
<img src="https://github.com/user-attachments/assets/c59063c2-488c-48f7-879d-8c8a4bd10861" width="33%"/>
<img src="https://github.com/user-attachments/assets/10dde968-9ebd-4390-9a95-feda238d05ca" width="33%"/>
</div>

## Informations supplémentaires

**🚨 iOS ONLY 🚨**
Une pull request est à prévoir pour Android ! Cela est lié au fait qu'Android ne propose pas de sélecteur de date en inline.

2024-09-05 15:44 UTC, Gabriel29306 commented
Si on veut garder le même style pour Android, il va falloir recoder un calendrier entier. Ou sinon va falloir adapter la modale. À voir

2024-09-05 20:58 UTC, tom-theret commented
Pourquoi changer le style du calendrier ?

2024-09-06 05:05 UTC, Gabriel29306 commented
> Pourquoi changer le style du calendrier ?

Car comme dit plutôt, Android ne propose pas de style inline pour les calendriers.

2024-09-06 08:26 UTC, tom-theret commented
Je suis en train de faire un calendrier qui respecte le design de Papillon, je l’envoie cette après-midi !

2024-09-06 08:27 UTC, tom-theret commented
De plus, ce calendrier a été codé dans le mauvais fichier

2024-09-06 12:22 UTC, tom-theret commented
![Simulator Screenshot - iPhone 15 Pro - 2024-09-06 at 14 22 05](https://github.com/user-attachments/assets/17931c5a-e3e2-4cd6-8a6f-d5def5b8f695)
![Screenshot_1725625332](https://github.com/user-attachments/assets/13f6f708-5266-49f4-ae27-cd2a7074244e)

J'arrive !

2024-09-06 12:30 UTC, Gabriel29306 commented
> [Simulator Screenshot - iPhone 15 Pro - 2024-09-06 at 14 22 05](https://github.com/user-attachments/assets/17931c5a-e3e2-4cd6-8a6f-d5def5b8f695)
> [Screenshot_1725625332](https://github.com/user-attachments/assets/13f6f708-5266-49f4-ae27-cd2a7074244e)
> 
> J'arrive !
> 

J'aime bien

2024-09-06 12:33 UTC, tom-theret commented
![Screenshot_1725625332](https://github.com/user-attachments/assets/e58f6d64-e430-4575-b788-6f31802b0e23)

Mais c'est uniquement le temps de trouver une solution, j'en ai une en tête mais faut que je code dans la lib que j'utilise et c'est la merde.

2024-09-06 12:40 UTC, Gabriel29306 commented
Bonne chance hein 🤷

2024-09-06 13:08 UTC, tom-theret commented
![image](https://github.com/user-attachments/assets/a3950d48-dd1e-4314-9202-6e8c7b3b717a)
![image](https://github.com/user-attachments/assets/6fb740f2-5a83-41c5-8501-3d1c8067a23e)

@Gabriel29306 je crois qu'on tien un truc là ?

2024-09-06 13:12 UTC, Gabriel29306 commented
> @Gabriel29306 je crois qu'on tien un truc là ?

Il y a juste l'énorme menu défilant qui est moche, à cause d'Android, sinon c'est bon.
Je sais plus qui fait /veut ça, mais c'est de reproduire le dropdown comme pour la sélection de compte. Mais ce serait à implémenter.

2024-09-06 13:16 UTC, tom-theret commented
> > @Gabriel29306 je crois qu'on tien un truc là ?
> 
> Il y a juste l'énorme menu défilant qui est moche, à cause d'Android, sinon c'est bon.
> Je sais plus qui fait /veut ça, mais c'est de reproduire le dropdown comme pour la sélection de compte. Mais ce serait à implémenter.

Je vais essayer d'intégrer la roue sur Android

2024-09-06 13:20 UTC, Gabriel29306 commented
Je sais pas si c'est possible

2024-09-06 16:09 UTC, oriionn commented
> ![image](https://private-user-images.githubusercontent.com/33373907/365173838-a3950d48-dd1e-4314-9202-6e8c7b3b717a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2Mzg0NjEsIm5iZiI6MTcyNTYzODE2MSwicGF0aCI6Ii8zMzM3MzkwNy8zNjUxNzM4MzgtYTM5NTBkNDgtZGQxZS00MzE0LTkyMDItNmU4YzdiM2I3MTdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA2VDE1NTYwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwNjY5ODJhNzNlMGM5M2U1NTJmNTZmY2QyNjJlZDQyMWFmOWNlZTljNDYxY2UyZDkyODc0MmE5MjlhYTRhMTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EJJrRSrwGkFUHkNKF7Oqks4-uBSy3sgEN5z-l3hb4rI) ![image](https://private-user-images.githubusercontent.com/33373907/365173907-6fb740f2-5a83-41c5-8501-3d1c8067a23e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2Mzg0NjEsIm5iZiI6MTcyNTYzODE2MSwicGF0aCI6Ii8zMzM3MzkwNy8zNjUxNzM5MDctNmZiNzQwZjItNWE4My00MWM1LTg1MDEtM2QxYzgwNjdhMjNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA2VDE1NTYwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3MGFhMDI3ZWYyMTY4OGNlOGQwMDI1MzY0ZDAzODYxNDQ1ZGM0NmE0ZWIyZGNjMWRjNjk0MTljZjc1ODI5NDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kJ-wffEbOMdKnmOjHiDD2YfsvhV_egENC8lYLS3w9HI)
> 
> @Gabriel29306 je crois qu'on tien un truc là ?

Moyen convaincu par vos propositions, autant faire un truc propre sur iOS, puis attendre d'avoir un truc propre sur Android pour pouvoir l'intégrer...

2024-09-06 16:27 UTC, tom-theret commented
> > ![image](https://private-user-images.githubusercontent.com/33373907/365173838-a3950d48-dd1e-4314-9202-6e8c7b3b717a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2Mzg0NjEsIm5iZiI6MTcyNTYzODE2MSwicGF0aCI6Ii8zMzM3MzkwNy8zNjUxNzM4MzgtYTM5NTBkNDgtZGQxZS00MzE0LTkyMDItNmU4YzdiM2I3MTdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA2VDE1NTYwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwNjY5ODJhNzNlMGM5M2U1NTJmNTZmY2QyNjJlZDQyMWFmOWNlZTljNDYxY2UyZDkyODc0MmE5MjlhYTRhMTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EJJrRSrwGkFUHkNKF7Oqks4-uBSy3sgEN5z-l3hb4rI) ![image](https://private-user-images.githubusercontent.com/33373907/365173907-6fb740f2-5a83-41c5-8501-3d1c8067a23e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2Mzg0NjEsIm5iZiI6MTcyNTYzODE2MSwicGF0aCI6Ii8zMzM3MzkwNy8zNjUxNzM5MDctNmZiNzQwZjItNWE4My00MWM1LTg1MDEtM2QxYzgwNjdhMjNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA2VDE1NTYwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3MGFhMDI3ZWYyMTY4OGNlOGQwMDI1MzY0ZDAzODYxNDQ1ZGM0NmE0ZWIyZGNjMWRjNjk0MTljZjc1ODI5NDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kJ-wffEbOMdKnmOjHiDD2YfsvhV_egENC8lYLS3w9HI)
> > @Gabriel29306 je crois qu'on tien un truc là ?
> 
> Moyen convaincu par vos propositions, autant faire un truc propre sur iOS, puis attendre d'avoir un truc propre sur Android pour pouvoir l'intégrer...

Faut encore que tes image soit visible

2024-09-06 16:39 UTC, Vilerio commented
Niveau visuel, j'aime bien, bravo !
Mais d'un autre côté, cette PR, comme beaucoup d'autres, montrent que le choix du react native pour être "cross plateforme" n'est pas forcément le plus pertinent. (Mais cela ne dépend pas de vous bien sûr, ce n'est pas un reproche)

2024-09-06 16:43 UTC, tom-theret commented
> Niveau visuel, j'aime bien, bravo ! Mais d'un autre côté, cette PR, comme beaucoup d'autres, montrent que le choix du react native pour être "cross plateforme" n'est pas forcément le plus pertinent. (Mais cela ne dépend pas de vous bien sûr, ce n'est pas un reproche)

Quel version aimes-tu ? Celle de @godetremy ou la mienne ?

2024-09-06 16:43 UTC, Vilerio approved these changes
Testé de mon côté de façon très basique, pas encore d'analyse détaillée du code ni des possibles erreurs.

2024-09-06 16:45 UTC, Vilerio commented
> > Niveau visuel, j'aime bien, bravo ! Mais d'un autre côté, cette PR, comme beaucoup d'autres, montrent que le choix du react native pour être "cross plateforme" n'est pas forcément le plus pertinent. (Mais cela ne dépend pas de vous bien sûr, ce n'est pas un reproche)
> 
> Quel version aimes-tu ? Celle de @godetremy ou la mienne ?

J'ai edit mon commentaire sans voir ton message, sry
Je n'ai pas pu tester l'ergonomie de ton travail, je n'ai pas de smartphone sous Androïd à portée de main malheureusement.

2024-09-07 17:31 UTC, tom-theret commented
Je n'ai rien posté sur ce PR mais sur mon fork

2024-09-07 21:34 UTC, tryon-dev commented
> ![image](https://private-user-images.githubusercontent.com/33373907/365173838-a3950d48-dd1e-4314-9202-6e8c7b3b717a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3NDUwNjcsIm5iZiI6MTcyNTc0NDc2NywicGF0aCI6Ii8zMzM3MzkwNy8zNjUxNzM4MzgtYTM5NTBkNDgtZGQxZS00MzE0LTkyMDItNmU4YzdiM2I3MTdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA3VDIxMzI0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3OTU5YTExMGRhNzdmMDk4ZGMxN2JkZjE2OTdhM2E0NmZmNzBlZjJhODlmOWEwNjMxZmNjMmY3YjczZDRlNTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nLpv1Cf_YuB-IkBp3GG5Gu-AdA09nvLKt5cPArWV1x4) ![image](https://private-user-images.githubusercontent.com/33373907/365173907-6fb740f2-5a83-41c5-8501-3d1c8067a23e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3NDUwNjcsIm5iZiI6MTcyNTc0NDc2NywicGF0aCI6Ii8zMzM3MzkwNy8zNjUxNzM5MDctNmZiNzQwZjItNWE4My00MWM1LTg1MDEtM2QxYzgwNjdhMjNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA3VDIxMzI0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmMTBiOTQzOTY3ZjAxYzM0NGU3MTk2NDhkZDZkYWMxNzVjMzlmOTQ0M2U1MTM3NDI4NzVkYWY5NGU0MmFjZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8hXdA9hFg1qf2404cAUuPKyuGqkzT4LVXxE5dJq_lUQ)
> 
> @Gabriel29306 je crois qu'on tien un truc là ?

Y'a volonté de nuire !!!

2024-09-07 21:43 UTC, tryon-dev approved these changes

2024-09-07 21:44 UTC, toi-et-moi approved these changes

2024-09-07 21:54 UTC, tom-theret commented
> > ![image](https://private-user-images.githubusercontent.com/33373907/365173838-a3950d48-dd1e-4314-9202-6e8c7b3b717a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3NDUwNjcsIm5iZiI6MTcyNTc0NDc2NywicGF0aCI6Ii8zMzM3MzkwNy8zNjUxNzM4MzgtYTM5NTBkNDgtZGQxZS00MzE0LTkyMDItNmU4YzdiM2I3MTdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA3VDIxMzI0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3OTU5YTExMGRhNzdmMDk4ZGMxN2JkZjE2OTdhM2E0NmZmNzBlZjJhODlmOWEwNjMxZmNjMmY3YjczZDRlNTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nLpv1Cf_YuB-IkBp3GG5Gu-AdA09nvLKt5cPArWV1x4) ![image](https://private-user-images.githubusercontent.com/33373907/365173907-6fb740f2-5a83-41c5-8501-3d1c8067a23e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3NDUwNjcsIm5iZiI6MTcyNTc0NDc2NywicGF0aCI6Ii8zMzM3MzkwNy8zNjUxNzM5MDctNmZiNzQwZjItNWE4My00MWM1LTg1MDEtM2QxYzgwNjdhMjNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA3VDIxMzI0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmMTBiOTQzOTY3ZjAxYzM0NGU3MTk2NDhkZDZkYWMxNzVjMzlmOTQ0M2U1MTM3NDI4NzVkYWY5NGU0MmFjZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8hXdA9hFg1qf2404cAUuPKyuGqkzT4LVXxE5dJq_lUQ)
> > @Gabriel29306 je crois qu'on tien un truc là ?
> 
> Y'a volonté de nuire !!!

Je te demande pardon ?

2024-09-07 22:00 UTC, tom-theret requested changes
Interval de dates incorrects ...

2024-09-07 22:03 UTC, tryon-dev commented
> > > ![image](https://private-user-images.githubusercontent.com/33373907/365173838-a3950d48-dd1e-4314-9202-6e8c7b3b717a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3NDUwNjcsIm5iZiI6MTcyNTc0NDc2NywicGF0aCI6Ii8zMzM3MzkwNy8zNjUxNzM4MzgtYTM5NTBkNDgtZGQxZS00MzE0LTkyMDItNmU4YzdiM2I3MTdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA3VDIxMzI0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3OTU5YTExMGRhNzdmMDk4ZGMxN2JkZjE2OTdhM2E0NmZmNzBlZjJhODlmOWEwNjMxZmNjMmY3YjczZDRlNTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nLpv1Cf_YuB-IkBp3GG5Gu-AdA09nvLKt5cPArWV1x4) ![image](https://private-user-images.githubusercontent.com/33373907/365173907-6fb740f2-5a83-41c5-8501-3d1c8067a23e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3NDUwNjcsIm5iZiI6MTcyNTc0NDc2NywicGF0aCI6Ii8zMzM3MzkwNy8zNjUxNzM5MDctNmZiNzQwZjItNWE4My00MWM1LTg1MDEtM2QxYzgwNjdhMjNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA3VDIxMzI0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmMTBiOTQzOTY3ZjAxYzM0NGU3MTk2NDhkZDZkYWMxNzVjMzlmOTQ0M2U1MTM3NDI4NzVkYWY5NGU0MmFjZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8hXdA9hFg1qf2404cAUuPKyuGqkzT4LVXxE5dJq_lUQ)
> > > @Gabriel29306 je crois qu'on tien un truc là ?
> > 
> > 
> > Y'a volonté de nuire !!!
> 
> Je te demande pardon ?

les pauvres utilisateurs android

2024-09-07 22:06 UTC, tom-theret commented
> > > > ![image](https://private-user-images.githubusercontent.com/33373907/365173838-a3950d48-dd1e-4314-9202-6e8c7b3b717a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3NDUwNjcsIm5iZiI6MTcyNTc0NDc2NywicGF0aCI6Ii8zMzM3MzkwNy8zNjUxNzM4MzgtYTM5NTBkNDgtZGQxZS00MzE0LTkyMDItNmU4YzdiM2I3MTdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA3VDIxMzI0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3OTU5YTExMGRhNzdmMDk4ZGMxN2JkZjE2OTdhM2E0NmZmNzBlZjJhODlmOWEwNjMxZmNjMmY3YjczZDRlNTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nLpv1Cf_YuB-IkBp3GG5Gu-AdA09nvLKt5cPArWV1x4) ![image](https://private-user-images.githubusercontent.com/33373907/365173907-6fb740f2-5a83-41c5-8501-3d1c8067a23e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3NDUwNjcsIm5iZiI6MTcyNTc0NDc2NywicGF0aCI6Ii8zMzM3MzkwNy8zNjUxNzM5MDctNmZiNzQwZjItNWE4My00MWM1LTg1MDEtM2QxYzgwNjdhMjNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA3VDIxMzI0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmMTBiOTQzOTY3ZjAxYzM0NGU3MTk2NDhkZDZkYWMxNzVjMzlmOTQ0M2U1MTM3NDI4NzVkYWY5NGU0MmFjZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8hXdA9hFg1qf2404cAUuPKyuGqkzT4LVXxE5dJq_lUQ)
> > > > @Gabriel29306 je crois qu'on tien un truc là ?
> > > 
> > > 
> > > Y'a volonté de nuire !!!
> > 
> > 
> > Je te demande pardon ?
> 
> les pauvres utilisateurs android

Tu préfères quoi ?

- Avoir un truc ou ne rien avoir ?

2024-09-07 22:12 UTC, oriionn commented
> > > > > ![image](https://private-user-images.githubusercontent.com/33373907/365173838-a3950d48-dd1e-4314-9202-6e8c7b3b717a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3NDUwNjcsIm5iZiI6MTcyNTc0NDc2NywicGF0aCI6Ii8zMzM3MzkwNy8zNjUxNzM4MzgtYTM5NTBkNDgtZGQxZS00MzE0LTkyMDItNmU4YzdiM2I3MTdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA3VDIxMzI0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3OTU5YTExMGRhNzdmMDk4ZGMxN2JkZjE2OTdhM2E0NmZmNzBlZjJhODlmOWEwNjMxZmNjMmY3YjczZDRlNTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nLpv1Cf_YuB-IkBp3GG5Gu-AdA09nvLKt5cPArWV1x4) ![image](https://private-user-images.githubusercontent.com/33373907/365173907-6fb740f2-5a83-41c5-8501-3d1c8067a23e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3NDUwNjcsIm5iZiI6MTcyNTc0NDc2NywicGF0aCI6Ii8zMzM3MzkwNy8zNjUxNzM5MDctNmZiNzQwZjItNWE4My00MWM1LTg1MDEtM2QxYzgwNjdhMjNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA3VDIxMzI0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmMTBiOTQzOTY3ZjAxYzM0NGU3MTk2NDhkZDZkYWMxNzVjMzlmOTQ0M2U1MTM3NDI4NzVkYWY5NGU0MmFjZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8hXdA9hFg1qf2404cAUuPKyuGqkzT4LVXxE5dJq_lUQ)
> > > > > @Gabriel29306 je crois qu'on tien un truc là ?
> > > > 
> > > > 
> > > > Y'a volonté de nuire !!!
> > > 
> > > 
> > > Je te demande pardon ?
> > 
> > 
> > les pauvres utilisateurs android
> 
> Tu préfères quoi ?
> 
>     * Avoir un truc ou ne rien avoir ?

Je préfère ne rien avoir puis attendre pour avoir un truc propre
(Signé, un utilisateur Android)

2024-09-07 22:13 UTC, tom-theret commented
Bah écoute, code la wheel sur android...

2024-09-07 22:15 UTC, oriionn commented
> Bah écoute, code la wheel sur android...

Autant garder la solution de Rémy, et attendre d'avoir un truc similaire sur Android, non ?
Je trouve d'ailleurs la solution de la wheel sur iOS très peu ergonomique aussi, le calendrier comme Rémy le fait, est plus ergonomique **et respecte vraiment le design de Papillon**

2024-09-07 22:17 UTC, tom-theret commented
Mais la solution de @godetremy n'est pas bonne, tu demande à l'utilisateur de sélectionner une semaine, pas un jour ! De plus, l'intervalle des dates affichées n'est pas correct.

2024-09-07 22:18 UTC, tom-theret commented
Tout le monde kiffe le design il y a juste l'équipe Papillon qui n'est pas heureuse... à la fin c'est à se demander si c'est pas fait exprès ...

2024-09-07 22:19 UTC, oriionn commented
> Mais la solution de @godetremy n'est pas bonne, tu demande à l'utilisateur de sélectionner une semaine, pas un jour ! De plus, l'intervalle des dates affichées n'est pas correct.

Elle est tout de même 100x plus ergonomique que la tienne qui utilise un dropdown/une wheel.

2024-09-07 22:20 UTC, oriionn commented
> Tout le monde kiffe le design il y a juste l'équipe Papillon qui n'est pas heureuse... à la fin c'est à se demander si c'est pas fait exprès ...

Et ces gens qui kiffent le design, ils sont dans la pièce avec nous ?

2024-09-07 22:20 UTC, tom-theret commented
Ah oui ? Bah va dire à un utilisateur de choisir une semaine en sélectionnant un jour ... vachement logique

2024-09-07 22:21 UTC, tom-theret commented
> > Tout le monde kiffe le design il y a juste l'équipe Papillon qui n'est pas heureuse... à la fin c'est à se demander si c'est pas fait exprès ...
> 
> Et ces gens qui kiffent le design, ils sont dans la pièce avec nous ?

@Gabriel29306 @raphckrman

2024-09-07 22:21 UTC, oriionn commented
> > > Tout le monde kiffe le design il y a juste l'équipe Papillon qui n'est pas heureuse... à la fin c'est à se demander si c'est pas fait exprès ...
> > 
> > 
> > Et ces gens qui kiffent le design, ils sont dans la pièce avec nous ?
> 
> @Gabriel29306 @raphckrman

Dans les commentaires de la PR @Gabriel29306 n'a pas dit "kiffer" le design, il a même qualifié de moche la version sur Android.

2024-09-07 22:23 UTC, tom-theret commented
> > > > Tout le monde kiffe le design il y a juste l'équipe Papillon qui n'est pas heureuse... à la fin c'est à se demander si c'est pas fait exprès ...
> > > 
> > > 
> > > Et ces gens qui kiffent le design, ils sont dans la pièce avec nous ?
> > 
> > 
> > @Gabriel29306 @raphckrman
> 
> Dans les commentaires de la PR @Gabriel29306 n'a pas dit "kiffer" le design, il a même qualifié de moche la version sur Android.

Pas de chance maintenant on travail à deux sur une version Android mais bref...

2024-09-07 22:23 UTC, oriionn commented
> Ah oui ? Bah va dire à un utilisateur de choisir une semaine en sélectionnant un jour ... vachement logique

Au pire @godetremy, tu ne veux pas faire en sorte que quand l'utilisateur choisi le mercredi de la semaine, ça le scroll automatique sur le mercredi de cette dite semaine, comme ça, c'est logique selon lui. ;)

2024-09-07 22:24 UTC, oriionn commented
> > > > > Tout le monde kiffe le design il y a juste l'équipe Papillon qui n'est pas heureuse... à la fin c'est à se demander si c'est pas fait exprès ...
> > > > 
> > > > 
> > > > Et ces gens qui kiffent le design, ils sont dans la pièce avec nous ?
> > > 
> > > 
> > > @Gabriel29306 @raphckrman
> > 
> > 
> > Dans les commentaires de la PR @Gabriel29306 n'a pas dit "kiffer" le design, il a même qualifié de moche la version sur Android.
> 
> Pas de chance maintenant on travail à deux sur une version Android mais bref...

Je vois pas le rapport, il a bien qualifié de "moche" la version sur Android, c'est un fait. Il n'a pas dit "kiffer" le design

2024-09-07 22:25 UTC, tom-theret commented
> > Ah oui ? Bah va dire à un utilisateur de choisir une semaine en sélectionnant un jour ... vachement logique
> 
> Au pire @godetremy, tu ne veux pas faire en sorte que quand l'utilisateur choisi le mercredi de la semaine, ça le scroll automatique sur le mercredi de cette dite semaine, comme ça, c'est logique selon lui. ;)

Mais connard tu comprends pas quoi dans le concept de demander à l'utilisateur l'intervalle de dates qui correspond à la semaine? c'est de la logique !

2024-09-07 22:27 UTC, oriionn commented
ratio
![image](https://github.com/user-attachments/assets/85263114-f5ef-4bcd-9272-e1a5432f77d4)

2024-09-07 22:28 UTC, tom-theret commented
OUI....

2024-09-07 22:28 UTC, tom-theret commented
Bah écoute, je crois qu'on a vraiment pas la même logique mdr

2024-09-07 22:37 UTC, yannouuuu commented
Mais de toute façon ça parait simple : tant que les deux plateformes n'ont pas la même UX la PR ne sera pas acceptée. Papillon est multiplateforme mais elle reprend les mêmes logiques pour chaque OS. Ici le fait d'avoir une liste sur android ne correspond tout simplement pas avec le choix fait sur iOS (qui oui est meilleur).
Je la mets en draft pour l'instant comme j'ai vu que tu voulais refaire le "calendrier roue" à l'identique sur Android.

2024-09-07 22:38 UTC, tom-theret commented
> Mais de toute façon ça parait simple : tant que les deux plateformes n'ont pas la même UX la PR ne sera pas acceptée. Papillon est multiplateforme mais elle reprend les mêmes logiques pour chaque OS. Ici le fait d'avoir une liste sur android ne correspond tout simplement pas avec le choix fait sur iOS (qui oui est meilleur). Je la mets en draft pour l'instant comme j'ai vu que tu voulais refaire le "calendrier roue" à l'identique sur Android.

Donc on ai d'accord que la wheel est une bonne idée ?

2024-09-07 22:41 UTC, oriionn commented
> Mais de toute façon ça parait simple : tant que les deux plateformes n'ont pas la même UX la PR ne sera pas acceptée. Papillon est multiplateforme mais elle reprend les mêmes logiques pour chaque OS. Ici le fait d'avoir une liste sur android ne correspond tout simplement pas avec le choix fait sur iOS (qui oui est meilleur). Je la mets en draft pour l'instant comme j'ai vu que tu voulais refaire le "calendrier roue" à l'identique sur Android.

Tu as mal compris la PR...

La PR propose de rajouter ça uniquement sur iOS :
![364831307-09ecc098-561c-4a29-a4b6-d666f41fd11a-1](https://github.com/user-attachments/assets/1ee5af68-9e55-45a3-944e-c9a80dfeec21)

Mais monsieur Tom n'est pas d'accord, et veut mettre ça : 

iOS :
![365160833-17931c5a-e3e2-4cd6-8a6f-d5def5b8f695-1](https://github.com/user-attachments/assets/c3c4da66-4e0e-4454-98c3-358a4a23160d)

Android :
<div>
![365160881-13f6f708-5266-49f4-ae27-cd2a7074244e](https://github.com/user-attachments/assets/eba081ca-fc45-4313-a3c6-45c51d0b9c1a)
![365164176-c3f1ed03-a0ce-4cb0-89fb-c50959c9fb9e](https://github.com/user-attachments/assets/ff06d7e3-20f9-4e8d-b574-4d9f95af4397)
</div>

2024-09-07 22:46 UTC, tom-theret commented
Oui mais il attend mon interprétation sur android hors la 'est uniquement un proto, je n'ai rien PR

2024-09-07 22:47 UTC, tom-theret commented
Mais remet le en draft, merde

2024-09-07 22:48 UTC, oriionn commented
> Mais remet le en draft, merde

Bah nan, la PR est ready, il a mal compris dans son message, il a dit que la PR voulait mettre une wheel sur iOS et un select sur Android... hors là c'est ton idée et pas celle de la PR

2024-09-07 22:49 UTC, tom-theret commented
> > Mais remet le en draft, merde
> 
> Bah nan, la PR est ready, il a mal compris dans son message, il a dit que la PR voulait mettre une wheel sur iOS et un select sur Android... hors là c'est ton idée et pas celle de la PR

Bah oui mais il attend un truc de prod pour les 2 OS

2024-09-07 22:50 UTC, yannouuuu commented
mb j'avais mal capté le tournant de la PR et oui c'est bien le [calendrier classique](https://private-user-images.githubusercontent.com/77058107/364831307-09ecc098-561c-4a29-a4b6-d666f41fd11a.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3NDk1OTYsIm5iZiI6MTcyNTc0OTI5NiwicGF0aCI6Ii83NzA1ODEwNy8zNjQ4MzEzMDctMDllY2MwOTgtNTYxYy00YTI5LWE0YjYtZDY2NmY0MWZkMTFhLlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA3VDIyNDgxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmZDMwNWUxMjc2NjIzZjllN2ViYTY3MDBhMDFjNGJiNmVkNGQ0YjA5MGEzMjkyMWE3NjBjYjIwN2E0ZTZjYjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Jv6wP03CYRN8S2b-w-gI7IvlhjM2oaL6zNfsVM3eGwI) qu'il faudrait refaire à l'identique

2024-09-07 22:52 UTC, tom-theret commented
Bon bah faut vraiment aller se faire voir ...

2024-09-07 22:53 UTC, tom-theret commented
C'est vraiment pas logique votre histoire mais bref...

2024-09-08 06:14 UTC, TinAD17tin commented
Puedo faire le chiant ?
Voici ce que je préfère dans chaque solution :
Celle de Godetremy :
+ À la PRONOTE

- Long pour bien choisir les bons jour mais :
          Contre intuitif si la sélection d’un jour donne la semaine
          Pose problème si l’utilisateur sélectionne deux semaine nan !?

Celle de Tom :
+ Plus intuitif, si as un devoir pour dans deux semaines tu as juste à descendre deux fois.

- Version android délaissée, mais c’est déjà le cas de la version de Rémy


Par contre, je trouve qu’il faudrait mettre le bouton pour les devoirs faits ailleurs, car ça veut dire qu’il faudrait obligatoirement passer par le calendrier/la roue pour masquer les devoirs fait.

2024-09-08 06:22 UTC, TinAD17tin commented
Et en tant qu’utilisateur normal, qui va juste défilé la semaine d’après ou juste quelques semaines après, et qui n’est pas (encore) développeur, bah je préfère la version de Tom, mais c’est à vous de voir. Car je trouve que c’est plus rapide/compréhensible pour l’utilisateur lambda, qui ne va pas lire les détails écrit au dessus des calendriers + pas savoir c’est qu’elle pour qu’elle jour son devoir voir même qu’elle jour il est (même si le jour en question est coloré). Alors qu’à contrario un mec normal si il sait que c’est 2 semaines après, il ouvre la roue, descend 2 fois et hop c’est good, sans même savoir c’est quelle jour, quelle jour il est actuellement

2024-09-08 09:06 UTC, godetremy commented
Bon c'est pas compliqué, on va créer le composant PapillonCalendar ça serra plus simple visiblement...

2024-09-08 10:43 UTC, oriionn commented
> Et en tant qu’utilisateur normal, qui va juste défilé la semaine d’après ou juste quelques semaines après, et qui n’est pas (encore) développeur, bah je préfère la version de Tom, mais c’est à vous de voir. Car je trouve que c’est plus rapide/compréhensible pour l’utilisateur lambda, qui ne va pas lire les détails écrit au dessus des calendriers + pas savoir c’est qu’elle pour qu’elle jour son devoir voir même qu’elle jour il est (même si le jour en question est coloré). Alors qu’à contrario un mec normal si il sait que c’est 2 semaines après, il ouvre la roue, descend 2 fois et hop c’est good, sans même savoir c’est quelle jour et quelle jour il est actuellement

Je vois ce que tu veux dire, mais sa version comprend plusieurs désavantages :
- Tu te perds rapidement si tu veux voir au-delà de 1 à 2 semaines de décalage (je me suis déjà perdu dans un select menu plus petit 💀)
- Ça ne respecte pas trop le design de Papillon (comparé à celle de Rémy qui est 🤩)

Et par rapport à la simplicité de faire +2 semaines, on peut dire de même pour celle de Rémy, elle offre même de la précision selon moi.

2024-09-08 11:05 UTC, Yaya-Cout commented
Le calendrier est quand-même beaucoup plus lisible que la roue, car tu as le mois visible facilement (c'est moins facile à lire sous forme de nombre), et que quand tu sais que tu as un travail à faire pour le 9 septembre, tu n'as pas à réfléchir à quelle semaine c'est en regardant les intervalles mais juste à cliquer sur le bon jour.
La roue donne juste des intervalles en vrac alors que le calendrier permet de mieux comprendre. Surtout si tu dois sélectionner un mois précis.
Si tu dois aller deux semaines plus tard, tu as juste à aller deux lignes en dessous.
Le problème initial est aussi que Android ne propose pas de calendrier inline, mais je ne vois pas pourquoi ça devrait être inline alors que sur l'écran d'à côté (devoirs), c'est un popup avec un calendrier natif, donc pourquoi faire quelque chose de différent au lieu d'unifier ?

2024-09-08 11:22 UTC, godetremy commented
> Le calendrier est quand-même beaucoup plus lisible que la roue, car tu as le mois visible facilement (c'est moins facile à lire sous forme de nombre), et que quand tu sais que tu as un travail à faire pour le 9 septembre, tu n'as pas à réfléchir à quelle semaine c'est en regardant les intervalles mais juste à cliquer sur le bon jour. La roue donne juste des intervalles en vrac alors que le calendrier permet de mieux comprendre. Surtout si tu dois sélectionner un mois précis. Si tu dois aller deux semaines plus tard, tu as juste à aller deux lignes en dessous. Le problème initial est aussi que Android ne propose pas de calendrier inline, mais je ne vois pas pourquoi ça devrait être inline alors que sur l'écran d'à côté (devoirs), c'est un popup avec un calendrier natif, donc pourquoi faire quelque chose de différent au lieu d'unifier ?

Le problème c'est comment ajouter les paramètre de l'onglet sur android ?

2024-09-08 13:11 UTC, tom-theret commented
> > Et en tant qu’utilisateur normal, qui va juste défilé la semaine d’après ou juste quelques semaines après, et qui n’est pas (encore) développeur, bah je préfère la version de Tom, mais c’est à vous de voir. Car je trouve que c’est plus rapide/compréhensible pour l’utilisateur lambda, qui ne va pas lire les détails écrit au dessus des calendriers + pas savoir c’est qu’elle pour qu’elle jour son devoir voir même qu’elle jour il est (même si le jour en question est coloré). Alors qu’à contrario un mec normal si il sait que c’est 2 semaines après, il ouvre la roue, descend 2 fois et hop c’est good, sans même savoir c’est quelle jour et quelle jour il est actuellement
> 
> Je vois ce que tu veux dire, mais sa version comprend plusieurs désavantages :
> 
> * Tu te perds rapidement si tu veux voir au-delà de 1 à 2 semaines de décalage (je me suis déjà perdu dans un select menu plus petit 💀)
> * Ça ne respecte pas trop le design de Papillon (comparé à celle de Rémy qui est 🤩)
> 
> Et par rapport à la simplicité de faire +2 semaines, on peut dire de même pour celle de Rémy, elle offre même de la précision selon moi.

@godetremy ne respecte pas le design Papillon à moins que c'est un changement surprise ?

2024-09-08 13:43 UTC, Rexxt commented
> Et en tant qu’utilisateur normal, qui va juste défilé la semaine d’après ou juste quelques semaines après, et qui n’est pas (encore) développeur, bah je préfère la version de Tom, mais c’est à vous de voir. Car je trouve que c’est plus rapide/compréhensible pour l’utilisateur lambda, qui ne va pas lire les détails écrit au dessus des calendriers + pas savoir c’est qu’elle pour qu’elle jour son devoir voir même qu’elle jour il est (même si le jour en question est coloré). Alors qu’à contrario un mec normal si il sait que c’est 2 semaines après, il ouvre la roue, descend 2 fois et hop c’est good, sans même savoir c’est quelle jour et quelle jour il est actuellement

bah après pour moi c'est une question d'UX localisée, à titre perso j'ai l'habitude de voir un calendrier assez lambda et ça m'a jamais dérangé plus que ça, à titre purement personel je m'axe plutôt sur la proposition de rémy

par contre tom je te trouve assez coincé du postérieur et ça me plaît pas

2024-09-08 13:46 UTC, Yaya-Cout commented
Pronote utilise un calendrier, d'ailleurs (sur téléphone en tout cas).
Les jours de la semaine en cours sont encadrés et il suffit de cliquer sur l'un des jours de la semaine pour la sélectionner.

2024-09-08 14:24 UTC, merged