Refactor Homeworks View: Improve Structure and Subject Grouping
PapillonApp/papillon-v7 pull request #178
Opened 2024-09-07 16:58 UTC by Louis-htmlcss

# 🚀 Nouvelle Pull Request

Proposez vos modifications pour améliorer Papillon

## Informations importantes

Merci de vous référer à la documentation sur la contribution si vous avez des questions à propos des pull requests (https://gitbook.getpapillon.xyz/organisation/outils-internes/github)

## Checklist d'avant pull request

Veuillez cocher toutes les cases applicables en remplaçant [ ] par [x].

- [x] Vous avez testé de build le projet avec vos modifications et ce build **a réussi**
- [x] Vous respectez les conventions de codage et de nommage du projet
- [x] Vous utilisez la **tabulation** pour l'indentation afin de maintenir un code lisible
- [x] Cette pull request **n'est pas un duplicata** d'une autre
- [x] Cette pull request est prête à être **revue** (review) et **fusionnée** (merge)
- [x] Il n'y a pas de **`TODO`** (aka des annotations pour du code manquant) dans vos modifications
- [x] Il n'y a pas **d'erreurs de langue** dans votre code (grammaire, vocabulaire, conjugaison, orthographe)
- [x] Les détails des changements ont été décrits ci-dessous
- [x] Cette pull-request n'est pas une **"breaking-change"** (des modifications qui vont entraîner la modification du fonctionnement de certaines fonctionnalités déjà existantes)

This PR refactors the Homeworks view to enhance its structure and improve the organization of homework items. Key changes include:

1. Grouped homework items by subject within each day.
2. Added subject headers with color-coded labels.
3. Removed redundant subject information from individual homework items.
4. Updated the `groupedHomework` data structure to accommodate the new grouping.
5. Optimized the `HomeworkItem` component's re-rendering conditions.
6. Sorte

2024-09-07 17:25 UTC, tom-theret commented
Peut-on avoir des photos s’il vous plaît ?
Il est assez pénible de ne pas avoir d’images des différentes modifications.

2024-09-07 17:31 UTC, Louis-htmlcss commented
> Peut-on avoir des photos s’il vous plaît ? Il est assez pénible de ne pas avoir d’images des différentes modifications.

Déso j'avais oublié alors que j'en avais deja faîte une 💀

![Screenshot_20240907-185843_Expo Go](https://github.com/user-attachments/assets/6ce6bc74-67a6-41be-acb3-0d944579d1fd)

2024-09-07 17:35 UTC, tom-theret commented
Merci! 😁
C'est très jolie et utile !

2024-09-07 17:48 UTC, Louis-htmlcss commented
> Merci! 😁 C'est très jolie et utile !

Merci

2024-09-07 18:03 UTC, Rexxt commented
propre

2024-09-07 18:10 UTC, Louis-htmlcss commented
> propre

Merci, tu peux review ?

2024-09-07 19:08 UTC, Gabriel29306 approved these changes
UwU

2024-09-07 22:39 UTC, tryon-dev approved these changes

2024-09-08 18:38 UTC, ecnivtwelve approved these changes
LGTM 👍🏽

2024-09-08 18:49 UTC, Louis-htmlcss commented
Je la met en draft car j'ai d'autres truc a rajouter

2024-09-09 07:13 UTC, Crazzynel commented
Urh... LGTM mais je peux pas approve donc j'attends mdrrrr

2024-09-09 15:14 UTC, Louis-htmlcss commented
> Urh... LGTM mais je peux pas approve donc j'attends mdrrrr

Mdrrrrr

2024-09-11 16:37 UTC, Louis-htmlcss commented
![Screenshot_20240911-183646_Expo Go.png](https://github.com/user-attachments/assets/a78954e6-1f3c-4f41-9a57-fb57999b9d8c)

2024-09-11 17:46 UTC, Louis-htmlcss commented
@godetremy

2024-09-11 18:38 UTC, Gabriel29306 commented
Je suis un peu plus dubitatif avec les emojis

2024-09-11 18:49 UTC, Louis-htmlcss commented
> Je suis un peu plus dubitatif avec les emojis

je trouve ca mieux pour moi

2024-09-14 16:09 UTC, ecnivtwelve requested changes
> [!NOTE]
> **Ne pas merge**, sera overwrite par la https://github.com/PapillonApp/Papillon/pull/192

Je m'occuperai de backport cette PR vu qu'elle a été quasi approuvée

2024-09-14 16:50 UTC, Louis-htmlcss commented
> Note
> 
> **Ne pas merge**, sera overwrite par la #192
> 
> Je m'occuperai de backport cette PR vu qu'elle a été quasi approuvée _**Note a @Louis-htmlcss, ne ferme pas la PR, elle sera réintégrée**_

ouqis tkt pas

2024-09-25 14:13 UTC, Louis-htmlcss commented
fait la : https://github.com/PapillonApp/Papillon/pull/221

2024-09-25 14:13 UTC, closed without merging