Style + added links + auto https
PapillonApp/papillon-v7 pull request #185
Opened 2024-09-08 12:43 UTC by Slysoks

# 🚀 Refactor de l'ancienne Pull Request

## Checklist d'avant pull request

- [X] Vous avez testé de build le projet avec vos modifications et ce build **a réussi**
- [X] Vous respectez les conventions de codage et de nommage du projet
- [X] Vous utilisez la **tabulation** pour l'indentation afin de maintenir un code lisible
- [X] Cette pull request **n'est pas un duplicata** d'une autre
- [X] Cette pull request est prête à être **revue** (review) et **fusionnée** (merge)
- [X] Il n'y a pas de **`TODO`** (aka des annotations pour du code manquant) dans vos modifications
- [X] Il n'y a pas **d'erreurs de langue** dans votre code (grammaire, vocabulaire, conjugaison, orthographe)
- [X] Les détails des changements ont été décrits ci-dessous
- [X] Cette pull-request n'est pas une **"breaking-change"** (des modifications qui vont entraîner la modification du fonctionnement de certaines fonctionnalités déjà existantes)

## Changelogs proposés

- Ajout de "https://" dans l'URL de connexion si "https://" ou "http://" ne sont pas précisés
- Ouverture du lien de donation lors du clic sur le bouton dans les paramètres

## Informations supplémentaires

- Formattage

2024-09-08 15:11 UTC, Gabriel29306 commented
Apple bloque les dons en dehors de sa propre plateforme, donc le bouton "Soutenir Papillon" n'est pas censé être utilisé. Peut-être qu'on peut mettre le ko fi quand on est sur Android, mais pas pour la marque à la pomme.

2024-09-08 18:24 UTC, ecnivtwelve requested changes

2024-09-08 18:24 UTC, ecnivtwelve commented on src/views/settings/Settings.tsx
> +          },
Comme l'a précisé @Gabriel29306 , Apple n'autorise pas les dons en dehors de leur processus de paiement in-app (pour bien prendre les 30% de taxes, ça avait vallu un refus de la v6 sur l'App Store)
Il va donc falloir attendre que les dons in-app soient ajoutés à l'avenir dans l'app

**Je préconiserais donc d'ajouter une condition `Platform.OS === 'android'` dessus !**

2024-09-08 18:45 UTC, Louis-htmlcss commented on src/views/settings/Settings.tsx
> +          },
Apple abuse vraiment dessus ptdr

2024-09-08 18:58 UTC, Gabriel29306 commented on src/views/settings/Settings.tsx
> +          },
Ils aiment l'argent

2024-09-08 19:02 UTC, Louis-htmlcss commented on src/views/settings/Settings.tsx
> +          },
> Ils aiment l'argent

Normal 💀

2024-09-09 17:41 UTC, Slysoks commented on src/views/settings/Settings.tsx
> +          },
C'est modifié !

2024-09-09 18:30 UTC, Gabriel29306 approved these changes
UwU

2024-09-09 18:56 UTC, Louis-htmlcss approved these changes

2024-09-09 20:38 UTC, Slysoks commented
Je suis en train de faire un système de détection d'URLs ds les devoirs

2024-09-11 07:07 UTC, ecnivtwelve approved these changes
LGTM 👍🏽

2024-09-11 07:07 UTC, ecnivtwelve commented on src/widgets/Components/GeneralAverage.tsx
> +    setHidden(typeof average !== "number" || average < 0 || average + "" === "NaN");
On pourrait pas utiliser `isNaN()` ici ?

2024-09-12 15:54 UTC, Slysoks commented on src/widgets/Components/GeneralAverage.tsx
> +    setHidden(typeof average !== "number" || average < 0 || average + "" === "NaN");
Je change de PC et je regade ça

2024-09-13 19:51 UTC, Slysoks commented
@tryon-dev

2024-09-18 09:40 UTC, tryon-dev approved these changes

2024-09-20 19:23 UTC, Slysoks commented
@ecnivtwelve Il y a un merge conflict...

2024-09-20 23:49 UTC, cleeemeeent commented
Je sais pas si c'est normal, mais lorsqu'on essaye de se connecter via EcoleDirecte, elle redirige sur la page de sélection d'établissement Skolengo (comme écrit dans le code)
![image](https://github.com/user-attachments/assets/a1d61458-e6b5-4813-b24b-c5b770d42845)

2024-09-21 13:15 UTC, Slysoks commented
> Je sais pas si c'est normal, mais lorsqu'on essaye de se connecter via EcoleDirecte, elle redirige sur la page de sélection d'établissement Skolengo (comme écrit dans le code)

Mais j'ai pas modifié cette partie

2024-09-21 13:40 UTC, cleeemeeent commented
le truc c'est que c'est pas encore implémenté de mémoire mais il y a toujours comme la connexion skolengo

> > Je sais pas si c'est normal, mais lorsqu'on essaye de se connecter via EcoleDirecte, elle redirige sur la page de sélection d'établissement Skolengo (comme écrit dans le code)
> 
> Mais j'ai pas modifié cette partie

2024-09-21 13:40 UTC, cleeemeeent commented
Sinon ça me parait bien

2024-09-21 22:33 UTC, cleeemeeent approved these changes

2024-09-22 11:44 UTC, Slysoks commented
Pk personne merge ma PR, ya juste 1 merge à régler

2024-09-24 19:48 UTC, Slysoks commented
@tryon-dev @ecnivtwelve Vs pouvez merge svp, il y a maintenant 2 merge conflict

2024-09-25 19:17 UTC, Louis-htmlcss commented
> @tryon-dev @ecnivtwelve Vs pouvez merge svp, il y a maintenant 2 merge conflict

Bas règle tes conflits 💀

2024-09-26 14:19 UTC, Louis-htmlcss commented
> > > @tryon-dev @ecnivtwelve Vs pouvez merge svp, il y a maintenant 2 merge conflict
> > 
> > Bas règle tes conflits 💀
> 
> T'y connais rien, faut avoir les droit d'écriture

Seulement pour overwrite

2024-09-26 18:56 UTC, Slysoks commented
> > > > @tryon-dev @ecnivtwelve Vs pouvez merge svp, il y a maintenant 2 merge conflict
> > > 
> > > 
> > > Bas règle tes conflits 💀
> > 
> > 
> > T'y connais rien, faut avoir les droit d'écriture
> 
> Seulement pour overwrite

Je m'excuse, en effet, tu avais raison...

2024-09-27 19:31 UTC, Vexcited commented on src/services/pronote/determinate-authentication-view.tsx
> +    pronoteURL = pronote.cleanURL(pronoteURL);
il faudrait que l'URL soit TOUJOURS clean.

`cleanURL` permet tout simplement de récupérer la base/root de l'instance.

cad:
```
https://demo.index-education.net/pronote/eleve.html?truc=1
```
devient
```
https://demo.index-education.net/pronote
```
ou
```
http://localhost/pronote/test/pas/racine/eleve.html?truc=1
```
devient
```
http://localhost/pronote/test/pas/racine
```
mais encore
```
http://localhost/eleve.html?truc=1
```
devient
```
http://localhost
```

et finalement
```
http://localhost/pronote
```
reste
```
http://localhost/pronote
```

bref, cette fonction est essentielle pour simplifier la vie de l'utilisateur en évitant de lui demander d'entrer le root de son instance manuellement

2024-09-27 22:39 UTC, Slysoks commented on src/services/pronote/determinate-authentication-view.tsx
> +    pronoteURL = pronote.cleanURL(pronoteURL);
C'est tout bon

2024-09-27 23:11 UTC, Vexcited approved these changes

2024-09-27 23:32 UTC, merged