Changement du message de cours annulé (Canceled -> Cours annulé)
PapillonApp/papillon-v7 pull request #216
Opened 2024-09-25 01:56 UTC by Bulgus

# 🚀 Nouvelle Pull Request

Proposez vos modifications pour améliorer Papillon

## Checklist d'avant pull request

Veuillez cocher toutes les cases applicables en remplaçant [ ] par [x].

- [ ] Vous avez testé de build le projet avec vos modifications et ce build **a réussi**
- [x] Vous respectez les conventions de codage et de nommage du projet
- [x] Vous utilisez la **tabulation** pour l'indentation afin de maintenir un code lisible
- [x] Cette pull request **n'est pas un duplicata** d'une autre
- [x] Cette pull request est prête à être **revue** (review) et **fusionnée** (merge)
- [x] Il n'y a pas de **`TODO`** (aka des annotations pour du code manquant) dans vos modifications
- [x] Il n'y a pas **d'erreurs de langue** dans votre code (grammaire, vocabulaire, conjugaison, orthographe)
- [x] Les détails des changements ont été décrits ci-dessous
- [x] Cette pull-request n'est pas une **"breaking-change"** (des modifications qui vont entraîner la modification du fonctionnement de certaines fonctionnalités déjà existantes)

## Changelogs proposés

Le message affiché au dessus des cours annulé a été changé (Avant "canceled" maintenant "Cours annulé")

## Images

![Cours annulé](https://github.com/user-attachments/assets/5cc8060b-b7b3-483e-9b0d-70ed896bb6b7)
![canceled](https://github.com/user-attachments/assets/100078d2-0909-403c-a725-b5a10379e2b0)

2024-09-25 10:07 UTC, Louis-htmlcss approved these changes

2024-09-25 10:19 UTC, cleeemeeent approved these changes
LGTM

2024-09-25 10:55 UTC, godetremy commented
@Vexcited, je suis pas trop sur de l'implémentation, je te laisse voir ! Si c'est ok je valide puis merge !

2024-09-25 11:14 UTC, ecnivtwelve approved these changes

2024-09-25 13:25 UTC, Kgeek33 requested changes
Ça ne marche pas lorsqu'il y a un prof. absent, c'est toujours marqué `canceled`

2024-09-25 13:46 UTC, Kgeek33 commented
Ça remarche, déso...
Par contre, ça n'affiche plus les changements de salle

2024-09-25 14:00 UTC, godetremy commented
> Ça remarche, déso...
> 
> Par contre, ça n'affiche plus les changements de salle

Il est probable que ce texte servent uniquement d'une indication pour l'interface ! C'est pour ça que je demande à Vexcited !

2024-09-26 14:21 UTC, tryon-dev commented
![image](https://github.com/user-attachments/assets/55863398-7f0f-427a-9adb-bdeb3e3ebdc0)
![image](https://github.com/user-attachments/assets/7fccb95a-792a-465b-915a-7300c26be069)

2024-10-02 15:00 UTC, vexcited commented
Alors le truc c'est que j'ai rajouté https://github.com/PapillonApp/Papillon/commit/e5b91ec7b3d869258fcd111918ebc66cf109e58d dernièrement et il faudrait juste que `statusText` soit affiché à la place de `status` dans l'UI.

La valeur dans l'enum doit pas être changé, elle est là uniquement dans le but à être utilisée en interne.

2024-10-02 15:18 UTC, Bulgus commented
> Alors le truc c'est que j'ai rajouté https://github.com/PapillonApp/Papillon/commit/e5b91ec7b3d869258fcd111918ebc66cf109e58d dernièrement et il faudrait juste que `statusText` soit affiché à la place de `status` dans l'UI.
> 
> 
> 
> La valeur dans l'enum doit pas être changé, elle est là uniquement dans le but à être utilisée en interne.

Je fais ça ce soir

2024-10-02 16:47 UTC, closed without merging

2024-10-02 17:15 UTC, Bulgus commented
@Vexcited J'ai refais une PR (#252), c'est bon ?