fix(News): error wheen title is undefined
PapillonApp/papillon-v7 pull request #223
Opened 2024-09-25 17:04 UTC by Kgeek33

# 🚀 Nouvelle Pull Request

Proposez vos modifications pour améliorer Papillon

## Informations importantes

Merci de vous référer à la documentation sur la contribution si vous avez des questions à propos des pull requests (https://gitbook.getpapillon.xyz/organisation/outils-internes/github)

## Checklist d'avant pull request

Veuillez cocher toutes les cases applicables en remplaçant [ ] par [x].

- [x] Vous avez testé de build le projet avec vos modifications et ce build **a réussi**
- [x] Vous respectez les conventions de codage et de nommage du projet
- [x] Vous utilisez la **tabulation** pour l'indentation afin de maintenir un code lisible
- [x] Cette pull request **n'est pas un duplicata** d'une autre
- [x] Cette pull request est prête à être **revue** (review) et **fusionnée** (merge)
- [x] Il n'y a pas de **`TODO`** (aka des annotations pour du code manquant) dans vos modifications
- [x] Il n'y a pas **d'erreurs de langue** dans votre code (grammaire, vocabulaire, conjugaison, orthographe)
- [x] Les détails des changements ont été décrits ci-dessous
- [x] Cette pull-request n'est pas une **"breaking-change"** (des modifications qui vont entraîner la modification du fonctionnement de certaines fonctionnalités déjà existantes)

## Changelogs proposés

Correction d'une erreur lorsqu'une actualité n'a pas de titre et est remplacé par "(aucun titre)"

## Informations supplémentaires

![Screenshot_2024-09-25-19-04-06-945_host exp exponent](https://github.com/user-attachments/assets/cf225aeb-fae9-4277-b9e9-216f935c08f7)

2024-09-25 20:19 UTC, tryon-dev requested changes
au lieu de mettre (aucun titre) je pense que c'est mieux de marquer Aucun Titre ou Actualité du 01/01/2024

2024-09-25 21:17 UTC, Rexxt commented
> au lieu de mettre (aucun titre) je pense que c'est mieux de marquer Aucun Titre ou Actualité du 01/01/2024

c'est moyennement conventionnel (la plupart des logiciels disent `(sans objet)` ou `(sans titre)` ou `(aucun titre)`) mais je vois ton point de vue

2024-09-26 08:25 UTC, ecnivtwelve commented on src/utils/magic/categorizeMessages.ts
> +      message.title = "(aucun titre)";
Peut-être juste "Sans-titre" suffirait ?

2024-09-26 09:08 UTC, Kgeek33 commented on src/utils/magic/categorizeMessages.ts
> +      message.title = "(aucun titre)";
Je vais faire comme pour les notes. Je vais mettre "Sans titre"
Je change ça de suite

2024-09-26 09:11 UTC, Kgeek33 commented
> au lieu de mettre (aucun titre) je pense que c'est mieux de marquer Aucun Titre ou Actualité du 01/01/2024

@tryon-dev @ecnivtwelve corrigé !

2024-09-26 11:58 UTC, tryon-dev approved these changes

2024-09-26 13:03 UTC, Cleboost approved these changes

2024-09-26 14:05 UTC, ecnivtwelve approved these changes

2024-09-26 14:06 UTC, merged