[Fix] Réparation de TOUS les types, et des erreur de lint
PapillonApp/papillon-v7 pull request #264
Opened 2024-10-05 10:51 UTC by camarm-dev

> [!NOTE]
> Draft PR, WIP

# 🚀 Nouvelle Pull Request

Comme j'ai pu le coinstater assez vite, les types de ce projet sont complètement cassés
```
Found 228 errors in 61 files.
```
_Message de `pnpm lint` sur la branche main_

J'ai donc **résolu tout les erreurs de types**, et j'ai pu ainsi faire fonctionner le linter, pour que le projet respecte les codes de styles définis dans le fichier de configuration.

## Informations importantes

Merci de vous référer à la documentation sur la contribution si vous avez des questions à propos des pull requests (https://gitbook.getpapillon.xyz/organisation/outils-internes/github)

## Checklist d'avant pull request

Veuillez cocher toutes les cases applicables en remplaçant [ ] par [x].

- [ ] Vous avez testé de build le projet avec vos modifications et ce build **a réussi**
- [ ] Vous respectez les conventions de codage et de nommage du projet
- [ ] Vous utilisez la **tabulation** pour l'indentation afin de maintenir un code lisible
- [ ] Cette pull request **n'est pas un duplicata** d'une autre
- [ ] Cette pull request est prête à être **revue** (review) et **fusionnée** (merge)
- [ ] Il n'y a pas de **`TODO`** (aka des annotations pour du code manquant) dans vos modifications
- [ ] Il n'y a pas **d'erreurs de langue** dans votre code (grammaire, vocabulaire, conjugaison, orthographe)
- [ ] Les détails des changements ont été décrits ci-dessous
- [ ] Cette pull-request n'est pas une **"breaking-change"** (des modifications qui vont entraîner la modification du fonctionnement de certaines fonctionnalités déjà existantes)

## Changelogs proposés

En gros le projet est bien clean.

## Informations supplémentaires

J'aimerais que des tests assez profond soit effectués avant de merge ceci: j'ai touché à l'entièreté de la base de code et je ne suis pas sur que tout mes changements fonctionnent dans toutes les circonstances...

Liste des tests effectués
- [ ] Test des devoirs avec Pronote
- [ ] Test des notes avec Pronote

2024-10-05 11:53 UTC, Gabriel29306 commented
Si tu fais une pr draft, tu pourrais juste rajouter un compteur ou un truc du genre dans le message initial pour que l'on sache où tu en es rendu ?

2024-10-06 20:23 UTC, Kgeek33 commented
Euh 😅
J'viens de tester ta PR et je suis bloqué sur la page d'accueil, je peux rien faire (Pronote)
Je regarde ce qui pose problème

2024-10-06 20:27 UTC, Kgeek33 commented
Bloqué lors de la 1ère utilisation de Papillon

2024-10-06 20:35 UTC, camarm-dev commented
> Euh 😅
> J'viens de tester ta PR et je suis bloqué sur la page d'accueil, je peux rien faire (Pronote)
> Je regarde ce qui pose problème

Ahah merci de tester je ne l'ai pas encore fait ! Je réglerai ce qui ne fonctionne pas, mais ne t'embête pas je ne pourrai pas bosser dessus avant vendredi prochain de toute manière...

Je te demanderai de review quand j'ouvrirai la PR 😉

2024-10-12 09:10 UTC, camarm-dev commented
Il y a des erreurs de ts dans certains modules... Je vais essayer de faire passer des PR sur ces modules pour **ENFIN** pouvoir le lint ce projet **correctement**... Pour l'instant le workflow ne passe pas, c'est normal. Je vous met l'avancée des PR et je vais compléter les tests dans la description de la PR au fur et à mesure.
- [ ] Correction de `react-native-infinite-pager`
- [ ] Correction de `react-native-reanimated-graph`

2024-10-12 11:16 UTC, Kgeek33 commented
> Il y a des erreurs de ts dans certains modules... Je vais essayer de faire passer des PR sur ces modules pour **ENFIN** pouvoir le lint ce projet **correctement**... Pour l'instant le workflow ne passe pas, c'est normal. Je vous met l'avancée des PR et je vais compléter les tests dans la description de la PR au fur et à mesure.
> - [ ] Correction de `react-native-infinite-pager`
> - [ ] Correction de `react-native-reanimated-graph`

Bon courage mdr

2024-10-19 09:19 UTC, camarm-dev commented
Résolution des conflits = apparition de nouvelles merdes:
```
Found 60 errors in 20 files.
```

J'espère réussir à tout corriger et à faire fonctionner cette app 😓

2024-10-19 09:33 UTC, Kgeek33 commented
C'est mieux que les 268 du début 😂

2024-10-20 11:16 UTC, Kgeek33 commented
@camarm-dev je vais t'aider :)

2024-10-20 11:22 UTC, camarm-dev commented
> @camarm-dev je vais t'aider :)

Viens sur ds alors 😉 https://discordapp.com/users/690581743425814548

2024-10-20 12:01 UTC, Kgeek33 commented
Je reprendrai en rentrant chez moi ce soir
J'ai résolu quelques erreurs assez facile à corriger. VScode me dit ça maintenant : 

> Found 49 errors in 10 files.

> > @camarm-dev je vais t'aider :)
> 
> Viens sur ds alors 😉 https://discordapp.com/users/690581743425814548

J'essaye de venir ce soir ou demain :)

2024-10-20 12:06 UTC, camarm-dev commented
> Je reprendrai en rentrant chez moi ce soir J'ai résolu quelques erreurs assez facile à corriger. VScode me dit ça maintenant :
> 
> ```
> Found 49 errors in 10 files.
> ```
> 
> > > @camarm-dev je vais t'aider :)
> > 
> > 
> > Viens sur ds alors 😉 https://discordapp.com/users/690581743425814548
> 
> J'essaye de venir ce soir ou demain :)

ah j'ai déjà tout résolu moi (sauf les 2 des nodes modules)

2024-10-20 12:11 UTC, Kgeek33 commented
Ah j'ai oublié de faire un git pull, j'crois 🤦
Quelles modules ?

2024-10-20 12:35 UTC, camarm-dev commented
> Ah j'ai oublié de faire un git pull, j'crois 🤦 Quelles modules ?

Nan j'avais pas push c'est de ma faute désolé ! Le linter trouve des problèmes dans `react-native-reanimated-graph` et dans `react-native-infinite-pager`...

2024-10-20 12:56 UTC, Kgeek33 commented
c pas grave
ok je regarde ça

2024-10-20 13:25 UTC, Kgeek33 commented
applique ces conversations et relance le GitHub actions. Si tjrs erreur, on peut skip pour le module `react-native-reanimated-graph`

2024-10-20 13:25 UTC, Kgeek33 commented
Et mets à jour le fichier `package-lock.json`, comme t'as changé le fichier `package.json`

2024-10-20 13:33 UTC, camarm-dev commented
> applique ces conversations et relance le GitHub actions. Si tjrs erreur, on peut skip pour le module `react-native-reanimated-graph`

J'ai énormément regarder, le seul moyen que je vois est **de skip le module** du typecheck mais impossible de réaliser ça... (j'ai beaucoup cherché et tester mais rien trouver...)

2024-10-20 13:34 UTC, camarm-dev commented
> Et mets à jour le fichier `package-lock.json`, comme t'as changé le fichier `package.json`

j'utilise pnpm 🤓...

2024-10-20 13:39 UTC, Kgeek33 commented
> j'utilise pnpm 🤓... 

A
J'peux pas push de commit, j'suis pas autorisé

2024-10-20 13:40 UTC, Kgeek33 commented
> > applique ces conversations et relance le GitHub actions. Si tjrs erreur, on peut skip pour le module `react-native-reanimated-graph`
> 
> J'ai énormément regarder, le seul moyen que je vois est **de skip le module** du typecheck mais impossible de réaliser ça... (j'ai beaucoup cherché et testé mais rien trouvé...)

Regarde mes reviews et applique les mdof8s que je te suggère
J'vais en rajouter une pour exclure le module

2024-10-20 13:42 UTC, camarm-dev commented
> > j'utilise pnpm 🤓...
> 
> A J'peux pas push de commit, j'suis pas autorisé

je vais faire une install npm tqt mais sinon t'as pas fini ta review les conv ne s'affichent pas ! Bon courage pour exclure le module 🤣

2024-10-20 13:44 UTC, Kgeek33 commented
> > > j'utilise pnpm 🤓...
> > 
> > A J'peux pas push de commit, j'suis pas autorisé
> 
> je vais faire une install npm tqt mais sinon t'as pas fini ta review les conv ne s'affichent pas ! Bon courage pour exclure le module 🤣 

Ah oui effectivement, j'arrange ça

2024-10-20 13:45 UTC, Kgeek33 requested changes
C bon ?

2024-10-20 13:45 UTC, Kgeek33 commented on package.json
>      "react-native-infinite-pager": "^0.3.16",
Met à jour vers la dernière version pour résoudre un des bugs ts
```suggestion
    "react-native-infinite-pager": "^0.3.18",
```

2024-10-20 13:45 UTC, Kgeek33 commented on package.json
> +    "typescript": "^5.3.3"
Peut-être mettre à jour vers la dernière version pour résoudre tous les bugs ?
```suggestion
    "typescript": "^5.6.3"
```

2024-10-20 13:45 UTC, Kgeek33 commented on .github/workflows/checks.yml
> +        run: pnpm lint
```suggestion
        run: pnpm lint --filter=!./node_modules/react-native-infinite-pager
```

2024-10-20 13:46 UTC, camarm-dev commented
> C bon ?

C'est mieux oui

2024-10-20 13:49 UTC, camarm-dev commented on .github/workflows/checks.yml
> +        run: pnpm lint
Si il y a un filtre à mettre c'est dans le package.json et il est inutile ici puisque c'est le `tsc` qui échoue et non pas le lint...

2024-10-20 13:50 UTC, camarm-dev commented on package.json
>      "react-native-infinite-pager": "^0.3.16",
ça a rien changé mais why not !

2024-10-20 13:53 UTC, camarm-dev commented on package.json
> +    "typescript": "^5.3.3"
ne change rien 😞...

2024-10-20 13:53 UTC, Kgeek33 commented on package.json
>      "react-native-infinite-pager": "^0.3.16",
Ah c'est bizarre, alors ça marchait sur une version < 0.3.16

2024-10-20 13:56 UTC, Kgeek33 commented
En soi, ce sont juste des erreurs dans node_modules, on peut skip un peu

2024-10-20 13:57 UTC, Kgeek33 commented
Pour le pnpm lint, faudrait juste skip le dossier node_modules, plus simple non ?

2024-10-20 14:04 UTC, camarm-dev commented
> Pour le pnpm lint, faudrait juste skip le dossier node_modules, plus simple non ?

Comme je l'ai déjà dis j'ai fais des recherches et c'est impossible... Les erreurs proviennent de la manière dont notre projet est configuré et dont on importe les modules donc c'est un peu chelou. C'est impossible d'ignorer des fichiers du typecheck puisque tsc est un peu têtu. Le problème qu'on a c'est qu'il check les modules importés pour je ne sais quelle raison et pour l'obliger à ne pas le faire il faudrait utiliser des `require` mais c'est pas possible dans le cas où on importe des types depuis ces modules... Donc je vois vraiment pas comment faire c'est pour ça que je suis bloqué depuis quelques temps...

2024-10-20 14:07 UTC, camarm-dev commented
Et ajoute moi sur discord pour discuter ce sera bien mieux...

2024-10-20 14:09 UTC, Kgeek33 commented
> Et ajoute moi sur discord pour discuter ce sera bien mieux...

Oui, j'vais faire ça tout à l'heure, j'pars rentrer chez moi (long trajet de 2h...)

2024-10-21 11:37 UTC, Kgeek33 requested changes
Après bcg de renseignement hier, voic les solutions possibles : 

1. **Modifier le fichier `eslint.config.js`** en ajoutant ceci dans le module.exports : 
```
{
    ignores: [".node_modules/"]
}
```

2. **Modifier le fichier `tsconfig.json`** en ajoutant ceci : 
```
{
  "exclude": ["node_modules"]
}
```

3. Change ton `checks.yml` avec ceci (_mais faut voir si on a bien un github token_) : [https://github.com/marketplace/actions/lint-action](https://github.com/marketplace/actions/lint-action)

2024-10-21 11:38 UTC, Kgeek33 commented
Et Discord, je n'arrive plus à retrouver mon compte, et je t'avoue que j'ai un peu la flm d'en refaire un 🤣

2024-10-21 11:48 UTC, camarm-dev commented
> Après bcg de renseignement hier, voic les solutions possibles : 
> 
> 1. **Modifier le fichier `eslint.config.js`** en ajoutant ceci dans le module.exports : 
> ```
> {
>     ignores: [".node_modules/"]
> }
> ```
> 
> 2. **Modifier le fichier `tsconfig.json`** en ajoutant ceci : 
> ```
> {
>   "exclude": ["node_modules"]
> }
> ```
> 
> 3. Change ton `checks.yml` avec ceci (_mais faut voir si on a bien un github token_) : [https://github.com/marketplace/actions/lint-action](https://github.com/marketplace/actions/lint-action)

Alors je vais me re-répeter mais aucune des solutions est valable... Eslint n'a rien a voir avec le crash de `tsc` et les excludes du tsconfig excluent du "build" mais pas du typecheck... 
L'histoire du Github Token j'ai pas bien compris, mon workflow fait bien ce qui est attendu c'est juste le typecheck qui ne passe pas... (le workflow exécute juste `pnpm lint`)

En gros on est juste bloqué, il faut trouver un moyen d'exclure les fichiers problématiques OU trouver pourquoi ça ne fonctionne pas (problème de config ts ? problème d'utilisation des modules ? de dépendance ?)...

J'ai réussi à faire passer le typecheck à l'aide de `// @ts-ignore` aux endroits problématiques dans les nodes_modules. C'est pas une solution viable (on va pas demander a tout le monde de modifier les nodes_modules).

Voilà voilà j'espère que c'est clair, je vais essayer de continuer mes recherches et de maintenir cette PR à jour...

2024-10-21 11:58 UTC, Kgeek33 commented
ouais ok je comprends mieux, déso de te faire répéter 😅
c vrai que `// @ts-ignore` n'est pas vrmt recommandé, continuons de chercher...

2024-10-21 19:47 UTC, camarm-dev commented
> ouais ok je comprends mieux, déso de te faire répéter 😅
> c vrai que `// @ts-ignore` n'est pas vrmt recommandé, continuons de chercher... 

Pas de soucis le problème est vraiment complexe à imaginer 😭 Le problème avec le `ts-ignore` c'est qu'il faut le mettre dans les nodes_modules en plus... Merci de m'aider en tout cas ! 😉

2024-10-25 11:45 UTC, Kgeek33 commented
@camarm-dev salut ! j'ai une bonne et une mauvaise nouvelle :)

2024-10-26 13:28 UTC, camarm-dev commented
> @camarm-dev salut ! j'ai une bonne et une mauvaise nouvelle :)

Je t'écoute.

2024-10-26 13:36 UTC, Kgeek33 commented
J'ai réussi à résoudre tous les problèmes de typage dans les node_modules, sans utiliser `// @ts-ignore` !!
Je vais te suggérer les modifs à faire

MAIS...

2024-10-26 13:38 UTC, Kgeek33 commented
Quand j'ai résolu tous les problèmes, ça m'a généré **plus de 21000 erreurs** à cause...
D'une indentation incorrecte 🤣😭

2024-10-26 13:41 UTC, Kgeek33 commented on babel.config.js
> +export default function (api) {
Pour pas poser problème de build avec Expo : 
```suggestion
module.exports = function (api) {
```

2024-10-26 13:42 UTC, Kgeek33 commented on package-lock.json
A réactualiser comme la version de `react-native-infinite-pager` a changé

2024-10-26 13:43 UTC, Kgeek33 commented on src/components/Global/InfiniteDatePager.tsx
> +import {InfinitePagerImperativeApi, InfinitePagerPageComponent} from "react-native-infinite-pager/src";
Résoud 1 des 2 erreurs du node_modules
```suggestion
import {InfinitePagerImperativeApi, InfinitePagerPageComponent} from "react-native-infinite-pager";
```

2024-10-26 13:45 UTC, Kgeek33 commented on src/services/skolengo/skolengo-account.ts
La 1ère ligne, supprimer `import { ReanimatedGraphPublicMethods } from "@birdwingo/react-native-reanimated-graph";`

2024-10-26 13:45 UTC, camarm-dev commented on src/components/Global/InfiniteDatePager.tsx
> +import {InfinitePagerImperativeApi, InfinitePagerPageComponent} from "react-native-infinite-pager/src";
Chez moi ça avait rien changé mais si ça fonctionne super 😃

2024-10-26 13:45 UTC, camarm-dev commented
> Quand j'ai résolu tous les problèmes, ça m'a généré **plus de 21000 erreurs** à cause... D'une indentation incorrecte 🤣😭

C'est normal là on résoud le typecheck et après il faudra corriger les erreurs de lint.

2024-10-26 13:49 UTC, Kgeek33 requested changes
Et en dernier, changer dans le fichier `src/views/account/Grades/Graph/GradesAverage.tsx` : 

![image](https://github.com/user-attachments/assets/b6144e4d-acb1-47f9-84b9-7a323444c379)

2024-10-26 13:50 UTC, camarm-dev commented
> Et en dernier, changer dans le fichier `src/views/account/Grades/Graph/GradesAverage.tsx` :
> 
> ![image](https://private-user-images.githubusercontent.com/164187100/380427146-b6144e4d-acb1-47f9-84b9-7a323444c379.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5NTA4ODMsIm5iZiI6MTcyOTk1MDU4MywicGF0aCI6Ii8xNjQxODcxMDAvMzgwNDI3MTQ2LWI2MTQ0ZTRkLWFjYjEtNDdmOS04NGI5LTdhMzIzNDQ0YzM3OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNlQxMzQ5NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMzlhMzRlZWM1YTU0NDcyNzU5ZmJlM2ZkN2FmYjVmMmI3YWNmMjdhMmI0NzYxNTRiNzhmYTk0NTYyZTVkMTYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.R6EybccPZBVFtj9bWRKG5cuDvuRWrAKI3TIh74kp9FE)

Envoie la ligne flemme de recopier là 😭. Sinon c'est super faudra juste voir le require risque de pas passer mais je vois l'idée c'est super j'y avais pas penser !

2024-10-26 13:51 UTC, camarm-dev commented on package-lock.json
J'ai remis à `0.3.18`

2024-10-26 13:51 UTC, Kgeek33 commented
> > Et en dernier, changer dans le fichier `src/views/account/Grades/Graph/GradesAverage.tsx` :
> > ![image](https://private-user-images.githubusercontent.com/164187100/380427146-b6144e4d-acb1-47f9-84b9-7a323444c379.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5NTA4ODMsIm5iZiI6MTcyOTk1MDU4MywicGF0aCI6Ii8xNjQxODcxMDAvMzgwNDI3MTQ2LWI2MTQ0ZTRkLWFjYjEtNDdmOS04NGI5LTdhMzIzNDQ0YzM3OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNlQxMzQ5NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMzlhMzRlZWM1YTU0NDcyNzU5ZmJlM2ZkN2FmYjVmMmI3YWNmMjdhMmI0NzYxNTRiNzhmYTk0NTYyZTVkMTYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.R6EybccPZBVFtj9bWRKG5cuDvuRWrAKI3TIh74kp9FE)
> 
> Envoie la ligne flemme de recopier là 😭. Sinon c'est super faudra juste voir le require risque de pas passer mais je vois l'idée c'est super j'y avais pas penser !

```
import { ReanimatedGraphProps, ReanimatedGraphPublicMethods } from "@birdwingo/react-native-reanimated-graph/src/core/dto/graphDTO";
const ReanimatedGraph: React.ForwardRefExoticComponent<ReanimatedGraphProps & React.RefAttributes<ReanimatedGraphPublicMethods>> = require("@birdwingo/react-native-reanimated-graph");
```

2024-10-26 13:54 UTC, camarm-dev commented
Heyyy ça fonctionne 🥳 ! Merci beaucoup là ! Je résoud les erreurs de linter maintenant !

2024-10-26 13:55 UTC, Kgeek33 commented
Cool !
Utilise Prettier

2024-10-26 13:56 UTC, Kgeek33 commented
Très rapide quand tu connais la commande pour exécuter la commande (VSCode) : `Maj` + `Alt` + `F`

2024-10-26 13:58 UTC, camarm-dev commented
J'ai ping tout les owners mybad la PR est ouverte mais pas testée...

2024-10-26 13:59 UTC, Kgeek33 commented
Je vais la tester att

2024-10-26 14:00 UTC, Kgeek33 commented
Supprime ton pnpm-lock.json pour tester ton checks.yml

2024-10-26 14:06 UTC, Vexcited commented
> Cool ! Utilise Prettier

Utilisez PAS Prettier s'il vous plait ! J'ai configuré eslint pour qu'il fasse le lint en même temps (avec stylistic) pour justement éviter de faire une configuration eslint x prettier (qui est extrêmement chiant à maintenir, voir <https://antfu.me/posts/why-not-prettier>)

2024-10-26 14:07 UTC, camarm-dev commented
> > Cool ! Utilise Prettier
> 
> Utilisez PAS Prettier s'il vous plait ! J'ai configuré eslint pour qu'il fasse le lint+style en même temps (avec stylistic) pour justement éviter de faire une configuration eslint x prettier (qui est extrêmement chiant à maintenir, voir https://antfu.me/posts/why-not-prettier)

Je l'ai pas écouté tqt j'ai utilisé la configuration actuelle 🤣 👍🏻

2024-10-26 14:08 UTC, Kgeek33 commented
> > Cool ! Utilise Prettier
> 
> Utilisez PAS Prettier s'il vous plait ! J'ai configuré eslint pour qu'il fasse le lint+style en même temps (avec stylistic) pour justement éviter de faire une configuration eslint x prettier (qui est extrêmement chiant à maintenir, voir <https://antfu.me/posts/why-not-prettier>)

Ah 😅 d'accord je retiens !

2024-10-26 14:14 UTC, Kgeek33 commented
Euh vos tests fonctionnent ?
Moi, j'suis sur une page d'accueil figé
![Screenshot_2024-10-26-16-14-05-299_host.exp.exponent.jpg](https://github.com/user-attachments/assets/7501a940-ac6d-4437-9c20-7b18fd39eac4)

2024-10-26 14:14 UTC, Kgeek33 commented
Sauf s'il faut se reconnecter ?

2024-10-26 14:20 UTC, camarm-dev commented
> Sauf s'il faut se reconnecter ?

Je sais pas je vais testé mais j'ai peut être cassé qqch c'est pas impossible

2024-10-26 14:21 UTC, Kgeek33 commented
J'ai testé en supprimant toutes les données, bloqué

2024-10-26 14:21 UTC, Kgeek33 commented
Ça doit être un module qui est défaillant

2024-10-26 14:30 UTC, Vexcited reviewed
C'est tout ce que j'ai à dire pour l'instant.
De plus, j'ai remarqué la présence de pnpm-lock.yml dans le projet maintenant, vu que le projet utilise seulement `npm` actuellement, je sais pas trop s'il faudrait switch vers `pnpm` dans l'état actuel...

Il faudrait supprimer `package-lock.json` si vous voulez faire le switch vers `pnpm`, mais je ne le recommande pas vraiment (car de souvenir il y avait des soucis avec react-native)

2024-10-26 14:30 UTC, Vexcited commented on src/addons/types.ts
> +  type: "log" | "error" | "warn" | "info" | string,
Faire `| string` rend l'union complétement inutile, autant faire `type: string` à ce moment là...

Je pense que pour résoudre les erreurs de type lors de l'utilisation, il faudrait probablement un `enum` comme ça on peut cast le type si besoin

2024-10-26 14:30 UTC, Vexcited commented on src/background/Notifications.ts
> +const papillonNotify = async (props: papillonNotifyProps) => {
On peut pas importer les types de la fonction `displayNotification` de `@notifee/react-native` pour les assigner à notre fonction à la place de les typer nous même ?

2024-10-26 14:30 UTC, Vexcited commented on src/services/local/utils/reduceIcalToCourse.ts
> +export const reduceIcalToCourse = (course: any, identityProvider: any, url: string): TimetableClass => {
`any` est la seule façon ici ?

2024-10-26 14:30 UTC, Vexcited commented on src/services/uphf/data/timetable.ts
> +      groups: []
@tom-theret on aurait besoin de précisions sur cette implémentation, pourquoi faire un item avec toutes les propriétés `null` si il n'y a rien ?

2024-10-26 14:30 UTC, Vexcited commented on src/views/account/Homeworks/Homeworks.tsx
> +        // @ts-ignore
Privilégiez `ts-expect-error` à la place de `ts-ignore` (pareil avec les autres présents dans ce fichier)

Ça permet d'être prévenu dès que l'erreur TS n'apparaît plus et que le commentaire est désormais inutile

2024-10-26 14:35 UTC, Kgeek33 commented
> C'est tout ce que j'ai à dire pour l'instant.
> 
> De plus, j'ai remarqué la présence de `pnpm-lock.yml` dans le projet maintenant, vu que le projet utilise seulement `npm` actuellement je ne sais pas trop s'il faudrait switch vers `pnpm` dans l'état actuel...
> 
> Il faudrait supprimer `package-lock.json` si vous voulez faire le switch vers `pnpm`, mais je ne le recommande pas vraiment (car de souvenir il y avait des soucis avec react-native)

J'pense qu'il est préférable de privilégier npm plutôt sur pnpm
Après, c'est que mon avis

2024-10-26 14:50 UTC, camarm-dev commented on src/services/local/utils/reduceIcalToCourse.ts
> +export const reduceIcalToCourse = (course: any, identityProvider: any, url: string): TimetableClass => {
oui c'est une réponse dont je n'ai pas le contenu... impossible pour moi de typer autrement, le `any` permet de faire passer le typecheck

2024-10-26 14:52 UTC, Gabriel29306 commented
`npm` est livré avec node donc plus simple pour la plupart des users

2024-10-26 14:59 UTC, camarm-dev commented on src/addons/types.ts
> +  type: "log" | "error" | "warn" | "info" | string,
Enfaite j'ai fais ça car outre le fait que ces types soient inutilisés car l'implémentation des addons n'est pas terminée (voire presque pas commencée), il y a un mélange entre le type `Log`, les logs de l'app (je pense), et `AddonLogs`, les logs d'un addon dans les paramètres des routes (`src/router/helpers/types.ts`). Je vais voir si modifier le type directement dans les paramètres de la route ne pose pas de problèmes.

2024-10-26 15:07 UTC, camarm-dev commented on src/addons/types.ts
> +  type: "log" | "error" | "warn" | "info" | string,
Résolu

2024-10-26 16:42 UTC, camarm-dev commented
- Bonne nouvelle j'ai résolu le bug qui empechait de faire quoique ce soit dans l'app (on pouvait pas changer de page enfaite)
- Mauvaise nouvelle le `require` ne fonctionne pas (@Kgeek33): 
```
 ERROR  Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.
```

2024-10-26 16:46 UTC, Kgeek33 commented
> - Bonne nouvelle j'ai résolu le bug qui empechait de faire quoique ce soit dans l'app (on pouvait pas changer de page enfaite)
> - Mauvaise nouvelle le `require` ne fonctionne pas (@Kgeek33): 
> ```
>  ERROR  Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.
> ```

Cool pour le changer de page, j'vais pouvoir retester

Pour le require, ça ne me surprend pas, j'ai fait un copié collé du typages dans le node_modules
J'vais voir pour une solution de contournement (_pour l'instant, tu peux mettre de type any le temps que je trouve_)

2024-10-26 16:49 UTC, camarm-dev commented
> > * Bonne nouvelle j'ai résolu le bug qui empechait de faire quoique ce soit dans l'app (on pouvait pas changer de page enfaite)
> > * Mauvaise nouvelle le `require` ne fonctionne pas (@Kgeek33):
> > 
> > ```
> >  ERROR  Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.
> > ```
> 
> Cool pour le changer de page, j'vais pouvoir retester
> 
> Pour le require, ça ne me surprend pas, j'ai fait un copié collé du typages dans le node_modules J'vais voir pour une solution de contournement (_pour l'instant, tu peux mettre de type any le temps que je trouve_)

Le type est très bien ! C'est le fait de faire un require pour importer un composant que ne plait pas à React (il doit prendre `ReanimtedGraph` pour un objet quelconque...)

2024-10-26 16:53 UTC, camarm-dev commented
Oui c'est cela, React attend une fonction ou une classe mais `ReanimatedGraph` est interprété comme object (à cause du require très certainement)

2024-10-26 16:57 UTC, Kgeek33 commented
ahh j'ai ma 1ère erreur lors de la connexion
je regarde où

et je regarde aussi pour le require

2024-10-26 17:04 UTC, Gabriel29306 commented
Peut-être que de mettre :
```ts
const ReanimatedGraph ...
```
On peut le remplacer par:
```ts
type ReanimatedGraph ...
```
(Je suis pas sûr, j'ai pas testé)

2024-10-26 17:06 UTC, camarm-dev commented
> Peut-être que de mettre :
> 
> ```ts
> const ReanimatedGraph ...
> ```
> 
> On peut le remplacer par:
> 
> ```ts
> type ReanimatedGraph ...
> ```
> 
> (Je suis pas sûr, j'ai pas testé)

Ça fonctionne pas malheureusement... @Kgeek33 où tu as une erreur j'ai rien moi ?

2024-10-26 17:07 UTC, Kgeek33 reviewed
ah mais j'ai crée moi même un bug sur une pr
voici la correction à faire

2024-10-26 17:07 UTC, Kgeek33 commented on src/views/account/Home/Elements/HomeworksElement.tsx
Ligne 57 et 58, préciser les variables `hwFinalList` et `hwFinalList2` avec le typage suivant : `undefined | Homework[]`
Ligne 60, remplacer le if comme ceci : `if (!hwFinalList || hwFinalList.length === 0) {`

2024-10-26 17:08 UTC, Kgeek33 commented
> Ça fonctionne pas malheureusement... @Kgeek33 où tu as une erreur j'ai rien moi ?

ça arrive 1 fois sur 2 ces erreurs là

2024-10-26 17:08 UTC, Kgeek33 commented
Alors pour le require...

2024-10-26 17:10 UTC, camarm-dev commented on src/views/account/Home/Elements/HomeworksElement.tsx
euuuh je comprend pas ça peut pas être undefined les variable (seulement des listes vides à la limite)

2024-10-26 17:13 UTC, Kgeek33 commented on src/views/account/Home/Elements/HomeworksElement.tsx
j'ai fais des console.log(hwFinalList) et ça renvoie undefinded, jspas pq

2024-10-26 17:14 UTC, Kgeek33 commented on src/views/account/Home/Elements/HomeworksElement.tsx
ah si, pask `homeworks[(new Date().getDay() === 6 || new Date().getDay() === 0) ? dateToEpochWeekNumber(actualDay) + 1 : dateToEpochWeekNumber(actualDay)]` peut-être undefined

2024-10-26 17:14 UTC, camarm-dev commented on src/views/account/Home/Elements/HomeworksElement.tsx
ah écoute je vais rien toucher moi là si on est pas vraiment sur...

2024-10-26 17:18 UTC, Kgeek33 commented on src/views/account/Home/Elements/HomeworksElement.tsx
le problème, (_en plus, il y avait une pr pour résoudre ça par qqun mais closed depuis_), ça affiche une erreur d'impossibilité de lire de length

à la limite, change juste le if et touche pas au typage

2024-10-26 17:32 UTC, Kgeek33 reviewed
Trouvé pour le `require` !

2024-10-26 17:32 UTC, Kgeek33 commented on src/views/account/Grades/Graph/GradesAverage.tsx
> +const ReanimatedGraph: React.ForwardRefExoticComponent<ReanimatedGraphProps & React.RefAttributes<ReanimatedGraphPublicMethods>> = require("@birdwingo/react-native-reanimated-graph");
```suggestion
const ReanimatedGraph = require("@birdwingo/react-native-reanimated-graph").default as React.ForwardRefExoticComponent<ReanimatedGraphProps & React.RefAttributes<ReanimatedGraphPublicMethods>>;
```

2024-10-26 17:35 UTC, Kgeek33 commented on src/views/account/Grades/Graph/GradesAverage.tsx
> +const ReanimatedGraph: React.ForwardRefExoticComponent<ReanimatedGraphProps & React.RefAttributes<ReanimatedGraphPublicMethods>> = require("@birdwingo/react-native-reanimated-graph");
ou alors : 
```suggestion
const ReanimatedGraph: React.ForwardRefExoticComponent<ReanimatedGraphProps & React.RefAttributes<ReanimatedGraphPublicMethods>> = require("@birdwingo/react-native-reanimated-graph").default;
```

2024-10-26 17:50 UTC, camarm-dev commented on src/views/account/Home/Elements/HomeworksElement.tsx
oui

2024-10-26 17:50 UTC, camarm-dev commented
Et bien j'ai l'impression qu'on a terminé !

2024-10-26 17:56 UTC, Kgeek33 approved these changes
Tout est parfait 👌
Bon, juste les animations foireuses sur certaines pages (où ça provoque un écran noir de temps en temps) mais dans une autre PR, non ? 
---
Testé depuis Pronote

2024-10-26 17:56 UTC, Kgeek33 commented
Mdrr jspas pq ça m'a mis le texte en gros 😂

2024-10-26 19:16 UTC, tom-theret commented on src/services/uphf/data/timetable.ts
> +      groups: []
J'ai écrit ça moi ?!

2024-10-26 19:20 UTC, tom-theret commented
**S’il vous plaît, merci de ne pas toucher au fichier UPHF, je sais qu'il y a 1 problème de types sur 1 ligne mais elle était inévitable quand j'ai créer cette implémentation. 
Maintenant il y a peut-être des nouveaux truc dans Papillon, au quel cas je ferai ma PR de mon côté !**

2024-10-26 19:33 UTC, merged

2024-10-26 19:34 UTC, Kgeek33 commented
Gg @camarm-dev