Enable dev mode
PapillonApp/papillon-v7 pull request #266
Opened 2024-10-05 23:11 UTC by Slysoks

# 🚀 Nouvelle Pull Request

Proposez vos modifications pour améliorer Papillon

## Informations importantes

Merci de vous référer à la documentation sur la contribution si vous avez des questions à propos des pull requests (https://gitbook.getpapillon.xyz/organisation/outils-internes/github)

## Checklist d'avant pull request

Veuillez cocher toutes les cases applicables en remplaçant [ ] par [x].

- [ ] Vous avez testé de build le projet avec vos modifications et ce build **a réussi**
- [ ] Vous respectez les conventions de codage et de nommage du projet
- [ ] Vous utilisez la **tabulation** pour l'indentation afin de maintenir un code lisible
- [ ] Cette pull request **n'est pas un duplicata** d'une autre
- [ ] Cette pull request est prête à être **revue** (review) et **fusionnée** (merge)
- [ ] Il n'y a pas de **`TODO`** (aka des annotations pour du code manquant) dans vos modifications
- [ ] Il n'y a pas **d'erreurs de langue** dans votre code (grammaire, vocabulaire, conjugaison, orthographe)
- [ ] Les détails des changements ont été décrits ci-dessous
- [ ] Cette pull-request n'est pas une **"breaking-change"** (des modifications qui vont entraîner la modification du fonctionnement de certaines fonctionnalités déjà existantes)

## Changelogs proposés

Ajout du mode développeur stocké dans le cache (id: "devmode").

## Informations supplémentaires

Il permet d'accéder au bouton pour voir les logs dans la liste de vues des paramètres. Ne s'applique pas sur iOS étant donné l'utilisation du showAlert nondéployable sur iOS

2024-10-06 07:22 UTC, Gabriel29306 requested changes

2024-10-06 07:22 UTC, Gabriel29306 commented on src/views/settings/SettingsAbout.tsx
> +              alert("Pour appliquer les changements, redémarrez l'application.");
Au lieu de faire ça, tu ne peux pas rediriger les gens directement vers l'écran de dev ?

2024-10-06 07:22 UTC, Gabriel29306 commented on src/views/settings/SettingsAbout.tsx
> +            () => Platform.OS === "android" ? setClickedOnDependencies(clickedOnDependencies + 1) : navigation.navigate("SettingsDevLogs")
Pourquoi faire différemment entre les plateformes ?

2024-10-06 08:49 UTC, Slysoks commented on src/views/settings/SettingsAbout.tsx
> +              alert("Pour appliquer les changements, redémarrez l'application.");
Nn, car il existe le mode dev qui n'était pas encore utilisé et donc quand on clique 8 fois ça active ou désactive. Et sur iOS y'a pas les modals je crois donc là ça redirige tt seul

2024-10-06 08:49 UTC, Slysoks commented on src/views/settings/SettingsAbout.tsx
> +            () => Platform.OS === "android" ? setClickedOnDependencies(clickedOnDependencies + 1) : navigation.navigate("SettingsDevLogs")
iOS ne supporte pas les modals

2024-10-06 13:40 UTC, LeGeek01 commented on src/views/settings/SettingsAbout.tsx
> +            () => Platform.OS === "android" ? setClickedOnDependencies(clickedOnDependencies + 1) : navigation.navigate("SettingsDevLogs")
en es-tu sûr ? quand j'avais développé les devtools sur la v6 il n'y avait pas ce soucis de modals sur iOS, vince avait même arrangé le tout pour que ça fonctionne partout

2024-10-06 15:16 UTC, Gabriel29306 commented on src/views/settings/SettingsAbout.tsx
> +            () => Platform.OS === "android" ? setClickedOnDependencies(clickedOnDependencies + 1) : navigation.navigate("SettingsDevLogs")
C'est une histoire de contexte. 
Sur iOS, les paramètres s'affichent dans une modale, alors que sur Android c'est une autre view.

2024-10-09 09:54 UTC, tryon-dev requested changes
Utilise le store des flags plutôt qu'un asyncstorage random

2024-10-09 20:28 UTC, Slysoks commented
> Utilise le store des flags plutôt qu'un asyncstorage random

Mais en fait cet id est utilisé qq part, donc autant en faire usage nn ?

2024-10-19 09:53 UTC, tryon-dev commented
hein ?

2024-10-21 09:10 UTC, Gabriel29306 commented
> > Utilise le store des flags plutôt qu'un asyncstorage random
> 
> Mais en fait cet id est utilisé qq part, donc autant en faire usage nn ?

C'est surtout que les flags sont pratiques et simples d'utilisation

2024-10-25 10:38 UTC, tryon-dev commented
Si tu ne répond pas je close d'ici 2j

2024-10-25 11:08 UTC, Slysoks commented
> Si tu ne répond pas je close d'ici 2j

Tkt, je suis tjrs là, vu que j'ai du temps, je vais essayer de le mettre dans les stores

2024-11-16 16:52 UTC, tryon-dev commented
Inactivité

2024-11-16 16:52 UTC, closed without merging