Feat(News): intégration "J'ai pris connaissance..." + changes
PapillonApp/papillon-v7 pull request #281
Opened 2024-10-09 21:36 UTC by Kgeek33

**Cette PR n'est pas en rapport avec #271**

# 🚀 Nouvelle Pull Request

Proposez vos modifications pour améliorer Papillon

## Informations importantes

Merci de vous référer à la documentation sur la contribution si vous avez des questions à propos des pull requests (https://gitbook.getpapillon.xyz/organisation/outils-internes/github)

## Checklist d'avant pull request

Veuillez cocher toutes les cases applicables en remplaçant [ ] par [x].

- [x] Vous avez testé de build le projet avec vos modifications et ce build **a réussi**
- [x] Vous respectez les conventions de codage et de nommage du projet
- [x] Vous utilisez la **tabulation** pour l'indentation afin de maintenir un code lisible
- [x] Cette pull request **n'est pas un duplicata** d'une autre
- [x] Cette pull request est prête à être **revue** (review) et **fusionnée** (merge)
- [x] Il n'y a pas de **`TODO`** (aka des annotations pour du code manquant) dans vos modifications
- [x] Il n'y a pas **d'erreurs de langue** dans votre code (grammaire, vocabulaire, conjugaison, orthographe)
- [x] Les détails des changements ont été décrits ci-dessous
- [x] Cette pull-request n'est pas une **"breaking-change"** (des modifications qui vont entraîner la modification du fonctionnement de certaines fonctionnalités déjà existantes)

## Changelogs proposés

- Ajout d"une CheckBox "J'ai lu et pris connaissance" lorsqu'une actualité demande un accusé de réception (_en gros_)
- Conversion variable `message` -> useState
  - Permet un affichage dynamique du texte "Marquer comme (non) lu"
  - Changement dynamique de ce useState lorsqu'on clique sur ce bouton
- Indentation du code effectué par Prettier

## Informations supplémentaires

1. Pronote interdit de décocher une actualité déjà accusé de réception. Du coup, il est impossible de décocher la checkBox
2. _les captures arrivent bientôt_

Closed #275

2024-10-11 16:43 UTC, Rexxt commented
2 minutes je regarde tout ça

2024-10-11 16:46 UTC, Rexxt approved these changes
LGTM, c'est propre

2024-10-11 16:46 UTC, Rexxt commented on src/views/account/News/Document.tsx
> +          paddingTop: !message.ref.needToAcknowledge ? 96 : 0,
peut-être `mustAcknowledge` serait plus correct que `needToAcknowledge`

2024-10-11 16:46 UTC, Rexxt commented on src/views/account/News/Document.tsx
> +                  color: message.acknowledged ? "grey" : theme.dark ? "white" : "dark",
toujours aussi immonde l'opérateur ternaire, mais ça c'est un avis perso

2024-10-11 16:57 UTC, Kgeek33 commented on src/views/account/News/Document.tsx
> +          paddingTop: !message.ref.needToAcknowledge ? 96 : 0,
ok je change ça de suite

2024-10-11 16:59 UTC, Kgeek33 commented on src/views/account/News/Document.tsx
> +                  color: message.acknowledged ? "grey" : theme.dark ? "white" : "dark",
je vais essayer de faire mieux :)

2024-10-11 17:08 UTC, Kgeek33 commented on src/views/account/News/Document.tsx
> +                  color: message.acknowledged ? "grey" : theme.dark ? "white" : "dark",
j'ai changé en : `message.acknowledged ? "grey" : theme.colors.text,`

2024-10-11 17:09 UTC, Kgeek33 commented on src/views/account/News/Document.tsx
> +          paddingTop: !message.ref.needToAcknowledge ? 96 : 0,
c'est fait ! (_avec la suppression du paddingTop qui servait à rien_)

2024-10-13 08:22 UTC, Rexxt approved these changes
ça m'a l'air bon, LGTM

2024-10-13 08:22 UTC, Rexxt commented on src/views/account/News/Document.tsx
>          <View style={{ paddingHorizontal: 16, marginTop: message.ref.needToAcknowledge ? 100 : 0 }}>
refactor la ligne là aussi

2024-10-13 16:27 UTC, tryon-dev commented
Mais pourquoi faire c'était déjà le cas nan ?

2024-10-13 16:41 UTC, Kgeek33 commented on src/views/account/News/Document.tsx
>          <View style={{ paddingHorizontal: 16, marginTop: message.ref.needToAcknowledge ? 100 : 0 }}>
j'avais même pas vu le marginTop dans le vue, j'enlève le contentContainerStyle dc

2024-10-13 16:42 UTC, Kgeek33 commented
@tryon-dev on pouvait juste marquer une actualité comme lue, pas la cocher dans certains cas

2024-10-15 21:28 UTC, Kgeek33 commented
> [!WARNING] 
> Sur le fichier `src/router/screens/views/index.ts`, **il faut préciser le type d'animation !**. Après, on aura des issues comme #140 

d'où le dernier commit "correction d'un affichage aléatoire"

2024-10-15 21:46 UTC, Kgeek33 commented
- @ecnivtwelve pq ? [https://github.com/PapillonApp/Papillon/commit/fe1431bcf2acb3a0d6877d0f72c360eede7949d7](https://github.com/PapillonApp/Papillon/commit/fe1431bcf2acb3a0d6877d0f72c360eede7949d7)
- @tryon-dev pq ? [https://github.com/PapillonApp/Papillon/commit/5a836e555862da9ccc68aaeed69b8755cdbb5241](https://github.com/PapillonApp/Papillon/commit/5a836e555862da9ccc68aaeed69b8755cdbb5241)

ça pose énormément de problèmes mtn (conflit avec les modifs de @tryon-dev sur les devs magics et conflit entre éduconnect et les autres services...)

2024-10-19 11:47 UTC, Kgeek33 commented
@tryon-dev

2024-10-27 13:02 UTC, ecnivtwelve requested changes
Ça n'a pas l'air de fonctionner chez moi...

2024-10-27 13:08 UTC, Kgeek33 commented
ah ?
qu'est-ce qui ne fonctionne pas ?

2024-10-27 20:01 UTC, Louis-htmlcss approved these changes

2024-10-27 20:02 UTC, Louis-htmlcss requested changes
Jsp si ta pr est en fait faite pour fix les notes sur le graphique

2024-10-27 20:05 UTC, Kgeek33 commented
Non cette pr c'est uniquement pour les actualités, je vais voir sur la 7.3 ce qui ne va pas

2024-10-27 20:14 UTC, Louis-htmlcss commented
> Non cette pr c'est uniquement pour les actualités, je vais voir sur la 7.3 ce qui ne va pas

Déso mdrr je me suis trompé de pr

2024-11-11 19:18 UTC, Gabriel29306 commented
@ecnivtwelve tu pourrais re review la PR ?

2024-11-11 19:19 UTC, Gabriel29306 commented
Toi aussi @Louis-htmlcss tu pourrais revoir ta review ?

2024-11-11 20:38 UTC, Louis-htmlcss approved these changes

2024-11-11 20:39 UTC, Louis-htmlcss commented
> Toi aussi @Louis-htmlcss tu pourrais revoir ta review ?

C'est good

2024-11-12 19:10 UTC, Gabriel29306 approved these changes

2024-11-16 16:41 UTC, ecnivtwelve commented
Il faut que je fasse une review supplémentaire, cependant le probléme étant que ton autre PR (https://github.com/PapillonApp/Papillon/pull/325) est si grosse qu'elle risque de break celle-ci, notamment vu les changements aux actualités.

2024-11-16 16:49 UTC, Kgeek33 commented
Je vais intégrer les changements de #325 directement dedans, comme ça, pas de risque de break

2024-11-16 21:43 UTC, Kgeek33 commented
@ecnivtwelve @Vexcited 
j'ai intégré des éléments de #325

2024-11-23 19:19 UTC, Rexxt commented
TODO : review

2024-11-23 19:58 UTC, Louis-htmlcss commented
> TODO : review

💀

2024-11-26 16:06 UTC, ecnivtwelve approved these changes
LGTM

2024-11-26 16:32 UTC, merged