Mutiples fixes
PapillonApp/papillon-v7 pull request #294
Opened 2024-10-17 20:11 UTC by Gabriel29306

# 🚀 Nouvelle Pull Request

Proposez vos modifications pour améliorer Papillon

## Informations importantes

Merci de vous référer à la documentation sur la contribution si vous avez des questions à propos des pull requests (https://gitbook.getpapillon.xyz/organisation/outils-internes/github)

## Checklist d'avant pull request

Veuillez cocher toutes les cases applicables en remplaçant [ ] par [x].

- [ ] Vous avez testé de build le projet avec vos modifications et ce build **a réussi**
- [x] Vous respectez les conventions de codage et de nommage du projet
- [x] Vous utilisez la **tabulation** pour l'indentation afin de maintenir un code lisible
- [x] Cette pull request **n'est pas un duplicata** d'une autre
- [ ] Cette pull request est prête à être **revue** (review) et **fusionnée** (merge)
- [x] Il n'y a pas de **`TODO`** (aka des annotations pour du code manquant) dans vos modifications
- [x] Il n'y a pas **d'erreurs de langue** dans votre code (grammaire, vocabulaire, conjugaison, orthographe)
- [x] Les détails des changements ont été décrits ci-dessous
- [x] Cette pull-request n'est pas une **"breaking-change"** (des modifications qui vont entraîner la modification du fonctionnement de certaines fonctionnalités déjà existantes)

## Changelogs proposés

fix: Centrage des icones pour les cours, les devoirs, widget LastGrade
fix: majuscules pour les noms de famille composés
fix: nom de police: semiBold => semibold
fix: icone de pièce jointe pour les communications
fix: bouton soutenir Papillon dans les paramètres
fix: chargement infini des actualités
fix: utilisation des safe area insets pour les views ayant un style de modale
refactor: Changement de l'animation pour les views ayant un style de modale
refactor: réarrangement des onglets dans SettingsTabs
refactor: configuration d'expo-font
refactor: nouvelles lignes entre les salles de classes
chore: Mise à jour des dépendances

## Informations supplémentaires

fix #279 
fix #256 
fix #233 
fix peut-être d'autres issues, maybe

2024-10-17 20:21 UTC, Gabriel29306 commented
Faut juste que je teste le tout puis je la met en ready

2024-10-17 20:44 UTC, Gabriel29306 commented
Bon, il n'y a plus d'animations pour les NewsItems, c'est pas trop grave

2024-10-17 21:15 UTC, Gabriel29306 commented
Je fais un build test et ça part en review

2024-10-18 12:09 UTC, Kgeek33 reviewed
Gg mais 3 points (_c'est le 1er qui me dérange surtout, mais j'aurai approve sinon_) : 
- Je trouve que la page Actualités extrêmement lente lors d'une ouverture d'une actualité
- Dommage pour les émojis mais tkt, j'ai prévu de refaire complètement l'affichage
- Bien joué pour les modals Android mais question. J'ai eu le réflexe de faire glisser la modal, mais fonctionne pas. C'est possible ? (_comme pour Apple_)

2024-10-18 12:18 UTC, Gabriel29306 commented
- Pour les actualités je ne sais pas d'où celà peut venir, c'est en fusionnant les changements que ça a foiré.
- Pour les emoji je m'en suis accupé, c'était rapide
- Pour les modales il faudrait revoir le fonctionnement pour faire comme sur Android

2024-10-18 12:28 UTC, Kgeek33 commented
- Oui moi aussi, depuis l'intégration d'école directe et d'autres modifs comme les devoirs intelligents, la page d'actualité est remplie de conflits et ça me casse ma pr #281 

- Pour les émojis, il y a un marginTop trop élevé, qui fait que l'émoji est un peu coupé (notamment l'émoji 🏀)

- J'ai trouvé ceci pour faire glisser une modal : [https://github.com/jefelewis/react-native-slide-modal](https://github.com/jefelewis/react-native-slide-modal)

2024-10-18 12:45 UTC, Gabriel29306 commented
Normalement j'ai réglé les emojis comme il faut, je vais vérifier que mes changements n'ont pas été overrides par le merge

2024-10-18 12:46 UTC, Kgeek33 commented
J'ai oublié de préciser, c'est sur la page d'accueil, la liste des dernières notes que ce comportement a lieu

2024-10-18 13:20 UTC, Gabriel29306 commented
C'est bon, c'est fait

2024-10-18 16:22 UTC, Kgeek33 approved these changes
LGTM 👍

Et j'ai trouvé la cause du problème de lenteur sur la page d'actualités. C'est pask qu'il est effectué 8 requêtes (_au lieu d'une_) pour mettre à jour le cache et Pronote

Faut voir quel useEffect pose problème ;)

2024-10-20 13:45 UTC, Kgeek33 requested changes
J'ai oublié de valider mes commentaires...

2024-10-20 13:45 UTC, Kgeek33 commented on src/views/account/News/News.tsx
>      navigation.addListener("focus", () => fetchData(true));
c'est cette ligne qui provoque une boucle infinie, faut la supprimer (_comme elle y est déjà dans le if d'après_)
```suggestion
```

2024-10-20 13:45 UTC, Kgeek33 commented on src/views/account/News/News.tsx
`account.personalization?.magicEnabled` n'existe plus depuis que les devoirs intelligents ont été intégrés, il faut remplacer par `account.personalization.MagicNews`

2024-10-20 22:45 UTC, Gabriel29306 commented
Pour les conflits faut que je passe par un ordi

2024-10-21 11:38 UTC, Kgeek33 commented
Je teste et je te dis si ça fonctionne

2024-10-21 11:49 UTC, Kgeek33 approved these changes
LGTM 👍

2024-10-21 11:50 UTC, Kgeek33 commented
T'en profiteras pour mettre à jour le fichier `package-lock.json` quand tu résoudras tes conflits 😉

2024-10-22 11:53 UTC, Kgeek33 reviewed
LGTM 👍
_Le `package-lock.json` n'est tjrs pas à jour, node me l'a encore modifié 😅_

2024-10-22 11:53 UTC, Kgeek33 approved these changes

2024-10-22 11:56 UTC, okayhappex commented
> LGTM 👍 _Le `package-lock.json` n'est tjrs pas à jour, node me l'a encore modifié 😅_

Pourquoi vous passez votre temps à insulter les mères sur ce repo ?

2024-10-22 11:56 UTC, Gabriel29306 commented
Node modifie quelle partie ?

2024-10-22 11:57 UTC, Gabriel29306 commented
> > LGTM 👍 _Le `package-lock.json` n'est tjrs pas à jour, node me l'a encore modifié 😅_
> 
> Pourquoi vous passez votre temps à insulter les mères sur ce repo ?

Hein ?

2024-10-22 11:59 UTC, Kgeek33 commented
> Node modifie quelle partie ?

![image](https://github.com/user-attachments/assets/9270c934-7a29-4026-a62a-57e411b18faf)

2024-10-22 11:59 UTC, Kgeek33 commented
> Pourquoi vous passez votre temps à insulter les mères sur ce repo ?

Sans commentaire...

2024-10-22 12:00 UTC, Kgeek33 commented
laisse tomber le react-native-slide-modal, j'suis en train de tester

2024-10-22 12:00 UTC, Gabriel29306 commented
> > Node modifie quelle partie ?
> 
> ![image](https://github.com/user-attachments/assets/9270c934-7a29-4026-a62a-57e411b18faf)
> 

Ah, bon c'est pas trop grave en vrai

2024-10-22 12:10 UTC, Kgeek33 commented
> > > Node modifie quelle partie ?
> > 
> > ![image](https://github.com/user-attachments/assets/9270c934-7a29-4026-a62a-57e411b18faf)
> > 
> 
> Ah, bon c'est pas trop grave en vrai

Oui ça va. Bon j'suis en train de tester pour faire glisser les modals sur Android. Si ça marche, j'te montre pour que tu l'intègres dans ta pr 😉

2024-10-22 12:26 UTC, Gabriel29306 commented
> Oui ça va. Bon j'suis en train de tester pour faire glisser les modals sur Android. Si ça marche, j'te montre pour que tu l'intègres dans ta pr 😉

C'est gentil mais non, le but de cet PR est de fixer quelques problèmes, pas d'ajouter des features

2024-10-22 12:41 UTC, Kgeek33 commented
> > Oui ça va. Bon j'suis en train de tester pour faire glisser les modals sur Android. Si ça marche, j'te montre pour que tu l'intègres dans ta pr 😉
> 
> C'est gentil mais non, le but de cet PR est de fixer quelques problèmes, pas d'ajouter des features

OK je le ferai dans une autre PR. T'en penses quoi en tout cas ?
https://github.com/user-attachments/assets/c2a9076e-6d00-4a67-be02-b9b2136276ee

2024-10-23 20:41 UTC, Gabriel29306 commented
@tryon-dev ce serait cool d'avoir ta review 😁

2024-10-25 10:39 UTC, tryon-dev commented
Hey je Check ça après

2024-10-28 17:11 UTC, Gabriel29306 commented
fix #317

2024-10-28 20:12 UTC, Gabriel29306 commented
@tryon-dev si tu pouvais review, ce serait cool. C'est un peu casse pied de devoir résoudre régulièrement les conflits 😅

2024-10-28 21:00 UTC, Kgeek33 commented
> @tryon-dev si tu pouvais review, ce serait cool. C'est un peu casse pied de devoir résoudre régulièrement les conflits 😅

Je suis tellement d'accord 🤣
Je review après le build de mon site ;)

2024-10-28 22:15 UTC, Kgeek33 approved these changes
LGTM 👍

2024-10-30 14:53 UTC, Kgeek33 commented
**SVP, acceptez cette pr !! Ça évitera les checks failed sur les nouvelles/actuelles pr, et corrigera bcp de bugs**

2024-10-30 19:12 UTC, Gabriel29306 commented
Il ne manque que @tryon-dev

2024-11-03 02:03 UTC, closed without merging

2024-11-03 02:04 UTC, Gabriel29306 commented
La PR a trop traînée et j'en ai marre de devoir résoudre les conflits à chaque autre PR acceptée. Flûte !

2024-11-03 09:22 UTC, Kgeek33 commented
Nonnnnnnn 😭😭😭😭

2024-11-03 09:23 UTC, Kgeek33 commented
J'peux te "l'emprunter"? 😂😂

2024-11-03 10:59 UTC, Gabriel29306 commented
Oui