fix: enabled chats
PapillonApp/papillon-v7 pull request #296
Opened 2024-10-18 20:10 UTC by imyanice

# 🚀 Nouvelle Pull Request

enables chats as a page, shows placeholder screen if account.service != ecoledirecte

2024-10-18 20:24 UTC, Louis-htmlcss commented
Ca a été fait exprès car l'interface n'est pas encore finie, à close.

2024-10-18 21:16 UTC, Kgeek33 commented
Non, faut pas closed
Il faut juste changer pour que ça redirige vers la page normale des messages uniquement pour les comptes École Directe. Sinon, les autres comptes, redirige vers la page de construction

2024-10-18 21:17 UTC, Kgeek33 commented
Après, à intégrer, jspas comment faire
@imyanice faut juste ajouter une condition

2024-10-18 21:18 UTC, Kgeek33 commented
Genre `account.service === École directe ? Placeholderscreen : Messages`

2024-10-19 07:02 UTC, imyanice commented
C'est déjà dans Messages.tsx...

2024-10-19 07:03 UTC, imyanice commented
https://github.com/PapillonApp/Papillon/blob/main/src/views/account/Chat/Messages.tsx#L62

2024-10-19 07:29 UTC, Kgeek33 commented
Je l'avais même pas vu dans ta pr sur école directe 😅

2024-10-19 07:30 UTC, Kgeek33 approved these changes
Dans ce cas, LGTM 👍

2024-10-19 09:37 UTC, imyanice commented
je mets à jour pawdirecte également car j'ai oublié

2024-10-19 09:39 UTC, Kgeek33 approved these changes

2024-10-19 19:46 UTC, Louis-htmlcss commented
> Non, faut pas closed
> Il faut juste changer pour que ça redirige vers la page normale des messages uniquement pour les comptes École Directe. Sinon, les autres comptes, redirige vers la page de construction.

L'interface est finie pour l'école directe, j'ai rien compris.

2024-10-19 19:52 UTC, Kgeek33 commented
PR #288  -> intégration messagerie École Directe 

Était prévu dans la pr la page indisponible pour les autres comptes : 

> https://github.com/PapillonApp/Papillon/blob/main/src/views/account/Chat/Messages.tsx#L62

Voilà

2024-10-19 20:12 UTC, Louis-htmlcss commented
ah deso je croyais que l'interface pour les messages etait pas finit

2024-10-19 20:12 UTC, Louis-htmlcss approved these changes

2024-10-19 20:17 UTC, Kgeek33 commented
> ah deso je croyais que l'interface pour les messages etait pas finit

C'est celle de pronote qui n'est pas encore terminée

2024-10-28 13:55 UTC, Vexcited commented on src/services/ecoledirecte/attendance.ts
> +  console.log(item);
```suggestion
```

Évite de balancer des `log` comme ça (on a un `Logger` fait exprès sinon)

2024-10-28 13:56 UTC, Vexcited requested changes
Juste un `console.log` à enlever, sinon tout est OK

2024-10-28 13:57 UTC, Vexcited approved these changes

2024-10-28 14:57 UTC, tryon-dev approved these changes

2024-10-28 14:57 UTC, merged