feat(Pronote): Popup informative
PapillonApp/papillon-v7 pull request #297
Opened 2024-10-19 19:25 UTC by Kgeek33

# 🚀 Nouvelle Pull Request

Proposez vos modifications pour améliorer Papillon

## Informations importantes

Merci de vous référer à la documentation sur la contribution si vous avez des questions à propos des pull requests (https://gitbook.getpapillon.xyz/organisation/outils-internes/github)

## Checklist d'avant pull request

Veuillez cocher toutes les cases applicables en remplaçant [ ] par [x].

- [x] Vous avez testé de build le projet avec vos modifications et ce build **a réussi**
- [x] Vous respectez les conventions de codage et de nommage du projet
- [x] Vous utilisez la **tabulation** pour l'indentation afin de maintenir un code lisible
- [x] Cette pull request **n'est pas un duplicata** d'une autre
- [x] Cette pull request est prête à être **revue** (review) et **fusionnée** (merge)
- [x] Il n'y a pas de **`TODO`** (aka des annotations pour du code manquant) dans vos modifications
- [x] Il n'y a pas **d'erreurs de langue** dans votre code (grammaire, vocabulaire, conjugaison, orthographe)
- [x] Les détails des changements ont été décrits ci-dessous
- [x] Cette pull-request n'est pas une **"breaking-change"** (des modifications qui vont entraîner la modification du fonctionnement de certaines fonctionnalités déjà existantes)

## Changelogs proposés

- Ajout d'une popup pour dire que les comptes autres que les élèves ne sont pas compatibles
- Optimisation du code

Closed #155 

## Informations supplémentaires

_une capture arrive_

2024-10-21 11:33 UTC, tryon-dev approved these changes

2024-10-21 17:10 UTC, Gabriel29306 requested changes

2024-10-21 17:10 UTC, Gabriel29306 commented on src/views/login/pronote/PronoteWebview.tsx
> +											!error.handle.shouldCustomDoubleAuth
Il y a un problème d'indentation ici

2024-10-21 17:20 UTC, Kgeek33 commented on src/views/login/pronote/PronoteWebview.tsx
> +											!error.handle.shouldCustomDoubleAuth
Ah oui quand même
Je regarde ça

2024-10-21 17:26 UTC, Kgeek33 commented
ah oui, j'avais activé les tabulations sur Prettier, voilà pq ça a du faire ça
Désactivé et corrigé normalement

2024-10-22 11:51 UTC, Gabriel29306 approved these changes
LGTM 👍

2024-10-25 19:37 UTC, ecnivtwelve reviewed
Un peu intrusif nan ?

2024-10-25 19:53 UTC, Kgeek33 commented
Jspas. Pour l'instant, quand un parent se connecte, il y a un chargement infini
À toi de me dire et je corrige vite fait ;)

2024-10-26 12:22 UTC, ecnivtwelve commented
> Jspas. Pour l'instant, quand un parent se connecte, il y a un chargement infini À toi de me dire et je corrige vite fait ;)

Par `!url.includes("identifiant")`, il check si ça load en boucle c'est ça ?

2024-10-26 12:27 UTC, Kgeek33 commented
Quand la personne se connecte à Pronote, Pawnote force la redirection vers un compte élève (donc url : mobile.eleve.html)
Quand c'est un compte élève, l'URL contient identifiant=...

S'il n'y a pas identifiant=, ça veut dire que tu essayes de te connecter à un compte élève alors que tes identifiants sont conçus pour un autre compte

2024-10-26 12:28 UTC, Kgeek33 commented
En version simplifié, ça boucle à l'infini en ce moment car Pawnote ne trouve pas dans l'URL `identifiant=`

2024-10-27 12:51 UTC, ecnivtwelve approved these changes
Ça me paraît bien !

2024-10-27 12:51 UTC, merged