fixs: Tous les bugs existants
PapillonApp/papillon-v7 pull request #325
Opened 2024-11-03 14:43 UTC by Kgeek33

> [!NOTE]
> 
> Cette PR a été faite dans sa grande majorité par @Gabriel29306 (#294 ), mais closed suite à l'enchaînement de conflit, **VU QUE PERSONNE FAISAIT DES REVIEWS !!!**
> 
> Elle est complétée avec les derniers bugs trouvées

# 🚀 Nouvelle Pull Request

Proposez vos modifications pour améliorer Papillon

## Informations importantes

Merci de vous référer à la documentation sur la contribution si vous avez des questions à propos des pull requests (https://gitbook.getpapillon.xyz/organisation/outils-internes/github)

## Checklist d'avant pull request

Veuillez cocher toutes les cases applicables en remplaçant [ ] par [x].

- [x] Vous avez testé de build le projet avec vos modifications et ce build **a réussi**
- [x] Vous respectez les conventions de codage et de nommage du projet
- [x] Vous utilisez la **tabulation** pour l'indentation afin de maintenir un code lisible
- [x] Cette pull request **n'est pas un duplicata** d'une autre
- [x] Cette pull request est prête à être **revue** (review) et **fusionnée** (merge)
- [x] Il n'y a pas de **`TODO`** (aka des annotations pour du code manquant) dans vos modifications
- [x] Il n'y a pas **d'erreurs de langue** dans votre code (grammaire, vocabulaire, conjugaison, orthographe)
- [x] Les détails des changements ont été décrits ci-dessous
- [x] Cette pull-request n'est pas une **"breaking-change"** (des modifications qui vont entraîner la modification du fonctionnement de certaines fonctionnalités déjà existantes)

## Changelogs proposés

### Sur la PR #294 

> fix: Centrage des icones pour les cours, les devoirs, widget LastGrade
> fix: majuscules pour les noms de famille composés
> fix: nom de police: semiBold => semibold
> fix: icone de pièce jointe pour les communications
> fix: bouton soutenir Papillon dans les paramètres
> fix: chargement infini des actualités
> fix: utilisation des safe area insets pour les views ayant un style de modale
> refactor: Changement de l'animation pour les views ayant un style de modale
> refactor: réarrangement des onglets dans SettingsTabs
> refactor: configuration d'expo-font
> refactor: nouvelles lignes entre les salles de classes
> refactor: bouton de donation en Android only
> chore: Mise à jour des dépendances

### Sur ma PR en sup.

> [!NOTE]
> 
> Elle est encore en draft, car d'autres bugs (_le plus important la page d'accueil_) sont à résoudre

> Correction d'un bug qui n'affichait rien quand on sélectionne une date sur l'emploi du temps
> Optimisation du code
> Homogénéité entre Apple et Android sur setShowDatePicker(false);
> Comme à chaque maj de Papillon, les mises à jour de l'app sur Android pose problème, car la versionCode ne correspond pas à celle du Play Store
> En ce moment, @LeGeek01 a mis une version code de "7211", alors je la passe à "7300"
> Correction de l'affichage fonctionnant 1 fois sur 10 lorsqu'on clique sur un devoir
> BONUS: ajout d'animations sur d'autres pages pour éviter ce genre de problème

## Informations supplémentaires

### Sur la PR #294 

- fix https://github.com/PapillonApp/Papillon/issues/279
- fix https://github.com/PapillonApp/Papillon/issues/256
- fix https://github.com/PapillonApp/Papillon/issues/233
- fix https://github.com/PapillonApp/Papillon/issues/317

### Sur ma PR en sup.

- Closed https://github.com/PapillonApp/Papillon/issues/310
- Closes https://github.com/PapillonApp/Papillon/issues/312
- Closes https://github.com/PapillonApp/Papillon/issues/232

2024-11-05 10:51 UTC, ecnivtwelve approved these changes
LGTM, peut être quelques checks que ça n'ait rien cassé avant merge

2024-11-05 10:53 UTC, Kgeek33 commented
Faudra principalement vérifier le passage de RenderHTML -> HTMLView

2024-11-05 11:07 UTC, ecnivtwelve requested changes
###### *Bloquage du merge avant vérifications supplémentaires*

2024-11-05 11:10 UTC, Kgeek33 commented
Oui c mieux, je te relancerai quand j'aurai complètement fini la pr (j'crois qu'il reste encore quelques bugs)

2024-11-06 17:09 UTC, Kgeek33 commented
la pr sera bientôt ouverte, je fix encore quelques trucs encore
@raphckrman j'ai adapté le code pour un typage correct (_Turboself_), tu pourras me dire si ça fonctionne ? Ici : https://github.com/PapillonApp/Papillon/pull/325/commits/60b521bdf7a4371cbe9a6439ba7ad45d04537a92#diff-39807ca358e4c2bbc6d37244014e6d5db1b815c357c4cda41f34df013c2f0ce4R28

2024-11-06 18:56 UTC, raphckrman commented
Je viens de tester, ça fonctionne de mon côté sur Turboself, cependant je n'ai plus les icones des services (turboself, ard, etc)

2024-11-06 18:58 UTC, Kgeek33 commented
Oui, la balise <Image> fonctionne plus
Je vais voir ce qui pose problème

2024-11-07 20:24 UTC, Kgeek33 commented
@raphckrman est-ce que t'as tjrs ce problème d'icône ?
jspas ce que j'ai fait, mais ça remarche de mon côté

2024-11-08 13:17 UTC, Kgeek33 commented
La pr será prête a être review ce soir

2024-11-08 21:18 UTC, cleeemeeent commented
y'a quoi a verif ?

2024-11-08 21:21 UTC, Kgeek33 commented
Dis moi si les icônes si s'affiche correctement déjà
sinon, dis moi aussi si les actualités s'affichent correctement, j'ai changé de librairie

2024-11-08 21:31 UTC, Kgeek33 commented
À vos tests ! Il faut principalement tester les endroits où du html est affiché (tel que les actualités, devoirs, chat...), il y a eu un changement de librairie pour moins de bugs

> [!ERROR]
>
> Les `PapillonCheck` ont été désactivé pour les devoirs sur l'écran d'accueil, car je rencontre l'erreur disant que `données is undefined` (_j'ai trouvé aucun code qui appelle `donnees`_)

2024-11-08 22:07 UTC, cleeemeeent commented
![image](https://github.com/user-attachments/assets/e2ad86d9-b65f-480c-a28d-5346068557de) good ici

2024-11-08 22:07 UTC, cleeemeeent commented
mais pas sur la page d'accueil au niveau des notes ![image](https://github.com/user-attachments/assets/313d9738-aa89-4f84-bdde-0d95d8eac8cc)

2024-11-08 22:08 UTC, Kgeek33 commented
Super pour les images ! 
Bizarre j'ai pas touché pour les émojis , mais je corrige ça de suite

2024-11-08 22:12 UTC, cleeemeeent commented
J'ai une erreur quand j'ouvre mes devoirs : [UNKOWN] not updated, see:TypeError: Cannot read property 'length' of undefined

2024-11-08 22:15 UTC, Kgeek33 commented
pour les émojis, c bon
bon l'erreur des devoirs, c'est ma logique qui était absente  😅, j'corrige mtn

2024-11-08 22:16 UTC, cleeemeeent commented
pas de soucis, je vérifie pour les emojis

2024-11-08 22:16 UTC, cleeemeeent commented
c'est good

2024-11-08 22:18 UTC, Kgeek33 commented
corrigé pour les devoirs

2024-11-08 22:20 UTC, cleeemeeent commented
![image](https://github.com/user-attachments/assets/ad265f97-78d3-45f2-b755-93b409376a00)

j'ai ça aussi

2024-11-08 22:22 UTC, cleeemeeent commented
J'ai ça quand je clique "à propos de papillon" :
 ERROR  TypeError: Cannot read property 'split' of undefined

This error is located at:
    in SettingsAbout (created by SceneView)
    in StaticContainer
    in EnsureSingleNavigator (created by SceneView)
    in SceneView (created by SceneView)
    in RCTView (created by View)
    in View (created by DebugContainer)
    in DebugContainer (created by MaybeNestedStack)
    in MaybeNestedStack (created by SceneView)
    in RCTView (created by View)
    in View (created by SceneView)
    in RNSScreen (created by Animated(Anonymous))
    in Animated(Anonymous) (created by InnerScreen)
    in Suspender (created by Freeze)
    in Suspense (created by Freeze)
    in Freeze (created by DelayedFreeze)
    in DelayedFreeze (created by InnerScreen)
    in InnerScreen (created by Screen)
    in Screen (created by SceneView)
    in SceneView (created by NativeStackViewInner)
    in Suspender (created by Freeze)
    in Suspense (created by Freeze)
    in Freeze (created by DelayedFreeze)
    in DelayedFreeze (created by ScreenStack)
    in RNSScreenStack (created by ScreenStack)
    in ScreenStack (created by NativeStackViewInner)
    in NativeStackViewInner (created by NativeStackView)
    in RCTView (created by View)
    in View (created by SafeAreaProviderCompat)
    in SafeAreaProviderCompat (created by NativeStackView)
    in NativeStackView (created by NativeStackNavigator)
    in PreventRemoveProvider (created by NavigationContent)
    in NavigationContent
    in Unknown (created by NativeStackNavigator)
    in NativeStackNavigator (created by SettingsScreen)
    in SettingsScreen (created by SceneView)
    in StaticContainer
    in EnsureSingleNavigator (created by SceneView)
    in SceneView (created by SceneView)
    in RCTView (created by View)
    in View (created by DebugContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer (created by DebugContainer)
    in DebugContainer (created by MaybeNestedStack)
    in MaybeNestedStack (created by SceneView)
    in RCTView (created by View)
    in View (created by SceneView)
    in RNSModalScreen (created by Animated(Anonymous))
    in Animated(Anonymous) (created by InnerScreen)
    in Suspender (created by Freeze)
    in Suspense (created by Freeze)
    in Freeze (created by DelayedFreeze)
    in DelayedFreeze (created by InnerScreen)
    in InnerScreen (created by Screen)
    in Screen (created by SceneView)
    in SceneView (created by NativeStackViewInner)
    in Suspender (created by Freeze)
    in Suspense (created by Freeze)
    in Freeze (created by DelayedFreeze)
    in DelayedFreeze (created by ScreenStack)
    in RNSScreenStack (created by ScreenStack)
    in ScreenStack (created by NativeStackViewInner)
    in NativeStackViewInner (created by NativeStackView)
    in RCTView (created by View)
    in View (created by SafeAreaProviderCompat)
    in SafeAreaProviderCompat (created by NativeStackView)
    in NativeStackView (created by NativeStackNavigator)
    in PreventRemoveProvider (created by NavigationContent)
    in NavigationContent
    in Unknown (created by NativeStackNavigator)
    in NativeStackNavigator (created by Router)
    in AlertProvider (created by Router)
    in EnsureSingleNavigator
    in BaseNavigationContainer
    in ThemeProvider
    in NavigationContainerInner (created by Router)
    in RCTView (created by View)
    in View (created by GestureHandlerRootView)
    in GestureHandlerRootView (created by Router)
    in RNCSafeAreaProvider (created by SafeAreaProvider)
    in SafeAreaProvider (created by Router)
    in RCTView (created by View)
    in View (created by Router)
    in Router (created by App)
    in App (created by withDevTools(App))
    in withDevTools(App)
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in main(RootComponent), js engine: hermes

2024-11-08 22:24 UTC, Kgeek33 commented
sur la page coupé en deux, tu testes sur un téléphone ?
et pour le split, ça doit être un problème généralisé, je corrige ça

2024-11-08 22:26 UTC, cleeemeeent commented
> sur la page coupé en deux, tu testes sur un téléphone ? et pour le split, ça doit être un problème généralisé, je corrige ça
Yep, je suis sur iPhone 13

2024-11-08 22:28 UTC, Kgeek33 commented
à propos, c'est corrigé, je regarde pour la page coupé en 2

2024-11-08 22:35 UTC, Kgeek33 commented
j'arrive pas à reproduire le bug, y compris sur un iphone

2024-11-08 22:56 UTC, Kgeek33 commented
@Gabriel29306 tu peux tester ?
c'est quand même ta pr de base :)

2024-11-08 23:15 UTC, Gabriel29306 commented
> @Gabriel29306 tu peux tester ?
> c'est quand même ta pr de base :)

Je teste et je te fais les retours

2024-11-08 23:54 UTC, Gabriel29306 commented
( Je vais peut-être faire des doublons par rapport aux autres messages)
| Fichier | Problème |
|---------|---------|
| ![Barre pas centree.jpg](https://github.com/user-attachments/assets/4539accc-a24b-440c-8b94-4531f66d6f72) | La barre sur l'écran d'accueil a été décalée |
| https://github.com/user-attachments/assets/67780c00-66a6-4819-9800-aef3c9d0c97e | La barre n'a pas l'animation où les 2 côtés bougent, peut être lié au problème précédent |
| ![Icones trop petites.jpg](https://github.com/user-attachments/assets/28352232-1dd8-4d97-8cf2-e8022b9acd49) | Les icones sont trop petites sur l'écran d'accueil |
| ![Emoji pas centré devoirs.jpg](https://github.com/user-attachments/assets/5e7d1d5f-8900-41ae-8bc0-a055e9978008) | Dans l'écran de devoir, l'icône n'est pas centrée |
| https://github.com/user-attachments/assets/9345afa7-35eb-4c21-a667-2010f2ed114e | Lors de l'ouverture et la fermeture d'une popup pour modifier une matière, il y a un lag plus ou moins important. À cause de ça j'ai cliqué plusieurs fois au même endroit, pour au final ouvrir une autre matière à cause du temps de traitement ? |
| https://github.com/user-attachments/assets/8c1e4f47-939b-4c3c-9c10-2247fa39cc45 | Lors de l'ajout ou du retrait d'un fond aux icônes de navigation, il y a l'animation qui bug |
| ![Chargement infini cantine.jpg](https://github.com/user-attachments/assets/d67cca02-783f-46b4-8397-7d40730fc3d7) | Lors que l'on a pas accès à la cantine, il y a un chargement infini (peut être parce que j'ai un compte TurboSelf, non affiché mais déjà configuré dans l'app) |
| https://github.com/user-attachments/assets/c3d5252c-564f-4ff8-8bbf-0d01f906f0ac | Et puis comme d'hab, un bug d'animation entre les différentes pages... |

Autre bug: lors de l'activation de Papillon Magic, certaines actualités disparaissent: 
| Avec | Sans |
| ![Screenshot_20241109_005153_Expo Go.jpg](https://github.com/user-attachments/assets/94e2336a-50df-4029-8c51-a8e456d9a525) | ![Screenshot_20241109_005234_Expo Go.jpg](https://github.com/user-attachments/assets/91fd2377-3ceb-406b-89a8-093460eddd9b) |



Bon voilà, j'ai mis tout ce qui m'a interpellé visuellement, je n'ai pas fouillé dans le code pour savoir pourquoi si ou ça...

2024-11-09 00:04 UTC, Kgeek33 commented
Merci je vais corriger tout ça demain, en détaillant chaque problème
Spoiler, j'ai peut-être fait n'importe quoi sur le typage de Turboself, d'où le bug infini, à voir

Et tu pourras m'expliquer après comment tu fais un serveur pronote via termux ? C'est intéressant

2024-11-09 00:05 UTC, Kgeek33 commented
Et dernier truc, comme je vois que t'as mis la page d'accueil au milieu de la navbar, est-ce que comme le dit une issue (jsplus laquelle), ça amène dans ton cas à Cours. Si oui ou non même , faut-il changer ce comportement ?

2024-11-09 00:25 UTC, Gabriel29306 commented
> Et tu pourras m'expliquer après comment tu fais un serveur pronote via termux ? C'est intéressant 

C'est juste un serveur expo go, après j'ai juste à me connecter en localhost avec expo go

2024-11-09 00:26 UTC, Gabriel29306 commented
> Et dernier truc, comme je vois que t'as mis la page d'accueil au milieu de la navbar, est-ce que comme le dit une issue (jsplus laquelle), ça amène dans ton cas à Cours. Si oui ou non même , faut-il changer ce comportement ? 

Ça amène directement à la page de Cours, la première de la nav bar.
Si on voulait changer ça, il faudrait plutôt faire un sélecteur d'onglet par défaut

2024-11-09 00:49 UTC, Gabriel29306 reviewed
Je ne mets pas en request change car c'est plus des voies d'amélioration que des besoins absolus, en plus il y a aussi plusieurs commentaires.

2024-11-09 00:49 UTC, Gabriel29306 commented on src/components/Restaurant/AccountButton.tsx
> +interface LESvariebles {
```suggestion
interface LESvariables {
```
Plutôt mettre vari**a**bles au lieu de vari**e**bles

2024-11-09 00:49 UTC, Gabriel29306 commented on src/components/Restaurant/AccountButton.tsx
> +const AccountButton = ({ account, isSelected, onPress, colors }: LESvariebles) => {
Modifier ici aussi de vari**e**bles en vari**a**bles

2024-11-09 00:49 UTC, Gabriel29306 commented on src/services/grades.ts
> +          }
Mettre `data?.xxxxx` au lieu du if serait mieux je pense

2024-11-09 00:49 UTC, Gabriel29306 commented on src/stores/account/index.ts
> +      if (instance !== undefined) {
Peut être simplifier par:
```suggestion
      if (instance) {
```

2024-11-09 00:49 UTC, Gabriel29306 commented on src/utils/ui/corner-radius.ts
> +    modelName = Device.deviceName ? Device.deviceName.toLowerCase() : null;
```suggestion
    modelName = Device.deviceName?.toLowerCase() ?? null;
```
On peut simplifier

2024-11-09 00:49 UTC, Gabriel29306 commented on src/views/account/Home/Elements/GradesElement.tsx
> +    if (grades?.[defaultPeriod] && grades[defaultPeriod].length > 0) {
```suggestion
    if (grades?.[defaultPeriod]?.length > 0) {
```
On peut simplifier

2024-11-09 00:49 UTC, Gabriel29306 commented on src/views/settings/SettingsAbout.tsx
> +            RN : {PackageJSON.dependencies["react-native"].split("^")[1]} | Expo : {PackageJSON.devDependencies.expo.split("^")[1]}
Il ne va pas y avoir de problème pour la production ?

2024-11-09 09:15 UTC, Kgeek33 commented
> > Et dernier truc, comme je vois que t'as mis la page d'accueil au milieu de la navbar, est-ce que comme le dit une issue (jsplus laquelle), ça amène dans ton cas à Cours. Si oui ou non même , faut-il changer ce comportement ?
> 
> Ça amène directement à la page de Cours, la première de la nav bar. Si on voulait changer ça, il faudrait plutôt faire un sélecteur d'onglet par défaut

ok donc je ferai ça dans une autre pr

2024-11-09 09:16 UTC, Kgeek33 commented
> Je ne mets pas en request change car c'est plus des voies d'amélioration que des besoins absolus, en plus il y a aussi plusieurs commentaires.

ok je fais ça de suite

2024-11-09 09:16 UTC, Kgeek33 commented on src/components/Restaurant/AccountButton.tsx
> +interface LESvariebles {
oups j'ai codé ça trop vite 😅

2024-11-09 09:20 UTC, Kgeek33 commented on src/services/grades.ts
> +          }
TypeScript il n'est pas content après, car grades peut être undefined
mais grades en ce moment est tjrs en erreur de type 🤣
je laisse ouvert

2024-11-09 09:23 UTC, Kgeek33 commented on src/utils/ui/corner-radius.ts
> +    modelName = Device.deviceName ? Device.deviceName.toLowerCase() : null;
je connaissais pas l'utilisation de `??`, mais oui !

2024-11-09 09:31 UTC, Kgeek33 commented on src/views/settings/SettingsAbout.tsx
> +            RN : {PackageJSON.dependencies["react-native"].split("^")[1]} | Expo : {PackageJSON.devDependencies.expo.split("^")[1]}
effectivement, faut remettre `expo` en tant que `dependencies` donc

2024-11-09 11:15 UTC, Kgeek33 commented
@Gabriel29306 j'ai tout corrigé, à l'exeption de la cantine (_comme je suis externe_)
> [!NOTE]
> 
> Pour la barre de la page d'accueil, j'ai supprimé les animation pour plus de simplicité 🤣

2024-11-09 11:23 UTC, Gabriel29306 commented
Ah si, il faut garder les animations, là l'app à l'air statique.
Et la barre n'est toujours pas alignée.
Je ne peux pas ce weekend mais, si tu me mets les droits sur ton repo, je pourrais le faire si tu veux.

2024-11-09 11:25 UTC, Gabriel29306 commented
Autre remarque, peut être liée aux animations, il n'y a plus "d'inertie" de scroll sur la page d'accueil.
Dès que l'on relâche le doigt, la page arrête le scroll directement, sans cette "inertie"

2024-11-09 11:32 UTC, Kgeek33 commented
Oui en fait, ce que j'ai fait, c'est que j'ai supprimé toutes les animations
Je te donne les droits :)

2024-11-09 11:35 UTC, Kgeek33 commented
C bon ?

2024-11-09 13:24 UTC, Kgeek33 commented
@Vexcited

2024-11-10 16:01 UTC, ecnivtwelve approved these changes
Après tests + push de fix, c'est tout bon pour moi

2024-11-10 16:03 UTC, ecnivtwelve requested changes
Presque tout bon, mais il faudrait rétablir les animations de la Home au moins sous iOS je pense

2024-11-10 16:11 UTC, LeGeek01 commented
c'est quoi ces animations dont vous parlez ?

2024-11-10 16:17 UTC, Kgeek33 commented
@LeGeek01 la nouvelle page d'accueil extrêmement buggé, j'ai supp les animations pour plus de stabilité

2024-11-10 16:18 UTC, Kgeek33 commented
@ecnivtwelve je vais voir ce que je peux faire et ce qui est mieux 😅

2024-11-10 16:22 UTC, LeGeek01 commented
> @LeGeek01 la nouvelle page d'accueil extrêmement buggé, j'ai supp les animations pour plus de stabilité

ouais celle que rémy avant proposé, mais pourquoi tu revert pas sa pr au lieu de supprimer les animations ? il avait pas dit que la nouvelle page n'était pas prête ?

2024-11-10 16:35 UTC, Kgeek33 commented
je pense que je vais faire ça
en fait, la pr était en draft mais comme il fallait faire la version 7.3.0, elle a été merged **alors qu'elle était toujours en draft**

2024-11-10 21:12 UTC, Gabriel29306 commented
> Presque tout bon, mais il faudrait rétablir les animations de la Home au moins sous iOS je pense

Même sur Android, car sinon la page ressemble à une page statique à scroll comme une image

2024-11-10 21:19 UTC, Kgeek33 commented
À la demande générale, un revert de la pr de rémy a été effectué
Donc retour de la page d'accueil des versions < 7.3.0, avec tout de même l'intégration des `onImportance`, qui déplace les sections en fonction de son importance

2024-11-10 21:20 UTC, Kgeek33 commented
un fix des widgets va être effectué, puis la pr sera ok

2024-11-10 21:26 UTC, Kgeek33 commented
@ecnivtwelve c'est bon, la page d'accueil est correct désormais

2024-11-10 23:07 UTC, Kgeek33 commented
mon merge a peut-être fait n'importe quoi, car j'ai installé VSCode sur ma tablette Android (_en utilisant code-server_) et c'est ma 1ère donc je vais vérifier si tout est bon

2024-11-11 17:52 UTC, Kgeek33 commented
@ecnivtwelve j'ai corrigé la page d'accueil, tu peux review ?

2024-11-11 18:27 UTC, cleeemeeent commented
Je vais voir pour review maintenant

2024-11-11 18:37 UTC, cleeemeeent commented
Pour le calendrier ça passe tous les jours jusqu'au séléctionné ?

2024-11-11 18:40 UTC, Kgeek33 commented
j'pense que c'est l'animation qui fait que ça balaye les jours jusqu'au jour sélectionné
tu peux me montrer une vidéo pour que je vois ce que ça donne sur Apple stp ?

2024-11-11 18:42 UTC, cleeemeeent commented
Ça donne ça sur iOS 18:
https://github.com/user-attachments/assets/ad680921-5dc8-4fdf-b913-db057a8da653

2024-11-11 18:44 UTC, Kgeek33 commented
c toi qui fait les clics partout, rassure-moi ? 😅

2024-11-11 19:04 UTC, Kgeek33 commented
@cleeemeeent j'ai trouvé le bug, je viens de le corriger (_à cause d'une animation_)

2024-11-11 19:12 UTC, cleeemeeent commented
> c toi qui fait les clics partout, rassure-moi ? 😅

les clics partout ?

2024-11-11 19:15 UTC, Kgeek33 commented
> > c toi qui fait les clics partout, rassure-moi ? 😅
> 
> les clics partout ?

quand j'ai vu ta vidéo, j'ai cru que tu t'amusais à cliquer sur n'importe quelle date alors que c'était juste un bug d'animation mdrr

2024-11-11 19:16 UTC, Clmnnt commented
good les animations :)

2024-11-11 19:17 UTC, cleeemeeent commented
Petit problème ici : ![image](https://github.com/user-attachments/assets/fc6f7a5c-f5d9-4b42-94ee-d280cb4f75ad)

2024-11-11 19:17 UTC, cleeemeeent commented
Le papillon ne s'affiche pas dans tous les onglets suivants

2024-11-11 19:18 UTC, Kgeek33 commented
CA RECOMMENCE !?
j'avais déjà rencontré ce bug mais jspas comment je l'avais résolu

2024-11-11 19:18 UTC, cleeemeeent commented
c'était sur les services cantines je crois

2024-11-11 19:19 UTC, Kgeek33 commented
ben en fait, le bug, c'est qu'un module (jspas lequel) refuse d'afficher les images en local

2024-11-11 19:20 UTC, Kgeek33 commented
go `npm-check-updates`, peut-être que je vais l'intégrer dans le package.json

2024-11-11 19:21 UTC, cleeemeeent commented
tu me tiens au courant comme ça je re-regarde

2024-11-12 14:48 UTC, ecnivtwelve commented
> ben en fait, le bug, c'est qu'un module (jspas lequel) refuse d'afficher les images en local

c'est `@react-native/assets-registry`, laisse le package json tel qu'il a été revert hier

2024-11-12 18:45 UTC, Kgeek33 commented
@ecnivtwelve @cleeemeeent les images fonctionnent de nouveau
à vous de review !

2024-11-12 18:49 UTC, cleeemeeent commented
je review après ! 😁

2024-11-12 19:02 UTC, cleeemeeent approved these changes
LGTM !

2024-11-14 15:38 UTC, LeGeek01 commented
après plusieurs tests de mon côté, faute de review et parce que l'expérience android est médiocre sur la 7.3.0, j'ai publié la 7.5.0 bêta (pour correspondre avec test flight) sur cette pr sur le play store.
par contre, où est passé la 7.4.0 ? il n'y a même pas de changelogs initiés

2024-11-14 16:04 UTC, Kgeek33 commented
Oh cool merci bcp !
Sur la 7.4.0, à un moment, ils ont mis le Package.json en 7.4 mais un peu plus tard, jspas pq, c'est passé sur la 7.5

2024-11-14 16:09 UTC, LeGeek01 commented
Bon tant pis en tout cas la version est en examen elle sera dispo dans le canal bêta après

2024-11-14 17:29 UTC, Kgeek33 commented
OK super merci !

2024-11-14 18:54 UTC, LeGeek01 commented
Bon l'examen dure longtemps je trouve

2024-11-14 19:18 UTC, Kgeek33 commented
Oui c vrai, on avait l'habitude que ça dure 1/2 heure, mais pas autant quand même

2024-11-14 19:36 UTC, Gabriel29306 commented
> Bon l'examen dure longtemps je trouve

Je devine que tu ne peux pas faire une release sur le GitHub?

2024-11-14 19:47 UTC, Kgeek33 commented
Non pas les droits
Ça serait intéressant un github actions qui le fasse

2024-11-14 19:48 UTC, Kgeek33 commented
@LeGeek01 @Gabriel29306 
Ah mon père (ingénieur en informatique) vient de m'annoncer que l'analyse des apk/aab peut prendre désormais jusqu'à 2 jours !

2024-11-14 19:52 UTC, Gabriel29306 commented
> @LeGeek01 @Gabriel29306 
> Ah mon père (ingénieur en informatique) vient de m'annoncer que l'analyse des apk/aab peut prendre désormais jusqu'à 2 jours ! 

Et merde...

2024-11-14 19:54 UTC, Kgeek33 commented
> > @LeGeek01 @Gabriel29306 
> > Ah mon père (ingénieur en informatique) vient de m'annoncer que l'analyse des apk/aab peut prendre désormais jusqu'à 2 jours ! 
> 
> Et merde...

Google saoule

2024-11-14 19:55 UTC, Gabriel29306 commented
C'est même plus dans certains cas:
> Toutes les modifications apportées à une application doivent être traitées avant de pouvoir être publiées. Le traitement peut prendre quelques heures ou jusqu'à sept jours (ou plus dans des cas exceptionnels), car cela dépend du temps de révision auquel votre application est soumise.

> [https://support.google.com/googleplay/android-developer/answer/9859654](https://support.google.com/googleplay/android-developer/answer/9859654?hl=en#:~:text=All%20app%20changes%20need%20to,your%20app%20is%20subject%20to.)

2024-11-14 20:02 UTC, Kgeek33 commented
Wtf 7 jours !?
Non la c'est trop là

2024-11-14 20:34 UTC, Kgeek33 commented
@ecnivtwelve une review serait cool !
Ça fait déjà 11 jours...

2024-11-15 06:17 UTC, LeGeek01 commented
La màj est dispo sur le play store

2024-11-15 06:18 UTC, Kgeek33 commented
Je viens de voir ça !

2024-11-15 06:19 UTC, LeGeek01 commented
On peut plus cocher les devoirs comme faits ?? J'avais pas ce bug moi

2024-11-15 06:20 UTC, Kgeek33 commented
Oh non j'ai créé un bug 😭😭
Les devoirs peuvent plus être coché sur toutes les pages

2024-11-15 06:23 UTC, Kgeek33 commented
Pourtant j'avais bien testé pour que ça soit uniquement sur la page d'accueil

2024-11-15 06:25 UTC, Kgeek33 commented
Ah si OK j'ai compris pourquoi
Je fais un fix de suite

2024-11-15 06:35 UTC, Kgeek33 commented
OK c'est corrigé
J'avais testé sur un appareil où les devoirs n'était pas sur la navbar, c'est pour ça, j'avais pas testé quand devoirs était dans la navbar

2024-11-15 06:42 UTC, LeGeek01 commented
Tu préfères quoi encore une paire de claques ou une paire de claques ?
T'as vu combien de temps la màj a pris pour passer ??? Putain x)

2024-11-15 06:46 UTC, Kgeek33 commented
Oui bien oui, on va pas faire une nouvelle version juste pour un petit fix
Je pourrai faire d'autres fixs s'il y a d'autres bugs (par exemple, en mode clair, on voit pas le nom du compte)

2024-11-15 07:06 UTC, Gabriel29306 commented
Étant sur la version GitHub j'ai pas de problèmes

2024-11-15 08:06 UTC, Kgeek33 commented
avec les devoirs ?
et pour le bug connu, faut être en mode clair et aller sur la page d'accueil, faire défiler. On voit extrêmement mal le nom du compte

2024-11-15 08:16 UTC, LeGeek01 commented
> Étant sur la version GitHub j'ai pas de problèmes

Sur cette pr ? @Gabriel29306

2024-11-15 08:43 UTC, Kgeek33 commented
après j'ai fait un commit ce matin, c'est peut-être pour ça fonctionne

2024-11-15 09:02 UTC, Gabriel29306 commented
> > Étant sur la version GitHub j'ai pas de problèmes
> 
> Sur cette pr ? @Gabriel29306 

Ah non, la release officielle

2024-11-15 13:13 UTC, ecnivtwelve commented
Je précise que la review de la PR est en cours de mon côté (et de celui de @Vexcited je crois bien), c'est juste encore une fois qu'il y a de nombreuses choses à vérifier comme la PR est majeure.

2024-11-15 13:19 UTC, LeGeek01 commented
> Je précise que la review de la PR est en cours de mon côté (et de celui de @Vexcited je crois bien), c'est juste encore une fois qu'il y a de nombreuses choses à vérifier comme la PR est majeure.

au lieu de nous laisser dans le vent, c'est une info à donner dès que vous commencez ça

2024-11-15 19:38 UTC, Kgeek33 commented
@ecnivtwelve @Gabriel29306 @LeGeek01 
Alors là, je viens d'apprendre la meilleure
On peut plus tester Papillon, faut monter Expo en version 52.
Jspas si ça nécessite les nouvelles versions majeures de React /React-native, où il faudra reprendre la majorité du code

2024-11-15 20:52 UTC, Gabriel29306 commented
Je vais voir si je peux faire une PR pour régler ce problème !

2024-11-15 21:13 UTC, Gabriel29306 commented
Au vu de tous les changements, que ce soit Expo ou React, il y a du taff

2024-11-15 21:20 UTC, Kgeek33 commented
Oui alors je te préviens, les nouvelles versions de React Native, il faut reprendre tout à 0

2024-11-15 21:43 UTC, Gabriel29306 commented
Je vais faire bug par bug. ChatGPT est mon ami

2024-11-16 08:40 UTC, LeGeek01 commented
En attendant il va falloir revenir aux bonnes vieilles méthodes... L'appli de dev

2024-11-16 10:14 UTC, Kgeek33 commented
@Gabriel29306 tu t'en occupes ou je le fais ?
Si tu t'en occupes, fais le bump directement sur cette pr, comme ça tout est fait d'un coup (t'as accès à mon fork)

2024-11-16 10:21 UTC, Gabriel29306 commented
Alors...
Je crois que certains modules sont incompatibles avec la nouvelle architecture

2024-11-16 10:42 UTC, Kgeek33 commented
> Alors... Je crois que certains modules sont incompatibles avec la nouvelle architecture

on est foutu mdrr
regardons ça, je vais ajouter un module `npm-check-updates` qui liste les packages à mettre à jour. je vais mettre la version interactive, puis quand le projet sera clean, je supprimerai la version interactive

2024-11-16 10:52 UTC, raphckrman commented
> Alors...
> Je crois que certains modules sont incompatibles avec la nouvelle architecture

En effet un des modules n'est pas compatible, j'ai un fix de ce module sur mon fork je vais PR juste après pour fix ça. De mon côté Expo 52 marche bien avec Papillon.

2024-11-16 10:58 UTC, Kgeek33 commented
> > Alors...
> > Je crois que certains modules sont incompatibles avec la nouvelle architecture
> 
> En effet un des modules n'est pas compatible, j'ai un fix de ce module sur mon fork je vais PR juste après pour fix ça. De mon côté Expo 52 marche bien avec Papillon.

Ca fonctionne avec les nouvelles versions de React ?

2024-11-16 10:58 UTC, raphckrman commented
Oui je suis à la dernière version de React Native

2024-11-16 11:00 UTC, Kgeek33 commented
> Oui je suis à la dernière version de React Native

ok ben tu veux pas mettre le fix sur la pr ? Comme ça, tout est balancé d'un coup ?
Je crois que c'est la dernière version de React (pas react-native) qui pose problème

2024-11-16 11:02 UTC, raphckrman commented
Yes si tu veux mais faut attendre que le mec fix son module incompatible je vais faire une PR sur son repo la dès que je peut

2024-11-16 11:03 UTC, Kgeek33 commented
> Yes si tu veux mais faut attendre que le mec fix son module incompatible je vais faire une PR sur son repo la dès que je peut

ok pas de problème, j'tenvoie l'invit

2024-11-16 11:07 UTC, Vexcited commented
> > Yes si tu veux mais faut attendre que le mec fix son module incompatible je vais faire une PR sur son repo la dès que je peut
> 
> ok pas de problème, j'tenvoie l'invit

Je vous en supplie, ne mettez pas tout dans la même PR, je m'explique : la raison pour laquelle cette PR n'est toujours pas review est tout simplement qu'elle fait BEAUCOUP trop de choses.

C'est ingérable, il aurait été préférable de tout séparer en petites PRs et je vous promets qu'aujourd'hui elles auraient possiblement toutes étaient merge, ou au moins review...

Ce que je veux dire par "ingérable" c'est que quand on review votre PR, on ne sait pas où donner de la tête : il y a des changements partout, comment on s'y retrouve ?

2024-11-16 11:13 UTC, Kgeek33 commented
> > > Yes si tu veux mais faut attendre que le mec fix son module incompatible je vais faire une PR sur son repo la dès que je peut
> > 
> > ok pas de problème, j'tenvoie l'invit
> 
> Je vous en supplie, ne mettez pas tout dans la même PR, je m'explique : la raison pour laquelle cette PR n'est toujours pas review est tout simplement qu'elle fait BEAUCOUP trop de choses.
> 
> C'est ingérable, il aurait été préférable de tout séparer en petites PRs et je vous promets qu'aujourd'hui elles auraient possiblement toutes étaient merge, ou au moins review...
> 
> Ce que je veux dire par "ingérable" c'est que quand on review votre PR, on ne sait pas où donner de la tête : il y a des changements partout, comment on s'y retrouve ?
>  

Oui ben je sais qu'elle fait BEAUCOUP de choses, **d'où l'intitulé "Tous les bugs existants"**...
Je comprends le temps de review mais par contre va falloir se dépêcher pask là, on peut plus tester Papillon, SDK 52 obligatoire, donc les nouvelles architectures de React !!
Et le processus de mise à niveau vers les dernières versions est très long à effectuer donc...

2024-11-16 11:14 UTC, Vexcited commented
> Je comprends le temps de review mais par contre va falloir se dépêcher pask là, on peut plus tester Papillon, SDK 52 obligatoire, donc les nouvelles architectures de React !! Et le processus de mise à niveau vers les dernières versions est très long à effectuer donc...

C'est pour ça que je demande à ce qu'elle soit dans une autre PR car petite PR = review vraiment + rapide et merge dans la journée souvent.

2024-11-16 11:15 UTC, Kgeek33 commented
Et pour qu'il y ait MOINS de choses, fallait accepter la pr de @Gabriel29306 bien avant ! _#294 pour rappel_
Mais bon, je dis ça, je dis rien....

2024-11-16 11:15 UTC, raphckrman commented
après tu peux toujours tester sur Expo 51 mais c'est plus chiant, tu peux utiliser npm run ios

2024-11-16 11:15 UTC, Vexcited commented
> Et pour qu'il y ait MOINS de choses, fallait accepter la pr de @Gabriel29306 bien avant ! _#294 pour rappel_ Mais bon, je dis ça, je dis rien....

Même soucis, trop de choses dans une seule PR.

2024-11-16 11:16 UTC, Kgeek33 commented
> > Je comprends le temps de review mais par contre va falloir se dépêcher pask là, on peut plus tester Papillon, SDK 52 obligatoire, donc les nouvelles architectures de React !! Et le processus de mise à niveau vers les dernières versions est très long à effectuer donc...
> 
> C'est pour ça que je demande à ce qu'elle soit dans une autre PR car petite PR = review vraiment + rapide et merge dans la journée souvent.

ok je vais faire ça, je reback juste le ncu et c'est bon pour moi

2024-11-16 12:14 UTC, Kgeek33 commented
@Vexcited tu penses que la pr pourra être review dans combien de temps ?

2024-11-16 12:16 UTC, vexcited commented
> @Vexcited tu penses que la pr pourra être review dans combien de temps ?

Une fois que quelqu'un aura la motivation de tout tester issue par issue en prenant soin de vérifier toutes les possibilités

2024-11-16 12:24 UTC, raphckrman commented
Je suis en train de tester petit à petit, j'ai un bug sur la page d'acceuil, quand tu full scroll le nom reste en blanc et pour le light mode ça devient illisible. 
<img width="607" alt="image" src="https://github.com/user-attachments/assets/344c8dab-f940-4866-8581-92a8aaf440d4">

2024-11-16 12:34 UTC, Kgeek33 commented
Oui bug connu, j'pense que pask c'est en mode transparent le nom du compte, j'essaye de corriger ça plus tard

2024-11-16 12:35 UTC, Kgeek33 commented
Tiens, tu peux me dire si la coche des devoirs s'affiche dans la page des devoirs ?
C'est normal que ça soit désactivé sur la page d'accueil

2024-11-16 12:37 UTC, raphckrman commented
Non ça ne s'affiche pas non plus sur la page des devoirs

2024-11-16 12:39 UTC, Kgeek33 commented
Ah mince, j'croyais que mon fix allait marcher
Comment tu fais pour tester Papillon ?

2024-11-16 12:41 UTC, raphckrman commented
j'ai fait npm run ios pour tester

2024-11-16 12:42 UTC, raphckrman commented
Le bug de la couleur du nom et prénom est présent sur toutes les pages

2024-11-16 12:43 UTC, raphckrman commented
ah nan mybad c'est moi j'ai mal vu

2024-11-16 12:43 UTC, Kgeek33 commented
OK je vais voir pour essayer de corriger ça
Pask quand je cochais les devoirs sur la page d'accueil, je rencontrai l'erreur "Cannot read 'donnees' of undefined"

2024-11-16 13:24 UTC, Kgeek33 commented
@raphckrman j'ai voulu faire `expo run:android`
mais ça me dit que Gradle 9.0 est obligatoire. Décidément, c'est la poisse aujourd'hui 🤣🤣

2024-11-16 14:23 UTC, imyanice commented
est ce que vous pouvez compartimenter vos prs et réécrire tout vos commits avec des descriptifs (fix 1, fix 2) et combiner ceux qui sont redondant (fix 1, fix 1 final, fix 1 final final, fix du fix 1).
merci!

2024-11-16 14:28 UTC, Kgeek33 commented
mes commits (fix 1, 2...), c'était juste les erreurs typescript, c'est pour ça que j'ai pas détaillé
Sinon, je détaille oui

2024-11-16 14:31 UTC, Kgeek33 commented
@raphckrman j'ai corrigé le nom du compte illisible en mode clair

2024-11-16 15:43 UTC, raphckrman commented
> @raphckrman j'ai corrigé le nom du compte illisible en mode clair

Il y a une ombre bug maintenant
<img width="427" alt="image" src="https://github.com/user-attachments/assets/1c4f354c-5123-4ec6-95e5-a622ce3ef021">

2024-11-16 15:45 UTC, Kgeek33 commented
Eh mdrr
C'était mieux avant j'pense

2024-11-16 15:59 UTC, raphckrman commented
Il y a un petit problème que j'ai vu en testant ton fork, elle consomme +770Mb de RAM pour une utilisation normal, alors que de base elle en consommait 320/400Mb (ce qui est déjà pas mal). Il y a une augmentation considérable de 200Mb en allant sur la page "Notes", et des augmentations aussi sur les pages "Cours" et "Devoirs"

2024-11-16 16:36 UTC, ecnivtwelve commented
Il devient vraiment très très difficile de gérer cette PR, son comportement et ses objectifs au vu de sa taille et de son ancienneté pourtant facile a découper
Certains problèmes simples a régler auraient pu l'être depuis longtemps si il n'étaient pas couplés a de nombreux changements majeurs.

Ici, la PR risque de casser involontairement bon nombre de fonctionnalités.

2024-11-16 16:41 UTC, Kgeek33 commented
Donc à la majorité, vous préférez que cette pr soit annulé pour que j'en fasse plusieurs mais plus légère ?

2024-11-16 16:42 UTC, Kgeek33 commented
Une pr = un fichier modifié en gros ?

2024-11-16 16:43 UTC, vexcited commented
> Donc à la majorité, vous préférez que cette pr soit annulé pour que j'en fasse plusieurs mais plus légère ?

Si possible, oui

2024-11-16 16:44 UTC, tryon-dev commented
> Donc à la majorité, vous préférez que cette pr soit annulé pour que j'en fasse plusieurs mais plus légère ?

Oui ca serait mieux

2024-11-16 16:46 UTC, ecnivtwelve commented
> Une pr = un fichier modifié en gros ?

Pas "un fichier", mais UN objectif ou au mieux une feature si pas éparpillée dans l'app (à noter fix de types et de formattage est un objectif INDÉPENDANT)

2024-11-16 16:47 UTC, ecnivtwelve commented
> Donc à la majorité, vous préférez que cette pr soit annulé pour que j'en fasse plusieurs mais plus légère ?

Si tu souhaites que l'ensemble des changements apparaissent rapidement, oui
- Quelque chose de simple comme des types ou un simple changement dans l'UI ne prendrait que quelques minutes a merge
- Un problème sur une PR ne bloque pas l'avancement d'une autre si elles sont bien indépendantes, contrairement à ici ou de nombreux changements pourtant prêts a passer en prod doivent attendre juste a cause d'un problème ailleurs
- Permettre de tracer les changements et d'en discuter rendrait la gestion des discussions plus efficaces et BIEN plus rapide

2024-11-16 16:47 UTC, Kgeek33 commented
OK ok, je vais faire ça, je close quand j'aurai totalement terminé
Déso de cette grosse pr 😅

2024-11-16 16:48 UTC, ecnivtwelve commented
> OK ok, je vais faire ça, je close quand j'aurai totalement terminé Déso de cette grosse pr 😅

On fera l'effort de les merge sous peu, d'autant plus que tes fix sont plutôt intéressants !

2024-11-16 16:51 UTC, Kgeek33 commented
> > OK ok, je vais faire ça, je close quand j'aurai totalement terminé Déso de cette grosse pr 😅
> 
> On fera l'effort de les merge sous peu, d'autant plus que tes fix sont plutôt intéressants !

Haha merci. 
Comme la version 7.5 a été publié sur les stores bêta (jspas pour Apple), est-ce qu'on bump vers une 7.6 ou 7.5.1 ?

2024-11-16 16:56 UTC, tryon-dev commented
nop justement c'est une beta pour l'instant qui n'est pas finalisé

2024-11-16 16:56 UTC, tryon-dev commented
il reste encore plusieurs build pour sortir sur les stores

2024-11-20 18:25 UTC, Kgeek33 commented
Ok tous les fixs ont été séparés dans plusieurs pr (_sauf l'affichage centré des émojis, en cours de travail_), cette pr est désormais closed

2024-11-20 18:25 UTC, closed without merging