Changements mineurs
PapillonApp/papillon-v7 pull request #34
Opened 2024-08-25 21:00 UTC by NowEwo

Papillon logo on top on Welcome Screen
Directly show "not supported" dialog when selecting unsupported services
Removed Unused imports
Added "More services coming soon" text on service selection view
The need help button sends to the Discord server

2024-08-25 21:07 UTC, Gabriel29306 approved these changes
Je dis oui

2024-08-25 21:23 UTC, tryon-dev commented
Hey, j'ai quelques petits commentaires pour ta PR : 
- si tu peux retirer le logo papillon en haut.
- si tu peux enlever le texte "Et encore plus de services à venir" dans le fichier src/views/login/ServiceSelector.tsx
Pour moi, après, c'est parfait, surtout le popup quand on clique sur les services pas supportés.

2024-08-25 21:25 UTC, NowEwo commented
Je fais ça demain dans la journée

2024-08-25 21:27 UTC, Rexxt commented
LGTM

2024-08-25 23:19 UTC, ecnivtwelve requested changes
Très sympa, l'ajout du lien Discord devra être temporaire pour ne pas exclure les non-utilisateurs du service et le logo je pense pas qu'il faut le garder mais sinon j'aime bien

2024-08-25 23:19 UTC, ecnivtwelve commented on src/views/welcome/FirstInstallation.tsx
> +      />
Pas forcément fan du logo sur le haut de l'écran, ça parait un peu random ? @toi-et-moi avis ?

2024-08-26 00:40 UTC, toi-et-moi commented on src/views/welcome/FirstInstallation.tsx
> +      />
je préférais le logo en bas effectivement

2024-08-26 08:33 UTC, Rexxt commented
> Très sympa, l'ajout du lien Discord devra être temporaire pour ne pas exclure les non-utilisateurs du service et le logo je pense pas qu'il faut le garder mais sinon j'aime bien

à titre perso je pense que le lien Discord il devrait être annexe parce que j'estime que Discord ne devrait pas être la solution principale pour demander de l'aide (voire pas la solution du tout) (étant donné que discord est un trou noir à informations et ça rend super difficile de Googler™️ un problème)

2024-08-26 08:34 UTC, Rexxt commented
pour l'alerte unsupported, "supporté" -> "pris en charge"

2024-08-26 08:36 UTC, toi-et-moi reviewed
Le logo en haut doit être mis en bas à mon humble avis et btw le discord en guise de support je suis pas sûr

2024-08-26 09:53 UTC, NowEwo commented
J'ai mis le Discord **temporairement** parce qu'il n'y a juste pas de centre d'aide et donc si les gens on des problèmes c'est toujours mieux qu'ils puissent au moins en demander ici (C'est mieux qu'un bouton qui mène vers rien)

2024-08-26 09:56 UTC, Rexxt commented
le centre d'aide ça devrait être ici sur les issues github

2024-08-26 09:58 UTC, NowEwo commented
Voilà

2024-08-26 10:13 UTC, ecnivtwelve approved these changes
Merci beaucoup ! Très sympa !

2024-08-26 10:13 UTC, merged