Mise à jour vers Expo 52
PapillonApp/papillon-v7 pull request #370
Opened 2024-11-16 18:33 UTC by raphckrman

# 🚀 Nouvelle Pull Request

Proposez vos modifications pour améliorer Papillon

## Informations importantes

Merci de vous référer à la documentation sur la contribution si vous avez des questions à propos des pull requests (https://gitbook.getpapillon.xyz/organisation/outils-internes/github)

## Checklist d'avant pull request

Veuillez cocher toutes les cases applicables en remplaçant [ ] par [x].

- [x] Vous avez testé de build le projet avec vos modifications et ce build **a réussi**
- [x] Vous respectez les conventions de codage et de nommage du projet
- [x] Vous utilisez la **tabulation** pour l'indentation afin de maintenir un code lisible
- [x] Cette pull request **n'est pas un duplicata** d'une autre
- [x] Cette pull request est prête à être **revue** (review) et **fusionnée** (merge)
- [x] Il n'y a pas de **`TODO`** (aka des annotations pour du code manquant) dans vos modifications
- [x] Il n'y a pas **d'erreurs de langue** dans votre code (grammaire, vocabulaire, conjugaison, orthographe)
- [x] Les détails des changements ont été décrits ci-dessous
- [ ] Cette pull-request n'est pas une **"breaking-change"** (des modifications qui vont entraîner la modification du fonctionnement de certaines fonctionnalités déjà existantes)

## Changelogs proposés

Passez sur Expo 52 pour des meilleurs perfs et continuer à tester via Expo Go.

2024-11-16 19:11 UTC, Kgeek33 commented on package.json
> +    "expo-location": "~npm i npm-check-updates\n18.0.1",
t sûr de ça ? 🤣

2024-11-16 19:17 UTC, raphckrman commented on package.json
> +    "expo-location": "~npm i npm-check-updates\n18.0.1",
Hein mais comment il est arrivé la mdrrr ? Je change ça

2024-11-16 20:20 UTC, Kgeek33 reviewed
c'est mieux que tout à l'heure mdrr
avant que t'appliques mon autre commentaire, mets à jour tous les packages vers la dernière version en exécutant `ncu -i` (version interactive) ou `ncu` (affiche les packages avec une mise à jour disponible)

Comme se sont des versions majeures, je te conseille de mettre à joour les packages 1 par 1, car je crois qu'un module nécessite une modification de code, jsplus lequel

2024-11-16 20:20 UTC, Kgeek33 commented on package.json
> +    "update": "ncu"
mets `"update: "ncu"` en 1ère position pour mettre ncu à l'avant
et je me disais bien que j'avais oublié un argument
```suggestion
    "update": "ncu -u"
```

2024-11-16 20:21 UTC, Kgeek33 commented
et tu peux mettre le 1er commentaire en résolu

2024-11-16 20:37 UTC, Kgeek33 commented
quand t'auras fait ça, relance-moi 😉

2024-11-16 20:41 UTC, raphckrman commented
c'est good

2024-11-17 13:24 UTC, Kgeek33 reviewed
Fais cette modif, mais sinon LGTM :)

2024-11-17 13:24 UTC, Kgeek33 commented on package-lock.json
Juste 3 trucs à corriger pour que npm soit content : 

- Ligne 8918 : changer `"eslint": "^3.17.0 || ^4 || ^5 || ^6 || ^7 || ^8"` => `"eslint": "^3.17.0 || ^4 || ^5 || ^6 || ^7 || ^8 || ^9"`
- Ligne 5557 : supprimer `"@react-navigation/native": "^7.0.3",`
- Faire après tout ça un `npm i` pour mettre à jour le package-lock.json

2024-11-17 15:50 UTC, Kgeek33 reviewed
Sur cette ligne là, tu dois faire la modification de la version de ESLint : https://github.com/raphckrman/PapillonV7/blob/ee8f6d831e44c21182364f42a04b440cefdc64ed/package-lock.json#L8893

`"eslint": "^3.17.0 || ^4 || ^5 || ^6 || ^7 || ^8"` => `"eslint": "^3.17.0 || ^4 || ^5 || ^6 || ^7 || ^8 || ^9"`

2024-11-17 15:50 UTC, Kgeek33 commented on package.json
> +    "eslint": "^3.17.0 || ^4 || ^5 || ^6 || ^7 || ^8 || ^9",
Non, faut pas ici. 
```suggestion
    "eslint": "^9.15.0",
```

2024-11-17 15:50 UTC, Kgeek33 commented on package.json
> +    "update": "ncu -u"
Comme ça, ça met à jour automatiquement
```suggestion
    "update": "ncu -u && npm i"
```

2024-11-17 18:14 UTC, Kgeek33 approved these changes
LGTM 👍

2024-11-17 21:07 UTC, ecnivtwelve commented on src/components/Global/PressableScale.tsx
> +import React, { forwardRef, useCallback, useMemo } from "react";
Une raison particulière pour détacher PressableScale de son module ? Une incompatibilité ?

2024-11-17 21:08 UTC, raphckrman commented on src/components/Global/PressableScale.tsx
> +import React, { forwardRef, useCallback, useMemo } from "react";
Yes c'est pas compatible, j'ai fait une PR sur le module original mais en attendant pour l'instant y'a pas d'update dessus + pas de MaJ depuis 1 an donc bon je doute que ça change

2024-11-17 22:20 UTC, raphckrman commented
je viens de remarquer qu'avec l'update des packages de kgeek ça fonctionne plus je vais regarder quel module pose problème demain

2024-11-18 18:34 UTC, Kgeek33 commented
Perso, l'application fonctionne mais des pages ne fonctionnent plus : 

- Onglets et Navigation => extrêmement lent
- Matières => affichage des options lorsqu'on clique sur une matière très bizarre
- Sélection d'une matière => la couleur sélectionnée ne fonctionne pas
- Toutes les autres page avec un défilement => ne scoll pas jusqu'au bout, donc des infos sont coupées

Je vais refaire une review pour corriger les problèmes de sécurité sur npm et (si j'ai le temps) corriger les bugs que j'ai listé

2024-11-18 18:35 UTC, Kgeek33 commented
Si tu rencontres un blocage d'Expo lors des tests, c'est pas Papillon qui déconne (enfin j'espère)
Elle plante, faut la redémarrer pour qu'elle fonctionne

2024-11-18 19:05 UTC, Kgeek33 requested changes
Pour corriger le bug de la sélection de couleur, il faut mettre un zIndex positif (j'ai mis `99` par exemple) => https://github.com/raphckrman/PapillonV7/blob/f256564b69db20d0da8f03288e7a118e8c513ca0/src/views/welcome/ColorSelector.tsx#L127

Les autres, j'ai pas 😅

2024-11-18 19:05 UTC, Kgeek33 commented on package-lock.json
Pour résoudre les problèmes de sécurité ;
Sur les 3 lignes suivantes : 

- https://github.com/raphckrman/PapillonV7/blob/f256564b69db20d0da8f03288e7a118e8c513ca0/package-lock.json#L9130
- https://github.com/raphckrman/PapillonV7/blob/f256564b69db20d0da8f03288e7a118e8c513ca0/package-lock.json#L9143-L9144

Remplacer `6.0.0` ou `6.0.5` => `7.0.6` (y compris sur `resolved`)

2024-11-18 20:30 UTC, raphckrman commented
> Perso, l'application fonctionne mais des pages ne fonctionnent plus :
> 
> * Onglets et Navigation => extrêmement lent
> * Matières => affichage des options lorsqu'on clique sur une matière très bizarre
> * Sélection d'une matière => la couleur sélectionnée ne fonctionne pas
> * Toutes les autres page avec un défilement => ne scoll pas jusqu'au bout, donc des infos sont coupées
> 
> Je vais refaire une review pour corriger les problèmes de sécurité sur npm et (si j'ai le temps) corriger les bugs que j'ai listé

Je vais regarder pour fixer tout ça, à noter que Expo 52 est très récent et qu'il y a actuellement pas mal d'issues concernant Expo 52, j'avais aussi une application très lente et avec des gros glitchs sur Expo Go, depuis la réinstallation d'Expo Go je n'ai plus cette lenteur et les glitchs.

2024-11-18 20:33 UTC, raphckrman commented
J'ai un bug sur Expo Go que j'ai pas sur le simulateur, tu as aussi des bugs visuels genre des noms de matières dans le vide sur certaines pages etc?

2024-11-18 20:35 UTC, Kgeek33 commented
> > Perso, l'application fonctionne mais des pages ne fonctionnent plus :
> > 
> > * Onglets et Navigation => extrêmement lent
> > * Matières => affichage des options lorsqu'on clique sur une matière très bizarre
> > * Sélection d'une matière => la couleur sélectionnée ne fonctionne pas
> > * Toutes les autres page avec un défilement => ne scoll pas jusqu'au bout, donc des infos sont coupées
> > 
> > Je vais refaire une review pour corriger les problèmes de sécurité sur npm et (si j'ai le temps) corriger les bugs que j'ai listé
> 
> Je vais regarder pour fixer tout ça, à noter que Expo 52 est très récent et qu'il y a actuellement pas mal d'issues concernant Expo 52, j'avais aussi une application très lente et avec des gros glitchs sur Expo Go, depuis la réinstallation d'Expo Go je n'ai plus cette lenteur et les glitchs.

Oui c'est pas surprenant qu'il y ait bcp d'issues, c'est dommage que ça soit brutale la migration, sans laisser genre 1 mois pour migration sdk 51 => 52
Pour tester en ce moment, j'ai fait un downgrade de l'app prenant en charge sdk 51. Sur l'autre appareil, j'ai fait la même et je l'ai mis à jour vers la dernière, c'est peut-être pour ça les plantages

2024-11-18 20:36 UTC, Kgeek33 commented
> J'ai un bug sur Expo Go que j'ai pas sur le simulateur, tu as aussi des bugs visuels genre des noms de matières dans le vide sur certaines pages etc?

Oui, comme des bugs extrêmement aléatoire de l'affichage de certaines pages, mais ça je pense que c'est du à React Native et non expo

2024-11-18 20:44 UTC, raphckrman commented
Je viens de push les fixs que tu m'as dis sur tu en remarque d'autre n'hésite pas à me le dire, je vais essayer de regarder aussi mais pour l'instant c'est plutôt instable à voir avec les MaJs de Expo et React Native

2024-11-18 20:50 UTC, Kgeek33 commented
Oui j'hésiterai pas à te signaler
Mais il va encore falloir changer des choses, car :

- Expo n'est pas content qu'on fasse des log, qui va être déprécié (et je comprends pas du tout pq)
- React Native et les `key` existants déjà (alors que bon, ce n'est pas le cas)
- React Native et sa magnifique version qui détruit certaines fonctionnalités

Bref, à revoir certains points...

2024-11-18 21:01 UTC, raphckrman commented
Je regarderais ça quand j'aurais un peu de temps, si tu veux je peux t'ajouter dans mon fork si tu veux fix des bugs dessus pour les rajouter ici

2024-11-18 21:03 UTC, Kgeek33 commented
Ah oui, ca serait cool 😁
En plus, demain aprem, j'ai pas cours donc je pourrai corriger des choses

2024-11-18 21:05 UTC, Kgeek33 commented
@Vexcited @ecnivtwelve
Avant que j'essaye de corriger des choses, vous pouvez review ? Pas bcp de commits mais bcp de lignes modifiées 😅

2024-11-18 21:06 UTC, raphckrman commented
Je t'ai invité sur le fork, y'a pas énormément de lignes la plupart c'est juste les package.json, package-lock.json

2024-11-18 21:10 UTC, Kgeek33 commented
Oui comme tous les packages ont été mis à jour vers la dernière version

2024-11-18 21:11 UTC, Kgeek33 commented
OK ben j'essaye de corriger des bugs demain aprem, j'pense qu'il va y avoir un peu de travail 😂

2024-11-19 18:03 UTC, Kgeek33 commented
bon j'ai corrigé plusieurs bugs par contre, il en reste énormément
je te recommande @raphckrman de mettre cette pr en draft, car c'est extrêmement compliqué de tester avec Expo 52 et React-Native (_l'appli plante extrêmement facilement_)

Pour le moment, pour tester sur Expo 51, il faut télécharger la version précédente ([https://apkpure.com/expo-go/host.exp.exponent/downloading/2.31.1](https://apkpure.com/expo-go/host.exp.exponent/downloading/2.31.1)) et désinstaller celle actuelle pour l'apk

2024-11-19 21:24 UTC, raphckrman commented
Comment l'appli plante? J'ai aucun crash de mon côté, après je suis sur iOS je sais pas si ça change quelque chose, je la passe en draft

2024-11-19 21:54 UTC, Kgeek33 commented
En gros, lors des tests, expo va fonctionner normalement et quand tu redémarres l'appli (expo donc), Papillon va figer et l'app ça planter complètement, sans raison 
Problème du côté d'expo 52 du coup

2024-11-24 13:49 UTC, Kgeek33 commented
@raphckrman tu peux réouvrir la pr mais 3 points à noter : (_je teste sur Android, pas encore testé sur iOS_)

- Le splash (_écran de démarrage de Papillon_) ne fonctionne plus, ça affiche une grosse icône de Papillon
![1732455978186](https://github.com/user-attachments/assets/300f8d5a-4dac-494f-88b9-5ba8dd04d30f)

- La page `Onglets et Navigation` ne fonctionne plus (_lorsqu'on veut déplacer des éléments_)
- La page `Notes` est extrêmement lente, notamment lors de l'affichage du graphique

> [!WARNING]
> 
> Lorsque vous rencontrez une erreur, que vous corrigez l'erreur, Expo va vous redirigez vers la page du choix des comptes. **Redémarrer l'app, sinon Expo va planter**
> 
> Oui, c'est compliqué de tester avec Expo 52

2024-11-26 17:46 UTC, Kgeek33 commented
@ecnivtwelve jnai vu que t'y travailles également
Tu veux pas intégrer tes modifs dans la pr pour plus d'efficacité (ou inversement)?

2024-11-26 18:17 UTC, ecnivtwelve commented
> @ecnivtwelve j'ai vu que t'y travailles également Tu veux pas intégrer tes modifs dans la pr pour plus d'efficacité (ou inversement)?

yes!

2024-11-27 13:58 UTC, Kgeek33 commented
j'ai merged ta branche directement dans cette pr, plusieurs fixs (notamment les conflits) seront résolus plus tard

2024-11-27 18:54 UTC, Kgeek33 commented
@raphckrman @ecnivtwelve @Vexcited @tryon-dev 
À vous de review (_oui, il y a un peu de travail 😅_) pour la compatibilité avec Expo 52 et la nouvelle architecture de React Native. Un bug gênant reste tout de même présent : 
Dans la page `Onglets et navigation` dans les paramètres de Papillon, le déplacement des matières ne va plus fonctionner (***sûrement un problème de Reanimated, qui recommande d'utiliser `useSharedValue`***)

2024-11-30 18:31 UTC, Clmnnt commented
J'ai toujours juste l'icone sur l'écran de démarrage, normal ?

2024-11-30 18:33 UTC, Kgeek33 commented
C'est une "nouveauté" d'expo (_que je n'aime pas du tout, rendu extrêmement moche_)

2024-11-30 18:37 UTC, Clmnnt commented
De @Orafilynie : 
Euh la version expo 52 presente un bug un peut dérangeant sur la homepage sur build natif IOS (bug non present sur expo go)
https://private-user-images.githubusercontent.com/86892516/391265706-8ca9fdd2-a57e-4192-944a-e980486cbb9a.mp4?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI5OTIwNjAsIm5iZiI6MTczMjk5MTc2MCwicGF0aCI6Ii84Njg5MjUxNi8zOTEyNjU3MDYtOGNhOWZkZDItYTU3ZS00MTkyLTk0NGEtZTk4MDQ4NmNiYjlhLm1wND9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTMwVDE4MzYwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3ZTg4Nzk3MmYwYjcyZGUzMTVkNDlhOTQyMGM3Nzg0M2RmY2FhODRjMjIwOTU2MzdhN2NkZTU4NmM1Njk0YTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.jX3wginPYWddyngxlLpntpgcafYQxnpF1B0HAhxNHJA

2024-11-30 18:43 UTC, Clmnnt reviewed
Il y a un bug ici 
https://github.com/user-attachments/assets/c8f391be-a9fb-4847-88ea-bea7396ba513

2024-11-30 18:44 UTC, Clmnnt commented
https://github.com/user-attachments/assets/fd797e4f-b042-46ef-9b05-325e72afd863

Ici aussi, il y a un problème

2024-11-30 19:05 UTC, Kgeek33 commented
> Il y a un bug ici https://github.com/user-attachments/assets/c8f391be-a9fb-4847-88ea-bea7396ba513

ah, il me tarde de commencer ma pr #378 🤣🤣

2024-11-30 19:05 UTC, Kgeek33 commented
> trim.E3EEE0BF-5E44-4A45-9A9B-71F16F88F03E.MOV 
> Ici aussi, il y a un problème

Les effets d'animation ?

2024-11-30 19:13 UTC, Clmnnt commented
> > trim.E3EEE0BF-5E44-4A45-9A9B-71F16F88F03E.MOV
> > Ici aussi, il y a un problème
> 
> Les effets d'animation ?

yep c'est ça

2024-12-01 11:31 UTC, Kgeek33 commented
@Clmnnt j'ai corrigé tes bugs signalés
je me suis renseigné pour le splash screen, j'ai testé mais fonctionne pas

2024-12-01 17:12 UTC, Kgeek33 approved these changes

2024-12-04 12:39 UTC, Clmnnt commented
De mon côté ça crash à l'ouverture de l'app

2024-12-04 12:53 UTC, Kgeek33 commented
> De mon côté ça crash à l'ouverture de l'app

carrément ?! bon je vais voir ce qui se passe plus tard

2024-12-04 13:07 UTC, Clmnnt commented
si tu  veux je te passe mes logs

2024-12-04 13:29 UTC, Kgeek33 commented
> si tu veux je te passe mes logs

oui stp pour que je vois

2024-12-04 13:30 UTC, Kgeek33 commented
je m'occupe de cette pr mtn, je testais une autre

2024-12-04 14:19 UTC, Clmnnt commented
```
 (NOBRIDGE) LOG  [LOG][2024-12-04T14:15:17.458Z][UNKOWN] reading ACCOUNT (caché)
 (NOBRIDGE) LOG  [INFO][2024-12-04T14:15:17.460Z][UNKOWN] rehydrating timetable
 (NOBRIDGE) LOG  [INFO][2024-12-04T14:15:17.460Z][UNKOWN] rehydrating homework
 (NOBRIDGE) LOG  [INFO][2024-12-04T14:15:17.460Z][UNKOWN] rehydrating grades
 (NOBRIDGE) LOG  [INFO][2024-12-04T14:15:17.461Z][UNKOWN] rehydrating news
 (NOBRIDGE) LOG  [INFO][2024-12-04T14:15:17.461Z][UNKOWN] rehydrating attendance
 (NOBRIDGE) LOG  [LOG][2024-12-04T14:15:17.613Z][UNKOWN] Reading addons folder
 (NOBRIDGE) LOG  [NAV][2024-12-04T14:15:17.621Z][ROUTER] User navigate into /AccountStack/Home/HomeScreen
 (NOBRIDGE) LOG  [LOG][2024-12-04T14:15:17.664Z][UNKOWN] update grades periods in cache
 (NOBRIDGE) LOG  [LOG][2024-12-04T14:15:17.708Z][UNKOWN] update grades periods in cache
 (NOBRIDGE) LOG  [LOG][2024-12-04T14:15:17.838Z][UNKOWN] instance undefined, reloading...
 (NOBRIDGE) LOG  [LOG][2024-12-04T14:15:17.856Z][UNKOWN] Found 0 folder to check...
 (NOBRIDGE) LOG  [ERROR][2024-12-04T14:15:18.184Z][UNKOWN] not updated, see:ErrorServiceUnauthenticated: pronote: "account.instance" is not defined, you need to authenticate first.
 (NOBRIDGE) LOG  [LOG][2024-12-04T14:15:18.198Z][UNKOWN] mutate property authentication in storage
 (NOBRIDGE) LOG  [LOG][2024-12-04T14:15:18.200Z][UNKOWN] done mutating property authentication in storage
 (NOBRIDGE) LOG  [LOG][2024-12-04T14:15:18.200Z][UNKOWN] mutate property instance in storage
 (NOBRIDGE) LOG  [LOG][2024-12-04T14:15:18.200Z][UNKOWN] done mutating property instance in storage
 (NOBRIDGE) LOG  [LOG][2024-12-04T14:15:18.200Z][UNKOWN] instance reload done !
 (NOBRIDGE) LOG  [INFO][2024-12-04T14:15:18.200Z][UNKOWN] found 0 external accounts
 (NOBRIDGE) LOG  [LOG][2024-12-04T14:15:18.200Z][UNKOWN] reloaded all external accounts
 (NOBRIDGE) LOG  [LOG][2024-12-04T14:15:18.201Z][UNKOWN] done reading ACCOUNT (caché) and rehydrating stores.
 (NOBRIDGE) LOG  [LOG][2024-12-04T14:15:18.279Z][UNKOWN] update grades periods in cache
 (NOBRIDGE) WARN  [Reanimated] Tried to modify key `primary` of an object which has been already passed to a worklet. See
https://docs.swmansion.com/react-native-reanimated/docs/guides/troubleshooting#tried-to-modify-key-of-an-object-which-has-been-converted-to-a-shareable
for more details.
 (NOBRIDGE) LOG  [INFO][2024-12-04T14:15:18.300Z][UNKOWN] PRONOTE->getGradesPeriods(): OK
 (NOBRIDGE) LOG  [INFO][2024-12-04T14:15:18.300Z][UNKOWN] PRONOTE->getGradesPeriods(): OK
 (NOBRIDGE) LOG  [INFO][2024-12-04T14:15:18.300Z][UNKOWN] PRONOTE->getGradesPeriods(): OK
```
1ère connexion.

Lors des autres, l'erreur " (NOBRIDGE) LOG  [ERROR][2024-12-04T14:15:18.184Z][UNKOWN] not updated, see:ErrorServiceUnauthenticated: pronote: "account.instance" is not defined, you need to authenticate first." n'ont pas lieu.

2024-12-04 14:19 UTC, Clmnnt commented
@Kgeek33

2024-12-04 15:04 UTC, Kgeek33 commented
Oui ça c'est normal, ça prend 30 secs pour se reconnecter

2024-12-10 21:40 UTC, Kgeek33 commented
@raphckrman tu peux ouvrir cette pr ?
ça fait 3 semaines que ça bouge pas, c'est dommage...

2024-12-10 23:16 UTC, raphckrman commented
C'est bon elle est open, je vais essayer de la review demain

2024-12-11 10:11 UTC, ecnivtwelve requested changes
![Simulator Screenshot - iPhone 14 Pro - 2024-12-11 at 11 11 19](https://github.com/user-attachments/assets/746cdf89-dc83-423e-b42d-cadbeeaf9189)
il y a toujours des bugs graphiques

2024-12-11 13:17 UTC, Kgeek33 commented
> ![Simulator Screenshot - iPhone 14 Pro - 2024-12-11 at 11 11 19](https://private-user-images.githubusercontent.com/32978709/394689959-746cdf89-dc83-423e-b42d-cadbeeaf9189.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5MjMyODQsIm5iZiI6MTczMzkyMjk4NCwicGF0aCI6Ii8zMjk3ODcwOS8zOTQ2ODk5NTktNzQ2Y2RmODktZGM4My00MjNlLWI0MmQtY2FkYmVlYWY5MTg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjExVDEzMTYyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2N2E1NTJlOGM0MzE0OTUyMWRjOWQyOWJmMWMyNmQ3M2I2MTBhZWQ4NjgwMDRmMGVkNDY2NTk0ZWVhMWU2ZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7ZRezZLNvo_8sCdWI4Vldl1_SMudcHftE5YjgtPtgaY) il y a toujours des bugs graphiques

ok je corrige ça mtn (ça doit être un zIndex qui pose problème j'pense)

2024-12-11 13:47 UTC, Kgeek33 commented
@Clmnnt effectivement, j'ai réinitialisé les onglets et lors du démarrage ça plante
je regarde si c'est juste iOS ou c'est un cas général

2024-12-11 13:47 UTC, Kgeek33 commented
mais en consultant les logs, ça doit être l'onglet Notes qui pose problème

2024-12-11 13:58 UTC, Kgeek33 commented
@Clmnnt je me suis déconnecté et reconnecté et ça refonctionne, bizarre...

2024-12-11 14:00 UTC, Kgeek33 commented
@Clmnnt laisse tomber tous mes messages, c'est juste expo qui ne fonctionne pas
faudra builder pour avoir un test réaliste

2024-12-11 14:16 UTC, Clmnnt commented
> @Clmnnt laisse tomber tous mes messages, c'est juste expo qui ne fonctionne pas faudra builder pour avoir un test réaliste

 Comment ça « Expo qui ne fonctionne pas » ?

2024-12-11 14:41 UTC, Kgeek33 commented
> > @Clmnnt laisse tomber tous mes messages, c'est juste expo qui ne fonctionne pas faudra builder pour avoir un test réaliste
> 
> Comment ça « Expo qui ne fonctionne pas » ?

Depuis Expo Go 52, quand tu veux tester, ça plante très facilement et t'as des bugs extrêmement chelou (par exemple la capture de @ecnivtwelve)
Dans notre cas, ça plante lors de la connexion alors qu'il n'y a aucune erreur dans les logs...

2024-12-11 14:42 UTC, Kgeek33 commented
j'suis en train de me rendre compte qu'on ne peut même pas builder correctement sur Android, les fichiers ne sont pas du tout à jour
@raphckrman t'as un Macbook ?

2024-12-11 17:15 UTC, raphckrman commented
j'avais pas vu mais ouais j'ai un mac je peut faire un build si tu veux

2024-12-11 17:48 UTC, Kgeek33 commented
> j'avais pas vu mais ouais j'ai un mac je peut faire un build si tu veux

Alors avant, supprimes l'intégralité du dossier `ios` et refais le en faisant un `npm run prebuild` (_normalement ça le recrée si je dis pas de bêtises_)
Et tu pourras me dire si tu rencontres le même bug que @Clmnnt et @ecnivtwelve stp ? Perso, je n'arrive pas du tout à builder, Gradle refuse, c'est un problème de Notifee

2024-12-11 18:14 UTC, raphckrman commented
J'obtiens un build réussi via XCode, je ne rencontre pas le bug de @ecnivtwelve et @Clmnnt sur le simulateur. Cependant il y a plusieurs bugs comme ceux là:
<img width="380" alt="image" src="https://github.com/user-attachments/assets/8221cfdf-fc1c-4ab7-a980-861c2f87bc03" />
<img width="402" alt="image" src="https://github.com/user-attachments/assets/eca7ea61-5e64-457c-830d-b535059135c8" />

Je vais voir pour les corriger en même temps que l'update pour ARD que je suis en train de faire
@Kgeek33

2024-12-11 19:56 UTC, Kgeek33 commented
> J'obtiens un build réussi via XCode, je ne rencontre pas le bug de @ecnivtwelve et @Clmnnt sur le simulateur. Cependant il y a plusieurs bugs comme ceux là:
> <img width="380" alt="image" src="https://github.com/user-attachments/assets/8221cfdf-fc1c-4ab7-a980-861c2f87bc03" />
> <img width="402" alt="image" src="https://github.com/user-attachments/assets/eca7ea61-5e64-457c-830d-b535059135c8" />
> 
> Je vais voir pour les corriger en même temps que l'update pour ARD que je suis en train de faire
> @Kgeek33 

Ok pas d'update à faire sur le dossier ios quand tu le supprimes et que tu fais `npm run prebuild` ?
Oui j'ai vu ça tout à l'heure, faut que tu mettes les margin/padding uniquement pour Android

2024-12-11 19:57 UTC, Kgeek33 commented
T'as fait pour ard ? Comme ça je fais un `ncu -u` pour mettre à jour vers la dernière version les modules (et résoudre les conflits)

2024-12-11 19:59 UTC, raphckrman commented
J'ai fait dans la PR #409

2024-12-11 20:03 UTC, Kgeek33 commented
J'avais même pas vu 😅

2024-12-11 20:21 UTC, Kgeek33 commented
J'suis en train de résoudre les conflits et je fais un `ncu -u`

2024-12-11 20:41 UTC, Kgeek33 commented
@raphckrman 
c'est pas grave que `balances` soit pas présent dans le fichier `src/views/settings/ExternalAccount/ARD.tsx`?

2024-12-11 20:46 UTC, raphckrman commented
Oh si en effet my bad j'avais pas vu je vais faire une PR pour ça et update turboself-api merci

2024-12-11 20:50 UTC, Kgeek33 commented
> Oh si en effet my bad j'avais pas vu je vais faire une PR pour ça et update turboself-api merci
> 

Ok tkt pas, ncu a mis `turboself-api` à la dernière version normalement (version 2.1.6)

2024-12-11 21:08 UTC, Kgeek33 commented
Rapide tes prs @raphckrman 😂

2024-12-11 21:11 UTC, raphckrman commented
> Rapide tes prs @raphckrman 😂

en même temps y'a 5 lignes ptdr

2024-12-11 21:17 UTC, Kgeek33 commented
Parfait, les checks sont passés
Maintenant, faut corriger des bugs aléatoires maintenant 😂

2024-12-11 21:23 UTC, Kgeek33 commented
J'ai corrigé le bug que t'as envoyé @raphckrman (input prénom /nom trop petit sur ios)

2024-12-11 21:54 UTC, raphckrman commented
En effet je viens de tester ce bug la est bon

2024-12-11 22:05 UTC, Kgeek33 commented
> En effet je viens de tester ce bug la est bon
> 

J'ai voulu tester lors de la 1ère utilisation sur Android et j'ai un bug sur la Webview où j'ai une requête à l'infini (ça m'amène vers mon ent et sans rien faire, ça ramène vers pronote, qui ferait la même chose à chaque fois)
Jspas si c'est du à mon ent ou à Papillon

2024-12-11 22:07 UTC, raphckrman commented
j'ai déjà eu ça mais sur une ancienne version sous Expo 51

2024-12-11 22:11 UTC, Kgeek33 commented
> j'ai déjà eu ça mais sur une ancienne version sous Expo 51

J'viens de tester en version prod, je rencontre pas ce problème. Ça doit être une erreur de code sûrement

2024-12-11 22:16 UTC, Kgeek33 commented
Les bugs connus actuellement sur Expo 52 (sera actualisé si de nouveaux bugs rencontrés) :

- La page Onglets et Navigation ne fonctionne pas, lorsqu'on veut déplacer des onglets
- Sur Android, lorsqu'on fait glisser le graphique, on rencontre une erreur d'import (pas retesté depuis)
- Sur iOS, il arrive un problème de superposition, faisant des affichages extrêmement chelou (voir capture @ecnivtwelve )
- Dans certains cas, lors du lancement d'Expo 52 et que Papillon essaye de se connecter à notre compte, ça plante (reporté par @Clmnnt )

2024-12-12 18:58 UTC, raphckrman commented
@Kgeek33 Je viens de faire un build iOS que j'ai installé et j'ai aucun soucis pour l'instant

2024-12-12 19:17 UTC, Kgeek33 commented
Ok super, tu rencontres des bugs ?

2024-12-12 19:19 UTC, raphckrman commented
nop aucun bug pour l'instant

2024-12-12 19:23 UTC, Kgeek33 commented
Oh super ! Je résous les conflits et j'essaye de builder pour Android

2024-12-12 19:36 UTC, Kgeek33 commented
Bon j'ai résolu les conflits, jspas si c'est correct mais j'pense

2024-12-12 21:25 UTC, Kgeek33 commented
Alors j'ai ajouté un fichier `notifee-mod.js` qui corrige un bug lors du build, à chaque fois une erreur causé par notifee
@raphckrman quand tu fais un `npx expo prebuild --clean`, est-ce que des fichiers sont modifiés ?

2024-12-12 21:32 UTC, raphckrman commented
Oui comme avant, ça modifie des fichiers

2024-12-12 22:12 UTC, Kgeek33 commented
Tu pourras refaire un commit sur les fichiers modifiés ? Normalement, ça modifiera plus après

2024-12-12 22:14 UTC, raphckrman commented
Dans la docs il est marqué de faire un prebuild avant, ça changera a nouveau dans le futur je vois pas l'utilité de les mettre ici sachant que dans le futur ça va pas être les même

2024-12-12 22:16 UTC, Kgeek33 commented
Oui c vrai, dis comme ça
Bon ben il y aura la splash screen à corriger et un chargement infini entre urls sur mon ent
![Screenshot_2024-12-12-22-13-11-351_xyz.getpapillon.app.dev.jpg](https://github.com/user-attachments/assets/cd15d126-9e37-43c5-882e-5b08f9924847)

2024-12-12 22:18 UTC, raphckrman commented
Chargement infini de la WebView je l'ai aussi et ça date d'avant Expo 52, le splashscreen je vais regarder

2024-12-12 22:24 UTC, Kgeek33 commented
En regardant le code, je vous pas comment arrêter la boucle infini (_sauf lors de l'injection de Javascript_)
Pour le splash screen, il faut utiliser le plugin `expo-splash-screen` et supprimer tous les paramètres `splash` en dehors du plugin dans `app.json` ("nouveauté" d'expo 52)

2024-12-12 23:44 UTC, raphckrman commented
C'est bon c'est fait

2024-12-13 06:01 UTC, Kgeek33 commented
Faudra aussi supprimer `splash` dans Android et ios, également non supporté

2024-12-15 21:03 UTC, Kgeek33 approved these changes
Des nouvelles ? Je sais que notre pr avec @raphckrman est assez grosse, mais les conflits sont très faciles et long à résoudre

2024-12-15 21:13 UTC, JyhuKo approved these changes

2024-12-17 22:21 UTC, raphckrman commented
On peut fêter les 1 mois de la PR, si des reviews peuvent commencer à arriver ça peut être sympathique, de mon côté j'ai build ça marche j'ai pas de bugs.

2024-12-17 22:27 UTC, JyhuKo commented
félicitation !

2024-12-17 22:27 UTC, JyhuKo approved these changes
ca marche de mon coté

2024-12-17 22:29 UTC, Kgeek33 commented
> On peut fêter les 1 mois de la PR, si des reviews peuvent commencer à arriver ça peut être sympathique

C'est trop long 😭😭. J'pense qu'il faudrait que tu fasses comme moi, tu close et tu la recrée avec un id différent
J'lai fait sur mes 2 pr inactives, j'ai vu la différence ajd 😂

2024-12-17 22:30 UTC, Kgeek33 commented
> j'ai build ça marche j'ai pas de bugs. (ça permettrait plus de contribution btw)

Faudrait que je retester (tiens je vais le faire de suite) et je vous tiens au courant

2024-12-17 22:38 UTC, Clmnnt commented
Bon Moisniverssaire la PR !

2024-12-17 22:39 UTC, Clmnnt approved these changes
bah LGTM 💯

2024-12-17 22:40 UTC, Clmnnt commented
fait que les codes owners review 😭

2024-12-17 22:41 UTC, Kgeek33 commented
Oh non, j'ai encore le bug infini de la Webview 😭😭

2024-12-17 22:43 UTC, Clmnnt commented
> Oh non, j'ai encore le bug infini de la Webview 😭😭

Quoi??

2024-12-17 22:43 UTC, raphckrman commented
> Oh non, j'ai encore le bug infini de la Webview 😭😭

wtf mais y'a que toi qui l'a mdrrrr

2024-12-17 22:47 UTC, Kgeek33 commented
C'est mon ent, ils sont débiles

Regardez le lien : `https://jeunes.nouvelle-aquitaine.fr/formation/au-lycee/lycee-connecte?callback=https%3A%2F%2Fmon.lyceeconnecte.fr%2Fcas%2Flogin%3Fservice%3Dhtt ps%253A%252F%252F[_je censure 🤣_].index-education.net%252Fpronote%252Fmobile.eleve.html%253Ffd%253D1`

2024-12-17 22:48 UTC, Kgeek33 commented
@Clmnnt quand je veux me connecter à mon compte pronote, j'ai un changement de lien infini lors de la connexion via ent

2024-12-17 23:04 UTC, Kgeek33 commented
J'AI TROUVÉ LE PROBLÈME !

2024-12-17 23:08 UTC, Kgeek33 commented
Ok j'ai fait un commit pour fix
Je poursuivrai les tests demain

2024-12-18 06:10 UTC, Rexxt commented
LGTM globalement

2024-12-18 06:11 UTC, Rexxt approved these changes
lgtm, vérifie le fonctionnement général par contre

2024-12-18 13:10 UTC, Kgeek33 commented
Alors ça fonctionne bien en général à la différence que la page de sélection des couleurs et la page lors de la modification de l'ordre des onglets ne fonctionnent pas
J'ai testé sur Expo 52 et on sait bien que c'est extrêmement buggé avec des plantages qui sortent de je ne sais où

Bref tout ça pour dire que je vais builder et voir si les bugs sont existants sur build

2024-12-19 07:24 UTC, Kgeek33 commented
Bon c'est pas stable sur build, même rendu sur Expo, en pire (c'est d'une extrême lenteur). Je vous partage ce que je me suis noté à faire pour une meilleure stabilité (_je ferai ça ajd ou demain_)

![Screenshot_2024-12-19-08-22-37-103_com.microsoft.todos-edit.jpg](https://github.com/user-attachments/assets/c3f659a5-a56d-4dc6-95cb-928990dd3e17)

2024-12-19 22:42 UTC, Kgeek33 commented
bon j'ai avancé, il manque juste la compatibilité avec Reanimated (c ca qui pose le plus de problème)
mais par contre, svp, faites des reviews pour faire avancer cette pr (_même si elle est grosse_)

2024-12-19 23:02 UTC, raphckrman commented
Je fais un build demain pour tester complètement l'app côté PRONOTE

2024-12-21 15:11 UTC, Kgeek33 approved these changes
Tous les bugs importants ont été corrigés !
A vous de review maintenant !

2024-12-21 16:21 UTC, raphckrman commented
Je viens de tester en faisant un build (iOS), de mon côté il n'y a pas de bugs (tester avec Pronote).

2024-12-21 19:15 UTC, Kgeek33 commented
@raphckrman 
Tu veux pas close cette pr et la refaire avec un id différent ?
Quand mes pr n'étaient jamais review, j'ai fait ça et j'ai eu des reviews. En plus la pr sera listée en 1er plutôt qu'en avant dernier comme c'est la plus récente

2024-12-21 19:16 UTC, raphckrman commented
> @raphckrman Tu veux pas close cette pr et la refaire avec un id différent ? Quand mes pr n'étaient jamais review, j'ai fait ça et j'ai eu des reviews. En plus la pr sera listée en 1er plutôt qu'en avant dernier comme c'est la plus récente

Je mentionne déjà les membres de l'équipe et si dans quelques jours c'est pas review je re open ?

2024-12-21 19:16 UTC, raphckrman commented
ça te va ?

2024-12-21 19:21 UTC, Kgeek33 commented
Ok, ça me va, mentionne les membres de l'équipe ! (_et fais également des rappels sur le Discord, pask j'ai pas_)
Closed et reopend change rien (_ou du moins avec moi mdrr_)

2024-12-21 19:22 UTC, Kgeek33 commented
Pask c'est très très chiant de tester les prs sans expo 52
_et encore, on peut faire des downgrade de l'app sur Android, sur ios, on peut rien faire_

2024-12-21 19:23 UTC, raphckrman commented
@ecnivtwelve @tryon-dev @godetremy @Vexcited @yannouuuu plusieurs personnes attendent la MaJ vers Expo 52 pour contribuer facilement, possible de review ?

2024-12-22 14:02 UTC, tryon-dev commented
yes je regarde ca tout de suite

2024-12-22 14:11 UTC, tryon-dev commented
https://github.com/user-attachments/assets/2098c68c-36b6-4999-891a-7123e0b60a05

Alors personnellement, je ne laisserais pas cela passer cela en PROD malheureusement, l'application a un comportement douteux donc je sais pas trop quoi en penser

2024-12-22 14:12 UTC, raphckrman commented
> ScreenRecording_12-22-2024_15-09-01_1.mov 
> Alors personnellement, je ne laisserais pas cela passer cela en PROD malheureusement, l'application a un comportement douteux donc je sais pas trop quoi en penser

C'est tester via Expo Go non ? Car ces bugs là n'arrivent pas sur un build

2024-12-22 14:12 UTC, tryon-dev commented
@raphckrman est ce que tu sais si un prebuild pourrais fix tout les probleme ?

2024-12-22 14:12 UTC, tryon-dev commented
Oui c'est via Expo Go

2024-12-22 14:13 UTC, raphckrman commented
> @raphckrman est ce que tu sais si un prebuild pourrais fix tout les probleme ?

J'ai toujours fais ça et j'ai pas ces bugs là, je peut te faire un enregistrement d'écran aussi

2024-12-22 14:13 UTC, raphckrman commented
> Oui c'est via Expo Go

Oui c'est ce que je me disais sur un vrai build tu n'as aucun bug sur ça

2024-12-22 14:14 UTC, Clmnnt commented
Le truc c'est que si c'est impossible de résoudre ces bugs graphiques bah ça sera jamais implémenté

2024-12-22 14:15 UTC, Clmnnt commented
(Surtout que c'est avec Expo Go donc ça se passe pas réellement

2024-12-22 14:19 UTC, Kgeek33 commented
effectivement, sur expo go (sur ios, sur android, je ne rencontre pas ce problème), il y a des bugs graphiques qui ne sortent de je ne sais où
le graphique ne fonctionne pas sur expo et tout ça... bref, faut vrmt tester cette pr via build et voir si ces bugs graphiques peuvent être corrigé

2024-12-22 14:51 UTC, Kgeek33 approved these changes

2024-12-22 21:03 UTC, raphckrman commented
> effectivement, sur expo go (sur ios, sur android, je ne rencontre pas ce problème), il y a des bugs graphiques qui ne sortent de je ne sais où le graphique ne fonctionne pas sur expo et tout ça... bref, faut vrmt tester cette pr via build et voir si ces bugs graphiques peuvent être corrigé sur expo au futur

Ça pourrait venir du routeur, il faudrait potentiellement en rewrite un, ce qui est un grand changement, on peut regarder si une autre solution est possible sinon il faudra voir ce que cette PR devient à cause du problème de routeur

2024-12-22 21:31 UTC, Kgeek33 commented
> Ça pourrait venir du routeur, il faudrait potentiellement en rewrite un, ce qui est un grand changement, on peut regarder si une autre solution est possible sinon il faudra voir ce que cette PR devient à cause du problème de routeur 

Jspas quoi penser... Entre des bugs graphiques sur ios qui ne sort de je ne sais où et sur Android où dès que tu rencontres une erreur, l'application plante...
Expo 52 pose vraiment problème (c'est peut-être oui le router), vivement la sortie de React Native 0.77 ! 😂 (et encore, j'ai zappé la migration vers React 19, bcp de modules incompatibles)

2024-12-26 01:18 UTC, Kgeek33 commented
@raphckrman bon, qu'est ce qu'on fait de cette pr ? 😂 😭

2024-12-26 01:23 UTC, raphckrman commented
Très bonne question, tu as le courage de t'attaquer au routeur ? 😂

2024-12-26 01:25 UTC, raphckrman commented
En vrai ça m'a l'air assez fastidieux, une V8 apportera surement un nouveau routeur bien rewrite donc je sais pas :/

2024-12-26 01:26 UTC, Kgeek33 commented
> Très bonne question, tu as le courage de t'attaquer au routeur ? 😂 

Je peux 😂, et toi t'as le courage ?

2024-12-26 01:27 UTC, Kgeek33 commented
> En vrai ça m'a l'air assez fastidieux, une V8 apportera surement un nouveau routeur bien rewrite donc je sais pas :/

Très clairement, notre pr est tellement grosse qui reprend tout que là, on se lance sur une V8 mdrrr

2024-12-26 01:27 UTC, Kgeek33 commented
@JyhuKo t'en penses quoi toi ? 🤣
J'te vois faire des émojis sur les messages mdrrr

2024-12-26 01:29 UTC, raphckrman commented
le problème de rewrite un routeur est que c'est chiant à mourir, ça entrainera de nouveaux bugs etc, j'en ai discuter avec Tryon l'autre jour l'intérêt d'une V8: "un tout nouveau Routeur et rewrite pas mal surtout pour garder une cohérence dans le code".
Il ne faut pas oublier aussi que Papillon V6 était sur Expo 49. A voir

2024-12-26 01:39 UTC, Kgeek33 commented
> le problème de rewrite un routeur est que c'est chiant à mourir, ça entrainera de nouveaux bugs etc, j'en ai discuter avec Tryon l'autre jour l'intérêt d'une V8: "un tout nouveau Routeur et rewrite pas mal surtout pour garder une cohérence dans le code".
> Il ne faut pas oublier aussi que Papillon V6 était sur Expo 49. A voir

Moi, je pense que oui, faut se lancer dans un nouveau router. Par contre, faudra beaucoup se renseigner avant de rewrtie ça pour éviter le plus bugs possible.
Bien sûr, chaque nouvelle version de React Native/Expo est tjrs compliqué à rendre compatible 😭

Qu'en penses-tu ?

2024-12-26 01:42 UTC, raphckrman commented
> > le problème de rewrite un routeur est que c'est chiant à mourir, ça entrainera de nouveaux bugs etc, j'en ai discuter avec Tryon l'autre jour l'intérêt d'une V8: "un tout nouveau Routeur et rewrite pas mal surtout pour garder une cohérence dans le code".
> > Il ne faut pas oublier aussi que Papillon V6 était sur Expo 49. A voir
> 
> Moi, je pense que oui, faut se lancer dans un nouveau router. Par contre, faudra beaucoup se renseigner avant de rewrok ça pour éviter le plus bugs possible. Bien sûr, chaque nouvelle version de React Native/Expo est tjrs compliqué à rendre compatible 😭
> 
> Qu'en penses-tu ?

Faut voir si le temps que ça prendra, personnellement j'ai pas énormément de temps à cause des projets que j'ai à côté qui ont une deadline. C'est donc possible selon moi mais il faut voir si on peut garder une cohérence dans le code même avec ce nouveau routeur.

2024-12-26 01:53 UTC, Kgeek33 commented
> Faut voir si le temps que ça prendra, personnellement j'ai pas énormément de temps à cause des projets que j'ai à côté qui ont une deadline. 

Ok tu me diras quand tu seras prêt à rewrok ça ! Perso, je suis en train de faire de coder une belle nouvelle version de mon site (j'suis le seul à coder min site donc pas de deadline, si p'tetre avant la rentrée je me fixe)

> C'est donc possible selon moi mais il faut voir si on peut garder une cohérence dans le code même avec ce nouveau routeur.

C'est ça le plus problématique à gérer, refaire sans aucun impact sur le code actuel

2024-12-26 01:54 UTC, Kgeek33 commented
On close la pr alors?

2024-12-26 01:57 UTC, raphckrman commented
On peut la passer en Draft en si tu veux histoire de faire ça bien ? Ou attendre l'avis d'un mainteneur qu'on sache directement si il vaut mieux close pour qu'ils le fassent dans une V8 comme avait suggéré Tryon ? Comme tu veux

2024-12-26 01:57 UTC, JyhuKo commented
> Ok tu me diras quand tu seras prêt à rewrok ça ! Perso, je suis en train de faire de coder une belle nouvelle version de mon site (j'suis le seul à coder min site donc pas de deadline, si p'tetre avant la rentrée je me fixe)

![image](https://github.com/user-attachments/assets/a7c29f26-f47d-488a-9b92-c7db17acc7fb)

2024-12-26 02:05 UTC, Kgeek33 commented
> On peut la passer en Draft en si tu veux histoire de faire ça bien ? Ou attendre l'avis d'un mainteneur qu'on sache directement si il vaut mieux close pour qu'ils le fassent dans une V8 comme avait suggéré Tryon ? Comme tu veux 

À la limite ouais on passe la pr en draft mais pendant ce temps, faut relancer les mainteneurs notamment pask on est vrmt dans le flou 🤣
En plus, React Native 0.77 sort bientôt, j'vous laisse imaginer tous les problèmes qu'on va avoir, déjà qu'on galère avec la 0.76 😂😂

2024-12-26 02:06 UTC, raphckrman commented
> > On peut la passer en Draft en si tu veux histoire de faire ça bien ? Ou attendre l'avis d'un mainteneur qu'on sache directement si il vaut mieux close pour qu'ils le fassent dans une V8 comme avait suggéré Tryon ? Comme tu veux
> 
> À la limite ouais on passe la pr en draft mais pendant ce temps, faut relancer les mainteneurs notamment pask on est vrmt dans le flou 🤣 En plus, React Native 0.77 sort bientôt, j'vous laisse imaginer tous les problèmes qu'on va avoir, déjà qu'on galère avec la 0.76 😂😂

Yes c'est pour ça a voir avec les mainteneurs, je switch en draft

2024-12-26 02:06 UTC, Kgeek33 commented
> 
> > Ok tu me diras quand tu seras prêt à rewrok ça ! Perso, je suis en train de faire de coder une belle nouvelle version de mon site (j'suis le seul à coder min site donc pas de deadline, si p'tetre avant la rentrée je me fixe)
> 
> ![image](https://github.com/user-attachments/assets/a7c29f26-f47d-488a-9b92-c7db17acc7fb)
> 
> 
> 

Mdrrr mais je m'impose des nouvelles fonctionnalités sur mon site qui prennent énormément de temps à être développé 😂

2024-12-26 02:10 UTC, Kgeek33 commented
> Yes c'est pour ça a voir avec les mainteneurs, je switch en draft

Okay parfait ben d'ici à ce qu'on ait des réponses, mais j'vais faire une pause sur Papillon (_juste mettre à jour mes branches_) et me concacrer à mon site (et à la rentrée bien évidemment 😒)
Et toi @raphckrman ?

2024-12-26 02:12 UTC, raphckrman commented
> > Yes c'est pour ça a voir avec les mainteneurs, je switch en draft
> 
> Okay parfait ben d'ici à ce qu'on ait des réponses, mais j'vais faire une pause sur Papillon (_juste mettre à jour mes branches_) et me concacrer à mon site (et à la rentrée bien évidemment 😒)
> Et toi @raphckrman ? 

J'ai une mise à jour prévu pour Papillon et après c'est full Swift pour le Swift Student Challenge il reste plus beaucoup de temps 🤓

2024-12-26 02:16 UTC, Kgeek33 commented
> > > Yes c'est pour ça a voir avec les mainteneurs, je switch en draft
> > 
> > Okay parfait ben d'ici à ce qu'on ait des réponses, mais j'vais faire une pause sur Papillon (_juste mettre à jour mes branches_) et me concacrer à mon site (et à la rentrée bien évidemment 😒)
> > Et toi @raphckrman ? 
> 
> J'ai une mise à jour prévu pour Papillon et après c'est full Swift pour le Swift Student Challenge il reste plus beaucoup de temps 🤓

Oh c'est super ça, bon courage d'avance !
Bon, c'est pas tout ça, mais on a bien mérité notre nuit de sommeil mdrrr 😂😂

2024-12-27 18:37 UTC, Kgeek33 commented
hey @raphckrman j'ai des infos pour toi (plutôt bonnes) sur cette pr

2024-12-27 18:50 UTC, raphckrman commented
> hey @raphckrman j'ai des infos pour toi (plutôt bonnes) sur cette pr

Tu as trouvé une solution ?

2024-12-27 18:58 UTC, Kgeek33 commented
> > hey @raphckrman j'ai des infos pour toi (plutôt bonnes) sur cette pr
> 
> Tu as trouvé une solution ?

alors depuis tout à l'heure je suis en train de réécrire le router, je peux faire un commit pour te montrer stv (j'ai crée un dossier `router-v2` en conservant le dossier de base pour faire une réécriture progressive)
et aussi, j'ai trouvé les sources de plantage lorsqu'on testait sur Expo 52 : c'est le module `react-native-gesture-handler` qui pose problème. mais quand on enlève la balise `<GestureHandlerRootView>`, il y a l'erreur suivante et je cherche quel fichier provoque l'erreur : 

ERROR  Warning: Error: NativeViewGestureHandler must be used as a descendant of GestureHandlerRootView. Otherwise the gestures will not be recognized. See https://docs.swmansion.com/react-native-gesture-handler/docs/installation for more details.

2024-12-27 19:11 UTC, raphckrman commented
incroyable tu as déjà push le début du nouveau router ?

2024-12-27 19:12 UTC, raphckrman commented
> > > hey @raphckrman j'ai des infos pour toi (plutôt bonnes) sur cette pr
> > 
> > 
> > Tu as trouvé une solution ?
> 
> alors depuis tout à l'heure je suis en train de réécrire le router, je peux faire un commit pour te montrer stv (j'ai crée un dossier `router-v2` en conservant le dossier de base pour faire une réécriture progressive) et aussi, j'ai trouvé les sources de plantage lorsqu'on testait sur Expo 52 : c'est le module `react-native-gesture-handler` qui pose problème. mais quand on enlève la balise `<GestureHandlerRootView>`, il y a l'erreur suivante et je cherche quel fichier provoque l'erreur :
> 
> ERROR Warning: Error: NativeViewGestureHandler must be used as a descendant of GestureHandlerRootView. Otherwise the gestures will not be recognized. See https://docs.swmansion.com/react-native-gesture-handler/docs/installation for more details.

L'erreur ne pourrait pas venir de TouchableOpacity?

2024-12-27 19:19 UTC, Kgeek33 commented
> incroyable tu as déjà push le début du nouveau router ?

je vais le faire là, mais je préviens l'affichage est un peu moche 😅

2024-12-27 19:19 UTC, Kgeek33 commented
> L'erreur ne pourrait pas venir de TouchableOpacity?

jspas mais en tout cas, tout ce que j'ai dit est faux, je viens de tester mdrrr

2024-12-27 19:23 UTC, Kgeek33 commented
et voilà, il y a des erreurs tsc, ça sera corrigé plus tard

2024-12-28 09:37 UTC, tom-theret commented
@Kgeek33 comment on peut faire pour te contacter en PV ?

2024-12-28 12:25 UTC, Kgeek33 commented
> @Kgeek33 comment on peut faire pour te contacter en PV ?

ah jspas, j'y ai jamais réfléchi 😅

2024-12-28 12:28 UTC, tom-theret commented
> > @Kgeek33 comment on peut faire pour te contacter en PV ?
> 
> ah jspas, j'y ai jamais réfléchi 😅

Bah donne moi un moyen 😅

2024-12-28 12:31 UTC, Kgeek33 commented
> Bah donne moi un moyen 😅

mon num, ça te va ? (_et tu pourras me contacter sur whatsapp, plus pratique_)

2024-12-28 12:46 UTC, tom-theret commented
> > Bah donne moi un moyen 😅
> 
> mon num, ça te va ? (_et tu pourras me contacter sur whatsapp, plus pratique_)

Si tu veux … +33 6 25 99 12 49

2024-12-28 12:50 UTC, tom-theret commented
@Kgeek33

2024-12-28 12:52 UTC, Kgeek33 commented
ok j'tenvoie un message (jsuis en train de faire un fix sur les bugs html en même temps)

2024-12-29 00:00 UTC, Kgeek33 commented
okay @raphckrman @tom-theret j'ai des informations pour vous !

alors j'pense pas poursuivre le nouveau router car j'ai fait des optimisations sur le fichier App.tsx qui améliore les perfs sur Expo 52 (avec test y compris sur iOS) => voir commit https://github.com/PapillonApp/Papillon/pull/370/commits/5cc2e768c34362dadaf74fc778eee8e69ff89c78

- Pour iOS, j'ai trouvé la source du problème au niveau du rendu graphique et attention, vous allez être choqué… c'est Reanimated qui pose (encore) problème ! Donc demain, je désactive tous les effets d'animation effectués par Reanimated (ça sera moche mais stable)
- Pour Android (j'ai pas testé pour iOS), cependant, quand une erreur est rencontré, Expo ne répond plus et pour l'instant je n'ai pas trouvé de pistes…

faites des tests (tout le monde svp) et dites moi ce qu'il faut corriger, mis à part les problèmes graphiques sur iOS :)

2024-12-29 00:03 UTC, tom-theret commented
Sauf qu'on a besoin des animations, c'est à ça qu'on reconnaît le tacts de Papillon

2024-12-29 00:05 UTC, Kgeek33 commented
> Sauf qu'on a besoin des animations, c'est à ça qu'on reconnaît le tacts de Papillon 

Mouais c'est ça le problème, il n'y aurait pas une alternative à Reanimated tout en faisant des animations ?

2024-12-29 21:21 UTC, Kgeek33 commented
je pense que la pr #556 va améliorer la stabilité avec expo 52

2024-12-31 21:04 UTC, Clmnnt commented
alors des news ?

2024-12-31 21:06 UTC, Kgeek33 commented
> alors des news ?

Côté Android, j'ai fait des tests build tout à l'heure et c'est rempli de plantage
Même Expo est un peu plus stable (_mais rempli de plantages également_)

2024-12-31 21:07 UTC, Clmnnt commented
c'est quoi qui fait bug ?

2024-12-31 21:07 UTC, Clmnnt commented
(de mon coté j'essaye de lancer avec expo go sur iOS)

2024-12-31 21:11 UTC, Kgeek33 commented
> c'est quoi qui fait bug ? 

Je pense que c'est `react-native-reanimated` (c'est sûr pour les problèmes graphiques sur ios) mais ça peut être aussi le router qui est incompatible et qu'il faut reprendre à 0 (_pour les plantages_)

2024-12-31 21:13 UTC, Clmnnt commented
mais Papillon sans animations c'est pas papillon hein :bruh:

2024-12-31 21:15 UTC, Clmnnt commented
ah ouais en effet c plein de bugs

2024-12-31 21:17 UTC, Kgeek33 commented
> mais Papillon sans animations c'est pas papillon hein :bruh: 

Oui c'est ça le problème, ça sera extrêmement moche à utiliser Papillon 
Faudrait trouver soit une alternative à ce module, soit (ou les 2) complètement réécrire le router (car j'avais constaté que le module `react-native-gesture-handler` provoquait des plantages lorsque j'avais commencé à réécrire le router)

2024-12-31 21:18 UTC, Kgeek33 commented
> ah ouais en effet c plein de bugs
> 
> 

Mais le problème c'est qu'il a plein de bugs sur Expo qui ne sont pas présents sur build et inversement donc on est bloqué...

2024-12-31 21:18 UTC, Clmnnt commented
ouais mais réécrire un router c pas super long ?

2024-12-31 21:24 UTC, Kgeek33 commented
> ouais mais réécrire un router c pas super long ?

Si, très long. Après, j'ai commencé à le réécrire la semaine dernière donc je peux poursuivre

2024-12-31 21:25 UTC, Kgeek33 commented
Qu'en penses tu ?

2025-01-01 11:30 UTC, Kgeek33 commented
Yo tlm, déjà bonne année ! 
voici un fil Reddit que j'ai trouvé parlant de la mise à niveau vers Expo 52 : [https://www.reddit.com/r/expo/comments/1gqblmj/expo_sdk_52/?tl=fr](https://www.reddit.com/r/expo/comments/1gqblmj/expo_sdk_52/?tl=fr)

Cela confirme bien nos pistes mais je m'attendais pas que `SafeAreaView` pose problème, je m'en suis pas rendu compte

2025-01-01 12:51 UTC, Gabriel29306 commented
Je sens que ça va être (encore plus) long...

2025-01-01 21:03 UTC, Kgeek33 commented
ok alors j'ai fait un logcat sur Android pour savoir qu'est-ce qui provoquait les plantages (testé via build). Et voici l'erreur retourné lors d'un plantage (juste lors de l'ouverture de l'app...)

```
reanimated::LayoutAnimationsManager::startLayoutAnimation
```

2025-01-04 20:21 UTC, Clmnnt commented
aie coup dur pour papillon qui aura jamais expo 52 :zjesus:

2025-01-04 20:23 UTC, JyhuKo commented
> aie coup dur pour papillon qui aura jamais expo 52 :zjesus:

pourquoi tu met des emojis discord ???

2025-01-04 20:24 UTC, Clmnnt commented
je voulais voir si les emojis s'affichaient dans le webhook discord (spoiler : non)

2025-01-04 20:27 UTC, Kgeek33 commented
> aie coup dur pour papillon qui aura jamais expo 52 :zjesus:

Bon de toute façon, j'en ai discuté avec @raphckrman mais cette branche est cassé (_des choses supprimées qui ont été push sur le main_) lors des merges à cause des conflits en continu, faut refaire une branche et reprendre les modifs

2025-01-04 20:27 UTC, JyhuKo commented
> je voulais voir si les emojis s'affichaient dans le webhook discord (spoiler : non)

dommage :( att jessaye un truc <:zjesus:1147231011881615461>

2025-01-04 20:27 UTC, JyhuKo commented
ezzzzzzzzzzz

2025-01-04 20:27 UTC, Kgeek33 commented
> > je voulais voir si les emojis s'affichaient dans le webhook discord (spoiler : non)
> 
> dommage :( att jessaye un truc <:zjesus:1147231011881615461>

mais mdrrrr

2025-01-04 20:27 UTC, JyhuKo commented
jsuis chaud

2025-01-04 20:27 UTC, Clmnnt commented
ouais y’a des conflicts

2025-01-04 20:29 UTC, Kgeek33 commented
> ouais y’a des conflicts

@raphckrman on reprend à zéro toutes les modifs sur une nouvelle pr ? risqué de faire un revert depuis un commit

2025-01-04 20:34 UTC, JyhuKo commented
> > aie coup dur pour papillon qui aura jamais expo 52 :zjesus:
> 
> Bon de toute façon, j'en ai discuté avec @raphckrman mais cette branche est cassé (_des choses supprimées qui ont été push sur le main_) lors des merges à cause des conflits en continu, faut refaire une branche et reprendre les modifs

c est pour ca que le graphique des notes  s'affiche plus ?

2025-01-04 21:10 UTC, Kgeek33 commented
> > > aie coup dur pour papillon qui aura jamais expo 52 :zjesus:
> > 
> > Bon de toute façon, j'en ai discuté avec @raphckrman mais cette branche est cassé (_des choses supprimées qui ont été push sur le main_) lors des merges à cause des conflits en continu, faut refaire une branche et reprendre les modifs
> 
> c est pour ca que le graphique des notes  s'affiche plus ?

Oui c'est désactivé sur Expo : sur ios pas de problème (lors de mes derniers tests) et sur Android ça provoque une erreur qui entraîne un plantage complet d'expo

2025-01-05 18:06 UTC, JyhuKo commented
du coup il ba ce passer quoi sur cette pr ???
<:moipls:1216817535153078334>

2025-01-05 18:17 UTC, Kgeek33 commented
> du coup il ba ce passer quoi sur cette pr ??? <:moipls:1216817535153078334>

je vais en discuter avec Raph, pour le moment va falloir se contenter d'Expo 51 (donc des simulateurs :zjesus: )
Mais si vous utilisez Android, vous pouvez tjrs faire un downgrade d'Expo Go pour pouvoir tester Papillon :)

2025-01-05 19:34 UTC, tryon-dev commented
Hello, malheureusement a moins de trouver la solution miracle Papillon restera sur expo 51

2025-01-11 20:21 UTC, closed without merging