fix: affichage correct des pages en ajoutant des animations
PapillonApp/papillon-v7 pull request #373
Opened 2024-11-16 21:25 UTC by Kgeek33

# 🚀 Nouvelle Pull Request

Proposez vos modifications pour améliorer Papillon

## Informations importantes

Merci de vous référer à la documentation sur la contribution si vous avez des questions à propos des pull requests (https://gitbook.getpapillon.xyz/organisation/outils-internes/github)

## Checklist d'avant pull request

Veuillez cocher toutes les cases applicables en remplaçant [ ] par [x].

- [x] Vous avez testé de build le projet avec vos modifications et ce build **a réussi**
- [x] Vous respectez les conventions de codage et de nommage du projet
- [x] Vous utilisez la **tabulation** pour l'indentation afin de maintenir un code lisible
- [x] Cette pull request **n'est pas un duplicata** d'une autre
- [x] Cette pull request est prête à être **revue** (review) et **fusionnée** (merge)
- [x] Il n'y a pas de **`TODO`** (aka des annotations pour du code manquant) dans vos modifications
- [x] Il n'y a pas **d'erreurs de langue** dans votre code (grammaire, vocabulaire, conjugaison, orthographe)
- [x] Les détails des changements ont été décrits ci-dessous
- [x] Cette pull-request n'est pas une **"breaking-change"** (des modifications qui vont entraîner la modification du fonctionnement de certaines fonctionnalités déjà existantes)

## Changelogs proposés

- Correction affichage incorrect des pages

## Issues en lien

- Closes #310 
- Closes #350 

## Informations supplémentaires

Provenant de #325

2024-11-16 21:25 UTC, Kgeek33 commented
@ecnivtwelve @Vexcited @tryon-dev

2024-11-16 21:27 UTC, Vexcited approved these changes, later dismissed
LTGM, à voir avec @ecnivtwelve au niveau des animations proposées

2024-11-16 22:07 UTC, Kgeek33 commented
> LTGM, à voir avec @ecnivtwelve au niveau des animations proposées

oui je pense qu'il faut faire des adaptations avec iOS

2024-11-17 21:02 UTC, ecnivtwelve commented on src/router/screens/account/index.tsx
>    createScreen("Home", () => <HomeStackScreen accountScreens={screens} />, {
On pourrait peut être éviter la redondance en appliquant les animations sur la fonction `createScreen()` directement

2024-11-17 21:02 UTC, ecnivtwelve commented on src/router/screens/account/index.tsx
> +    animation: "simple_push",
Il serait également préférable d'appliquer le changement uniquement sur Android, vu que sur iOS, ce n'est pas nécéssaire et pas forcément très esthétique

2024-11-18 18:04 UTC, Kgeek33 commented on src/router/screens/account/index.tsx
> +    animation: "simple_push",
normalement cette animation n'a aucune influence sur la page d'accueil, je vais mettre `none` à la place

2024-11-18 18:16 UTC, Kgeek33 commented on src/router/screens/account/index.tsx
>    createScreen("Home", () => <HomeStackScreen accountScreens={screens} />, {
alors pour éviter que je fasse n'importe quoi, j'ai fait ceci :  
`const animation = "slide_from_bottom";`

et à la place de `animation: "slide_from_bottom"`, j'ai fait `animation`

2024-11-18 18:16 UTC, Kgeek33 commented on src/router/screens/account/index.tsx
>    createScreen("Home", () => <HomeStackScreen accountScreens={screens} />, {
si c'est pas bon, réouvre une conversation, j'essaierai de corriger :)

2024-11-26 15:49 UTC, ecnivtwelve requested changes

2024-11-26 15:49 UTC, ecnivtwelve commented on src/router/screens/account/index.tsx
> +const animation = "slide_from_bottom";
Je réitère ma demande d'appliquer ce changement uniquement **sous Android**

2024-11-26 16:34 UTC, Kgeek33 commented on src/router/screens/account/index.tsx
> +const animation = "slide_from_bottom";
Je fais ça en rentrant chez moi, dans 15 min au plus tard

2024-11-26 17:32 UTC, Kgeek33 commented on src/router/screens/account/index.tsx
> +const animation = "slide_from_bottom";
C'est bon pour moi

2024-12-11 10:05 UTC, ecnivtwelve commented
Depuis, ça a été intégré dans le `createScreen`
https://github.com/PapillonApp/Papillon/blob/8d49e128e96243dc6a2c27070aa09380a04126c6/src/router/helpers/create-screen.ts#L12-L14

2024-12-11 10:05 UTC, closed without merging

2024-12-11 10:06 UTC, Kgeek33 commented
Ok c'est plus pratique 😂