Import and export subjects colors and names
PapillonApp/papillon-v7 pull request #392
Opened 2024-11-30 13:40 UTC by codeuriii

# 🚀 Nouvelle Pull Request

Proposez vos modifications pour améliorer Papillon

## Informations importantes

Merci de vous référer à la documentation sur la contribution si vous avez des questions à propos des pull requests (https://gitbook.getpapillon.xyz/organisation/outils-internes/github)

## Checklist d'avant pull request

Veuillez cocher toutes les cases applicables en remplaçant [ ] par [x].

- [x] Vous avez testé de build le projet avec vos modifications et ce build **a réussi**
- [x] Vous respectez les conventions de codage et de nommage du projet
- [x] Vous utilisez la **tabulation** pour l'indentation afin de maintenir un code lisible
- [x] Cette pull request **n'est pas un duplicata** d'une autre
- [x] Cette pull request est prête à être **revue** (review) et **fusionnée** (merge)
- [x] Il n'y a pas de **`TODO`** (aka des annotations pour du code manquant) dans vos modifications
- [x] Il n'y a pas **d'erreurs de langue** dans votre code (grammaire, vocabulaire, conjugaison, orthographe)
- [x] Les détails des changements ont été décrits ci-dessous
- [x] Cette pull-request n'est pas une **"breaking-change"** (des modifications qui vont entraîner la modification du fonctionnement de certaines fonctionnalités déjà existantes)

## Changelogs proposés

Page des paramètres de matière (SettingsSubjects.tsx)
- Ajout d'un bouton exporter qui permet de copier un json contenant les informations des matières, leurs nom, couleurs etc.
- Ajout d'un bouton importer qui permet de remplacer le json existant par le json contenu dans la presse papier. Une simple vérification de si le contenu de la presse papier est un json.

## Informations supplémentaires

Je sais pas pourquoi il y a des modifications dans le package.json

2024-11-30 15:54 UTC, Kgeek33 commented
C'est normal la modification du fichier `package.json`, c'est npm ou autre qui a remis les dépendances dans l'ordre alphabétique. Mais ça n'a rien changé de plus, sinon le fichier `package-lock.json` serait changé

2024-11-30 15:57 UTC, Kgeek33 commented
Jppas tester, comme on est tjrs en expo 51 (expo 52 obligatoire 🙄)
Bref, ça vérifie uniquement le presse papier ? Ou on peut chercher un fichier JSON depuis le stockage du téléphone ?

2024-11-30 16:20 UTC, codeuriii commented
Ca utilise uniquement la presse papier, je trouve que c'est plus simple de copier du texte que de gérer des fichiers sur tel

2024-11-30 16:20 UTC, codeuriii commented
je dois faire la migration expo 52 ?

2024-11-30 16:28 UTC, Kgeek33 commented
> Ca utilise uniquement la presse papier, je trouve que c'est plus simple de copier du texte que de gérer des fichiers sur tel

OK, oui c'est compréhensible

2024-11-30 16:29 UTC, Kgeek33 commented
> je dois faire la migration expo 52 ?

Non non, c'est trop de changements. Mais regarde, on l'a fait sur la pr #370 (n'hésite pas à tester d'ailleurs :))

2024-11-30 16:31 UTC, codeuriii commented
Du coup concrètement je dois faire quoi a part attendre le review du code ?

2024-11-30 18:24 UTC, Kgeek33 commented
> Du coup concrètement je dois faire quoi a part attendre le review du code ?

Rien, faut attendre la review de ton code 😂
À la limite, je peux installer une ancienne version d'expo sur mon tél pour pouvoir tester

2024-12-01 06:21 UTC, codeuriii commented
Ok merci bah on va attendre tranquilou

2024-12-01 15:34 UTC, Kgeek33 requested changes
Parfait dans l'ensemble, juste les fautes de frappe que je t'ai signalé
Cependant, p'têtre qu'il serait mieux d'utiliser `showAlert` pour Android et `Alert.Alert` ? faut voir avec les autres

2024-12-01 15:34 UTC, Kgeek33 commented on src/views/settings/SettingsSubjects.tsx
> +                "Exporter les couleurs actuelles vers la presse papier ?",
Faute de frappe
```suggestion
                "Exporter les couleurs actuelles vers le presse papier ?",
```

2024-12-01 15:34 UTC, Kgeek33 commented on src/views/settings/SettingsSubjects.tsx
> +                "Importer une table de couleurs depuis la presse papier ?",
Faute de frappe
```suggestion
                "Importer une table de couleurs depuis le presse papier ?",
```

2024-12-01 16:29 UTC, codeuriii commented
> Parfait dans l'ensemble, juste les fautes de frappe que je t'ai signalé Cependant, p'têtre qu'il serait mieux d'utiliser `showAlert` pour Android et `Alert.Alert` ? faut voir avec les autres

Pour ca, je me suis inspiré de la popup pour reset les matières donc jsp

2024-12-01 17:07 UTC, Kgeek33 commented
> > Parfait dans l'ensemble, juste les fautes de frappe que je t'ai signalé Cependant, p'têtre qu'il serait mieux d'utiliser `showAlert` pour Android et `Alert.Alert` ? faut voir avec les autres
> 
> Pour ca, je me suis inspiré de la popup pour reset les matières donc jsp

Oh, il y avait déjà `Alert.Alert`?🤦
OK my bad, j'm'en occuperai dans ma pr #378

2024-12-01 17:08 UTC, Kgeek33 approved these changes
Parfait 👌

2024-12-10 04:49 UTC, codeuriii commented
et pour cette pr ? y a quoi qui bloque ?

2024-12-11 09:59 UTC, ecnivtwelve commented
Pas forcément fan de l'intégration depuis le presse-papier, peut être mieux de faire ça via le stockage comme la V6

2024-12-11 10:09 UTC, codeuriii commented
en pratique ca va etre des gens qui partage leurs config a le reste de la classe donc
1. pour exporter, il faut faire un fichier, l'enregistrer au bon endroit, faire en sorte que cet endroit est accessible et retrouvable par "l'émetteur" pour envoyer aux gens, qui téléchargent, mettent au bon endroit, retrouve dans papillon et enfin import.
2. l'émetteur copie, envoie te texte sur n'importe quel réseaux social (insta gère uniquement les images) et les autres copie le texte en un clique et import dans papillon

Le copié collé est beaucoup plus simple

2024-12-11 10:14 UTC, ecnivtwelve commented
> Le copié collé est beaucoup plus simple

C'est pas forcément très propre, ça peut créer des très longs messages et des bugs assez facilement, donc pas forcément convaincu par cette intégration perso

2024-12-11 10:15 UTC, codeuriii commented
comment ca des bugs ?
et puis je parle pas de la messagerie papillon, et oui effectivement des messages peuvent etre longs mais les gens savent

2024-12-12 07:43 UTC, ecnivtwelve commented
> comment ca des bugs ? et puis je parle pas de la messagerie papillon, et oui effectivement des messages peuvent etre longs mais les gens savent

Ça n'empêche pas que c'est vraiment pas propre et peu safe

2024-12-12 07:44 UTC, codeuriii commented
Je comprend pas, la data qu'elle soit dans.un fichier ou dans la presse papier, ça change rien à la data

2024-12-12 07:48 UTC, ecnivtwelve commented
> Je comprend pas, la data qu'elle soit dans.un fichier ou dans la presse papier, ça change rien à la data

Bah c'est une horrible manière (niveau UX ou stabilité) de faire transiter ça par le clipboard

2024-12-12 07:49 UTC, codeuriii commented
C'est mieux que la gestion de fichier sur téléphone.

2024-12-12 07:49 UTC, codeuriii commented
En plus c'est crossplatform

2024-12-12 13:43 UTC, ecnivtwelve commented
> C'est mieux que la gestion de fichier sur téléphone.

Non.

2024-12-12 14:03 UTC, codeuriii commented
> > C'est mieux que la gestion de fichier sur téléphone.
> 
> Non.

sisi je t'assure

2024-12-12 14:45 UTC, tryon-dev commented
C'est horrible de faire cela je refuse d'avance la PR

2024-12-12 14:49 UTC, codeuriii commented
ta essayé de tester avant de critiquer ?

2024-12-12 14:49 UTC, codeuriii commented
et bien je vais implémenter les fichiers mais je garde le presse papier

2024-12-12 14:50 UTC, codeuriii commented
Si c si horrible que ca, pourquoi Kgeek a approuvé ?

2024-12-13 08:37 UTC, ecnivtwelve commented
> Si c si horrible que ca, pourquoi Kgeek a approuvé ?

Une personne approuvant (encore plus n'étant pas mainteneur) ne garantit ni la pertinence ni l'UX de ta fonctionnalité. Merci bien pour ta PR mais celle-ci ne maintient pas les conditions d'expérience utilisateur requises.

2024-12-13 10:37 UTC, codeuriii commented
C'est pour ca que je vais rajouter les fichiers, même si je pense que c'est plus pratique.
Vous avez pensé a faire un sondage ? pour voir ce que les gens trouvent plus simple

2024-12-13 13:05 UTC, Kgeek33 commented
j'ai approuvé pask le code est correct. après, je suis d'accord avec @ecnivtwelve, le problème de cette fonctionnalité, c'est que il peut facilement y avoir un bug si un caractère Json est modifié
De plus, en tout cas sur Android, le presse papier s'efface au bout d'1 heure. (_on suppose_) si la personne a copié le Json et qu'elle attend au bout de 2 heures, il va rien se passer. 
pire encore, la personne peut faire des copié/collé entre temps et quand ça va récupérer le presse papier, erreur

2024-12-13 13:06 UTC, Kgeek33 commented
le fichier est mieux, car c'est plus accessible pour tout le monde (notamment au niveau du partage entre personne), ou il y aura moins de risque de bugs :)

2024-12-14 02:30 UTC, codeuriii commented
> j'ai approuvé pask le code est correct. après, je suis d'accord avec @ecnivtwelve, le problème de cette fonctionnalité, c'est que il peut facilement y avoir un bug si un caractère Json est modifié
> De plus, en tout cas sur Android, le presse papier s'efface au bout d'1 heure. (_on suppose_) si la personne a copié le Json et qu'elle attend au bout de 2 heures, il va rien se passer. 
> pire encore, la personne peut faire des copié/collé entre temps et quand ça va récupérer le presse papier, erreur

C'est pour ça que je regarde si le string est jsonable. Si il y a une erreur, c'est fort probable que ça ne marche pas donc pas d'erreur de l'app

2024-12-15 15:23 UTC, codeuriii commented
todo
document picker avec react native ou jsp quoi
ptet expo jsp

2024-12-16 13:25 UTC, codeuriii commented
voila c'est pret

2024-12-16 17:57 UTC, Kgeek33 commented
Résout tes conflits, je testerai plus tard

2024-12-17 03:24 UTC, codeuriii commented
comment je fais ca ?

2024-12-17 06:20 UTC, Kgeek33 commented
Tu utilises VSCode ?

2024-12-17 07:21 UTC, codeuriii commented
Oui

2024-12-17 08:04 UTC, Kgeek33 commented
> Oui

Pour résoudre les conflits :

- Déjà, faut être sur la branche de ta pr (`main`)
- Ouvre un terminal (Affichage => Terminal)
- Écris tout d'abord `git fetch --all --prune`
- Ensuite quand c'est bon tu écris (tjrs dans la console) `git merge upstream/main`
- Et là, sur ton VSCode, tu pourras résoudre les conflits qui s'affichent là où tu fais les commits

2024-12-17 10:26 UTC, codeuriii commented
j'ai utilisé github et ca m'a l'air bon

2024-12-19 03:19 UTC, codeuriii commented
J'ai bien besoin d'une review svp

2024-12-19 07:25 UTC, Kgeek33 commented
> J'ai bien besoin d'une review svp

Déso, j'ai oublié de review, extrêmement concentré sur le lycée et sur la mise à niveau vers expo 52
Je fais ça ce soir ou ce midi. Appuie sur l'icône piyr me redemander une review comme la dernière fois

2024-12-19 15:21 UTC, codeuriii commented
Tkt c pas grave

2024-12-19 21:01 UTC, Kgeek33 requested changes
ok ça fonctionne bien en général mais applique mes recommandations au cas où si une erreur surviendrait lors de l'import depuis le presse papier/fichier

et aussi, il y a des rendus bizarres sur les `Alert.Alert` (des padding ou des margin, jspas)

2024-12-19 21:01 UTC, Kgeek33 commented on src/views/settings/SettingsSubjects.tsx
> +                        }
ajoute un `else` au cas où si le fichier JSON ou le presse papier est cassée (_même si c'est improbable, c'est pour les testeurs chiants comme moi mdrr_)
Tu fais un `Alert.Alert` en disant qu'une erreur est survenue

2024-12-19 21:01 UTC, Kgeek33 commented on src/views/settings/SettingsSubjects.tsx
> +                          }
même chose, ajoute un `else`

2024-12-23 12:42 UTC, closed without merging

2024-12-23 13:20 UTC, codeuriii commented
mais wsh ta un problème ?

2024-12-23 13:22 UTC, JyhuKo commented
> mais wsh ta un problème ?

mdrrrr pq

2024-12-23 13:24 UTC, codeuriii commented
bah le reuf il ferme alors que je travaille dessus et j'ai rien demandé

2024-12-23 13:26 UTC, JyhuKo commented
j'avoue il est en pierre, il a meme pas mis de comment

2024-12-23 13:34 UTC, godetremy commented
> mais wsh ta un problème ?

Hello,

Si t'as PR a été close c'est que sont intégration ne nous semble pas optimisée.

En revanche, peu importe la PR et la raison **tu dois rester respecter envers n'importe qui** au risque de te retrouver exclu de la contribution.

Merci 🙃

2024-12-23 13:35 UTC, codeuriii commented
a quel moment j'ai manqué de respect ?
si vous pouviez etre encore moins précis j'apprécierais