Choose color hex for subjects
PapillonApp/papillon-v7 pull request #393
Opened 2024-12-01 08:22 UTC by codeuriii

# 🚀 Nouvelle Pull Request

Proposez vos modifications pour améliorer Papillon

## Informations importantes

Merci de vous référer à la documentation sur la contribution si vous avez des questions à propos des pull requests (https://gitbook.getpapillon.xyz/organisation/outils-internes/github)

## Checklist d'avant pull request

Veuillez cocher toutes les cases applicables en remplaçant [ ] par [x].

- [x] Vous avez testé de build le projet avec vos modifications et ce build **a réussi**
- [x] Vous respectez les conventions de codage et de nommage du projet
- [x] Vous utilisez la **tabulation** pour l'indentation afin de maintenir un code lisible
- [x] Cette pull request **n'est pas un duplicata** d'une autre
- [x] Cette pull request est prête à être **revue** (review) et **fusionnée** (merge)
- [x] Il n'y a pas de **`TODO`** (aka des annotations pour du code manquant) dans vos modifications
- [x] Il n'y a pas **d'erreurs de langue** dans votre code (grammaire, vocabulaire, conjugaison, orthographe)
- [x] Les détails des changements ont été décrits ci-dessous
- [x] Cette pull-request n'est pas une **"breaking-change"** (des modifications qui vont entraîner la modification du fonctionnement de certaines fonctionnalités déjà existantes)

## Changelogs proposés

Dans le menu paramètres, matières, et clique sur une matière, j'ai rajouté un bouton + qui permet d'ouvrir une fenêtre et de rentrer un code hexadécimal pour une couleur personalisée.

2024-12-01 09:14 UTC, Louis-htmlcss commented
On peut avoir une image stp

2024-12-01 10:50 UTC, codeuriii commented
Pas de problèmes j'envoie ca de suite

2024-12-01 11:03 UTC, codeuriii commented
![image](https://github.com/user-attachments/assets/1e4e2a9f-e51d-40ff-85ea-2834c3426cac)

2024-12-01 12:34 UTC, raphckrman commented
Je suis pas sur niveau design, il faudrait une review de @ecnivtwelve ou @toi-et-moi aussi

2024-12-01 12:36 UTC, codeuriii commented
Ok si jamais ca va pas je changerais, juste je peux rajouter des commits et ca va se mettre direct dans cette pull request ?

2024-12-01 12:52 UTC, raphckrman commented
oui si tu les met sur la même branche

2024-12-01 12:53 UTC, codeuriii commented
Parfait bah je tafferais dessus au pire

2024-12-01 13:15 UTC, Louis454545 requested changes
il ya  quelque probleme, deja, en mode sombre  le bouton pour le color picker n'ait pas visible en mode sombre. Puis l'ui du color picker ne repecte pas du tout l'ui de l'application comme la dit @raphckrman

2024-12-01 13:40 UTC, codeuriii commented
Je travail sur le mode sombre, je suis toute ouie pour des suggestions

2024-12-01 13:45 UTC, Louis454545 commented
> Je travail sur le mode sombre, je suis toute ouie pour des suggestions

j'avais deja proposer de pouvoir choisir la couleur de l'application mais ils ne voulaient pas car il voulaient avoir leur propre pallete de couleur

2024-12-01 13:46 UTC, codeuriii commented
Je parlait de la forme des boutons, j'avance bien sur le dark

2024-12-01 13:59 UTC, Louis-htmlcss commented
utilise lucid  react pour  l'icone, utilise l'icone Palette en vrai c'est mieux

2024-12-01 13:59 UTC, codeuriii commented
Quelle icone ?

2024-12-01 14:00 UTC, Louis-htmlcss commented
> Quelle icone ?



> Quelle icone ?

https://lucide.dev/icons/palette

2024-12-01 14:00 UTC, codeuriii commented
Je dois modifier quelle icone ?

2024-12-01 14:01 UTC, Louis-htmlcss commented
> Je dois modifier quelle icone ?

pour aller sur ton modificatuer de  couleur

2024-12-01 14:01 UTC, codeuriii commented
le + ?

2024-12-01 14:01 UTC, Louis-htmlcss commented
> le + ?

ouais

2024-12-01 14:01 UTC, Louis-htmlcss commented
apres  tu  fait comme tu veux mais je trouve ca mieux

2024-12-01 14:02 UTC, codeuriii commented
Pk il faut le changer ?

2024-12-01 14:02 UTC, codeuriii commented
Ah oui je vois, style une pipette

2024-12-01 14:02 UTC, Louis-htmlcss commented
C'est pas grave, focalise toi surtout sur l'ui de ton color  picker

2024-12-01 14:13 UTC, codeuriii commented
Tu peux review stp @Louis-htmlcss

2024-12-01 14:16 UTC, Louis454545 commented
il faut aussi que les boutons soit de la couleur de l'application, puis regarde sur les autres fichiers comment est fait un bouton comme ca ta la meme ui

2024-12-01 14:16 UTC, codeuriii commented
Ok je fais ca

2024-12-01 14:23 UTC, codeuriii commented
Je trouve ca ou ?

2024-12-01 14:24 UTC, Louis-htmlcss commented
par  exemple 

> Je trouve ca ou ?

par exemple dans le choix de couleur de l'application

2024-12-01 14:33 UTC, codeuriii commented
Comment on change la width pour 45%?

2024-12-01 14:34 UTC, Louis454545 commented
> Comment on change la width pour 45%?

Google est ton ami

2024-12-01 15:40 UTC, Kgeek33 reviewed
Correct en général (_même s'il faudrait désactiver le bouton `Valider` tant que l'utilisateur n'a pas saisi les 6 caractères obligatoires_)
Mais je suis d'accord qu'au niveau du design, on peut mieux faire. Ce que j'aurai fait, c'est que quand l'utilisateur clique sur le bouton +, ça affiche une ligne comme "Nom de la matière" avec un bouton "Valider"

2024-12-01 15:40 UTC, Kgeek33 commented on src/views/settings/SettingsSubjects.tsx
> +    console.log(newColor);
À supprimer
```suggestion
```

2024-12-01 16:11 UTC, codeuriii commented
> Correct en général (_même s'il faudrait désactiver le bouton `Valider` tant que l'utilisateur n'a pas saisi les 6 caractères obligatoires_) Mais je suis d'accord qu'au niveau du design, on peut mieux faire. Ce que j'aurai fait, c'est que quand l'utilisateur clique sur le bouton +, ça affiche une ligne comme "Nom de la matière" avec un bouton "Valider"

Sorry je sais pas faire la ligne en question, mais je fais le validate disable

2024-12-01 17:05 UTC, Kgeek33 commented
> > Correct en général (_même s'il faudrait désactiver le bouton `Valider` tant que l'utilisateur n'a pas saisi les 6 caractères obligatoires_) Mais je suis d'accord qu'au niveau du design, on peut mieux faire. Ce que j'aurai fait, c'est que quand l'utilisateur clique sur le bouton +, ça affiche une ligne comme "Nom de la matière" avec un bouton "Valider"
> 
> Sorry je sais pas faire la ligne en question, mais je fais le validate disable

Faut juste copier le code où c'est marqué "Nom de la matière" mais je vais regarder d'abord le rendu de tes récents commits

2024-12-01 17:32 UTC, Kgeek33 commented
@codeuriii voilà à quoi je pensais :) 

![Screenshot_2024-12-01-18-31-28-316_host.exp.exponent.png](https://github.com/user-attachments/assets/fd4e35bd-35a1-46e3-af54-58fbe7545a83)

2024-12-02 02:36 UTC, codeuriii commented
Et tu l'as dev ou c'est que du design ?

2024-12-02 11:55 UTC, Kgeek33 commented
> Et tu l'as dev ou c'est que du design ?
> Parce que si tu l'as dev, je peux l'ajouter stv

Je l'ai dev oui. J'tenvoie le code plus tard

2024-12-02 12:24 UTC, codeuriii commented
Fais un commit plus tot, je me chargerais de rendre ca fonctionnel

2024-12-02 12:30 UTC, Kgeek33 commented
> Fais un commit plus tot, je me chargerais de rendre ca fonctionnel

OK faut que tu me donnes les droits (Paramètres de ton repo => Collaborateurs => t'écris mon pseudo)

2024-12-02 12:34 UTC, codeuriii commented
Bah pk ta deja fais des commits plus haut refais pareil

2024-12-02 12:36 UTC, Kgeek33 commented
Ah oui j'ai oublié, c'est plus simple😅
Je fais ça plus tard

2024-12-02 12:36 UTC, codeuriii commented
parfait tu gère

2024-12-02 16:22 UTC, Kgeek33 requested changes
Voilà ce que j'ai fait
À améliorer bien sûr, mais c'est la base pour un affichage correct :)

2024-12-02 16:22 UTC, Kgeek33 commented on src/views/settings/SettingsSubjects.tsx
>                  </MemoizedNativeList>
```suggestion
                    {isModalVisible && (
                      <MemoizedNativeList>
                        <MemoizedNativeItem>
                          <MemoizedNativeText variant="subtitle" numberOfLines={1}>
                            Écrire la couleur (6 caractères)
                          </MemoizedNativeText>
                          <TextInput
                            style={{
                              fontFamily: "medium",
                              fontSize: 16,
                              color: colors.text,
                            }}
                            value={customColor.startsWith("#") ? customColor : "#" + customColor}
                            onChangeText={(text) => {
                              if (!text.startsWith("#") || Number.isNaN(parseInt(text.split("#")[1]))) {
                                text = "#";
                              }

                              const validText = text.slice(0, 7).toUpperCase();
                              setCustomColor(validText);
                              if (/^#[0-9A-F]{6}$/i.test(validText)) {
                                setDisableValidate(false);
                              } else {
                                setDisableValidate(true);
                              }
                            }}
                            autoFocus
                          />
                        </MemoizedNativeItem>
                      </MemoizedNativeList>
                    )}
                  </MemoizedNativeItem>
                </MemoizedNativeList>
```

2024-12-02 16:22 UTC, Kgeek33 commented on src/views/settings/SettingsSubjects.tsx
> +                </Modal>
Laisse ça en commentaire pour le moment
```suggestion
```

2024-12-02 16:32 UTC, codeuriii commented
J'ai tout commit, je taff dessus

2024-12-02 16:41 UTC, Kgeek33 commented
ok très bien. faut juste ajouter une prévisualisation de la couleur et (_peut-être_) un bouton Valider

2024-12-02 16:42 UTC, codeuriii commented
j'ai pensé, pourquoi s'embeter avec le bouton palette, autant laisser toujours ouvert

2024-12-02 16:49 UTC, Kgeek33 commented
> j'ai pensé, pourquoi s'embeter avec le bouton palette, autant laisser toujours ouvert

vsy, travailles y, publie ça en commit et je testerai pour dire ce que j'en pense :)

2024-12-02 16:50 UTC, codeuriii commented
je pense que je publierais ca demain soir

2024-12-03 14:08 UTC, codeuriii commented
@Kgeek33 tu peux tester et review stp

2024-12-03 14:21 UTC, Kgeek33 commented
Ok je te review au plus tôt à 18h

2024-12-03 14:21 UTC, codeuriii commented
il est quelle heure chez toi ? chez moi il est 18h25, donc jsp

2024-12-03 14:22 UTC, Kgeek33 commented
15h25 perso

2024-12-03 14:22 UTC, codeuriii commented
ah ok, donc ca fais 21h pour moi, bah je verrai ta review demain

2024-12-03 21:21 UTC, Kgeek33 requested changes
Voilà pour l'instant mes recommandations, mais c'est parfait dans l'ensemble

2024-12-03 21:21 UTC, Kgeek33 commented on src/views/settings/SettingsSubjects.tsx
> +                    {(
```suggestion
```
Et faudra réindenter tout le code à la suite

2024-12-03 21:21 UTC, Kgeek33 commented on src/views/settings/SettingsSubjects.tsx
> +                    )}
```suggestion
```
Jusqu'ici !

2024-12-03 21:21 UTC, Kgeek33 commented on src/views/settings/SettingsSubjects.tsx
> +                            Écrire la couleur (6 caractères)
Pour éviter que l'utilisateur fasse ça en premier :

```suggestion
                            Ou écrire la couleur (6 caractères)
```

2024-12-03 21:21 UTC, Kgeek33 commented on src/views/settings/SettingsSubjects.tsx
> +                              autoFocus
```suggestion
```
Plus besoin

2024-12-03 21:21 UTC, Kgeek33 commented on src/views/settings/SettingsSubjects.tsx
> +  const [customColor, setCustomColor] = useState("");
Pour éviter que <TextInput> soit vide 
```suggestion
  const [customColor, setCustomColor] = useState(selectedSubject[1].color);
```
Et si ça fonctionne, il faudrait peut-être remplacer `selectedSubject[1].color` => `customColor` pour une automatisation du choix des couleurs

2024-12-04 02:44 UTC, codeuriii commented
Je regarderais ça ce midi, ce qui fais pour vous 7h

2024-12-04 06:09 UTC, codeuriii commented
concrètement, je commit ca, et ca peut  se merge ?

2024-12-04 06:20 UTC, Kgeek33 commented
> concrètement, je commit ca, et ca peut  se merge ?

Il faudra attendre la review de 2 personnes de l'équipe Papillon. Si 2 personnes de l'équipe approuvent ta pr, alors elle sera merge

2024-12-04 06:34 UTC, codeuriii commented
comment on fais pour faire partie de l'équipe et gérer les pull requests ?

2024-12-04 06:37 UTC, Kgeek33 commented
> comment on fais pour faire partie de l'équipe et gérer les pull requests ?

Jspas, mais j'pense qu'il faut demander l'autorisation sur le Discord de Papillon. 
Perso, j'fais pas partie de l'équipe mais j'suis juste contributeur

2024-12-04 06:39 UTC, Kgeek33 commented
Donc je peux review des pr (_comme ce que je t'ai fait_) à la différence que quand j'accepte une pr, c'est juste pour l'affichage.
Il faut 2 review approuvées de l'équipe pour que la pr puisse être merge

2024-12-04 08:26 UTC, codeuriii commented
Voila tout est beau tout est propre, l'indent est bon, et la default color aussi

2024-12-04 09:09 UTC, Kgeek33 commented
> Voila tout est beau tout est propre, l'indent est bon, et la default color aussi

OK parfait, je fais ça tout à l'heure
Redemande-moi de review, t'as un bouton pour relancer

![Screenshot_2024-12-04-10-09-26-321_com.opera.browser-edit.jpg](https://github.com/user-attachments/assets/caca8467-0203-462a-bb43-272cabf08ae5)

2024-12-04 11:05 UTC, Louis454545 commented
Dommage,  je ne participe plus à ce projet, surtout que je venais de finir le background fetch et les notifs

2024-12-04 12:51 UTC, Kgeek33 commented
> Dommage, je ne participe plus à ce projet, surtout que je venais de finir le background fetch et les notifs

ah mince, c'est dommage 😢

2024-12-04 13:29 UTC, Kgeek33 requested changes
tu fais tout ça et là, je pourrai approuver ! mais vrmt pas mal

2024-12-04 13:29 UTC, Kgeek33 commented on src/views/settings/SettingsSubjects.tsx
> +                          <TouchableOpacity
pour rendre l'icône de validation intéractive
```suggestion
                          {customColor !== selectedSubject[1].color && (
                            <TouchableOpacity
```

2024-12-04 13:29 UTC, Kgeek33 commented on src/views/settings/SettingsSubjects.tsx
> +                                setCustomColor("");
non faut pas. Mais on va rendre ça encore plus intéractif !
```suggestion
                                setSelectedSubject((prev) => {
                                  if (prev) {
                                    prev[1].color = customColor;
                                  }
                                  return prev;
                                });
```

2024-12-04 13:29 UTC, Kgeek33 commented on src/views/settings/SettingsSubjects.tsx
> +                          </TouchableOpacity>
et on n'oublie pas
```suggestion
                            </TouchableOpacity>
                          )}
```

2024-12-04 13:29 UTC, Kgeek33 commented on src/views/settings/SettingsSubjects.tsx
> +import { Alert, FlatList, KeyboardAvoidingView, Text, TextInput, TouchableOpacity, View, Modal, StyleSheet, Button } from "react-native";
pour une indentation parfaite : 
```suggestion
import {
  Alert,
  FlatList,
  KeyboardAvoidingView,
  Text,
  TextInput,
  TouchableOpacity,
  View,
  Modal,
  StyleSheet,
  Button
} from "react-native";
```

2024-12-04 13:33 UTC, codeuriii commented
chef je fais quoi du coup ?

2024-12-04 13:35 UTC, Kgeek33 commented
Tu commits ce que je t'ai dit comme modif, tu indentes correctement, et c'est tout

2024-12-04 13:36 UTC, codeuriii commented
je pense que c mieux de laisser une croix des fois que l'utilisateur mette nimporte quoi et ne sais pas trop a quoi s'attendre, genre il met sa valeur et y a rien qui se passe, c mieux de laisser la croix.

2024-12-04 13:36 UTC, codeuriii commented
mais les indents a part celle des import est correcte

2024-12-04 13:39 UTC, Kgeek33 commented
> je pense que c mieux de laisser une croix des fois que l'utilisateur mette nimporte quoi et ne sais pas trop a quoi s'attendre, genre il met sa valeur et y a rien qui se passe, c mieux de laisser la croix.

Ah oui ça laisse afficher la croix. C'est juste que si c'est la couleur saisie dans le <TextInput> est la même que celle enregistrée, alors le bouton pour valider est caché, c'est ça que j'ai modifié
La croix, je n'y ai pas touchée

2024-12-04 13:45 UTC, codeuriii commented
c parfait tout est propre tout est nickel

2024-12-04 13:48 UTC, Kgeek33 commented
ok je teste

2024-12-04 13:58 UTC, Kgeek33 approved these changes
Parfait 👍

2024-12-04 15:27 UTC, codeuriii commented
@Vexcited hello est ce que tu peux me dire ce que t'en pense stp, et éventuellement merge si c bon, merciii

2024-12-06 07:37 UTC, godetremy commented
Cette PR devra avoir l'avis de Tom, car elle touche à l'interface ! Je lui transmet !

2024-12-09 07:13 UTC, godetremy commented
- On a regardé l'intégration avec Tomer d'autres et on trouve pas l'interface exceptionnelle ! Deja le principe de mettre un code hexadécimal précis n'est pas très UX friendly ! Il faudrait une roue des couleurs selon moi !

2024-12-09 07:40 UTC, codeuriii commented
C'est pour les personne qui ne trouvent pas la couleur qu'ils veulent bah y a ça. Ps une roue des couleurs c'est trop gros

2024-12-09 12:38 UTC, codeuriii commented
C'est surtout pour les plus avancés qui feront leurs papillon en fonction de pronote bien comme il faut puis exporterons pour leurs camarades

2024-12-11 09:57 UTC, ecnivtwelve approved these changes
J'ai fait quelques changements de design, sinon nickel !

2024-12-11 10:11 UTC, codeuriii commented
ta fais le commit et tt ? ca peut se merge ?

2024-12-11 10:13 UTC, ecnivtwelve commented
> ta fais le commit et tt ? ca peut se merge ?

j'ai commit dans ta PR, ça sera ajouté a celle-ci : https://github.com/PapillonApp/Papillon/pull/393/commits/508c786c015572d8c47fe71867bc6ef92d72707e

2024-12-11 10:13 UTC, codeuriii commented
parfait alors, tu peux merge ?

2024-12-11 10:15 UTC, ecnivtwelve commented
> parfait alors, tu peux merge ?

il faut attendre une seconde review comme indiqué dans les reviewers en attente : 2 mainteneurs de Papillon doivent valider chaque ajout dans l'app

2024-12-11 10:16 UTC, codeuriii commented
pourquoi ?

2024-12-11 16:10 UTC, tryon-dev approved these changes

2024-12-11 16:10 UTC, codeuriii commented
tu peux merge plz

2024-12-11 16:12 UTC, codeuriii commented
@tryon-dev

2024-12-11 19:48 UTC, merged