Fix des titres en général
PapillonApp/papillon-v7 pull request #444
Opened 2024-12-13 18:40 UTC by Slysoks

# 🚀 Nouvelle Pull Request

## Checklist d'avant pull request
Veuillez cocher toutes les cases applicables en remplaçant [ ] par [x].

- [ ] Vous avez testé de build le projet avec vos modifications et ce build **a réussi**
- [X] Vous respectez les conventions de codage et de nommage du projet
- [X] Vous utilisez la **tabulation** pour l'indentation afin de maintenir un code lisible
- [X] Cette pull request **n'est pas un duplicata** d'une autre
- [X] Cette pull request est prête à être **revue** (review) et **fusionnée** (merge)
- [X] Il n'y a pas de **`TODO`** (aka des annotations pour du code manquant) dans vos modifications
- [X] Il n'y a pas **d'erreurs de langue** dans votre code (grammaire, vocabulaire, conjugaison, orthographe)
- [X] Les détails des changements ont été décrits ci-dessous
- [X] Cette pull-request n'est pas une **"breaking-change"** (des modifications qui vont entraîner la modification du fonctionnement de certaines fonctionnalités déjà existantes)

## Changelogs proposés
Décrivez les modifications que vous avez effectuées.

Modification des styles :
- Suppression du trimestre à côté de "Vie Scolaire" sur la page d'accueil (scoll-view du bas)
- Suppression du "le " uniquement lors de la glisse sur le graphique des notes
- Suppression des initiales dans les actualités
- Modification de l'emplacement du nom de l'auteur d'une actualité
- Changement de l'icône des nouvelles notes (sur les widgets de l'écran d'accueil, [voir sur Lucide](https://lucide.dev/icons/file-check))
- Rajout du bouton "Soutenir Papillon" (Android uniquement)
- 

## Informations supplémentaires
Ajoutez ici toute information supplémentaire si nécessaire.

Non testé sur iOS (g pas d'iPhone / MAC)

2024-12-13 19:28 UTC, ecnivtwelve requested changes
Hormis les initiales, ça me semble bon pour moi

2024-12-13 19:28 UTC, ecnivtwelve commented on src/views/account/News/Atoms/Item.tsx
> -      }
Pourquoi supprimer les initiales ici ?

2024-12-13 19:28 UTC, ecnivtwelve commented on src/views/account/News/Document.tsx
> -          />
Même question

2024-12-13 19:52 UTC, Slysoks commented on src/views/account/News/Atoms/Item.tsx
> -      }
Je trouve que ça n'apporte pas grand chose, par contre je comptais dans une future PR mettre un bandeau vertical à gauche des actus avec la couleur, comme sur les cours :
![Screenshot_20241213_205149_Papillon](https://github.com/user-attachments/assets/b3cf9533-cff9-47d6-b438-c41ab21c06b8)

2024-12-13 19:52 UTC, Slysoks commented on src/views/account/News/Document.tsx
> -          />
Idem

2024-12-13 20:15 UTC, ecnivtwelve commented on src/views/account/News/Atoms/Item.tsx
> -      }
Pour le moment il vaut peut être mieux les garder ?

2024-12-13 21:28 UTC, Slysoks commented on src/views/account/News/Atoms/Item.tsx
> -      }
fix

2024-12-13 21:28 UTC, Slysoks commented on src/views/account/News/Document.tsx
> -          />
fix

2024-12-14 22:57 UTC, Kgeek33 approved these changes
J'trouve qu'il manque qqch sans les initiales sur les actualités mais le code et la pr fonctionne
LGTM 👍

2024-12-17 18:35 UTC, godetremy approved these changes

2024-12-22 09:53 UTC, Slysoks commented
@ecnivtwelve

2024-12-23 14:03 UTC, tryon-dev approved these changes

2024-12-25 19:15 UTC, merged