chore: update folder `.gitHub`
PapillonApp/papillon-v7 pull request #449
Opened 2024-12-13 22:19 UTC by Kgeek33

# ✨ Nouvelle Pull Request

Merci de contribuer à l'amélioration de Papillon !

Tu te poses des questions sur les pull requests (PR) ? Une documentation a spécialement été crée ici => https://gitbook.getpapillon.xyz/organisation/outils-internes/github

## Avant toute chose...

Pour nous aider à tester ta PR, merci de cocher une des cases suivantes (_en rajoutant un `x` dans les crochets_) :

Type de pull request :

- [ ] **Breaking change** (_des modifications avec un impact sur les fonctionnalités actuelles_)
- [ ] **Feat** (_ajoute une amélioration/nouveauté_)
- [ ] **Fix** (_permet de corriger un bug_)
- [x] **Chore** (_des modifications en dehors du dossier `src`_)
- [ ] **Styles** (_change/ajoute du style_)

## Résumé des changements effectués

> [!NOTE]
> 
> Cette PR est presque terminé, je finis les updates des workflows (_et d'intégrer les fonctionnalités demandées_)

- Fix des extentions `.yaml` => `.yml` pour le bon fonctionnement de GitHub
- Refonte du fichier `PULL_REQUEST_TEMPLATE.md` pour plus de simplicité lors de la création d'une PR
- Mise à jour du pré remplissage des issues pour plus de simplification et Papillon vers la dernière version
- Le workflow `checks.yml` a été mis à jour afin de prévenir directement les erreurs sur la conversation de la PR ! (_et utilisation de `npm` plutôt que `pnpm`_)

## Capture(s) d'écran (pour rendre le test de ta PR rapide)

_il y a pas besoin_

## Issue(s) en rapport

> [!NOTE]
>
> Cette section permet de "linker" des issues à ta PR. Cela signifie qu'une fois ta PR mergée, les issues listées ci-dessous seront automatiquement fermées

- Closed #105 

_S'il y en a plusieurs, continuer à les lister_

- Closed #177 
- Closed #225 
- Closed #382

2024-12-13 23:06 UTC, Kgeek33 commented
@ecnivtwelve tu peux autoriser l'écriture des actions dans le repo pour que mon workflow fonctionne ?
c'est pour qu'il poste un message lorsqu'il y a une erreur TypeScript/ESLint

2024-12-16 18:31 UTC, Gabriel29306 requested changes

2024-12-16 18:31 UTC, Gabriel29306 commented on .github/workflows/start_build.yml
> -        run: npm ci
`npm ci` va suivre les versions utilisées dans le `package-lock.json`.
Tandis que `npm install` ne va que regarder les packages et installer les plus récents, avec leurs possibles changements.

2024-12-16 18:31 UTC, Gabriel29306 commented on .github/workflows/start_build.yml
> +      - name: 🚀 Build APKs for specific ABIs
Et expo ?
`npx expo prebuild` ?

2024-12-16 18:31 UTC, Gabriel29306 commented on android/app/build.gradle
> +    }
Pas de risque que expo fasse disparaitre tout ça ?

2024-12-16 18:40 UTC, Kgeek33 commented on .github/workflows/start_build.yml
> -        run: npm ci
ok je viens de changer ça

2024-12-16 18:43 UTC, Gabriel29306 commented
Si tu veux, tu peux prendre des bouts d'action (c'est pas fait pour être utilisé sur le repon officiel):
https://github.com/Gabriel29306/PapillonV7/blob/main/.github%2Fworkflows%2Fbuild.yml

2024-12-16 18:58 UTC, Kgeek33 commented on .github/workflows/start_build.yml
> +      - name: 🚀 Build APKs for specific ABIs
ok c'est bon également

2024-12-16 18:59 UTC, Kgeek33 commented on android/app/build.gradle
> +    }
comme on a pas ajouter l'argument `-c` dans le prebuild, non ça ne supprimera pas cette section
ça changera juste la version et versionCode

2024-12-16 19:00 UTC, Kgeek33 commented
> Si tu veux, tu peux prendre des bouts d'action (c'est pas fait pour être utilisé sur le repon officiel): https://github.com/Gabriel29306/PapillonV7/blob/main/.github%2Fworkflows%2Fbuild.yml

dis-moi ce que t'en penses de mes 2 derniers commits

2024-12-16 19:02 UTC, Kgeek33 commented
et tu pourras demander à changer les droits des github actions pour que mon workflow marche @Gabriel29306 stp ?
ça envoie un message directement dans la conversation pour prévenir des erreurs typescript/eslint !

2024-12-17 22:43 UTC, JyhuKo commented
je pense tu devrais rename la PR avec un Titre plus alléchant

2024-12-17 23:10 UTC, Kgeek33 commented
> je pense tu devrais rename la PR avec un Titre plus alléchant

Ok je fais ça mdr

2024-12-17 23:12 UTC, Kgeek33 commented
C'est bon !

2024-12-25 19:17 UTC, ecnivtwelve commented
toujours draft ou reviewable ?

2024-12-25 19:20 UTC, Kgeek33 commented
> toujours draft ou reviewable ?

De base je voulais faire un workflow qui fait un qr code pour tester les pr plutôt que de faire des git clone mais comme expo 52 est problématique, je vais mettre l'idée de côté 

Donc oui, elle peut être review, je change ça

2024-12-25 19:40 UTC, Kgeek33 commented
- Faut juste changer les autorisations du repo (sur le Github Actions) pour que le workflow `checks.yml` fonctionne
- Et également changer les autorisations du Play Store pour que la publication d'une nouvelle version bêta fonctionne

2024-12-25 19:41 UTC, Clmnnt commented
euh attends comment ça publication d’une bêta quand ?

2024-12-25 19:42 UTC, Clmnnt commented
au merge de la PR ?

2024-12-25 19:44 UTC, Kgeek33 commented
Non en fait, à chaque fois qu'on exécute le workflow `start_build.yml`, ça rencontre toujours une erreur lors de la publication d'une release bêta sur le play store :

![Screenshot_2024-12-25-20-43-06-038_com.github.android.jpg](https://github.com/user-attachments/assets/0b1777c9-cfb0-422e-9f3d-3cb158c56673)

2024-12-25 19:46 UTC, Clmnnt commented
il s’exécute à chaque commit ?

2024-12-25 19:48 UTC, Kgeek33 commented
> il s’exécute à chaque commit ?

Non ça j'ai pas changé, il s'exécute manuellement

2024-12-25 19:48 UTC, Clmnnt commented
manuellement ? cad ?

2024-12-25 19:48 UTC, Clmnnt commented
tout le monde peut l’exécuter ?

2024-12-25 19:51 UTC, Kgeek33 commented
Tout ceux qui ont les droits d'écritures sur ce repo peuvent l'exécuter (donc que l'équipe Papillon)

2024-12-26 00:51 UTC, Gabriel29306 approved these changes

2024-12-27 11:39 UTC, Kgeek33 commented
ça serait cool qu'on mette les droits d'écritures au Github actions pour que mon workflow fonctionne svp

2024-12-29 16:20 UTC, Kgeek33 commented
@ecnivtwelve @yannouuuu vous pouvez review svp ? 
pour un fonctionnement optimal des workflows, il faut faire ces adaptations suivantes => https://github.com/PapillonApp/Papillon/pull/449#issuecomment-2561985010

2024-12-30 17:49 UTC, ecnivtwelve commented
je sais pas vraiment comment tout ça fonctionne, je laisse ça aux autres

2024-12-30 17:57 UTC, Kgeek33 commented
ok d'accord, est-il juste possible alors de donner les permissions d'écritures à Github Actions dans les paramètres du repo ? (_pour que les workflows fonctionnent_)

2025-01-04 17:38 UTC, ecnivtwelve commented
@godetremy ?

2025-01-06 20:56 UTC, Bulgus approved these changes

2025-01-07 23:10 UTC, Bulgus approved these changes

2025-01-18 20:35 UTC, Gabriel29306 approved these changes

2025-01-19 18:41 UTC, Bulgus commented
Peut être pas la bonne PR, mais y'a des doublons # Expo dans le gitignore, si ça peut être clean au passage ^^

2025-01-19 19:02 UTC, Kgeek33 commented
ok je vais en profiter pour fix ça ^^

2025-01-20 16:25 UTC, JyhuKo approved these changes

2025-02-01 20:47 UTC, Gabriel29306 commented
Up

2025-02-08 21:10 UTC, godetremy submitted a review, later dismissed

2025-02-08 22:06 UTC, Kgeek33 commented
@camarm-dev t'en penses quoi de mon workflow pour vérifier le lint ?? 
il faudrait juste donner les autorisations à github-actions (écriture + possibilité de review) pour que ça fonctionne correctement

2025-02-08 23:28 UTC, camarm-dev commented
> @camarm-dev t'en penses quoi de mon workflow pour vérifier le lint ?? @godetremy il faudrait juste donner les autorisations à github-actions (écriture + possibilité de review) pour que ça fonctionne correctement => [ici](https://github.com/PapillonApp/Papillon/settings/actions), section "Workflow permissions"

J'ai lu un peu en Z là parceque je vais aller dormir, mais ça m'a l'air intéressant. Après je sais pas si ça apporte vraiment quelque-chose :
- Github Action qui envoie un request-changes juste avec la sortie tsc/eslint je vois pas trop l'interet
- Github Action qui aprouve la PR quand le check passe; je trouve que c'est pas forcément utile non-plus. Github intègre très bien ce fonctionnement et bloque le merge quand les checks passent pas, et c'est affiché en assez gros en plus...

Déjà que je trouve difficile de s'y retrouver dans la conversation de la PR entre les commits, les commentaires, les review ect... Si on rajoute une review + 1 commit + 1 request change à chaque push ça va faire trop...

Je trouve que c'est vraiment génial comme niveau d'automatisation t'as fait du bon boulot mais je vois pas trop l'utilité dans le cadre de Papillon malheureusement, je suis désolé... Après c'est que mon avis... 😄

2025-02-08 23:46 UTC, camarm-dev requested changes

2025-02-08 23:46 UTC, camarm-dev commented on .github/PULL_REQUEST_TEMPLATE.md
> +> Cette section permet de "linker" des issues à ta PR. Cela signifie qu'une fois ta PR mergée, les issues listées ci-dessous seront automatiquement fermées
```suggestion
> Cette section te permet de référencer des issues en lien avec ta PR. Pour que les issues soient fermées automatiquement au merge, utilise les "[closing keywords](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests)" de Github (exemples ci-dessous).
```
C'est peut être plus précis et français comme ça.

2025-02-08 23:46 UTC, camarm-dev commented on .github/PULL_REQUEST_TEMPLATE.md
> +- [ ] **Chore** (_des modifications en dehors du dossier `src`_)
Je trouve ça dommage d'avoir enlever cette section. Même si la liste est longue, elle permet de se poser les bonne questions avant d'ouvrir la PR.

De plus, pour savoir si une PR est à propos d'une fonctionnalité, d'un fix, du style ou d'autre chose, faire ce genre de liste n'est pas approprié:
- Le sujet de la doit être PR décrit plus haut (pas besoin de redemander au contributeur le type de changement donc). En plus, le type de PR ne change la manière dont elle est traitée, donc c'est une information peu essentielle.
- Les cases à cocher sont interprétées comme des tâches par Github (et c'est bel et bien ce qu'un case à cocher représente). Sauf qu'ici ta liste ne permet en aucun cas de vérifier l'avancement de la PR

Moi j'aurai laissé la liste d'avant: c'est vraiment la TODO liste à avoir pour chaque PR, pour guider le contributeur.

2025-02-08 23:57 UTC, Kgeek33 commented
> > @camarm-dev t'en penses quoi de mon workflow pour vérifier le lint ?? @godetremy il faudrait juste donner les autorisations à github-actions (écriture + possibilité de review) pour que ça fonctionne correctement => [ici](https://github.com/PapillonApp/Papillon/settings/actions), section "Workflow permissions"
> 
> J'ai lu un peu en Z là parceque je vais aller dormir, mais ça m'a l'air intéressant. Après je sais pas si ça apporte vraiment quelque-chose :
> - Github Action qui envoie un request-changes juste avec la sortie tsc/eslint je vois pas trop l'interet
> - Github Action qui aprouve la PR quand le check passe; je trouve que c'est pas forcément utile non-plus. Github intègre très bien ce fonctionnement et bloque le merge quand les checks passent pas, et c'est affiché en assez gros en plus...
> 
> Déjà que je trouve difficile de s'y retrouver dans la conversation de la PR entre les commits, les commentaires, les review ect... Si on rajoute une review + 1 commit + 1 request change à chaque push ça va faire trop...
> 
> Je trouve que c'est vraiment génial comme niveau d'automatisation t'as fait du bon boulot mais je vois pas trop l'utilité dans le cadre de Papillon malheureusement, je suis désolé... Après c'est que mon avis... 😄 

C'est vrai que j'avais pas cette vision des choses et dis comme ça, c'est vrai que ça peut ne pas être efficace. Pour le check obligatoire jspas s'il est actif actuellement mais c'est vrai que j'avais vu cette option
J'vais changer pour juste lancer le lint npm (mdrr j'ai repris un workflow que j'ai fait sur un repo pour ma nsi et je l'ai adapté pour que ça check en Typescript et non python 😄)

2025-02-08 23:57 UTC, Kgeek33 commented on .github/PULL_REQUEST_TEMPLATE.md
> +> Cette section permet de "linker" des issues à ta PR. Cela signifie qu'une fois ta PR mergée, les issues listées ci-dessous seront automatiquement fermées
J'étais pas trop inspiré pour l'explication 😂😂
Mais pas mal ce que tu proposes

2025-02-09 00:09 UTC, Kgeek33 commented on .github/PULL_REQUEST_TEMPLATE.md
> +- [ ] **Chore** (_des modifications en dehors du dossier `src`_)
J'lavais enlevé pask bcp avait signalé ne pas avoir la capacité de build et tout ça et certaines tâches pouvaient être simplifié...
Par rapport au type de pr, bcp n'ont pas le réflexe de le préciser sur le titre mais après, il est vrai que certains ne complète tout simplement pas la description de la pr

Enfin bref merci de la suggestion, je vais adapter ça pour avoir la todo list d'avant, tout en étant simplifié :)

2025-02-09 00:34 UTC, Kgeek33 commented
@camarm-dev c'est bon, j'ai appliqué tes suggestions !
Je t'ai même fait une dédicace dans le fichier `PULL_REQUEST_TEMPLATE.md`

2025-02-09 08:03 UTC, camarm-dev approved these changes
L'avant dernière tâche est 👌🏻.

Sinon le workflow t'as enlevé ce que je trouvais superflux donc c'est parfait pour moi 👍🏻

Et après pour la preview il faudrait passer sur Expo 52, tu sais si c'est prévu ou pas ?

2025-02-09 10:48 UTC, Kgeek33 commented
> L'avant dernière tâche est 👌🏻.
> 
> Sinon le workflow t'as enlevé ce que je trouvais superflux donc c'est parfait pour moi 👍🏻
> 
> Et après pour la preview il faudrait passer sur Expo 52, tu sais si c'est prévu ou pas ?

Parfait alors, merci !
J'avais tenté une pr pour rendre compatible Papillon avec Expo 52 mais : https://github.com/PapillonApp/Papillon/pull/701#issuecomment-2628426056
Mais j'ai vu Vince qui a créé une branche `rewrite/52` donc à voir

Mais. c'est _peut-être_ faisable une preview qui utilise Expo 51 cependant, il faudrait que Expo Go sur notre tél soit sur la dernière version qui supporte Expo 51 et éviter qu'il soit mis à jour automatiquement par les stores
Perso c'est mon cas, mais jspas si c'est possible sur ios

2025-02-09 11:15 UTC, TinAD17tin commented
D’ici là yaura Expo 53

2025-02-09 11:17 UTC, TinAD17tin commented
> > L'avant dernière tâche est 👌🏻.
> > Sinon le workflow t'as enlevé ce que je trouvais superflux donc c'est parfait pour moi 👍🏻
> > Et après pour la preview il faudrait passer sur Expo 52, tu sais si c'est prévu ou pas ?
> 
> Parfait alors, merci ! J'avais tenté une pr pour rendre compatible Papillon avec Expo 52 mais : [#701 (comment)](https://github.com/PapillonApp/Papillon/pull/701#issuecomment-2628426056) Mais j'ai vu Vince qui a créé une branche `rewrite/52` donc à voir
> 
> j'suis sur Expo Go 2.31.2 (supportant Expo 51) avec désactivation mise à jour automatique mais jspas si c'est possible sur ios
Impossible de downgrade sur iOS à part de sideload un .ipa.
Par contre bloquer les MAJs automatiques oui ça c’est possible (c’est mon cas, je fais les MAJs que quand ça bug)

2025-02-09 11:19 UTC, Bulgus commented on .github/ISSUE_TEMPLATE/bug.yml
> +description: Signaler des bugs nous permet à améliorer Papillon !
nous permet **d**'améliorer ;)

2025-02-09 11:21 UTC, Bulgus commented on .github/ISSUE_TEMPLATE/bug.yml
> +      description: Plus de détails nous permettent de trouver plus vite le bug !
simple question de goût, mais je trouve la formulation étrange
que penses-tu de 
_Plus de détails nous permet de trouver plus vite le bug !_
Ou différemment : 
_Plus il y a de détail plus nous pourrons vite trouver le bug !_

2025-02-09 11:23 UTC, Bulgus commented on .github/ISSUE_TEMPLATE/bug.yml
> +      description: Ce que Papillon doit faire
_devrait_ (conditionnel, si tout fonctionnait, Papillon devrait...)

2025-02-09 11:24 UTC, Bulgus commented on .github/ISSUE_TEMPLATE/bug.yml
> +      description: Cela permettra que le bug soit trouvé et résolu encore plus vite
Encore une question de gout
`Cela permettra une résolution encore plus rapide du bug`

2025-02-09 11:25 UTC, Bulgus commented on .github/ISSUE_TEMPLATE/feature.yml
> +      description: Fait place à ta créativité en détaillant ce que tu veux
_Fais_ (impératif seconde personne singulier)

2025-02-09 11:30 UTC, Bulgus commented on .github/PULL_REQUEST_TEMPLATE.md
> +Tu te poses des questions sur les pull requests (PR) ? Une documentation a spécialement été crée ici => https://gitbook.getpapillon.xyz/organisation/outils-internes/github
_créée_ (la documentation)

2025-02-09 11:31 UTC, Kgeek33 commented
je tente un workflow qui génère un qr code mais ça m'étonnerait qu'il fonctionne
ah ben voilà mdrr

2025-02-09 11:33 UTC, Kgeek33 commented on .github/ISSUE_TEMPLATE/bug.yml
> +      description: Plus de détails nous permettent de trouver plus vite le bug !
J'aime bien la 2ème !

2025-02-09 11:33 UTC, Bulgus commented
Hello :)
Désolé pour tous ces commentaires chiant 😅
Sinon mis à part ça, LGTM ^^

2025-02-09 11:35 UTC, Kgeek33 commented on .github/ISSUE_TEMPLATE/feature.yml
> +      description: Fait place à ta créativité en détaillant ce que tu veux
Oh les mauvais souvenirs des cours de français 😂

2025-02-09 11:38 UTC, Kgeek33 commented
> Impossible de downgrade sur iOS à part de sideload un .ipa.
> Par contre bloquer les MAJs automatiques oui ça c’est possible (c’est mon cas, je fais les MAJs que quand ça bug)

ok je vais voir

2025-02-09 11:39 UTC, Kgeek33 commented
> Hello :) Désolé pour tous ces commentaires chiant 😅 Sinon mis à part ça, LGTM ^^

Salut, tkt pas, j'viens de tout corriger ^^

2025-02-09 11:41 UTC, Bulgus commented on .github/ISSUE_TEMPLATE/bug.yml
> +      description: Plus de détails nous permettent de trouver plus vite le bug !
Allez je suis chiant ;)
j'ai mal tapé, je trouve que ça sonne mieux comme ça
Et détail**s** 😭
`Plus il y a de détails plus vite nous pourrons trouver le bug !`

2025-02-09 11:42 UTC, Bulgus commented
> > Hello :) Désolé pour tous ces commentaires chiant 😅 Sinon mis à part ça, LGTM ^^
> 
> Salut, tkt pas, j'viens de tout corriger ^^

Super ^^

2025-02-09 11:48 UTC, Bulgus commented
Tu sais pourquoi mon email est exposé sur ton commit en co autored 😭  ?

2025-02-09 11:54 UTC, Kgeek33 commented
> Tu sais pourquoi mon email est exposé sur ton commit en co autored 😭 ?

j'ai cherché depuis VSCode et ça m'en a proposé 2 et je savais pas lequel choisir ☠️

2025-02-09 11:55 UTC, Bulgus commented
> j'ai cherché depuis VSCode et ça m'en a proposé 2 et je savais pas lequel choisir ☠️
Ah okay ^^

Pas grave, mais ça doit être parce que pendant une période je l'avais configuré avec cet email, et ton VS code doit l'avoir en mémoire...

2025-02-09 12:52 UTC, Bulgus commented
> Allez je suis chiant ;) j'ai mal tapé, je trouve que ça sonne mieux comme ça Et détail**s** 😭 `Plus il y a de détails plus vite nous pourrons trouver le bug !`

Plus que ça, et je serais bon pour approuve :)

2025-02-09 13:24 UTC, Kgeek33 commented on .github/ISSUE_TEMPLATE/bug.yml
> +      description: Plus de détails nous permettent de trouver plus vite le bug !
tkt :)

2025-02-09 13:26 UTC, Kgeek33 commented
> > Allez je suis chiant ;) j'ai mal tapé, je trouve que ça sonne mieux comme ça Et détail**s** 😭 `Plus il y a de détails plus vite nous pourrons trouver le bug !`
> 
> Plus que ça, et je serais bon pour approuve :)

c'est bon pour moi, et je me suis pas fait avoir pour le co author mdrr

2025-02-09 13:28 UTC, Kgeek33 commented
et le workflow pour qr code, c'est faisable mais par contre faut que Expo Go soit en version 2.31 et tout ça, on verra ça plus tard

2025-02-09 13:40 UTC, Bulgus commented
> c'est bon pour moi, et je me suis pas fait avoir pour le co author mdrr

okayy super ;)

2025-02-09 13:40 UTC, Bulgus approved these changes
LGTM !

2025-02-09 22:37 UTC, camarm-dev commented on .github/workflows/checks.yml
>            fi
À voir si l'équipe trouve que c'est utile de commit les fix automatiques du linter... Moi j'aime bien l'idée; ça permet de faire passer le typecheck même si on a des petites erreurs de tabulations ect...

2025-02-09 22:38 UTC, camarm-dev approved these changes
LGTM

2025-02-09 23:00 UTC, Kgeek33 commented on .github/workflows/checks.yml
>            fi
oui voilà sachant que ça peut être des erreurs toute bête, ça fix automatiquement et tout le monde est content ^^

2025-03-07 20:01 UTC, raphckrman approved these changes
LGTM, des news sur cette PR du côté des mainteneurs ? Ça fait un moment qu'elle est ouverte

2025-03-13 10:10 UTC, ecnivtwelve approved these changes

2025-03-13 10:10 UTC, merged