feature: garder le bouton des devoirs non faits visible
PapillonApp/papillon-v7 pull request #452
Opened 2024-12-14 09:47 UTC by codeuriii

# 🚀 Nouvelle Pull Request

Proposez vos modifications pour améliorer Papillon

## Informations importantes

Merci de vous référer à la documentation sur la contribution si vous avez des questions à propos des pull requests (https://gitbook.getpapillon.xyz/organisation/outils-internes/github)

## Checklist d'avant pull request

Veuillez cocher toutes les cases applicables en remplaçant [ ] par [x].

- [x] Vous avez testé de build le projet avec vos modifications et ce build **a réussi**
- [x] Vous respectez les conventions de codage et de nommage du projet
- [x] Vous utilisez la **tabulation** pour l'indentation afin de maintenir un code lisible
- [x] Cette pull request **n'est pas un duplicata** d'une autre
- [x] Cette pull request est prête à être **revue** (review) et **fusionnée** (merge)
- [x] Il n'y a pas de **`TODO`** (aka des annotations pour du code manquant) dans vos modifications
- [x] Il n'y a pas **d'erreurs de langue** dans votre code (grammaire, vocabulaire, conjugaison, orthographe)
- [x] Les détails des changements ont été décrits ci-dessous
- [x] Cette pull-request n'est pas une **"breaking-change"** (des modifications qui vont entraîner la modification du fonctionnement de certaines fonctionnalités déjà existantes)

## Changelogs proposés

- Ajout d'une page de paramètre qui permet de choisir si on a envie de laisser le bouton checked square actif et/ou visible.

## Informations supplémentaires

J'ai besoin d'aide pour les textes style le nom de la page dans les paramètres.

2024-12-14 13:53 UTC, Bulgus commented
Je trouve que c'est une bonne idée dans l'immédiat, mais (selon moi) : 
- Il y a un double affichage de l'état du settings (le bouton que tu as ajouté et le cercle en pointillé déjà présent). Il vaudrait mieux supprimer le cercle je pense.
![Capture d’écran 2024-12-14 à 14 40 19](https://github.com/user-attachments/assets/7455dc25-e10d-4adb-93bb-fcac827075eb)

- Il y a un lag lors du clic sur le bouton de check, qui n'est pas présent lors du toggle en maintenant appuyé le numéro de semaine.

https://github.com/user-attachments/assets/407c38a7-672f-4c9c-8fe5-500e0e865345

- Les deux settings rajoutés on leur place dans l'onglet "Onglets & Navigation" pour moi

---------------------------------------------------------------------------------------------

(Questions de goûts)
Proposition de description du setting "Devoirs non-faits" : "Activer l'affichage par défaut des devoirs non-faits uniquement"
(_Actuel : "Activer par défaut le fait d'afficher uniquement les devoirs non-faits"_)

Proposition de description du setting "Garder visible" : "Garder visible l'icône de bascule tous les devoirs / devoirs non-faits"
(_Actuel : "Garder visible dans la barre du haut a côté du champ de recherche"_)

---------------------------------------------------------------------------------------------

Edit : pense à mettre des screen dans la PR, c'est bien plus pratique pour review

2024-12-14 17:13 UTC, codeuriii commented
Ok je vais travailler dessus un grand merci

2024-12-14 17:28 UTC, codeuriii commented
je viens de vérifier et le lag ne provient pas de moi, il est présent dans papillon normal. Je crains que je ne puisse faire grand chose

2024-12-14 17:39 UTC, codeuriii commented
je pense que c'est mieux de laisser une page faite pour dans les settings

2024-12-14 17:40 UTC, codeuriii commented
dans le futur pourquoi pas rajouter d'autres choses pour personaliser telle que le rangement des devoirs faits en bas, ou le classement des devoirs en fonctions de l'emploie du temps

2024-12-14 17:41 UTC, codeuriii commented
bon je viens de voir que c'est déja implémenté mais tkt

2024-12-14 17:42 UTC, codeuriii commented
![image](https://github.com/user-attachments/assets/cb010aca-b003-44d4-88fc-edafad7906b4)

2024-12-14 17:42 UTC, codeuriii commented
![image](https://github.com/user-attachments/assets/2540d509-f027-4099-a798-590647e841de)

2024-12-14 17:42 UTC, codeuriii commented
![image](https://github.com/user-attachments/assets/c2501f3b-a9b2-47d5-9864-da12e55170dd)
![image](https://github.com/user-attachments/assets/a907842e-2e05-4e64-8e43-b55949e7f42a)

2024-12-14 19:08 UTC, Bulgus commented
> je viens de vérifier et le lag ne provient pas de moi, il est présent dans papillon normal. Je crains que je ne puisse faire grand chose

Mais pourquoi il n'y a aucun lag lorsque le toggle est effectué en maintenant la semaine ? Dans tous les cas il faut patch ça, peut importe d'où ça vient...

> dans le futur pourquoi pas rajouter d'autres choses pour personaliser telle que le rangement des devoirs faits en bas, ou le classement des devoirs en fonctions de l'emploie du temps

J'aime bien l'idée du tri fait / non fait comme setting, je pense que la page de ces settings peut s'appeler "Devoirs" tout simplement

> bon je viens de voir que c'est déja implémenté mais tkt

De quoi ?

> ![image](https://private-user-images.githubusercontent.com/113228775/395808209-c2501f3b-a9b2-47d5-9864-da12e55170dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQyMDMzMDIsIm5iZiI6MTczNDIwMzAwMiwicGF0aCI6Ii8xMTMyMjg3NzUvMzk1ODA4MjA5LWMyNTAxZjNiLWE5YjItNDdkNS05ODY0LWRhMTJlNTUxNzBkZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxNFQxOTAzMjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jY2ExMjM2ODlhOWY3Y2JmNTZkYjI5YWVkZmU0ZjYyMjJhZGVmMDE4ZWI4YjQ5YjFmOWU1NGI1ZGJlZTJhNWM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.-1_RcSYTl44fSI55Yc0JBisYGXUJBI0CY6jZk60msck) ![image](https://private-user-images.githubusercontent.com/113228775/395808226-a907842e-2e05-4e64-8e43-b55949e7f42a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQyMDMzMDIsIm5iZiI6MTczNDIwMzAwMiwicGF0aCI6Ii8xMTMyMjg3NzUvMzk1ODA4MjI2LWE5MDc4NDJlLTJlMDUtNGU2NC04ZTQzLWI1NTk0OWU3ZjQyYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxNFQxOTAzMjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NGEzYmVhNmZhM2M5OGI1Y2U2MDFmMTY4NzdlMzgyMjBkMzUzMmQ2ZDA2ZjZlZTdiMTg0YTU2NzlmMTBiMjJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.w8gCME5wbBLKxHXWQiQ6YChb015EYnLOHAPjYG7ICP0)

Nice parfait ! C'est plus clair que le rond d'avant en plus

2024-12-14 22:51 UTC, Kgeek33 requested changes
Voilà ma review
Les fonctionnalités (_en général_) ajoutées sur Papillon sont très intéressantes, mais faudrait les mettre à l'avant sur la page d'accueil pour que l'utilisateur consulte au moins les nouveautés

Par exemple, les requêtes en arrière-plan, c'est bien la dernière chose que j'ai consulté sur la nouvelle version car on n'est pas au courant (7.6.0)

2024-12-14 22:51 UTC, Kgeek33 commented on src/views/settings/SettingsCheck.tsx
> +            Garder visible l'icône de bascule tous les devoirs / devoirs non-faits
Il faudrait changer l'explication car quand j'ai vu cette explication, j'ai cru d'abord que ça cachait les coches des devoirs quand les devoirs sont faits

2024-12-14 22:51 UTC, Kgeek33 commented on src/views/account/Homeworks/Homeworks.tsx
Ligne 582 : sur le `TouchableOpacity`, il serait intéressant d'ajouter un `onLongPress` qui redirige sur la page des paramètres que t'as crée pour changer des options

2024-12-15 09:31 UTC, Bulgus commented on src/views/settings/SettingsCheck.tsx
> +            Garder visible l'icône de bascule tous les devoirs / devoirs non-faits
Pas faux
Comme ça c'est mieux ?
_Garder visible l'icône de tri des devoirs non-faits_

2024-12-15 09:44 UTC, codeuriii commented
![image](https://github.com/user-attachments/assets/5755a09c-91aa-4d55-8eb5-7c6ba6bd67de)

2024-12-15 09:44 UTC, codeuriii commented
le fait de ranger les devoirs a déja été implémenté

2024-12-15 10:02 UTC, Bulgus commented
Bon, j'ai changé d'avis. Je viens de test avec les dernier commit @codeuriii, et c'est très bien lorsque l'icône est gardée affiché par défaut, mais lorsque qu'elle est masquée : 
- Il y a un doublon avec le cercle des semaines encore une fois
- Et son accès n'est pas intuitif

Donc je suggère tout simplement de **laisser tout le temps le bouton affiché**, complètement supprimer le cercle, et ne laisser qu'un seul setting, celui de l'activation par défaut du tri.
Je trouve que l'interface avec le bouton "check" est très bien quand il est affiché.

Tu me dis ce que tu en penses, mais à mon avis d'un point de vu expérience utilisateur, le plus simple c'est ça !

2024-12-15 10:07 UTC, Kgeek33 commented
> Donc je suggère tout simplement de laisser tout le temps le bouton affiché, complètement supprimer le cercle, et ne laisser qu'un seul setting, celui de l'activation par défaut du tri.
Je trouve que l'interface avec le bouton "check" est très bien quand il est affiché.

Je vais tester tout à l'heure les derniers commits mais c'est vrai que je suis d'accord, c'est plus efficace avec le paramètre affiché par défaut. 

Et ça revient à mon commentaire précédent, il y a plein de fonctionnalités sur Papillon mais le problème, c'est que l'utilisateur doit fouiller pour découvrir ces fonctionnalités
En rapport avec la page des devoirs, si je connaissais pas cette fonctionnalité, j'aurai même pas eu l'idée de cliquer sur "Semaine [...]"

2024-12-15 10:10 UTC, Bulgus commented
> > Donc je suggère tout simplement de laisser tout le temps le bouton affiché, complètement supprimer le cercle, et ne laisser qu'un seul setting, celui de l'activation par défaut du tri.
> > Je trouve que l'interface avec le bouton "check" est très bien quand il est affiché.
> 
> Je vais tester tout à l'heure les derniers commits mais c'est vrai que je suis d'accord, c'est plus efficace avec le paramètre affiché par défaut.
> 
> Et ça revient à mon commentaire précédent, il y a plein de fonctionnalités sur Papillon mais le problème, c'est que l'utilisateur doit fouiller pour découvrir ces fonctionnalités En rapport avec la page des devoirs, si je connaissais pas cette fonctionnalité, j'aurai même pas eu l'idée de cliquer sur "Semaine [...]"

Oui voilà, la même, j'ai mis du temps à savoir que ça existait
donc pour moi le mieux c'est que ça soit là tout le temps, c'est intuitif comme icône on comprend !

2024-12-15 10:15 UTC, codeuriii commented
todo
Je vais laisser afficher le bouton par défaut genre cocher dans le menu vrai par défaut
ensuite je pense laisser le cercle dashed car il montre que c'est coché si c'est caché (de plus on le verra pas souvent car il sera caché par défaut)
fix le long press pour aller dans les parametres

2024-12-15 10:17 UTC, Kgeek33 commented
> Oui voilà, la même, j'ai mis du temps à savoir que ça existait

À travailler ça dans une pr, choisir à chaque fois qu'on va dans la page d'accueil, faire un random et afficher une fonctionnalité pas évidente à trouver
Par exemple : Titre : "Le savais-tu?" et Message : "En cliquant sur le graphique de l'évolution de ta moyenne générale, ça va afficher les moyennes générales minimales et maximales (théoriques)" (tu t'en souviens qu'on voulait supprimer cette fonctionnalité @Bulgus 😂)

> donc pour moi le mieux c'est que ça soit là tout le temps, c'est intuitif comme icône on comprend !

Oui je suis d'accord !

2024-12-15 10:27 UTC, codeuriii commented
todo
[x] Je vais laisser afficher le bouton par défaut genre cocher dans le menu vrai par défaut
[x} ensuite je pense laisser le cercle dashed car il montre que c'est coché si c'est caché (de plus on le verra pas souvent car il sera caché par défaut)
[ ] fix le long press pour aller dans les parametres

2024-12-15 10:28 UTC, Bulgus commented
> todo Je vais laisser afficher le bouton par défaut genre cocher dans le menu vrai par défaut ensuite je pense laisser le cercle dashed car il montre que c'est coché si c'est caché (de plus on le verra pas souvent car il sera caché par défaut)

En fait le truc c'est que je vois pas pourquoi quelqu'un voudrait cacher ce bouton de tri ? Et je pense que moins il y a de features / tweaks plus c'est simple et intuitif, donc je partirais sur complètement enlever cette possibilité perso...


> À travailler ça dans une pr, choisir à chaque fois qu'on va dans la page d'accueil, faire un random et afficher une fonctionnalité pas évidente à trouver Par exemple : Titre : "Le savais-tu?" et Message : "En cliquant sur le graphique de l'évolution de ta moyenne générale, ça va afficher les moyennes générales minimales et maximales (théoriques)" (tu t'en souviens qu'on voulait supprimer cette fonctionnalité @Bulgus 😂)

Ça peut être ça oui, mais ça prend de la place... ou alors, une visité guidée lors de nouvelles features... (chaud)
(Oui mdrr je m'en souviens bien et je vois toujours pas leur utilité 😂😭)

> todo

Édite ton précédent message ça sera plus simple et ça fera moins de messages !

2024-12-15 10:32 UTC, codeuriii commented
> En fait le truc c'est que je vois pas pourquoi quelqu'un voudrait cacher ce bouton de tri ? Et je pense que moins il y a de features / tweaks plus c'est simple et intuitif, donc je partirais sur complètement enlever cette possibilité perso...
si c'est la, je pense qu'il y a une raison, et puis c mieux de pouvoir tout custommiser, je trouve ca reste dans l'état desprit open source et linux etc. L'utilisateur lambda aura l'icone toujours affichée et ceux bidouilleurs ou les gens qui ont un petit telephone pourront cacher
> Édite ton précédent message ça sera plus simple et ça fera moins de messages !
j'ai fini de toute facon mdr

2024-12-15 10:34 UTC, Bulgus commented
> si c'est la, je pense qu'il y a une raison, et puis c mieux de pouvoir tout custommiser, je trouve ca reste dans l'état desprit open source et linux etc. L'utilisateur lambda aura l'icone toujours affichée et ceux bidouilleurs ou les gens qui ont un petit telephone pourront cacher

Oui okay, nan mais il faut juste que ça soit affiché par défaut et c'est le cas, donc ça me parait bon ! Je teste une dernière fois et je review

2024-12-15 10:36 UTC, Kgeek33 commented
> En fait le truc c'est que je vois pas pourquoi quelqu'un voudrait cacher ce bouton de tri ? Et je pense que moins il y a de features / tweaks plus c'est simple et intuitif, donc je partirais sur complètement enlever cette possibilité perso...

Même si je suis d'accord, créer une page de Paramètres juste pour 1 option, bof mdrrr (sauf si on peut relier avec l'issue #337)

> Ça peut être ça oui, mais ça prend de la place... ou alors, une visité guidée lors de nouvelles features... (chaud)
> (Oui mdrr je m'en souviens bien et je vois toujours pas leur utilité 😂😭)

Ça serait à la place des nouveautés de Papillon, dans le même genre
Ça sert tjrs à rien 😂

2024-12-15 10:42 UTC, Bulgus commented
> Même si je suis d'accord, créer une page de Paramètres juste pour 1 option, bof mdrrr (sauf si on peut relier avec l'issue #337)

Oui oui et puis ça casse rien, fin c'est là au pire du pire c'est useless

> Ça serait à la place des nouveautés de Papillon, dans le même genre 

Ah oui, pas bête...

> Ça sert tjrs à rien 😂

Nan 😂

2024-12-15 10:52 UTC, codeuriii commented
et voila tout est beau tout est propre pour la review

2024-12-15 10:53 UTC, Kgeek33 commented
j'vais y travailler dans une autre pr
d'abord, j'vais essayer de boucler ma pr sur les tablettes (comme ça, les gens pourront tester)

2024-12-15 10:53 UTC, Kgeek33 commented
> et voila tout est beau tout est propre pour la review

j'teste ça plus tard :)

2024-12-15 12:48 UTC, Kgeek33 commented on src/views/account/Homeworks/Homeworks.tsx
> +            onLongPress={() => navigation.navigate("SettingStack", {view: "SettingsCheck"})}
```suggestion
            onLongPress={() => navigation.navigate("SettingStack", {view: "SettingsCheck"})}
            delayLongPress={2000}
```

2024-12-15 12:49 UTC, Kgeek33 requested changes
Juste ça pour que `onLongPress` fonctionne et soit pas trop chiant et c'est parfait !

2024-12-15 12:58 UTC, Kgeek33 approved these changes
Parfait, LGTM 👍

2024-12-25 19:19 UTC, ecnivtwelve commented
je recall @toi-et-moi pour son avis niveau UX

2025-01-01 10:17 UTC, codeuriii commented
Je me permet de relancer poliment

2025-01-11 20:34 UTC, tryon-dev requested changes, later dismissed
Quel est le but de la PR ?, réexplique moi stp

2025-01-11 20:37 UTC, codeuriii commented
Cette pr rajoute une page dans les paramètres et permet de garder le bouton fais visible et/ou activé par défaut, comme sur l'application Pronote. De plus elle ne supprime rien et c'est possible de checker les deux paramètres pour désactiver la visibilité par défaut et l'activation par défaut. Pour finir, étant sur mobile je ne vois pas tes changements demandés et il est minuit quarantes chez moi donc j'aimerais bien que tu fasse un résumé rapide, merciiii

2025-01-11 20:58 UTC, godetremy commented
> [!NOTE]
> Cette review est le résultat de la concertation de toute l'équipe Papillon.

# Expérience utilisateur
L'idée semble intéressante, mais l'UX nous semblent trop complexe. (Nous même avons eu du mal à comprendre)

Le plus simple serait de garder le dernière état du check des devoirs. Pour ce qui est de la fonction de l'afficher constamment, nous ne trouvons pas ça intéressant.

# Interface utilisateur
## Disparition du texte "Recherche"
![Simulator Screenshot - iPhone 16 - 2025-01-11 at 21 42 35](https://github.com/user-attachments/assets/05c56c07-9d7a-4c63-942c-f524fef592a2)
Disparu dans l'univers

2025-01-12 07:53 UTC, codeuriii commented
Je sais mais si je le laisse il est coupé à la fin sur les plus petits appareils

2025-01-12 08:04 UTC, codeuriii commented
Todo:
- [ ] Remettre le texte rechercher (même si il se coupe)
- [ ] Stocker le dernier état du bouton
- [ ] Supprimer le paramètre d'activation par défaut sur la page
- [ ] Déplacer l'autre paramètre dans une autre page
- [ ] Supprimer la page créée

2025-01-17 18:00 UTC, codeuriii commented
J'ai fini j'ai hâte de ma review

2025-01-21 15:49 UTC, codeuriii commented
Je comprend pas le eslint, j'ai pas touché a ce code mais il y a une erreur dans src/views/account/Grades/Subjects/Subjects.tsx

2025-01-21 15:52 UTC, JyhuKo commented
je pense c'est pcq le lint du main est cassé

2025-01-21 15:53 UTC, codeuriii commented
quand je vais voir en local ca me dit que il peut pas importer jsp quoi

2025-02-08 21:41 UTC, godetremy commented
# Réunion hebdo du 08/02/2024
## Modifications à apporter
Il te reste quelque propriété à retirer des stores. Nous avions également dit que la pages des paramètre devrait disparaître pourtant, elle est encore dans les fichiers....

2025-03-13 11:02 UTC, ecnivtwelve commented
Sera surement réintégrée a l'avenir, close pour cleanup

2025-03-13 11:02 UTC, closed without merging