feat(home) : next week courses
PapillonApp/papillon-v7 pull request #459
Opened 2024-12-14 16:32 UTC by Bulgus

# 🚀 Nouvelle Pull Request

Proposez vos modifications pour améliorer Papillon

## Informations importantes

Merci de vous référer à la documentation sur la contribution si vous avez des questions à propos des pull requests (https://gitbook.getpapillon.xyz/organisation/outils-internes/github)

## Checklist d'avant pull request

Veuillez cocher toutes les cases applicables en remplaçant [ ] par [x].

- [X] Vous avez testé de build le projet avec vos modifications et ce build **a réussi**
- [X] Vous respectez les conventions de codage et de nommage du projet
- [X] Vous utilisez la **tabulation** pour l'indentation afin de maintenir un code lisible
- [X] Cette pull request **n'est pas un duplicata** d'une autre
- [X] Cette pull request est prête à être **revue** (review) et **fusionnée** (merge)
- [X] Il n'y a pas de **`TODO`** (aka des annotations pour du code manquant) dans vos modifications
- [X] Il n'y a pas **d'erreurs de langue** dans votre code (grammaire, vocabulaire, conjugaison, orthographe)
- [X] Les détails des changements ont été décrits ci-dessous
- [X] Cette pull-request n'est pas une **"breaking-change"** (des modifications qui vont entraîner la modification du fonctionnement de certaines fonctionnalités déjà existantes)

## Changelogs proposés

Add next week to the home timetable and add label when next course is on the next week

## Informations supplémentaires

![Capture d’écran 2024-12-14 à 17 31 51](https://github.com/user-attachments/assets/436f533a-b7aa-45eb-acf4-d12d808f2afd)

2024-12-14 21:23 UTC, Kgeek33 commented
Je vais tester ça mais si par exemple, une personne a cours le samedi, ça va fonctionner ? (on sait jamais mdrrr)

2024-12-14 21:37 UTC, Bulgus commented
> Je vais tester ça mais si par exemple, une personne a cours le samedi, ça va fonctionner ? (on sait jamais mdrrr)

Mdrrr ça arrive vraiment en plus
Oui, en gros ça ajoute juste la semaine suivante à la semaine actuelle, donc ça parcours tous les jours inclus dedans oui (c'est pas clair mais en gros oui ça fonctionne)

2024-12-14 21:42 UTC, Kgeek33 commented
> > Je vais tester ça mais si par exemple, une personne a cours le samedi, ça va fonctionner ? (on sait jamais mdrrr)
> 
> Mdrrr ça arrive vraiment en plus
> Oui, en gros ça ajoute juste la semaine suivante à la semaine actuelle, donc ça parcours tous les jours inclus dedans oui (c'est pas clair mais en gros oui ça fonctionne)

Ok, tkt j'ai compris mdrr

2024-12-14 22:33 UTC, Kgeek33 requested changes
Pour afficher l'emploi du temps réel de l'élève :

- Ligne 92 => peux-tu supprimer `.slice(0, 3);`

2024-12-14 22:34 UTC, Kgeek33 commented
comme c'est pas toi qui a fait la modif, j'peux pas suggérer le code

2024-12-15 09:29 UTC, Bulgus commented
> Pour afficher l'emploi du temps réel de l'élève :
> 
> * Ligne 92 => peux-tu supprimer `.slice(0, 3);`

Le truc c'est que ça fait vite chargé quand on a beaucoup de cours
Et je pense que l'idée du home c'est d'avoir des aperçus
je sais pas, je te laisse juger : 

https://github.com/user-attachments/assets/0fc2e74f-dacb-4e44-a305-c4447ddeec27

2024-12-15 10:02 UTC, Kgeek33 commented
Oui c'est ça le problème. Alors fais ça (att j'te review ce qu'il faut changer)

2024-12-15 10:04 UTC, Kgeek33 commented
Non e' fait, jspas comment le dire
En gros, faudrait préciser à l'utilisateur que ce sont les 3 prochains cours
J'pensais à par exemple : Cours de demain (3 prochains cours) mais je trouve pas ça esthétique

2024-12-15 10:06 UTC, Bulgus commented
> Non e' fait, jspas comment le dire En gros, faudrait préciser à l'utilisateur que ce sont les 3 prochains cours J'pensais à par exemple : Cours de demain (3 prochains cours) mais je trouve pas ça esthétique

Ah oui okay je vois ce que tu veux dire
Oui c'est pas beau avec (3 prochains cours)
Alors maybe transformer le "Voir plus" en "Voir tout" ?

(Par contre ça modifie tous les textes "Voir plus", mais ça me semble logique comme ça)

![Capture d’écran 2024-12-15 à 11 09 11](https://github.com/user-attachments/assets/b6a6ab21-ff66-4e54-b363-8553befd4ec8)

2024-12-15 10:12 UTC, Kgeek33 commented
> Alors maybe transformer le "Voir plus" en "Voir tout" ?

Non on peut pas, car le lundi par exemple, ça affiche en entier l'emploi du temps à ce jour
J'viens de penser à "Aperçu des cours de demain" (bof un peu)

Ou sinon, on ajoute un bouton qui dit "Afficher l'emploi du temps en entier" après avoir lister 3 matières

2024-12-15 10:25 UTC, Bulgus commented
> > Alors maybe transformer le "Voir plus" en "Voir tout" ?
> 
> Non on peut pas, car le lundi par exemple, ça affiche en entier l'emploi du temps à ce jour J'viens de penser à "Aperçu des cours de demain" (bof un peu)
> 
> Ou sinon, on ajoute un bouton qui dit "Afficher l'emploi du temps en entier" après avoir lister 3 matières

Ah oui mince
(oui c'est pas fou)

Heuuu oui why not un bouton c'est peut être le mieux mais ça prends de la place quoi
Je sais pas, pour l'instant laisser tel quel c'est peut être le plus simple, on va suivre le figma
Et "Prochains cours" ne veut pas dire "Tous les prochains cours en soit" moi ça me choque pas

2024-12-15 10:32 UTC, Kgeek33 commented
Oui ça prend de la place, problématique
Oui laissons comme c'est, très bien :)

2024-12-16 18:04 UTC, Kgeek33 approved these changes
ah oui, j'ai oublié 🤣

2024-12-25 15:47 UTC, Kgeek33 commented
tu peux link l'issue : #289

2024-12-25 19:16 UTC, ecnivtwelve approved these changes

2024-12-26 15:42 UTC, Bulgus commented
> tu peux link l'issue : #289

Ma PR ne répond pas au problème de l'issue si ?

2024-12-26 18:27 UTC, Kgeek33 commented
> > tu peux link l'issue : #289
> 
> Ma PR ne répond pas au problème de l'issue si ?

C'est ce que t'as fait sur la page d'accueil

2024-12-26 18:30 UTC, Kgeek33 commented
Et ça résout pas l'issue #469 ?

2024-12-26 18:30 UTC, Kgeek33 commented
Mince me suis trompé de pr... 😭🤣

2024-12-26 18:32 UTC, Kgeek33 commented
Sauf s'il faut l'intégrer sur la page de l'emploi du temps directement et là du coup, oui pas en rapport

2025-01-11 21:14 UTC, tryon-dev approved these changes

2025-01-11 21:16 UTC, merged