feat(texts) : Transformation from formal to informal and some syntactic modifications
PapillonApp/papillon-v7 pull request #460
Opened 2024-12-14 20:39 UTC by Bulgus

## Checklist d'avant pull request

Veuillez cocher toutes les cases applicables en remplaçant [ ] par [x].

- [X] Vous avez testé de build le projet avec vos modifications et ce build **a réussi**
- [X] Vous respectez les conventions de codage et de nommage du projet
- [X] Vous utilisez la **tabulation** pour l'indentation afin de maintenir un code lisible
- [X] Cette pull request **n'est pas un duplicata** d'une autre
- [X] Cette pull request est prête à être **revue** (review) et **fusionnée** (merge)
- [X] Il n'y a pas de **`TODO`** (aka des annotations pour du code manquant) dans vos modifications
- [X] Il n'y a pas **d'erreurs de langue** dans votre code (grammaire, vocabulaire, conjugaison, orthographe)
- [X] Les détails des changements ont été décrits ci-dessous
- [X] Cette pull-request n'est pas une **"breaking-change"** (des modifications qui vont entraîner la modification du fonctionnement de certaines fonctionnalités déjà existantes)

## Changelogs proposés

- [En accord avec le figma] Transformation from formal to informal (vouvoiement vers tutoiement)
- Slight syntactic changes
- Grammatical correction (by @Kgeek33 )

2024-12-14 21:18 UTC, Kgeek33 requested changes
Parfait, j'allais justement faire une pr sur ça
Quelques fautes à corriger et c'est parfait

2024-12-14 21:18 UTC, Kgeek33 commented on src/views/login/IdentityProvider/IdentityProviderSelector.tsx
> +      description: "Utilises ton compte Sorbonne pour te connecter",
```suggestion
      description: "Utilise ton compte Sorbonne pour te connecter",
```

2024-12-14 21:18 UTC, Kgeek33 commented on src/views/login/ecoledirecte/EcoleDirecteCredentials.tsx
> +              <NativeText variant={"subtitle"}>Répond à la question suivante pour continuer de t'authentifier</NativeText>
```suggestion
              <NativeText variant={"subtitle"}>Réponds à la question suivante pour continuer ton authentification</NativeText>
```

2024-12-14 21:18 UTC, Kgeek33 commented on src/views/settings/ExternalAccount/QrcodeScanner.tsx
> +          Lie ton QR Code à ton compte
```suggestion
          Associe ton QR Code à ton compte
```

2024-12-14 21:18 UTC, Kgeek33 commented on src/views/settings/SettingsAddons.tsx
> +                <NativeText variant={"subtitle"} style={{flex: 1}}>Les extensions non signé ne sont pas vérifiee par nos équipes. Tu es responsable de l'installation de celle-ci.</NativeText>
```suggestion
                <NativeText variant={"subtitle"} style={{flex: 1}}>Les extensions non signées ne sont pas vérifiées par nos équipes. Tu es responsable de l'installation de celle-ci.</NativeText>
```

2024-12-14 21:18 UTC, Kgeek33 commented on src/views/settings/SettingsAddons.tsx
> +                                    permission.name == "PERM_SCHOOLDATA_AUTH" ? "Accéder au données d'authentification de ton compte principal (DANGEREUX)":
```suggestion
                                    permission.name == "PERM_SCHOOLDATA_AUTH" ? "Accéder aux données d'authentification de ton compte principal (DANGEREUX)":
```

2024-12-14 21:18 UTC, Kgeek33 commented on src/views/settings/SettingsAddons.tsx
> +                      {(permission.name == "PERM_SCHOOLDATA_AUTH" ? "Cette autorisation transmet à l'extension les jetons de connexion vers tes services. Avec ceci, l'extension peut éxécuter n'import
```suggestion
                      {(permission.name == "PERM_SCHOOLDATA_AUTH" ? "Cette autorisation transmet à l'extension les jetons de connexion vers tes services. Avec ceci, l'extension peut exécuter n'importe quelle action. Sois prudent.\n\n":"") + permission.reason}
```

2024-12-14 21:18 UTC, Kgeek33 commented on src/views/settings/SettingsTabs.tsx
> +                  {newTabs.map((tab) => tab.label).join(", ")}. Appuis ici pour les ajouter.
```suggestion
                  {newTabs.map((tab) => tab.label).join(", ")}. Appuie ici pour les ajouter.
```

2024-12-14 21:18 UTC, Kgeek33 commented on src/views/welcome/ChangelogScreen.tsx
> +              Tu es peut-être hors-ligne ou alors quelque chose ne s'est pas passé comme prévu...
```suggestion
              Tu es peut-être hors-ligne ou alors une erreur est survenue...
```
J'ai pris 1 heure à chercher si passé avait un e en plus, alors j'ai changé la phrase 😂

2024-12-14 21:18 UTC, Kgeek33 commented on src/views/welcome/DevMenu.tsx
> +            Intégre tes options et paramètres de développement ici.
```suggestion
            Intègre tes options et paramètres de développement ici.
```

2024-12-14 21:29 UTC, Bulgus commented on src/views/welcome/ChangelogScreen.tsx
> +              Tu es peut-être hors-ligne ou alors quelque chose ne s'est pas passé comme prévu...
mdrrr c'est plus simple 😂

2024-12-14 21:34 UTC, Bulgus commented
> Parfait, j'allais justement faire une pr sur ça Quelques fautes à corriger et c'est parfait

"Quelques fautes"... beaucoup trop de fautes désolé 😭 
Et j'ai pas du tout fait gaffe à voir si y'en avait pas de base dans les textes...
Merci pour toutes les modifs !
Ça me parait bon, juste il faut attendre trois reviews vu que ça touche à tous les fichiers 💀

2024-12-14 21:47 UTC, Kgeek33 commented
> > Parfait, j'allais justement faire une pr sur ça Quelques fautes à corriger et c'est parfait
> 
> "Quelques fautes"... beaucoup trop de fautes désolé 😭 
> Et j'ai pas du tout fait gaffe à voir si y'en avait pas de base dans les textes...
> Merci pour toutes les modifs !
> Ça me parait bon, juste il faut attendre trois reviews vu que ça touche à tous les fichiers 💀 

Mais non tkt pas, en plus c'était des fautes déjà présentes 😂
Pas de problème, moi j'attends depuis 1 mois ma pr #346 😭😭😭

2024-12-14 21:47 UTC, Kgeek33 approved these changes
Parfait, LGTM 👍

2024-12-14 21:48 UTC, Bulgus commented
> > > Parfait, j'allais justement faire une pr sur ça Quelques fautes à corriger et c'est parfait
> > 
> > 
> > "Quelques fautes"... beaucoup trop de fautes désolé 😭
> > Et j'ai pas du tout fait gaffe à voir si y'en avait pas de base dans les textes...
> > Merci pour toutes les modifs !
> > Ça me parait bon, juste il faut attendre trois reviews vu que ça touche à tous les fichiers 💀
> 
> Mais non tkt pas, en plus c'était des fautes déjà présentes 😂 Pas de problème, moi j'attends depuis 1 mois ma pr #346 😭😭😭

Aïe aïe aïe... 😭 
Ça va pas prendre longtemps à être en conflict en plus vu le nombre de ligne que ça change 💀

2024-12-14 21:53 UTC, Kgeek33 commented
> > > > Parfait, j'allais justement faire une pr sur ça Quelques fautes à corriger et c'est parfait
> > > 
> > > 
> > > "Quelques fautes"... beaucoup trop de fautes désolé 😭
> > > Et j'ai pas du tout fait gaffe à voir si y'en avait pas de base dans les textes...
> > > Merci pour toutes les modifs !
> > > Ça me parait bon, juste il faut attendre trois reviews vu que ça touche à tous les fichiers 💀
> > 
> > Mais non tkt pas, en plus c'était des fautes déjà présentes 😂 Pas de problème, moi j'attends depuis 1 mois ma pr #346 😭😭😭
> 
> Aïe aïe aïe... 😭 
> Ça va pas prendre longtemps à être en conflict en plus vu le nombre de ligne que ça change 💀 

Par contre, si cette pr prend plus de 2 jours, je pète un câble 😂
Srx, c'est pas compliqué à review, changement vous => tu et la conjugaison est adapté

2024-12-14 22:09 UTC, Bulgus commented
> Par contre, si cette pr prend plus de 2 jours, je pète un câble 😂 Srx, c'est pas compliqué à review, changement vous => tu et la conjugaison est adapté

Oui normalement c'est assez rapide...

2024-12-14 22:17 UTC, Kgeek33 commented
Tu pourris review ma pr stp ? 
j'suis tellement dans le déni que je te demande de review mdrr 🤣

2024-12-14 22:18 UTC, Bulgus commented
> Tu pourris review ma pr stp ? j'suis tellement dans le déni que je te demande de review mdrr 🤣

Oui oui j'allais voir si t'en avais pas une en attente justement 😭 
C'est laquelle ?

2024-12-14 22:26 UTC, Kgeek33 commented
#372 et #346 stp

2024-12-14 22:28 UTC, Kgeek33 approved these changes
(_j'crois que je l'ai déjà fait mdr_)
j'viens de tester et ça fonctionne ! LGTM 👍

2024-12-14 22:32 UTC, Bulgus commented
> (_j'crois que je l'ai déjà fait mdr_) j'viens de tester et ça fonctionne ! LGTM 👍

_(Pas grave mdrrr)_

Et je check tes PR demain matin !

2024-12-14 22:35 UTC, Kgeek33 commented
> Et je check tes PR demain matin !

Parfait merci !

2024-12-15 23:25 UTC, ecnivtwelve submitted a review, later dismissed
LGTM

2024-12-20 13:43 UTC, Kgeek33 commented
@Bulgus conflits 😭😭
Il faudrait que la pr soit merge avant une nouvelle release, pask tutoyer sur la sélection d'un établissement et vouvoyer sur le reste de l'app...

2024-12-20 13:45 UTC, Bulgus commented
@Kgeek33 
j'ai vu ça... je perd espoir que les PR soient review un jour, donc bon...
Mais clairement faut que ça soit merge pour une future version, une fois que c'est fait y'aura pas de conflict, et puis rajouter "tutoyer l'utilisateur" dans la checklist de la template d'une nouvelle PR.. et ça sera bien 😭

2024-12-20 13:49 UTC, Kgeek33 commented
Perd pas espoir, c juste très long. Résous quand même tes conflits
Propose ta modif sur ma pr qui fait un update du dossier `.github` #449 stp

2024-12-20 13:55 UTC, Bulgus commented
> Perd pas espoir, c juste très long. Résous quand même tes conflits

T'as raison ;)
C'est fait, mais pas sur de l'avoir correctement résolu (j'ai jamais résolu de conflits)

> Propose ta modif sur ma pr qui fait un update du dossier `.github` #449 stp

Je fais ça !

Edit : j'arrive pas je vois pas ou tu veux que je le mette, y'a plus la checklist de PR ? Y'a juste le type de PR à cocher ?

2024-12-20 21:58 UTC, Kgeek33 commented
> C'est fait, mais pas sur de l'avoir correctement résolu (j'ai jamais résolu de conflits)

tu l'as fait depuis github ou vscode ?

2024-12-20 21:59 UTC, Kgeek33 commented
> Edit : j'arrive pas je vois pas ou tu veux que je le mette, y'a plus la checklist de PR ? Y'a juste le type de PR à cocher ?

propose sur ma pr ce qu'il faut changer. et oui, il y a plus la checklist, tout est automatisé (objectif) avec des workflows (et franchement, il n'y avait pas besoin de la majorité des cases)

2024-12-21 12:58 UTC, Bulgus commented
> tu l'as fait depuis github ou vscode ?

Github !

> propose sur ma pr ce qu'il faut changer. et oui, il y a plus la checklist, tout est automatisé (objectif) avec des workflows (et franchement, il n'y avait pas besoin de la majorité des cases)

J'ai essayé mais j'arrive pas à comprendre la ou il faut le mettre, vu que y'a pas de checklit 😭

2024-12-21 14:16 UTC, Kgeek33 commented
> Github !

c'est vrai que c'est compliqué à résoudre sur github

> J'ai essayé mais j'arrive pas à comprendre la ou il faut le mettre, vu que y'a pas de checklit 😭

mets ça dans la conversation de la pr, j'y travaillerai sur ça plus tard

2024-12-25 19:14 UTC, ecnivtwelve approved these changes, later dismissed

2024-12-25 19:15 UTC, ecnivtwelve commented
> > Perd pas espoir, c juste très long. Résous quand même tes conflits
> 
> T'as raison ;) C'est fait, mais pas sur de l'avoir correctement résolu (j'ai jamais résolu de conflits)
> 
> > Propose ta modif sur ma pr qui fait un update du dossier `.github` #449 stp
> 
> Je fais ça !
> 
> Edit : j'arrive pas je vois pas ou tu veux que je le mette, y'a plus la checklist de PR ? Y'a juste le type de PR à cocher ?

excuse nous, c'est noël, j'essaye toujours d'apposer une review en quelques jours si je peux, certaines comme celle-ci sont relativement larges quand même

2025-01-04 21:23 UTC, tryon-dev approved these changes, later dismissed

2025-01-06 11:23 UTC, Kgeek33 commented
@Bulgus jspas si tu l'as fait lors du merge, mais faut tutoyer l'utilisateur sur la réaction des notes (notamment dans les paramètres)

2025-01-06 12:10 UTC, Bulgus commented
> @Bulgus jspas si tu l'as fait lors du merge, mais faut tutoyer l'utilisateur sur la réaction des notes (notamment dans les paramètres) 

Ah oui pas bête, je m'en occupe ce soir.
Mais ça devient un peu chiant, je dois me mettre à jour sur chaque nouveauté, il faudrait que ça soit merge puis que les nouvelles PR soient faites en tutoiement
Bref...
Merci de l'info!

2025-01-06 13:17 UTC, Kgeek33 commented
> > @Bulgus jspas si tu l'as fait lors du merge, mais faut tutoyer l'utilisateur sur la réaction des notes (notamment dans les paramètres)
> 
> Ah oui pas bête, je m'en occupe ce soir. Mais ça devient un peu chiant, je dois me mettre à jour sur chaque nouveauté, il faudrait que ça soit merge puis que les nouvelles PR soient faites en tutoiement Bref... Merci de l'info!

s de problème. je pense que ta pr sera merge pour la v7.7.1

2025-01-11 21:19 UTC, tryon-dev approved these changes

2025-01-11 21:19 UTC, ecnivtwelve approved these changes

2025-01-11 21:19 UTC, merged