Feat(homeworks) : Switch to next week if no homeworks remain in current week
PapillonApp/papillon-v7 pull request #461
Opened 2024-12-14 21:26 UTC by Bulgus

# 🚀 Nouvelle Pull Request

Proposez vos modifications pour améliorer Papillon

## Informations importantes

Merci de vous référer à la documentation sur la contribution si vous avez des questions à propos des pull requests (https://gitbook.getpapillon.xyz/organisation/outils-internes/github)

## Checklist d'avant pull request

Veuillez cocher toutes les cases applicables en remplaçant [ ] par [x].

- [X] Vous avez testé de build le projet avec vos modifications et ce build **a réussi**
- [X] Vous respectez les conventions de codage et de nommage du projet
- [X] Vous utilisez la **tabulation** pour l'indentation afin de maintenir un code lisible
- [X] Cette pull request **n'est pas un duplicata** d'une autre
- [X] Cette pull request est prête à être **revue** (review) et **fusionnée** (merge)
- [X] Il n'y a pas de **`TODO`** (aka des annotations pour du code manquant) dans vos modifications
- [X] Il n'y a pas **d'erreurs de langue** dans votre code (grammaire, vocabulaire, conjugaison, orthographe)
- [X] Les détails des changements ont été décrits ci-dessous
- [X] Cette pull-request n'est pas une **"breaking-change"** (des modifications qui vont entraîner la modification du fonctionnement de certaines fonctionnalités déjà existantes)

## Changelogs proposés

- Display the next week if no homework remains between the current day and sunday

## Informations supplémentaires

Les vidéos sont prises après un refresh de l'app.

https://github.com/user-attachments/assets/536f749a-aa3a-486e-8b4e-1c187230ec5e

https://github.com/user-attachments/assets/fdeb7122-b94e-4a7f-bb1a-e4d53fc6d4b9

2024-12-14 21:29 UTC, Kgeek33 reviewed
Good, dis-moi ce que t'en penses de ma suggestion

2024-12-14 21:29 UTC, Kgeek33 commented on src/views/account/Homeworks/Homeworks.tsx
> +    if (dayOfWeek === 6 || dayOfWeek === 0) {
```suggestion
    if (dayOfWeek >= 5 || dayOfWeek === 0) {
```
J'pense que tu peux le faire dès le vendredi, on suppose que l'élève ne fait pas les devoirs le jour même ;)

2024-12-14 21:35 UTC, Bulgus commented on src/views/account/Homeworks/Homeworks.tsx
> +    if (dayOfWeek === 6 || dayOfWeek === 0) {
J'ai hésité, mais en vrai moi ça m'arrive souvent donc je sais pas... 😭 
Genre j'ai des perms le vendredi matin, et je check souvent les devoirs des cours de l'aprèm...

2024-12-14 21:35 UTC, Kgeek33 approved these changes
Parfait, LGTM 👍

2024-12-14 21:37 UTC, Kgeek33 commented
Mince, j'me suis trompé de pr 😂

2024-12-14 21:37 UTC, Kgeek33 commented on src/views/account/Homeworks/Homeworks.tsx
> +    if (dayOfWeek === 6 || dayOfWeek === 0) {
Ah ben laisse comme c'était
Mais jspas, faut voir ce que fait Pronote

2024-12-14 21:39 UTC, Kgeek33 commented on src/views/account/Homeworks/Homeworks.tsx
> +    if (dayOfWeek === 6 || dayOfWeek === 0) {
Ok non en fait, après réflexion, c'est mieux à partir du samedi

2024-12-14 21:40 UTC, Kgeek33 approved these changes
LGTM 👍

2024-12-14 21:40 UTC, Bulgus commented on src/views/account/Homeworks/Homeworks.tsx
> +    if (dayOfWeek === 6 || dayOfWeek === 0) {
Je sais pas, j'utilise jamais
Mais je pense faut le faire qu'à partir du samedi 
Mais normalement ça existe pas les devoirs le week end
ah mais si, si quelqu'un à cours le week end ?
heuuu 😭

2024-12-14 21:40 UTC, Kgeek33 commented on src/views/account/Homeworks/Homeworks.tsx
> +    if (dayOfWeek === 6 || dayOfWeek === 0) {
Tu peux mettre en resolved!

2024-12-14 21:41 UTC, Kgeek33 commented
Les cours le week-end, humm....
C'est très rare, argh, jspas 😂

2024-12-14 21:44 UTC, Kgeek33 commented
Faudrait faire comme ton autre PR, vérifier d'abord qu'il n'y a pas de devoirs le samedi et dimanche et après, basculer sur la semaine suivante
Tu peux t'inspirer du code dans `HomeworkElement` du dossier Home qui filtre les devoirs

2024-12-14 21:47 UTC, Bulgus commented
> Faudrait faire comme ton autre PR, vérifier d'abord qu'il n'y a pas de devoirs le samedi et dimanche et après, basculer sur la semaine suivante Tu peux t'inspirer du code dans `HomeworkElement` du dossier Home qui filtre les devoirs

Yep j'étais en train d'essayer de faire ça
ah oui pas bête le code du Home je check ça

2024-12-14 21:51 UTC, Kgeek33 commented
> > Faudrait faire comme ton autre PR, vérifier d'abord qu'il n'y a pas de devoirs le samedi et dimanche et après, basculer sur la semaine suivante Tu peux t'inspirer du code dans `HomeworkElement` du dossier Home qui filtre les devoirs
> 
> Yep j'étais en train d'essayer de faire ça
> ah oui pas bête le code du Home je check ça

En plus, c'est moi qui ai fait ce code 😂😂

2024-12-14 22:10 UTC, Bulgus commented
> > > Faudrait faire comme ton autre PR, vérifier d'abord qu'il n'y a pas de devoirs le samedi et dimanche et après, basculer sur la semaine suivante Tu peux t'inspirer du code dans `HomeworkElement` du dossier Home qui filtre les devoirs
> > 
> > 
> > Yep j'étais en train d'essayer de faire ça
> > ah oui pas bête le code du Home je check ça
> 
> En plus, c'est moi qui ai fait ce code 😂😂

J'ai fais un truc différent, c'était plus simple pour moi, et ça me semble le plus logique comme ça (voir commit)

2024-12-14 22:17 UTC, Kgeek33 commented
je regarde ça

2024-12-14 22:24 UTC, Kgeek33 requested changes
c tout ce qui faut changer mais ça fonctionne bien !

2024-12-14 22:24 UTC, Kgeek33 commented on src/views/account/Homeworks/Homeworks.tsx
> +  const getWeekNumber = (homeworks) => {
```suggestion
  const getWeekNumber = (homeworks: Record<number, Homework[]>) => {
```
par rapport à TypeScript

2024-12-14 22:31 UTC, Bulgus commented
> c tout ce qui faut changer mais ça fonctionne bien !

Yess nickel ! Merci :D

2024-12-14 22:35 UTC, Kgeek33 approved these changes
Parfait, LGTM 👍

2024-12-17 18:18 UTC, ecnivtwelve commented on src/views/account/Homeworks/Homeworks.tsx
> +    });
si ça n'a pas encore fetch, on skip direct la semaine actuelle ?

2024-12-17 18:45 UTC, Bulgus commented on src/views/account/Homeworks/Homeworks.tsx
> +    });
Non, je n'y ai pas pensé ! Ligne 176 à 183, j'ai rajouté quelque chose pour vérifier si les données sont load, si non elles sont fetch, ça devrait éviter que ça passe à la semaine d'après parce que ça n'a pas encore fetch

2024-12-17 19:21 UTC, Rexxt commented on src/views/account/Homeworks/Homeworks.tsx
> +    if (dayOfWeek === 6 || dayOfWeek === 0) {
y a des gens qui ont cours le samedi !

2024-12-17 19:21 UTC, Rexxt commented on src/views/account/Homeworks/Homeworks.tsx
> +  const getWeekNumber = (homeworks) => {
oue

2024-12-17 19:22 UTC, Rexxt commented
todo : review détaillée

pour moi c'est un peu un antipattern

2025-01-11 21:28 UTC, godetremy commented
> [!NOTE]
> Cette review est le résultat de la concertation de toute l'équipe Papillon.

Malheureusement, nous n'arrivons pas à accéder à la page des devoirs depuis les modifications... Rectifie ta PR, puis un nouveau check sera fait la semaine prochaine.

2025-01-13 12:47 UTC, closed without merging