Course/course content
PapillonApp/papillon-v7 pull request #462
Opened 2024-12-15 11:15 UTC by Gabriel29306

# 🚀 Nouvelle Pull Request

Proposez vos modifications pour améliorer Papillon

## Informations importantes

Merci de vous référer à la documentation sur la contribution si vous avez des questions à propos des pull requests (https://gitbook.getpapillon.xyz/organisation/outils-internes/github)

## Checklist d'avant pull request

Veuillez cocher toutes les cases applicables en remplaçant [ ] par [x].

- [ ] Vous avez testé de build le projet avec vos modifications et ce build **a réussi**
- [x] Vous respectez les conventions de codage et de nommage du projet
- [x] Vous utilisez la **tabulation** pour l'indentation afin de maintenir un code lisible
- [x] Cette pull request **n'est pas un duplicata** d'une autre
- [ ] Cette pull request est prête à être **revue** (review) et **fusionnée** (merge)
- [x] Il n'y a pas de **`TODO`** (aka des annotations pour du code manquant) dans vos modifications
- [x] Il n'y a pas **d'erreurs de langue** dans votre code (grammaire, vocabulaire, conjugaison, orthographe)
- [x] Les détails des changements ont été décrits ci-dessous
- [x] Cette pull-request n'est pas une **"breaking-change"** (des modifications qui vont entraîner la modification du fonctionnement de certaines fonctionnalités déjà existantes)

## Changelogs proposés

Les contenus de cours sont maintenant là !
> [!NOTE]
> Uniquement pour Pronote (Il y a peut être pour les autres services ?)

## Informations supplémentaires

Il faut juste que je rajoute le type de ressource !

2024-12-15 12:25 UTC, Kgeek33 commented
Je teste ça tout à l'heure mais les modifs n'ont pas d'impact sur École Directe ?
Sur ce commit : https://github.com/PapillonApp/Papillon/commit/7e185ed8c27c6a1eb5e8d4b1a605f08cef994aef

2024-12-15 12:28 UTC, Kgeek33 commented
Et tu peux link cette issue : #132

2024-12-15 12:28 UTC, Gabriel29306 commented
Celà ne devrait pas affecter école directe. 
Je ne fais que des ajouts

2024-12-15 12:55 UTC, Kgeek33 approved these changes
Une petite bordure pour bien différencier les pj du contenu des cours serait cool
Mais LGTM 👍

2024-12-15 16:42 UTC, Gabriel29306 commented
Pour bien fonctionner, cet PR requière une nouvelle release de Pawnote avec le categoryText.

2024-12-15 19:29 UTC, JyhuKo approved these changes

2024-12-15 19:47 UTC, Kgeek33 approved these changes

2024-12-20 21:20 UTC, raphckrman requested changes
Tu as eu une erreur sur le workflow, tu pourrais regarder le lint ?

2024-12-20 21:42 UTC, Gabriel29306 commented
> Tu as eu une erreur sur le workflow, tu pourrais regarder le lint ?

Il fallait que je mette à jour Pawnote.
Là il y a une erreur de lint sur une partie que je n'ai pas touchée.

2024-12-20 22:09 UTC, raphckrman commented
Je ne peut pas voir le contenu du cours de mon côté, les requêtes partent bien.
![image](https://github.com/user-attachments/assets/8e078d34-a78c-4f24-89f7-ec9a8c623366)

2024-12-20 22:11 UTC, raphckrman commented
Après quelques test j'ai l'erreur à chaque fois, je n'ai plus les cours dans l'EDT (bien retourné par Pronote)

2024-12-20 23:31 UTC, raphckrman commented
Juste ça sinon ça marche 
![image](https://github.com/user-attachments/assets/8193556c-7401-48e7-8474-c9d6012f602a)

2024-12-20 23:34 UTC, raphckrman commented
Pour une review des designers:
![image](https://github.com/user-attachments/assets/28f0da22-e789-40f7-92cc-88454c54d196)
![image](https://github.com/user-attachments/assets/31df3852-8511-4386-af28-192a7e05792c)

2024-12-20 23:55 UTC, raphckrman requested changes
fix l'erreur des key

2024-12-20 23:55 UTC, raphckrman commented on src/views/account/Lessons/Document.tsx
> +                    <>
```suggestion
                    <React.Fragment key={"res_" + index}>
```

2024-12-20 23:55 UTC, raphckrman commented on src/views/account/Lessons/Document.tsx
> +                    </>
```suggestion
                    </React.Fragment>
```

2024-12-21 13:04 UTC, Kgeek33 approved these changes
LGTM 👍

2024-12-21 13:36 UTC, Clmnnt approved these changes
C'est oui ou bien c'est non ? Bah c'est oui :) (désolé pour cette blague pas très drôle)

2024-12-22 14:57 UTC, camarm-dev approved these changes
LGTM 👍🏻 (testé)

2024-12-23 21:37 UTC, toi-et-moi commented
l'interface est beaucoup trop complexe, pour une telle feature il faut repenser toute l'interface, la c'est franchement pas ouf niveau UX ne parlons pas des padding et des native lists dans des native lists... l'idée en sois est bonne mais mal exécutée

2024-12-25 19:20 UTC, ecnivtwelve submitted a review, later dismissed
d'accord avec @toi-et-moi mais la feature est relativement bien implémentée -> on pourra faire des améliorations UX à postériori

2024-12-25 22:19 UTC, JyhuKo approved these changes

2024-12-26 00:36 UTC, Gabriel29306 commented
> l'interface est beaucoup trop complexe, pour une telle feature il faut repenser toute l'interface, ...

Actuellement, je ne suis pas chez moi, et ceux pendant toutes les vacances, mais les mainteneurs ont les droits d'écriture sur la PR, donc si tu veux, tu peux le faire librement 😉

2024-12-26 01:13 UTC, raphckrman approved these changes
LGTM, à voir dans le futur pour l'UI

2024-12-27 11:00 UTC, merged