better readme
PapillonApp/papillon-v7 pull request #465
Opened 2024-12-15 19:26 UTC by JyhuKo

# 🚀 Nouvelle Pull Request

Proposez vos modifications pour améliorer Papillon

## Informations importantes

Merci de vous référer à la documentation sur la contribution si vous avez des questions à propos des pull requests (https://gitbook.getpapillon.xyz/organisation/outils-internes/github)

## Checklist d'avant pull request

Veuillez cocher toutes les cases applicables en remplaçant [ ] par [x].

- [ ] Vous avez testé de build le projet avec vos modifications et ce build **a réussi**
- [ x] Vous respectez les conventions de codage et de nommage du projet
- [ x] Vous utilisez la **tabulation** pour l'indentation afin de maintenir un code lisible
- [ x] Cette pull request **n'est pas un duplicata** d'une autre
- [x ] Cette pull request est prête à être **revue** (review) et **fusionnée** (merge)
- [ x] Il n'y a pas de **`TODO`** (aka des annotations pour du code manquant) dans vos modifications
- [x ] Il n'y a pas **d'erreurs de langue** dans votre code (grammaire, vocabulaire, conjugaison, orthographe)
- [x ] Les détails des changements ont été décrits ci-dessous
- [ x] Cette pull-request n'est pas une **"breaking-change"** (des modifications qui vont entraîner la modification du fonctionnement de certaines fonctionnalités déjà existantes)

## Changelogs proposés

Décrivez les modifications que vous avez effectuées.
modification du readme, j'ai changé le lien pour la doc de dev car ca mettait page introuvable
## Informations supplémentaires

Ajoutez ici toute information supplémentaire si nécessaire.

2024-12-15 19:44 UTC, Kgeek33 requested changes
Voilà ma review !
Et peut-être lister les services de cantine piyr mettre à l'avant Papillon ? ;)

2024-12-15 19:44 UTC, Kgeek33 commented on README.md
> +Pour commencer à développer sur Papillon v7, consultez le [centre de documentation pour développeurs](https://developers.papillon.bzh/).
On peut utiliser le langage informel mtn (tutoiement) 
```suggestion
Pour commencer à développer sur Papillon v7, consulte le [centre de documentation pour développeurs](https://developers.papillon.bzh/).
```

2024-12-15 19:44 UTC, Kgeek33 commented on README.md
>  ![A propos du projet](https://raw.githubusercontent.com/PapillonApp/Papillon/main/.github/assets/part_dev_dark.svg#gh-dark-mode-only)
```suggestion
 ![À propos du projet](https://raw.githubusercontent.com/PapillonApp/Papillon/main/.github/assets/part_dev_dark.svg#gh-dark-mode-only)
```

2024-12-15 19:44 UTC, Kgeek33 commented on README.md
>  ![A propos du projet](https://raw.githubusercontent.com/PapillonApp/Papillon/main/.github/assets/part_dev_light.svg#gh-light-mode-only)
```suggestion
 ![À propos du projet](https://raw.githubusercontent.com/PapillonApp/Papillon/main/.github/assets/part_dev_light.svg#gh-light-mode-only)
```

2024-12-15 19:44 UTC, Kgeek33 commented on README.md
Ligne 4 et 5, tu peux mettre en commentaire stp ?

2024-12-15 20:17 UTC, JyhuKo commented on README.md
comment ca ?

2024-12-15 20:25 UTC, JyhuKo commented
> Voilà ma review ! Et peut-être lister les services de cantine piyr mettre à l'avant Papillon ? ;)

oui mais j'ai aucune idée de ceux qui sont dispo a part turboself je crois

2024-12-15 20:26 UTC, raphckrman commented
> > Voilà ma review ! Et peut-être lister les services de cantine piyr mettre à l'avant Papillon ? ;)
> 
> oui mais j'ai aucune idée de ceux qui sont dispo a part turboself je crois

Turboself, ARD, Izly, Alise

2024-12-15 20:29 UTC, JyhuKo commented
> Turboself, ARD, Izly, Alise

mercii

2024-12-15 20:46 UTC, Kgeek33 commented on README.md
Il n'y a plus besoin de dire que Papillon est en mise à jour majeure...
En markdown, si je me trompe pas, pour mettre en commentaire du code, c'est comme en html : `<!--le code-->`

2024-12-15 20:48 UTC, Kgeek33 commented on README.md
Oui voilà c'est ça
Comme ça ça affiche plus l'image mais on pourra la réutiliser si nécessaire au futur

2024-12-15 20:49 UTC, Kgeek33 commented
@raphckrman Alise n'est pas sur Papillon, si ?
Sur la 7.6.0 ça y est pas

2024-12-15 20:50 UTC, Kgeek33 commented
@JyhuKo j'attends que tu commits ma suggestion pour que j'approuve :)

2024-12-15 20:51 UTC, Kgeek33 commented
Ok je me tais pour Alise, j'avais pas vu les prs en attente 😂

2024-12-15 20:51 UTC, raphckrman commented
pas encore, bientôt j'espère 👀

2024-12-15 20:52 UTC, raphckrman commented
j'attend juste la review

2024-12-15 20:53 UTC, JyhuKo commented
> @JyhuKo j'attends que tu commits ma suggestion pour que j'approuve :)

good ?

2024-12-15 20:53 UTC, Kgeek33 approved these changes
Parfait, LGTM 👍

2024-12-15 21:35 UTC, JyhuKo commented
j'ai add le discord , je sais pas si je le laisse ou pas

2024-12-15 21:44 UTC, Kgeek33 commented
Non c'est très bien, tu peux le laisser

2024-12-15 23:26 UTC, ecnivtwelve approved these changes

2024-12-16 10:46 UTC, tryon-dev approved these changes

2024-12-16 10:46 UTC, merged