fix(home): Utilisation correcte sur Android + Non vide le week-end (Page d'accueil, V2)
PapillonApp/papillon-v7 pull request #483
Opened 2024-12-16 18:10 UTC by Kgeek33

# 🚀 Nouvelle Pull Request

Proposez vos modifications pour améliorer Papillon

## Informations importantes

Merci de vous référer à la documentation sur la contribution si vous avez des questions à propos des pull requests (https://gitbook.getpapillon.xyz/organisation/outils-internes/github)

## Checklist d'avant pull request

Veuillez cocher toutes les cases applicables en remplaçant [ ] par [x].

- [x] Vous avez testé de build le projet avec vos modifications et ce build **a réussi**
- [x] Vous respectez les conventions de codage et de nommage du projet
- [x] Vous utilisez la **tabulation** pour l'indentation afin de maintenir un code lisible
- [x] Cette pull request **n'est pas un duplicata** d'une autre
- [x] Cette pull request est prête à être **revue** (review) et **fusionnée** (merge)
- [x] Il n'y a pas de **`TODO`** (aka des annotations pour du code manquant) dans vos modifications
- [x] Il n'y a pas **d'erreurs de langue** dans votre code (grammaire, vocabulaire, conjugaison, orthographe)
- [x] Les détails des changements ont été décrits ci-dessous
- [x] Cette pull-request n'est pas une **"breaking-change"** (des modifications qui vont entraîner la modification du fonctionnement de certaines fonctionnalités déjà existantes)

## Changelogs proposés

- Utilisation plus facile de la page d'accueil
- En fonction du défilement, l'arrière-plan s'adapte
- Fix de l'affichage incorrect du nom du compte en mode clair
- Affichage d'un message lorsqu'aucune absence/note/devoir…

## Capture(s) d'écran

| Avant | Après |
|--------|--------|
| ![1733158800565](https://github.com/user-attachments/assets/46704b56-63ee-477c-9713-97996ac475f4) | ![1733158800570](https://github.com/user-attachments/assets/3ba627f1-b749-4dbd-b239-940440bafe1a) | 

## Issues en lien

- Closes #315 
- Closes #311 
- Closes #338 
- Closes #332 
- Closes #317 
- Closes #279 
- Closes #391 
- Closes #414 
- Closes #453 
- Closes #457 

## Informations supplémentaires

Copier-coller de #372

2024-12-17 17:16 UTC, Kgeek33 commented
@oriionn tu peux review stp ?
Si qqun a Android (ou même ios), peut-il review ?

2024-12-17 17:23 UTC, oriionn commented
> @oriionn tu peux review stp ? Si qqun a Android (ou même ios), peut-il review ?

Je vais check ça mais je garantie rien (mon environnement de dev/testing est assez instable)

2024-12-17 17:25 UTC, Kgeek33 commented
> > @oriionn tu peux review stp ? Si qqun a Android (ou même ios), peut-il review ?
> 
> Je vais check ça mais je garantie rien (mon environnement de dev/testing est assez instable)

Ok c pas grave, du moment que ça peut arrêter les plaintes des utilisateurs à chaque fois 🤣
Instable ?

2024-12-17 17:31 UTC, oriionn commented
> > > @oriionn tu peux review stp ? Si qqun a Android (ou même ios), peut-il review ?
> > 
> > 
> > Je vais check ça mais je garantie rien (mon environnement de dev/testing est assez instable)
> 
> Ok c pas grave, du moment que ça peut arrêter les plaintes des utilisateurs à chaque fois 🤣 Instable ?

Le stockage de mon PC tkt

2024-12-18 11:18 UTC, Kgeek33 commented
@oriionn (_et je m'adresse à tout le monde_)
Plutôt que de faire des git clone, avez-vous pensez à ajouter des remotes sur votre projet local ?
C'est ce que je fais et c'est très pratique, efficace et gagne en stockage ;)

2024-12-20 06:39 UTC, Kgeek33 commented
@ecnivtwelve j'avais oublié de supprimer le fichier Home.android.tsx, il n'est plus utilisé dc déso de ton commit mdr

2024-12-25 19:09 UTC, ecnivtwelve requested changes
J'ai des influences très étranges sur iOS, cette PR devrait pas concerner uniquement Android ???

https://github.com/user-attachments/assets/1068b7a0-d235-48c0-afbd-a45d7d8f0264

2024-12-25 19:24 UTC, Kgeek33 commented
> J'ai des influences très étranges sur iOS, cette PR devrait pas concerner uniquement Android ???
> 
> https://github.com/user-attachments/assets/1068b7a0-d235-48c0-afbd-a45d7d8f0264
> 
> 

Oui ça devait que concerner que Android mais ça devait améliorer pour ios également
J'vais voir pour réaméliorer ça

2024-12-26 20:24 UTC, ecnivtwelve commented
> > J'ai des influences très étranges sur iOS, cette PR devrait pas concerner uniquement Android ???
> > 
> >   
> >     
> >     
> > 
> >     Simulator.Screen.Recording.-.iPhone.14.Pro.-.2024-12-25.at.20.09.02.mp4
> 
> Oui ça devait que concerner que Android mais ça devait améliorer pour ios également J'vais voir pour réaméliorer ça

en vrai te complique pas la tâche, applique tes fix android et on verra ensuite pour iOS (qui fonctionne bien à priori)

2024-12-26 20:28 UTC, Kgeek33 commented
> en vrai te complique pas la tâche, applique tes fix android et on verra ensuite pour iOS (qui fonctionne bien à priori)

ok oui, je vais faire ça et j'y travaillerai sur une autre pr (équité entre ios en android)

2024-12-26 20:56 UTC, Kgeek33 commented
Le rendu sur Android :

https://github.com/user-attachments/assets/69af8e13-9d37-4cc1-8bb3-ba4c477c2fa3

2024-12-27 10:57 UTC, ecnivtwelve commented
j'ai toujours de la dégression et des bugs sous iOS

2024-12-27 11:04 UTC, Kgeek33 commented
> j'ai toujours de la dégression et des bugs sous iOS

c'est bizarre ça, je regarde c*qu'est-ce que j'ai oublié pour ios

2024-12-27 11:20 UTC, Kgeek33 commented
@ecnivtwelve ok j'ai oublié les onscroll qu'il y avait sur ios, ça devrait être bon

2024-12-27 11:25 UTC, Clmnnt commented
@Kgeek33 oublie pas de sync pour le lint :))

2024-12-27 11:38 UTC, Kgeek33 commented
> @Kgeek33 oublie pas de sync pour le lint :))

ah là j'y peux rien, le lint a installé la dernière version de `axios` alors qu'on ne l'a pas installé (_d'où ma pr #449 pour fix ça ;)_)

2025-01-10 14:08 UTC, MysaVS commented
> Le rendu sur Android :
> 
>  VID_20241226_215534.mp4

Est ce que le commit a été appliqué sur la 7.7.1 car j'ai toujours le probleme de scroll sur android.

2025-01-10 15:06 UTC, Kgeek33 commented
> > Le rendu sur Android :
> > 
> >  VID_20241226_215534.mp4
> 
> Est ce que le commit a été appliqué sur la 7.7.1 car j'ai toujours le probleme de scroll sur android.

Non comme ma pr n'a pas été merge cependant, le scrool a été changé mais ça reste tout de même inconfortable à utiliser

2025-01-11 21:11 UTC, closed without merging

2025-01-11 22:00 UTC, Kgeek33 commented
🥲