Improved Home & Homeworks
PapillonApp/papillon-v7 pull request #501
Opened 2024-12-18 00:27 UTC by JyhuKo

# 🚀 Nouvelle Pull Request

Proposez vos modifications pour améliorer Papillon

## Informations importantes

Merci de vous référer à la documentation sur la contribution si vous avez des questions à propos des pull requests (https://gitbook.getpapillon.xyz/organisation/outils-internes/github)

## Checklist d'avant pull request

Veuillez cocher toutes les cases applicables en remplaçant [ ] par [x].

- [x] Vous avez testé de build le projet avec vos modifications et ce build **a réussi**
- [x] Vous respectez les conventions de codage et de nommage du projet
- [x] Vous utilisez la **tabulation** pour l'indentation afin de maintenir un code lisible
- [x] Cette pull request **n'est pas un duplicata** d'une autre
- [x] Cette pull request est prête à être **revue** (review) et **fusionnée** (merge)
- [x] Il n'y a pas de **`TODO`** (aka des annotations pour du code manquant) dans vos modifications
- [x] Il n'y a pas **d'erreurs de langue** dans votre code (grammaire, vocabulaire, conjugaison, orthographe)
- [x] Les détails des changements ont été décrits ci-dessous
- [x] Cette pull-request n'est pas une **"breaking-change"** (des modifications qui vont entraîner la modification du fonctionnement de certaines fonctionnalités déjà existantes)

## Changelogs proposés
Dans le Home , suppression de la période car ca mettait "toutes" donc "Vie scolaire - toutes" mais toutes quoi ? donc c'était pas clair
changement du temps pour les devoir vu que c'était pas le même sur le home et en allant sur le devoir directement et si il était plus de minuit ou je sais pas trop ca mettait quand même un jour de plus donc au lieu de demain par exemple ca mettait après demain alors qu'il était minuit et quelques

2024-12-18 00:39 UTC, raphckrman requested changes
Mise à part le code dupliqué, LGTM

2024-12-18 00:39 UTC, raphckrman commented on src/views/account/Homeworks/Document.tsx
> +  };
Est-ce possible de ne pas dupliqué le code ? Ça le rend lourd à lire etc, possible de faire une fonction utilisé dans Item et Document.tsx ? Actuellement tu duplique la fonction dans les 2 fichiers

2024-12-18 09:10 UTC, JyhuKo commented
> Mise à part le code dupliqué, LGTM

good ?

2024-12-18 10:35 UTC, ecnivtwelve commented on src/views/account/Homeworks/Document.tsx
> +  };
+1

2024-12-18 10:35 UTC, JyhuKo commented on src/views/account/Homeworks/Document.tsx
> +  };
good normalement

2024-12-18 10:35 UTC, ecnivtwelve commented
> > Mise à part le code dupliqué, LGTM
> 
> good ?

Peut-être mieux de le mettre dans un fichier `utils` appart ?

2024-12-18 10:36 UTC, JyhuKo commented
> `utils`

je vais faire ca

2024-12-18 10:45 UTC, JyhuKo commented
done

2024-12-18 17:08 UTC, raphckrman approved these changes
LGTM

2024-12-18 20:06 UTC, tryon-dev approved these changes

2024-12-19 12:54 UTC, ecnivtwelve approved these changes

2024-12-19 12:54 UTC, merged