Fix Lesson Context
PapillonApp/papillon-v7 pull request #512
Opened 2024-12-19 16:55 UTC by JyhuKo

# 🚀 Nouvelle Pull Request

Proposez vos modifications pour améliorer Papillon

## Informations importantes

Merci de vous référer à la documentation sur la contribution si vous avez des questions à propos des pull requests (https://gitbook.getpapillon.xyz/organisation/outils-internes/github)

## Checklist d'avant pull request

Veuillez cocher toutes les cases applicables en remplaçant [ ] par [x].

- [x] Vous avez testé de build le projet avec vos modifications et ce build **a réussi**
- [x] Vous respectez les conventions de codage et de nommage du projet
- [x] Vous utilisez la **tabulation** pour l'indentation afin de maintenir un code lisible
- [x] Cette pull request **n'est pas un duplicata** d'une autre
- [x] Cette pull request est prête à être **revue** (review) et **fusionnée** (merge)
- [x] Il n'y a pas de **`TODO`** (aka des annotations pour du code manquant) dans vos modifications
- [x] Il n'y a pas **d'erreurs de langue** dans votre code (grammaire, vocabulaire, conjugaison, orthographe)
- [x] Les détails des changements ont été décrits ci-dessous
- [x] Cette pull-request n'est pas une **"breaking-change"** (des modifications qui vont entraîner la modification du fonctionnement de certaines fonctionnalités déjà existantes)

## Changelogs proposés
si le contexte est vide ca l'enleve, améliorer / fix

## Informations supplémentaires
![image](https://github.com/user-attachments/assets/94070539-592f-4f55-bdd9-adbf13e2f0aa)

2024-12-19 19:25 UTC, Rexxt commented
on peut avoir un rendu après ?

2024-12-19 19:26 UTC, Rexxt reviewed
ça a l'air de bien se goupiller, mais si tu veux faire du code ésotérique, explique-le avec des commentaires

2024-12-19 19:26 UTC, Rexxt commented on src/views/account/Lessons/Document.tsx
> +          enabled: Boolean(lesson.building?.trim()),
super ésotérique comme syntaxe

2024-12-19 19:29 UTC, JyhuKo commented on src/views/account/Lessons/Document.tsx
> +          enabled: Boolean(lesson.building?.trim()),
my bad

2024-12-19 19:37 UTC, JyhuKo commented
théoriquement ca faisait déjà ca avant mais maintenant ca vérifie mieux

2024-12-20 21:14 UTC, raphckrman requested changes
Merci de régler les erreurs de Lint pour éviter de casser ce dernier, sinon c'est good globalement

2024-12-25 19:00 UTC, ecnivtwelve submitted a review, later dismissed

2024-12-25 22:16 UTC, JyhuKo commented
je sais pas comment ca marche les conflicts :(

2024-12-26 01:02 UTC, Kgeek33 approved these changes
Le code a l'air correct !

2024-12-26 20:21 UTC, ecnivtwelve approved these changes

2024-12-26 20:21 UTC, merged