Better Home Lessons
PapillonApp/papillon-v7 pull request #535
Opened 2024-12-22 18:55 UTC by JyhuKo

# 🚀 Nouvelle Pull Request

Proposez vos modifications pour améliorer Papillon

## Informations importantes

Merci de vous référer à la documentation sur la contribution si vous avez des questions à propos des pull requests (https://gitbook.getpapillon.xyz/organisation/outils-internes/github)

## Checklist d'avant pull request

Veuillez cocher toutes les cases applicables en remplaçant [ ] par [x].

- [x] Vous avez testé de build le projet avec vos modifications et ce build **a réussi**
- [x] Vous respectez les conventions de codage et de nommage du projet
- [x] Vous utilisez la **tabulation** pour l'indentation afin de maintenir un code lisible
- [x] Cette pull request **n'est pas un duplicata** d'une autre
- [x] Cette pull request est prête à être **revue** (review) et **fusionnée** (merge)
- [x] Il n'y a pas de **`TODO`** (aka des annotations pour du code manquant) dans vos modifications
- [x] Il n'y a pas **d'erreurs de langue** dans votre code (grammaire, vocabulaire, conjugaison, orthographe)
- [x] Les détails des changements ont été décrits ci-dessous
- [x] Cette pull-request n'est pas une **"breaking-change"** (des modifications qui vont entraîner la modification du fonctionnement de certaines fonctionnalités déjà existantes)

## Changelogs proposés

Ajout des vacances et du weekend comme dans l'onglet cours

## Informations supplémentaires

https://github.com/PapillonApp/Papillon/issues/525

2024-12-22 20:35 UTC, raphckrman requested changes
Pourrais-tu résoudre les erreurs de Lint dans ton code stp ?

2024-12-22 20:35 UTC, JyhuKo commented
> Pourrais-tu résoudre les erreurs de Lint dans ton code stp ?

biensur

2024-12-22 20:50 UTC, JyhuKo commented
lets gooo

2024-12-22 20:55 UTC, raphckrman reviewed
LGTM globalement, j'ai suggéré quelques changements

2024-12-22 20:55 UTC, raphckrman commented on src/utils/format/holidayEmoji.ts
> +  ];
Pourquoi les deux sont-ils séparés ? Puisqu'à la fin ils sont rassemblés

2024-12-22 20:55 UTC, raphckrman commented on src/utils/format/holidayEmoji.ts
> +  return "📚"; // Emoji par défaut
```suggestion
  return "🏝️"; // Emoji par défaut
```
Plus adapté vu qu'on parle des vacances selon moi

2024-12-22 20:59 UTC, raphckrman reviewed
quelques questionnements ici

2024-12-22 20:59 UTC, raphckrman commented on src/views/account/Home/Elements/TimetableElement.tsx
> +  }
Si un élève à un événement dans son EDT le samedi ou le dimanche il ne le verra pas ? C'est rare mais il faut faire attention à tous les cas

2024-12-22 20:59 UTC, raphckrman commented on src/views/account/Home/Elements/TimetableElement.tsx
> +
```suggestion

```

2024-12-23 11:13 UTC, Nicolasfr340 commented on src/utils/format/holidayEmoji.ts
> +    { start: new Date(`${year + 1}-07-05`), end: new Date(`${year + 1}-09-01`), emoji: "🏖️" }, // Grandes vacances
Mes suggestions d'emojis dans l'ordre du code:

🍾 ou 🎇-> et modifier la date pour que ce soit du 31-12 au 01-01 (au lieu de juste le jour après le nouvel an)

🥚 -> cet emoji plutôt que ✝️, pour que ce soit "moins" religieux

💼 -> celui-là plutôt que l'autre qui fait très communiste USSR

[…]

🕊️ -> Lundi de pentecotes 

pour l'armistice 45 💐
pour la fête nationale 🇫🇷
pour l'armistice 18 💐

🐝 vacances de printemps
@JyhuKo

2024-12-23 11:13 UTC, Nicolasfr340 commented on src/views/account/Lessons/Atoms/Page.tsx
>          description="Profitez de vos vacances, à bientôt."
Ce serait intéressant d'indiquer la durée des vacances:

"Retour en classe le [dernier jour sans cours +1], d'ici là profitez de vos vacances, à bientôt." 
Mais sur la page d'accueil juste, dans le petit popup de l'agenda

Et par contre pourquoi pas avoir plus d'infos dans l'agenda du style "Vacances de [nom vacances] du [date début complète (ex: 21 décembre)] au [date fin complète (ex: 6 janvier)]"

2024-12-23 14:06 UTC, Wateir commented on src/views/account/Lessons/Atoms/Page.tsx
>          description="Profitez de vos vacances, à bientôt."
juste faire [Dernier jour + 1] ca marchera vraiment ? car le dernier jour c'est pas le vendredi ? et les cours recommence que le lundi, or cela indiquerai le samedi

2024-12-23 21:07 UTC, vinicel commented on src/utils/format/holidayEmoji.ts
> +  const allPeriods = [
```suggestion
  const periods = [
```

2024-12-23 21:07 UTC, vinicel commented on src/utils/format/holidayEmoji.ts
> +  return "🏝️"; // Emoji par défaut
Plus lisible et optimisé
```suggestion
return periods.find((period) => date >= period.start && date <= period.end)?.emoji ?? "🏝️";
```

2024-12-24 10:05 UTC, Nicolasfr340 commented on src/views/account/Lessons/Atoms/Page.tsx
>          description="Profitez de vos vacances, à bientôt."
Oui mais en comptant aussi les jours sans cours du coup 

En gros il regarde sur les prochains jours après le dernier jour des vacances, il compte le nombre de jours sans cours (ex: 1 ou 2) en partant du premier jour qu'il regarde, et il ajoute le nombre au nombre de jours de vacances, par contre si il ne détecte pas de jours sans cours en partant du début, il ajoute 0 car c'est le nombre de jours consécutifs sans cours à partir du premier jour

Du style les vacances s'arrêtent vendredi, le programme regarde sur les 7 prochains jours, il détecte des jours consécutifs sans cours au début de son échantillon de jours (Donc jour 1 et jour 2 il trouve des jours sans cours) -> il les ajoute au nombre de jours des vacances

2024-12-25 18:42 UTC, ecnivtwelve commented on src/views/account/Lessons/Atoms/Page.tsx
>          description="Profitez de vos vacances, à bientôt."
ça consommerait trop de ressources réseau un peu inutiles non ?

2024-12-25 18:42 UTC, ecnivtwelve approved these changes
LGTM pour moi

2024-12-25 18:58 UTC, vinicel approved these changes

2024-12-26 01:05 UTC, Kgeek33 commented on src/views/account/Lessons/Atoms/Page.tsx
>          description="Profitez de vos vacances, à bientôt."
Effectivement, même si c'est une bonne idée, cela consommerait beaucoup de ressources et après, ça va prendre trop de temps pour retourner la durée

2024-12-26 01:05 UTC, Kgeek33 approved these changes
Le code a l'air bon ! 👍

2024-12-26 20:19 UTC, merged