Feat/week frequency
PapillonApp/papillon-v7 pull request #545
Opened 2024-12-26 18:00 UTC by Skythrew

# 🚀 Nouvelle Pull Request

## Informations importantes

Merci de vous référer à la documentation sur la contribution si vous avez des questions à propos des pull requests (https://gitbook.getpapillon.xyz/organisation/outils-internes/github)

## Checklist d'avant pull request

Veuillez cocher toutes les cases applicables en remplaçant [ ] par [x].

- [x] Vous avez testé de build le projet avec vos modifications et ce build **a réussi**
- [x) Vous respectez les conventions de codage et de nommage du projet
- [x] Vous utilisez la **tabulation** pour l'indentation afin de maintenir un code lisible
- [x] Cette pull request **n'est pas un duplicata** d'une autre
- [x] Cette pull request est prête à être **revue** (review) et **fusionnée** (merge)
- [x] Il n'y a pas de **`TODO`** (aka des annotations pour du code manquant) dans vos modifications
- [x] Il n'y a pas **d'erreurs de langue** dans votre code (grammaire, vocabulaire, conjugaison, orthographe)
- [x] Les détails des changements ont été décrits ci-dessous
- [x] Cette pull-request n'est pas une **"breaking-change"** (des modifications qui vont entraîner la modification du fonctionnement de certaines fonctionnalités déjà existantes)

## Changelogs proposés

Affichage de la "fréquence" de la semaine en cours sur la page d'emploi du temps. Typiquement, "Semaine Q1", "Semaine Q2".

* Closes #319 *

2024-12-26 18:29 UTC, Kgeek33 commented
Peux-tu mettre une capture d'écran stp ?

2024-12-26 18:31 UTC, Kgeek33 commented
Et ça résout pas l'issue #469 ?

2024-12-26 20:19 UTC, ecnivtwelve submitted a review, later dismissed
j'ai fait des changements d'UI + rendu l'option optionnelle

2024-12-26 21:04 UTC, Kgeek33 requested changes
Change juste ça, sinon LGTM

2024-12-26 21:04 UTC, Kgeek33 commented on src/views/account/Lessons/Lessons.tsx
> +  const [shouldShowWeekFrequency, setShouldShowWeekFrequency] = useState(false);
j'aurai préféré que ça soit activé par défaut
```suggestion
  const [shouldShowWeekFrequency, setShouldShowWeekFrequency] = useState(true);
```

2024-12-26 21:55 UTC, Skythrew commented on src/views/account/Lessons/Lessons.tsx
> +  const [shouldShowWeekFrequency, setShouldShowWeekFrequency] = useState(false);
Fait 👍

2024-12-26 21:55 UTC, Clmnnt commented
possible de faire un screen de ce que ça fait ?

2024-12-26 22:45 UTC, Kgeek33 approved these changes
Parfait LGTM 👍

2024-12-26 22:46 UTC, Kgeek33 commented
> possible de faire un screen de ce que ça fait ?

Déso, mon pc est éteint 😅

2024-12-26 22:47 UTC, Kgeek33 commented
Mais ça ajoute dans un joli encadré la semaine
Genre si t'es en semaine q1, ça affichera dans un encadré à côté de la date Q1

2024-12-27 09:53 UTC, Skythrew commented
> possible de faire un screen de ce que ça fait ?

ça donne ça dans le header de la page de l'emploi du temps:

![Capture d’écran du 2024-12-27 10-53-20](https://github.com/user-attachments/assets/7f9cfb51-6f6b-4deb-b6da-4e0d8f7b0caf)

2024-12-27 09:55 UTC, Skythrew commented
> Et ça résout pas l'issue #469 ?

A priori non, ça a l'air d'être une donnée à part, vu que sur le screen donné dans l'issue on voit bien "Week Q2"

2024-12-27 10:56 UTC, ecnivtwelve commented
pas forcément pour l'activer par défaut, cependant on peut rendre l'option persistante dans l'account?

2024-12-27 10:57 UTC, Skythrew commented
C'est vrai, je peux m'occuper de ça si vous voulez

2024-12-27 13:52 UTC, Kgeek33 commented
ok pour rendre l'option persistante dans l'account
si l'option doit être désactivé par défaut, alors faudrait trouver un moyen pour mettre cette option à l'avant pask elle ne peut ne pas être facile à trouver (_mais ça, peut-être le faire dans une autre pr_)

2024-12-29 16:07 UTC, ecnivtwelve commented
> ok pour rendre l'option persistante dans l'account si l'option doit être désactivé par défaut, alors faudrait trouver un moyen pour mettre cette option à l'avant pask elle ne peut ne pas être facile à trouver (_mais ça, peut-être le faire dans une autre pr_)

après c'est une feature qu'on peut considérer comme "avancée", c'est pourquoi le but est de la laisser aux utilisateurs qui en veulent plus

2025-01-09 21:44 UTC, NathanBnm commented
On est d'accord que le nom de la semaine est dynamique et récupéré sur Pronote ?

Vous parlez de Q1 et Q2 mais sur le compte que j'ai c'est A et B.

2025-01-09 21:53 UTC, Skythrew commented
Yes évidemment

2025-01-11 21:58 UTC, godetremy commented
> [!NOTE]
> Cette review est le résultat de la concertation de toute l'équipe Papillon.

Nous sommes d'accord pour valider cette PR, mais tu devrais faire un paramètre pour rendre cette option optionnelle (désactivée par défaut).

Nous revérifiions cette PR la semaine prochaine, si cela est corrigé, ta PR sera merge. ✌️

2025-01-12 11:50 UTC, Skythrew commented
C'est bon pour moi. L'option a bien été rendue persistante et est désormais désactivée par défaut.

2025-01-12 11:52 UTC, Kgeek33 reviewed
Juste ça

2025-01-12 11:52 UTC, Kgeek33 commented on src/views/account/Lessons/Lessons.tsx
> +  const [shouldShowWeekFrequency, setShouldShowWeekFrequency] = useState(account.personalization.showWeekFrequency);
Peut être undefined :

```suggestion
  const [shouldShowWeekFrequency, setShouldShowWeekFrequency] = useState(account.personalization.showWeekFrequency ?? false);
```

2025-01-12 12:11 UTC, Skythrew commented on src/views/account/Lessons/Lessons.tsx
> +  const [shouldShowWeekFrequency, setShouldShowWeekFrequency] = useState(account.personalization.showWeekFrequency);
Si l'option n'est pas définie, elle est déjà mise à `false` par défaut.

2025-01-12 15:53 UTC, Kgeek33 commented
Je review plus tard

2025-01-12 18:12 UTC, Kgeek33 requested changes
okay t'as des erreurs eslint et une erreur sur la déclaration du typage (détail) mais fonctionne bien

2025-01-12 18:12 UTC, Kgeek33 commented on src/services/pronote/timetable.ts
> +    textLabel: 'Semaine',
```suggestion
    textLabel: "Semaine",
```

2025-01-12 18:12 UTC, Kgeek33 commented on src/services/pronote/timetable.ts
> +  }
```suggestion
  };
```

2025-01-12 18:12 UTC, Kgeek33 commented on src/services/pronote/timetable.ts
> +}
```suggestion
};
```

2025-01-12 18:12 UTC, Kgeek33 commented on src/services/timetable.ts
> +
```suggestion

```

2025-01-12 18:12 UTC, Kgeek33 commented on src/views/account/Lessons/Lessons.tsx
> +          { weekFrequency && shouldShowWeekFrequency && (
```suggestion
          {weekFrequency && shouldShowWeekFrequency && (
```

2025-01-12 18:12 UTC, Kgeek33 commented on src/services/shared/Timetable.ts
> +}
attention, pas de majuscules, c'est autre chose

```suggestion
export interface WeekFrequency {
  textLabel: string,
  freqLabel: string,
  num: number
}
```

2025-01-13 06:41 UTC, Skythrew commented on src/services/shared/Timetable.ts
> +}
Ah oui bien vu en effet, résolu avec le dernier commit :+1:

2025-01-13 06:41 UTC, Skythrew commented on src/views/account/Lessons/Lessons.tsx
> +          { weekFrequency && shouldShowWeekFrequency && (
Corrigé avec le dernier commit.

2025-01-13 06:42 UTC, Skythrew commented on src/services/pronote/timetable.ts
> +}
Corrigé avec le dernier commit

2025-01-13 06:42 UTC, Skythrew commented on src/services/timetable.ts
> +
Corrigé avec le dernier commit.

2025-01-13 06:42 UTC, Skythrew commented on src/services/pronote/timetable.ts
> +  }
Corrigé avec le dernier commit.

2025-01-13 06:42 UTC, Skythrew commented on src/services/pronote/timetable.ts
> +    textLabel: 'Semaine',
Corrigé avec le dernier commit.

2025-01-13 06:43 UTC, Skythrew commented
Les erreurs restantes ESLint ne sont pas du ressort de cette PR et sont d'ailleurs résolues par mon autre PR #637 .

2025-01-21 15:13 UTC, merged