Implémentation des discussions (Pronote)
PapillonApp/papillon-v7 pull request #546
Opened 2024-12-26 22:39 UTC by raphckrman

# 🚀 Nouvelle Pull Request

Proposez vos modifications pour améliorer Papillon

## Informations importantes

Merci de vous référer à la documentation sur la contribution si vous avez des questions à propos des pull requests (https://gitbook.getpapillon.xyz/organisation/outils-internes/github)

## Checklist d'avant pull request

Veuillez cocher toutes les cases applicables en remplaçant [ ] par [x].

- [x] Vous avez testé de build le projet avec vos modifications et ce build **a réussi**
- [x] Vous respectez les conventions de codage et de nommage du projet
- [x] Vous utilisez la **tabulation** pour l'indentation afin de maintenir un code lisible
- [x] Cette pull request **n'est pas un duplicata** d'une autre
- [x] Cette pull request est prête à être **revue** (review) et **fusionnée** (merge)
- [ ] Il n'y a pas de **`TODO`** (aka des annotations pour du code manquant) dans vos modifications
- [x] Il n'y a pas **d'erreurs de langue** dans votre code (grammaire, vocabulaire, conjugaison, orthographe)
- [x] Les détails des changements ont été décrits ci-dessous
- [x] Cette pull-request n'est pas une **"breaking-change"** (des modifications qui vont entraîner la modification du fonctionnement de certaines fonctionnalités déjà existantes)

## Changelogs proposés

Implementation de la page "Discussions" pour Pronote avec les thèmes, j'ai repris une partie du code de la branch ``features/chat``

⚠️ Il y a des ``TODO`` pour Ecole Directe/Skolengo

## Preview
(ce n'est pas une vraie conversation, j'ai repris celle sur Figma et j'ai flouté les noms des professeurs mais il y a le nom et la matière en dessous si elle est renvoyée par Pronote dans la page "Créer une discussion")

| Page principale | Créer une discussion | Discussion | ChatDetails | ChatThemes |
|----------------|----------------------|-------------|------------|--------------|
| ![Screenshot 2024-12-26 at 21 34 56](https://github.com/user-attachments/assets/7c8c9378-6471-48b9-953b-fc6ff01ea5e8) | ![Screenshot 2024-12-26 at 22 35 01](https://github.com/user-attachments/assets/9e817903-95e4-4280-b8a2-cd5de25881a4) | ![Screenshot 2024-12-25 at 22 37 43](https://github.com/user-attachments/assets/415d4ac9-cfb6-495e-81b6-a3213bf2cfb5) | ![Screenshot 2024-12-25 at 22 43 50](https://github.com/user-attachments/assets/7d125595-6f37-4da5-8db1-93f7f435d598) | ![image](https://github.com/user-attachments/assets/8476fe62-fc2b-4752-85ce-69987bb0d78d) |

2024-12-26 22:46 UTC, raphckrman commented
@ecnivtwelve @toi-et-moi si c'est possible d'avoir une review sur le design ce serait parfait

2024-12-27 00:28 UTC, Kgeek33 commented
Perso en regardant les captures, j'aime bien le design, je testerai demain

Question : depuis le plan vigipirate (qui perdure), dans mon lycée et sûrement dans d'autres, les discussions sont autorisées uniquement sur une plage horaire. Que se passe-t-il si on essaye d'envoyer un message en dehors de cette plage horaire ? Pronote affiche ça :

![Screenshot_2024-12-27-01-27-35-433_com.IndexEducation.Pronote-edit.jpg](https://github.com/user-attachments/assets/41148426-efe3-4205-b700-db021613219b)

2024-12-27 00:29 UTC, raphckrman commented
Je connaissais absolument pas ce cas, il faudrait que je regarde avec Pawnote ce que ça renvoi

2024-12-27 00:41 UTC, Kgeek33 commented
> Je connaissais absolument pas ce cas, il faudrait que je regarde avec Pawnote ce que ça renvoi

Ah ben attends, j'vais voir sur ma tablette si je peux tester
Ça doit sûrement faire un chargement infini quand on veut créer une discussion je pense

2024-12-27 01:11 UTC, Kgeek33 commented
Bon j'ai testé et je retiens 5 choses :

- Pq les conversations se lisent de bas en haut ?? Pour moi, il est naturel de lire du plus ancien au plus récent donc de haut en bas
- Bug : en mode sombre, le texte "Envoyer un message à [...]" ne s'affiche pas, lisible uniquement en mode clair
- Bug : quand on scrool piyr choisir les destinataires, ça n'arrive pas jusqu'au bout et la liste est donc coupée 
- Question : T'as intégré les thèmes j'ai vu en regardant les fichiers mais ça m'en propose que le thème par défaut, c'est normal ? 
- Idée : plutôt que d'afficher notre profil pronote sur les conversations avec notre prénom/nom et photo individuelle, pq ne pas plutôt prendre en compte le profil qu'on a choisi sur Papillon ?

Voilà, c'est surtout le 1er point qui me gêne énormément
J'ai pas testé encore l'envoi de message je le ferai demain

2024-12-27 01:14 UTC, raphckrman commented
Normalement c'est censé être la cas je rajouterai un check demain, pour le mode sombre pareil je change ça demain, la liste des destinataires pareils de mon côté c'était pas coupé. Oui y'a que le thème par défaut car j'ai juste pas créé de thème (énorme flemme de créer d'autres themes). Pour ton idée, càd ? Actuellement ça affiche soit ta photo soit celle que tu as défini ? Tu parle de aussi ajouter le nom et prénom défini dans les paramètres ?

2024-12-27 01:20 UTC, Kgeek33 commented
> Normalement c'est censé être la cas je rajouterai un check demain, pour le mode sombre pareil je change ça demain, la liste des destinataires pareils de mon côté c'était pas coupé. Oui y'a que le thème par défaut car j'ai juste pas créé de thème (énorme flemme de créer d'autres themes). Pour ton idée, càd ? Actuellement ça affiche soit ta photo soit celle que tu as défini ? Tu parle de aussi ajouter le nom et prénom défini dans les paramètres ?

Ok tu me préviendras quand t'auras fait les fixs ! Tkt pour les thèmes mdrr
Actuellement, ça renvoie ton profil pronote donc ton nom et prénom et la photo de profil renseigné par l'établissement
Moi j'aurai préféré que ça renvoie le profil Papillon

Ce que ça renvoie actuellement sur les discussions à chaque message que t'écris :
![Screenshot_2024-12-27-02-18-34-609_com.IndexEducation.Pronote-edit.jpg](https://github.com/user-attachments/assets/a6c9d636-82cc-46e6-a1ba-5d393fdd3335)

Ce que j'aurai préféré que ça affiche :
![Screenshot_2024-12-27-02-19-22-623_xyz.getpapillon.app.png](https://github.com/user-attachments/assets/826e1b1f-0cfa-4e71-b448-0d07d5375a23)

2024-12-27 01:21 UTC, raphckrman commented
Normalement tu as photo de profil défini, mais en effet j'ai pas mis le nom et prénom merci de la remarque. Tu vois bien ta photo de profil modifié ?

2024-12-27 01:24 UTC, Kgeek33 commented
> Normalement tu as photo de profil défini, mais en effet j'ai pas mis le nom et prénom merci de la remarque. Tu vois bien ta photo de profil modifié ?
> 
> 

Ah je viens d'y penser mais j'crois que ça n'a pas sauvegardé ma pdp personnalisée lors de mes tests (j'ai du réinstaller Expo car passé automatiquement sur sdk 52)
Faut que je reteste

2024-12-27 01:24 UTC, raphckrman commented
de mon côté la PP personnalisé s'affiche, à toi de me dire, je fais les modifs demain soir au plus tard

2024-12-27 01:36 UTC, Kgeek33 commented
Ok je te dirai ça. Par contre, depuis l'intégration des compétences, il n'y a plus aucun effort pour Android 😂😂. Les modals ne fonctionnent pas sur Android et donc pour quitter une page, il faut utiliser soit les gestures soit les boutons du système, pas très pratique 

Je voulais attendre le support d'expo 52 pour faire ma pr d'équité entre ios et Android (dont le support des slide modal pour Android) mais vu comment on galère à mettre en support, j'me lance dès demain
=> Du coup change rien sur ça, j'm'en occuperai à part

2024-12-27 01:40 UTC, raphckrman commented
je sais pas si moi c'est bon pour Android j'ai pas d'Android pour vraiment tester a fon

2024-12-27 01:43 UTC, Kgeek33 commented
> je sais pas si moi c'est bon pour Android j'ai pas d'Android pour vraiment tester a fond

Tkt c'est juste les modal qui pose problème sur Android, c'est tout
J'te tiens au courant puur ma future pr

2024-12-27 01:44 UTC, raphckrman commented
np, je fix tout les bugs de cette PR demain, si tu en a d'autres hésite pas

2024-12-27 10:55 UTC, ecnivtwelve approved these changes, later dismissed
LGTM 👍🏽

2024-12-27 20:46 UTC, raphckrman commented
@Kgeek33 j'ai résolu les bugs que tu as report mais je n'arrive pas à reproduire celui du dark mode de mon côté il s'affiche en dark mode
![Screenshot 2024-12-27 at 21 29 15](https://github.com/user-attachments/assets/3a0dccc5-0f83-4bb7-9adc-a1dc5fed7a6e)

2024-12-27 20:55 UTC, Kgeek33 commented
> @Kgeek33 j'ai résolu les bugs que tu as report mais je n'arrive pas à reproduire celui du dark mode de mon côté il s'affiche en dark mode ![Screenshot 2024-12-27 at 21 29 15](https://private-user-images.githubusercontent.com/41128238/399008158-3a0dccc5-0f83-4bb7-9adc-a1dc5fed7a6e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUzMzMxNzEsIm5iZiI6MTczNTMzMjg3MSwicGF0aCI6Ii80MTEyODIzOC8zOTkwMDgxNTgtM2EwZGNjYzUtMGY4My00YmI3LTlhZGMtYTFkYzVmZWQ3YTZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI3VDIwNTQzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2Y2UxMDgxOGU5OTVlYTMyZTIyM2FmMmM0OTBhY2U0N2JiMjg1NWYxNmMyZDU2ZTBmMTBkZWQwY2RmNTE2MmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.CXsN29r6qKH7CueF-6HlTpkTVPuts8Hp2KN4Df4adaA)

ok je vais tester (_ça va me changer d'expo 52 mdrr_)

2024-12-27 20:57 UTC, raphckrman commented
vas-y je te laisse me re dire normalement j'ai appliquer les autres changements/bugs

2024-12-27 21:03 UTC, tryon-dev commented
Hello je suis entrain de review la PR mais un petit truc me dérange, c'est pas grand chose mais bon je met la quand meme
![image](https://github.com/user-attachments/assets/2403f341-e8d9-4f3a-9591-0f4ef58fe24c)

2024-12-27 21:06 UTC, Kgeek33 commented
> Hello je suis entrain de review la PR mais un petit truc me dérange, c'est pas grand chose mais bon je met la quand meme ![image](https://private-user-images.githubusercontent.com/68423470/399009960-2403f341-e8d9-4f3a-9591-0f4ef58fe24c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUzMzM3MzUsIm5iZiI6MTczNTMzMzQzNSwicGF0aCI6Ii82ODQyMzQ3MC8zOTkwMDk5NjAtMjQwM2YzNDEtZThkOS00ZjNhLTk1OTEtMGY0ZWY1OGZlMjRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI3VDIxMDM1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxODRhNmQ2OGY0MzZlZDBjNDAwY2M2NGJmYzg5NGFjNDRhYmVhZTdhMTIzYjdmMzM0NzNkMDcwN2MzZGQ0OWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.XsF-GOfTg7Byv6Ecvth_QXlpxlcE7Oxoaq8zletN9-A)

ah ben non, faut mettre ce header uniquement sur Android et pas pour ios

2024-12-27 21:06 UTC, raphckrman commented
Ah oui je n'avais pas vu ça vu que je l'avais directement dans les pages en bas, je devrais raccourcir le texte ? Je vais regarder

2024-12-27 21:06 UTC, LeGeek01 commented
peut-être mettre uniquement "créer" ?

2024-12-27 21:07 UTC, raphckrman commented
Oui je vais mettre ça

2024-12-27 21:07 UTC, tryon-dev commented
Et aussi petit bug jsp si ca t'arrive a toi mais 

https://github.com/user-attachments/assets/d8a7cc7f-0c68-4278-8c40-30136f40c283

2024-12-27 21:07 UTC, raphckrman commented
oh j'avais pas eu ça mais je vais regarder

2024-12-27 21:10 UTC, Kgeek33 commented
je rencontre toujours le bug du mode sombre mais j'ai trouvé un fix, j'te fais une review du code après

2024-12-27 21:11 UTC, raphckrman commented
pas de soucis je comprend pas pourquoi je l'ai pas de mon côté

2024-12-27 21:13 UTC, Kgeek33 commented
et par rapport au restriction d'envoi de messages sur mon établissement, ça renvoie ça dans les logs :

`[sendMessageInChat]: Not Implementend.`

2024-12-27 21:14 UTC, raphckrman commented
ça le fait que quand y'a les restrictions ? ou même en temps normal ?

2024-12-27 21:15 UTC, tryon-dev commented
et aussi n'hesite pas a faire une PR sur le dataset de Papillon et de changer les URL 😎

2024-12-27 21:19 UTC, raphckrman commented
yes je voulais justement savoir si je faisais ça direct dans la PR ou si vous allez changer ça vous après

2024-12-27 21:21 UTC, Kgeek33 requested changes
Voilà mais en général, ça fonctionne ! :)
Par contre, rip aux gens d'Android mdrr

2024-12-27 21:21 UTC, Kgeek33 commented on src/views/account/Chat/Modals/Chat.tsx
> +                style={{
```suggestion
                placeholderTextColor={colors.text}
                style={{
```

2024-12-27 21:21 UTC, Kgeek33 commented on src/views/account/Chat/Modals/Chat.tsx
> +  console.log(chatTheme?.lightModifier.headerBackgroundColor);
```suggestion
```

2024-12-27 21:21 UTC, Kgeek33 commented on src/views/account/Chat/Messages.tsx
> +        }}
```suggestion
          gap: 5,
          paddingRight: 15,
        }}
```

2024-12-27 21:22 UTC, Kgeek33 commented
> ça le fait que quand y'a les restrictions ? ou même en temps normal ?

j'ai pas testé l'envoi de messages en dehors des restrictions (j'ai rien à dire à mes profs mdrr) mais logiquement, ça renvoie ça uniquement pendant les restrictions

2024-12-27 21:22 UTC, raphckrman commented
> > ça le fait que quand y'a les restrictions ? ou même en temps normal ?
> 
> j'ai pas testé l'envoi de messages en dehors des restrictions (j'ai rien à dire à mes profs mdrr) mais logiquement, ça renvoie ça uniquement pendant les restrictions

Oui pareil c'est le truc que j'ai pas pu tester c'est pour ça je demande

2024-12-27 21:24 UTC, Kgeek33 commented
j'ai fait un merge de la branche main car j'avais tjrs le problème d'affichage entre les pages

2024-12-27 21:25 UTC, Kgeek33 commented
> Oui pareil c'est le truc que j'ai pas pu tester c'est pour ça je demande

Envoyer un message à mon prof de nsi pour faire de la pub de Papillon, non ? 🤣

2024-12-27 22:11 UTC, Kgeek33 approved these changes
LGTM 👍

2024-12-27 22:14 UTC, tryon-dev commented
![image](https://github.com/user-attachments/assets/70192ed1-b4d5-4ca1-b544-5943e2186f02)
Et aussi si c'est possible d'augmenter le gradient

2024-12-27 23:48 UTC, tryon-dev commented
j'ai deux petites erreurs douteuse, si tu peux check : 

 WARN  "undefined80" is not a valid color or brush
 WARN  Could not find image file:///private/var/containers/Bundle/Application/C9BB944C-1754-415E-A026-C9604A54249B/Papillon.app/undefined.png

2024-12-27 23:50 UTC, tryon-dev commented
![image](https://github.com/user-attachments/assets/2ff9a37c-9afd-4af1-98b1-ce9872e33802)
et aussi j'ai aucun Destinataire

2024-12-27 23:51 UTC, Clmnnt commented
tu peux envoyer des messages sur pronote de base ?

2024-12-27 23:53 UTC, Kgeek33 commented
> ![image](https://github.com/user-attachments/assets/2ff9a37c-9afd-4af1-98b1-ce9872e33802)
> et aussi j'ai aucun Destinataire

Aucun destinataire si la messagerie est bloqué totalement par contre. Que disent les logs ?

2024-12-27 23:54 UTC, raphckrman commented
il y a un moyen dans Pawnote de savoir si la messagerie est bloqué ?

2024-12-27 23:54 UTC, raphckrman commented
> j'ai deux petites erreurs douteuse, si tu peux check :
> 
> WARN "undefined80" is not a valid color or brush WARN Could not find image file:///private/var/containers/Bundle/Application/C9BB944C-1754-415E-A026-C9604A54249B/Papillon.app/undefined.png

Je vais regarder je pense que c'est à cause des thèmes quand c'est par défaut mais j'ai pas ce soucis quand je met un autre theme que celui par défaut

2024-12-27 23:56 UTC, Kgeek33 commented
> il y a un moyen dans Pawnote de savoir si la messagerie est bloqué ?

Faut voir dans les logs ce que ça dit

2024-12-27 23:57 UTC, raphckrman commented
yes tu as ce bug toi aussi ou de ton côté ça marche nickel?

2024-12-27 23:59 UTC, Kgeek33 commented
> yes tu as ce bug toi aussi ou de ton côté ça marche nickel?

Comme moi c'est bloqué uniquement sur un créneau horaire, les destinataires s'affichent correctement de min côté

2024-12-28 14:11 UTC, tryon-dev commented
le probleme c'est que ma messagerie n'est pas bloqué

2024-12-28 14:11 UTC, tryon-dev commented
![image](https://github.com/user-attachments/assets/f5e86368-127e-40b1-b42e-7f074c4ed84d)

2024-12-28 14:22 UTC, raphckrman commented
J'arrive pas du tout à reproduire le bug, qu'est ce que Pawnote renvoi ?

2024-12-28 14:24 UTC, Kgeek33 commented
Ah ça c'est bizarre comme comportement, faut regarder ce que disent les logs

2024-12-29 16:05 UTC, ecnivtwelve approved these changes, later dismissed

2024-12-30 00:51 UTC, ecnivtwelve approved these changes
still LGTM 👍🏽

2024-12-30 17:47 UTC, merged