Ajout d'une alerte lors de la connexion a une instance de demo
PapillonApp/papillon-v7 pull request #59
Opened 2024-08-26 21:40 UTC by raphckrman

# 🚀 Nouvelle Pull Request

Proposez vos modifications pour améliorer Papillon

## Informations importantes

Merci de vous référer à la documentation sur la contribution si vous avez des questions à propos des pull requests (https://gitbook.getpapillon.xyz/organisation/outils-internes/github)

## Checklist d'avant pull request

Veuillez cocher toutes les cases applicables en remplaçant [ ] par [x].

- [x] Vous avez testé de build le projet avec vos modifications et ce build **a réussi**
- [x] Vous respectez les conventions de codage et de nommage du projet
- [x] Vous utilisez la **tabulation** pour l'indentation afin de maintenir un code lisible
- [x] Cette pull request **n'est pas un duplicata** d'une autre
- [x] Cette pull request est prête à être **revue** (review) et **fusionnée** (merge)
- [x] Il n'y a pas de **`TODO`** (aka des annotations pour du code manquant) dans vos modifications
- [x] Il n'y a pas **d'erreurs de langue** dans votre code (grammaire, vocabulaire, conjugaison, orthographe)
- [x] Les détails des changements ont été décrits ci-dessous
- [x] Cette pull-request n'est pas une **"breaking-change"** (des modifications qui vont entraîner la modification du fonctionnement de certaines fonctionnalités déjà existantes)

## Changelogs proposés

Ajout d'une alerte quand on souhaite se connecter avec une instance de démo pour éviter les issues inutiles. Idée venant de l'issue https://github.com/PapillonApp/Papillon/issues/57

## Informations supplémentaires

Comme l'a dit Vexcited dans l'issue https://github.com/PapillonApp/Papillon/issues/57 cette modification vérifie si l'URL contient ``demo.index-education.net``. Voilà a quoi ressemble l'alerte:
![image](https://github.com/user-attachments/assets/93f7cd6a-dcde-43d8-92bd-c8a1f89921eb)

2024-08-26 21:48 UTC, ecnivtwelve requested changes
Implémentation simple mais efficace, a voir si elle sera modifiée -> Juste la typo a revoir et c'est nickel !

2024-08-26 21:48 UTC, ecnivtwelve commented on src/services/pronote/determinate-authentication-view.tsx
> +      title: "Instance non supportée",
Petit typo, `non supportée`, sinon nice !

2024-08-26 21:48 UTC, ecnivtwelve commented on src/services/pronote/determinate-authentication-view.tsx
> +      ]
peut être ajouter une action annuler mais ça se peut c'est beaucoup ?

2024-08-26 21:49 UTC, Vexcited commented
Pour la meilleure implémentation, faudrait utiliser `.information.demo` (cf. https://github.com/LiterateInk/Pawnote/blob/7006c4e6b9192a5c2137e5eb14b5b420c91fc017/src/models/session-information.ts#L9) sur la `session` et ça serait parfait (mais bon j'en connais pas d'autre des instances de démo...)

2024-08-26 21:49 UTC, ecnivtwelve approved these changes
Finalement j'approuve, on verra plus tard pour les détails UX

2024-08-26 21:50 UTC, Rexxt commented
"supporté.e.s" -> "pris.e.s en charge"

2024-08-26 21:51 UTC, NonozgYtb commented
> Finalement j'approuve, on verra plus tard pour les détails UX

Cela coute 4 lignes de code, je pense que cela peut se faire facilement et nous évitera de le mettre dans un autre PR !

2024-08-26 21:53 UTC, tryon-dev commented
Il n'y a pas moyen de mettre cela directement dans la view pour que ca ne redirige pas vers la page de connexion tant que l'utilisateur n'a pas cliqué sur "Continuer quand meme"

2024-08-26 22:02 UTC, NonozgYtb commented
> Il n'y a pas moyen de mettre cela directement dans la view pour que ca ne redirige pas vers la page de connexion tant que l'utilisateur n'a pas cliqué sur "Continuer quand meme"

J'ai pas compris...

2024-08-26 22:04 UTC, tryon-dev commented
Actuellement si je me connecte avec un url demo ca m'envoyer quand meme sur la login view avec une popup devant moi
il faudrais que la popup apparaise devant moi et quand je clic ca m'envoye sur la login view

2024-08-26 22:21 UTC, raphckrman commented
> Actuellement si je me connecte avec un url demo ca m'envoyer quand meme sur la login view avec une popup devant moi il faudrais que la popup apparaise devant moi et quand je clic ca m'envoye sur la login view

Yes j'ai compris, je modifie ça pour que il y ai l'alert quand on click sur confirmer lors de la saisie de l'URL Pronote

2024-08-26 22:26 UTC, raphckrman commented
> Pour la meilleure implémentation, faudrait utiliser `.information.demo` (cf. https://github.com/LiterateInk/Pawnote/blob/7006c4e6b9192a5c2137e5eb14b5b420c91fc017/src/models/session-information.ts#L9) sur la `session` et ça serait parfait (mais bon j'en connais pas d'autre des instances de démo...)

Je vois mais je connais pas d'autres instances de démo, les gens utilisent tous demo.index-education.net (en tout cas tout le monde qui créé des issues inutiles dessus)

2024-08-27 06:43 UTC, Gabriel29306 commented
Pour le dark mode, la couleur est toujours bonne ou pas ?

2024-08-27 07:35 UTC, Gabriel29306 commented
On pourrait rajouter un background rouge pour le `continuer`, je teste ça 

![Screenshot_20240827_093300_Expo Go.jpg](https://github.com/user-attachments/assets/532c458d-9862-472e-9a41-dcb073360b41)

2024-08-27 07:46 UTC, Gabriel29306 commented
À vous de choisir

2024-08-27 08:24 UTC, tom-theret commented
Sans background car tu as 1 primary et 1 secondary

2024-08-27 08:59 UTC, Rexxt commented
vu le layout il faudrait que ça soit sans background, on réserve habituellement les backgrounds pour une action primaire et si on en a déjà une bah ça sert pas à grand chose si les deux uniques boutons du modal sont primaires

2024-08-27 09:15 UTC, Gabriel29306 commented
Ok je retiens ça pour mes connaissances personnelles

2024-08-27 09:51 UTC, Vexcited approved these changes

2024-08-27 12:08 UTC, merged